BOFH alasan # 1:kelajuan jam

%
BOFH alasan # 2:suar solar

%
BOFH alasan # 3:radiasi elektromagnet dari serpihan satelit

%
BOFH alasan # 4:statik dari seluar nilon

%
BOFH alasan # 5:statik daripada peraturan slaid plastik

%
BOFH alasan # 6:pemanasan global

%
BOFH alasan # 7:penyaman kuasa miskin

%
BOFH alasan # 8:penumpukan statik

%
BOFH alasan # 9:kesan doppler

%
BOFH alasan # 10:keretakan tekanan perkakasan

%
BOFH alasan # 11:gangguan magnet daripada kad wang / kredit

%
BOFH alasan # 12:sendi kering plug kabel

%
BOFH alasan # 13:kami menunggu [syarikat telefon] untuk menetapkan garis yang

%
BOFH alasan # 14:bunyi seperti masalah Windows, cuba memanggil sokongan Microsoft

%
BOFH alasan # 15:anomali routing sementara

%
BOFH alasan # 16:seseorang telah mengira pi pada pelayan

%
BOFH alasan # 17:elektron lemak dalam garis

%
BOFH alasan # 18:perlindungan lonjakan berlebihan

%
BOFH alasan # 19:terapung titik pemproses limpahan

%
BOFH alasan # 20:membahagikan demi sifar ralat

%
BOFH alasan # 21:masalah pematuhan POSIX

%
BOFH alasan # 22:resolusi monitor terlalu tinggi

%
BOFH alasan # 23:papan kekunci secara tidak wajar berorientasikan

%
BOFH alasan # 24:paket rangkaian ke bukit (menggunakan merpati pembawa)

%
BOFH alasan # 25:Pengurangan elektron fluks

%
BOFH alasan # 26:Sabtu pertama selepas bulan penuh pertama di Winter

%
BOFH alasan # 27:radiositi pengurangan

%
BOFH alasan # 28:CPU radiator rosak

%
BOFH alasan # 29:Ia berfungsi dengan cara yang Wang lakukan, apa masalahnya

%
BOFH alasan # 30:positron router kerosakan

%
BOFH alasan # 31:gangguan telefon selular

%
BOFH alasan # 32:tekanan techtonic

%
BOFH alasan # 33:gangguan piezo-elektrik

%
BOFH alasan # 34:ralat (l) pengguna

%
BOFH alasan # 35:bekerja seperti yang direka bentuk

%
BOFH alasan # 36:meja perisian dinamik menghubungkan rosak

%
BOFH alasan # 37:turun naik graviti berat, memindahkan komputer ke lantai pesat

%
BOFH alasan # 38:Setiausaha dipasang pengering rambut ke UPS

%
BOFH alasan # 39:aktiviti pengganas

%
BOFH alasan # 40:tidak memori yang cukup, pergi mendapatkan upgrade sistem

%
BOFH alasan # 41:ralat konfigurasi sampukan

%
BOFH alasan # 42:kegagalan paket spageti kabel punca

%
BOFH alasan # 43:bos terlupa kata laluan sistem

%
BOFH alasan # 44:cuti bank - Kredit sistem operasi tidak dicaj semula

%
BOFH alasan # 45:serangan virus, luser bertanggungjawab

%
BOFH alasan # 46:tangki air sisa melimpah ke komputer

%
BOFH alasan # 47:Complete Transient Lockout

%
BOFH alasan # 48:eter buruk dalam kabel

%
BOFH alasan # 49:pelepasan bogon

%
BOFH alasan # 50:Perubahan dalam kelajuan putaran Bumi

%
BOFH alasan # 51:zarah sinar kosmik merempuh pinggan cakera keras

%
BOFH alasan # 52:Bau daripada kakitangan jaga rumah yang tidak bersih rosak kepala pita

%
BOFH alasan # 53:Little hamster dalam roda berjalan mempunyai koronari; menunggu penggantian untuk Fedexed dari Wyoming

%
BOFH alasan # 54:anjing-anjing jahat dipukau syif malam

%
BOFH alasan # 55:Plumber tersalah anggap panel laluan untuk perlawanan dinding hiasan

%
BOFH alasan # 56:Juruelektrik dibuat popcorn dalam bekalan kuasa

%
BOFH alasan # 57:Groundskeepers mencuri kata laluan root

%
BOFH alasan # 58:tekanan tinggi kegagalan sistem

%
BOFH alasan # 59:percubaan gagal, keperluan sistem direka semula

%
BOFH alasan # 60:sistem telah dipanggil semula

%
BOFH alasan # 61:tidak diluluskan oleh FCC

%
BOFH alasan # 62:perlu untuk membalut sistem dalam kerajang aluminium untuk menyelesaikan masalah

%
BOFH alasan # 63:tidak berpijak di bumi dengan betul, sila mengebumikan komputer

%
BOFH alasan # 64:CPU memerlukan recalibration

%
BOFH alasan # 65:sistem perlu reboot

%
BOFH alasan # 66:bit baldi limpahan

%
BOFH alasan # 67:menyahkarau kod diperlukan daripada syarikat perisian

%
BOFH alasan # 68:hanya terdapat pada keperluan untuk mengetahui asas

%
BOFH alasan # 69:simpulan dalam kabel disebabkan aliran data untuk menjadi dipintal dan kinked

%
BOFH alasan # 70:lipas bersarang terpintas keluar kabel eter

%
BOFH alasan # 71:Sistem fail penuh dengan ia

%
BOFH alasan # 72:Syaitan melakukannya

%
BOFH alasan # 73:Daemons melakukannya

%
BOFH alasan # 74:Anda keluar dari memori

%
BOFH alasan # 75:Tidak ada apa-apa masalah

%
BOFH alasan # 76:cakera keras unoptimized

%
BOFH alasan # 77:Typo dalam kod

%
BOFH alasan # 78:Ya, ya, yang dikenali sebagai had reka bentuk

%
BOFH alasan # 79:Lihatlah, buddy: Windows 3.1 ADALAH Perlindungan General Fault.

%
BOFH alasan # 80:Itu satu komputer hebat yang anda mempunyai di sana; Bagaimana fikiran kamu, bagaimana ia akan bekerja sebagai mesin BSD?

%
BOFH alasan # 81:Sila maafkan saya, saya perlu litar AC talian melalui kepala saya untuk mendapatkan kerja pangkalan data ini.

%
BOFH alasan # 82:Yeah, pakaian mama yo anda lucu dan anda perlu tetikus untuk memadam fail.

%
BOFH alasan # 83:kakitangan sokongan digantung lebih, menghantar aspirin dan kembali KEMUDIAN.

%
BOFH alasan # 84:Seseorang sedang berdiri di atas kabel ethernet, menyebabkan kekusutan yang dalam kabel

%
BOFH alasan # 85:Windows 95 tanpa izin "ciri"

%
BOFH alasan # 86:paket runt

%
BOFH alasan # 87:Kata laluan terlalu kompleks untuk menyahsulit

%
BOFH alasan # 88:kanak-kanak Boss 'fuck mesin

%
BOFH alasan # 89:kehilangan tenaga elektromagnet

%
BOFH alasan # 90:pemotongan bajet

%
BOFH alasan # 91:Mouse dikunyah melalui kabel kuasa

%
BOFH alasan # 92:mengendalikan fail basi (lain kali menggunakan Tupperware (tm)!)

%
BOFH alasan # 93:Ciri belum dilaksanakan

%
BOFH alasan # 94:gangguan Internet

%
BOFH alasan # 95:Pentium FDIV bug

%
BOFH alasan # 96:Penjual tidak lagi menyokong produk

%
BOFH alasan # 97:Kecil serangan kamikaze haiwan untuk bekalan kuasa

%
BOFH alasan # 98:vendor meletakkan bug di sana.

%
BOFH alasan # 99:SIMM crosstalk.

%
BOFH alasan # 100:IRQ keciciran

%
BOFH alasan # 101:Backbone runtuh

%
BOFH alasan # 102:syarikat Power ujian kenaikan voltan baru (penciptaan) peralatan

%
BOFH alasan # 103:pengendali mogok kerana mesin kopi patah

%
BOFH alasan # 104:pita sandaran ditulis ganti dengan salinan CD kegemaran pengurus sistem

%
BOFH alasan # 105:UPS terganggu kuasa pelayan

%
BOFH alasan # 106:juruelektrik tidak tahu apa kabel kuning begitu dia tepian tercabut ethernet keluar.

%
BOFH alasan # 107:Papan kekunci tidak dipasang

%
BOFH alasan # 108:Paip bekalan air penyaman udara pecah atas bilik mesin

%
BOFH alasan # 109:Pencawang elektrik di tempat letak kereta meletup.

%
BOFH alasan # 110:Batu-batu rolling konsert di jalan menyebabkan coklat keluar

%
BOFH alasan # 111:jurujual memandu atas papan CPU.

%
BOFH alasan # 112:monitor dipasang ke dalam port siri

%
BOFH alasan # 113:pelayan nama Root tidak segerak

%
BOFH alasan # 114:denyutan elektro-magnetik dari Perancis atas alasan ujian nuke.

%
BOFH alasan # 115:bar ruang keyboard anda menjana kod kekunci palsu.

%
BOFH alasan # 116:yang mesen sebenar menjadi mesen pseudo dan sebaliknya.

%
BOFH alasan # 117:pencetak yang difikirkan router itu.

%
BOFH alasan # 118:router yang difikirkan pencetak itu.

%
BOFH alasan # 119:penggodam jahat dari Serbia.

%
BOFH alasan # 120:kita beralih kepada FDDI.

%
BOFH alasan # 121:sistem halon pergi dan membunuh pengendali.

%
BOFH alasan # 122:kerana Bill Gates adalah saksi Yehuwa dan supaya tiada apa yang boleh bekerja pada hari St. Swithin ini.

%
BOFH alasan # 123:pengguna kepada nisbah komputer terlalu tinggi.

%
BOFH alasan # 124:pengguna untuk catuan komputer terlalu rendah.

%
BOFH alasan # 125:kita beralih kepada Sprint.

%
BOFH alasan # 126:ia mempunyai Intel Inside

%
BOFH alasan # 127:bit melekit pada cakera.

%
BOFH alasan # 128:Power Company menghadapi masalah EMP dengan reaktor mereka

%
BOFH alasan # 129:Cincin itu memerlukan satu mukjizat yang lain

%
BOFH alasan # 130:pengurusan baru

%
BOFH alasan # 131:telnet: Tidak dapat menyambung ke hos jauh: Sambungan ditolak

%
BOFH alasan # 132:SCSI Chain overterminated

%
BOFH alasan # 133:Ia tidak dipasang.

%
BOFH alasan # 134:kerana lag rangkaian kerana terlalu banyak orang yang sedang bermain deathmatch

%
BOFH alasan # 135:Anda meletakkan cakera dalam terbalik.

%
BOFH alasan # 136:Daemons longgar dalam rangkaian.

%
BOFH alasan # 137:Pengguna telah mengedarkan pornografi pada pelayan; sistem dirampas oleh FBI.

%
BOFH alasan # 138:BNC (otak tidak bersambung)

%
BOFH alasan # 139:UBNC (otak pengguna tidak bersambung)

%
BOFH alasan # 140:LBNC (luser otak tidak bersambung)

%
BOFH alasan # 141:cakera berputar ke belakang - bertukar-tukar hemisfera pelompat.

%
BOFH alasan # 142:talian telefon Lelaki merentas disambungkan baru dengan bas kuasa ac.

%
BOFH alasan # 143:terpaksa menggunakan tukul untuk membebaskan kepala pemacu cakera tersekat.

%
BOFH alasan # 144:Terlalu sedikit computrons didapati.

%
BOFH alasan # 145:tayar rata di station wagon dengan pita. ( "Jangan sekali-kali memandang rendah jalur lebar wagon stesen penuh pita melemparkan ke lebuh raya" Andrew S. Tannenbaum)

%
BOFH alasan # 146:Komunikasi satelit yang digunakan oleh tentera untuk peperangan bintang.

%
BOFH alasan # 147:Parti-bug dalam protokol Aloha.

%
BOFH alasan # 148:Memasukkan syiling untuk permainan baru

%
BOFH alasan # 149:Dew pada talian telefon.

%
BOFH alasan # 150:Arcserve terhempas pelayan lagi.

%
BOFH alasan # 151:Ada yang diperlukan PowerStrip, jadi mereka telah dikejutkan suis.

%
BOFH alasan # 152:Saya kuda ekor melanda pada suis hidup / mati pada jalur kuasa.

%
BOFH alasan # 153:Besar untuk sedikit ralat endian penukaran

%
BOFH alasan # 154:Anda boleh menala sistem fail, dan anda tidak boleh menala ikan (dari kebanyakan halaman tunefs manusia)

%
BOFH alasan # 155:terminal Dumb

%
BOFH alasan # 156:proses Zombie menghantui komputer

%
BOFH alasan # 157:Penyegerakan masa yang tidak betul

%
BOFH alasan # 158:proses yang tidak berfungsi lagi

%
BOFH alasan # 159:proses degil

%
BOFH alasan # 160:bukan berlebihan kegagalan kipas

%
BOFH alasan # 161:memantau kebocoran VLF

%
BOFH alasan # 162:bug dalam RAID

%
BOFH alasan # 163:tidak "apa-apa" pada papan kekunci

%
BOFH alasan # 164:reput akar

%
BOFH alasan # 165:backbone Scoliosis

%
BOFH alasan # 166:/ Pub / makan tengah hari

%
BOFH alasan # 167:perlanggaran yang berlebihan & ambulans paket tidak cukup

%
BOFH alasan # 168:le0: tidak pembawa: masalah kabel transceiver?

%
BOFH alasan # 169:disiarkan paket pada frekuensi salah

%
BOFH alasan # 170:popper dapat memproses kernel jumbo

%
BOFH alasan # 171:NOTIS: alloc: / dev / null: sistem fail penuh

%
BOFH alasan # 172:pseudo-pengguna pada pseudo-terminal

%
BOFH alasan # 173:penyusuran rekursi daripada gelung balik gunung mata

%
BOFH alasan # 174:pelarasan tulang belakang

%
BOFH alasan # 175:OS bertukar ke cakera

%
BOFH alasan # 176:wap dari penyejatan pelekat melekit-komen

%
BOFH alasan # 177:sticktion

%
BOFH alasan # 178:kaki pendek di atas meja proses

%
BOFH alasan # 179:multicasts pada paket patah

%
BOFH alasan # 180:kebocoran eter

%
BOFH alasan # 181:Atilla Hub

%
BOFH alasan # 182:recalibration endothermal

%
BOFH alasan # 183:sistem fail tidak cukup besar untuk Jumbo Kernel Patch

%
BOFH alasan # 184:gelung dijumpai di dalam gelung dalam gelung balik berlebihan

%
BOFH alasan # 185:sistem yang digunakan semua kertas untuk paging

%
BOFH alasan # 186:keizinan ditolak

%
BOFH alasan # 187:Memformat Page. Tunggu ...

%
BOFH alasan # 188:..disk atau pemproses yang sedang terbakar.

%
BOFH alasan # 189:SCSI terlalu luas.

%
BOFH alasan # 190:Maklumat proprietari.

%
BOFH alasan # 191:Hanya taip 'mv * / dev / null.

%
BOFH alasan # 192:kucing melarikan diri pada sistem.

%
BOFH alasan # 193:Adakah anda membayar Bayaran Sokongan baru?

%
BOFH alasan # 194:Kami hanya menyokong sambungan 1200 mata asas.

%
BOFH alasan # 195:Kami hanya menyokong sambungan 28000 bps.

%
BOFH alasan # 196:Saya tiada aras internet, hanya janitor, saya hanya lilin.

%
BOFH alasan # 197:Saya minta maaf pentium yang tidak akan lakukan, anda memerlukan SGI untuk berhubung dengan kami.

%
BOFH alasan # 198:Post-it Nota Enapcemar bocor ke monitor.

%
BOFH alasan # 199:keriting dalam saraf keyboard anda kehilangan elektrik.

%
BOFH alasan # 200:monitor memerlukan satu lagi kotak piksel.

%
BOFH alasan # 201:RPC_PMAP_FAILURE

%
BOFH alasan # 202:kernel panik: menulis sahaja ingatan (/ dev / wom0) kapasiti melebihi.

%
BOFH alasan # 203:Tulis sahaja ingatan subsistem terlalu lambat untuk mesin ini. Hubungi peniaga tempatan anda.

%
BOFH alasan # 204:Hanya mengambil telefon dan memberi modem menyambung bunyi. "Baik anda berkata kita perlu mendapatkan lebih banyak garis supaya kita tidak mempunyai talian suara."

%
BOFH alasan # 205:dinamik Quantum memberi kesan transistor

%
BOFH alasan # 206:Polis sedang memeriksa semua paket internet dalam carian untuk narco-net-pengedar

%
BOFH alasan # 207:Kami sedang cuba satu konsep baru menggunakan tetikus streaming. Malangnya, seseorang itu belum hidup yang disambungkan kepada komputer ..... sila menanggung dengan kami.

%
BOFH alasan # 208:mel dihalakan melalui Jerman ... dan mereka menapis kami.

%
BOFH alasan # 209:Hanya orang yang mempunyai nama-nama yang bermula dengan 'A' mendapat mail minggu ini (a la Microsoft)

%
BOFH alasan # 210:Kami tidak membayar bil Internet dan ia telah terputus.

%
BOFH alasan # 211:kilat.

%
BOFH alasan # 212:Sudah tentu ia tidak berfungsi. Kami telah dilakukan naik taraf perisian.

%
BOFH alasan # 213:Tukar bahasa anda ke Finland.

%
BOFH alasan # 214:lampu neon menjana ion negatif. Jika menukar mereka tidak berfungsi, membawa mereka keluar dan meletakkan kerajang timah di hujung.

%
BOFH alasan # 215:aktiviti nuklear yang tinggi di kawasan anda.

%
BOFH alasan # 216:Apa jawatan adalah anda? Oh, yang itu. Adakah anda tahu bahawa bangunan anda dibina di atas tapak penyelidikan universiti pertama nuklear? Dan wow, tidak adakah anda salah seorang yang bernasib baik, pejabat anda adalah hak ke atas mana teras dikebumikan!

%
BOFH alasan # 217:The SKM kehabisan gas.

%
BOFH alasan # 218:The UPS tidak mempunyai sandaran bateri.

%
BOFH alasan # 219:Recursivity. Panggilan semula jika ia berlaku lagi.

%
BOFH alasan # 220:Seseorang fikir Butang Merah Besar adalah suis lampu.

%
BOFH alasan # 221:kerangka utama yang perlu berehat. Ia semakin lama, anda tahu.

%
BOFH alasan # 222:Saya tidak pasti. Cuba panggil ibu pejabat Internet - itu dalam buku ini.

%
BOFH alasan # 223:Garis semua sibuk (menyibukkan keluar, iaitu: -? Mengapa membiarkan mereka dalam untuk memulakan dengan).

%
BOFH alasan # 224:9 Jan 16:41:27 Huber su: 'su root berjaya untuk .... pada / dev / pts / 1

%
BOFH alasan # 225:Ia adalah orang-orang komputer dalam X {kota dunia}. Mereka menjaga perkara-perkara pemadat sehingga.

%
BOFH alasan # 226:Sebuah satelit star wars sengaja meletupkan WAN.

%
BOFH alasan # 227:kesilapan yang teramat besar betul-betul di hadapan skrin

%
BOFH alasan # 228:fungsi yang tidak disokong pada masa ini, tetapi Bill Gates meyakinkan kita ia akan dipaparkan dalam naik taraf seterusnya.

%
BOFH alasan # 229:kekutuban yang salah aliran neutron

%
BOFH alasan # 230:keluk Lusers pembelajaran yang kelihatan sebagai fraktal

%
BOFH alasan # 231:Kami terpaksa mematikan bahawa perkhidmatan mematuhi Bill CDA.

%
BOFH alasan # 232:Pengionan daripada penghawa dingin

%
BOFH alasan # 233:TCP / IP UDP penggera ambang ditetapkan terlalu rendah.

%
BOFH alasan # 234:Seseorang penyiaran paket pigmi dan router yang tidak tahu bagaimana untuk berurusan dengan mereka.

%
BOFH alasan # 235:Rangkaian frame relay baru belum katil turun gelung pemancar perisian lagi.

%
BOFH alasan # 236:Fanout menjatuhkan voltan terlalu banyak, cuba memotong beberapa orang-orang kesan sedikit

%
BOFH alasan # 237:Plat voltan terlalu rendah pada tiub penyahmodulat

%
BOFH alasan # 238:Anda melakukan wha ... oh _dear _....

%
BOFH alasan # 239:CPU memerlukan galas dibungkus semula

%
BOFH alasan # 240:Terlalu banyak pin kecil pada CPU mengelirukan ia, bengkok ke belakang dan sebagainya sehingga 10-20% kemas dikeluarkan. Jangan _not_ meninggalkan bit logam dilihat!

%
BOFH alasan # 241:_Rosin_ Solder teras? Tetapi ...

%
BOFH alasan # 242:Software menggunakan US ukuran, tetapi OS berada di metrik ...

%
BOFH alasan # 243:Komputer fleetly, tetikus dan semua.

%
BOFH alasan # 244:Kucing anda cuba untuk makan tetikus.

%
BOFH alasan # 245:The Borg cuba mengasimilasikan sistem anda. Rintangan adalah sia-sia.

%
BOFH alasan # 246:Ia mesti telah ribut petir kita mempunyai (semalam) (minggu lepas) (bulan lepas)

%
BOFH alasan # 247:Oleh kerana masalah Belanjawan Persekutuan kita telah dipaksa untuk mengurangkan bilangan pengguna boleh mengakses sistem pada satu-satu masa. (Iaitu tidak dibenarkan ....)

%
BOFH alasan # 248:radiasi terlalu banyak yang datang dari tanah.

%
BOFH alasan # 249:Malangnya kita telah kehabisan bit / bytes / apa sahaja. Jangan bimbang, bekalan seterusnya akan datang minggu depan.

%
BOFH alasan # 250:beban Program terlalu berat untuk pemproses untuk mengangkat.

%
BOFH alasan # 251:Proses berjalan perlahan-lahan kerana bekalan kuasa yang lemah

%
BOFH alasan # 252:ISP kami mempunyai {pensuisan, routing, SMDS, frame relay} masalah

%
BOFH alasan # 253:Kami telah kehabisan lesen

%
BOFH alasan # 254:Gangguan daripada sinaran lunar

%
BOFH alasan # 255:Berdiri bilik sahaja di dalam bas.

%
BOFH alasan # 256:Anda perlu memasang antara muka RTFM.

%
BOFH alasan # 257:Itu akan menjadi kerana perisian yang tidak berfungsi.

%
BOFH alasan # 258:Yang mudah untuk menetapkan, tetapi saya tidak boleh diganggu.

%
BOFH alasan # 259:tali leher seseorang terperangkap dalam pencetak, dan jika apa-apa lagi mendapat dicetak, dia akan berada dalam juga.

%
BOFH alasan # 260:Kami akan meningkatkan / dev / null

%
BOFH alasan # 261:Berita Usenet adalah daripada tarikh

%
BOFH alasan # 262:pelayan POP kami telah diculik oleh weasel a.

%
BOFH alasan # 263:Ia terperangkap dalam Web.

%
BOFH alasan # 264:modem anda tidak berbahasa Inggeris.

%
BOFH alasan # 265:tetikus melarikan diri.

%
BOFH alasan # 266:Kesemua paket kosong.

%
BOFH alasan # 267:The UPS adalah mogok.

%
BOFH alasan # 268:Neutrino beban lebih pada pelayan nama yang

%
BOFH alasan # 269:Melting cakera keras

%
BOFH alasan # 270:Seseorang telah merosakkan sehingga petunjuk kernel

%
BOFH alasan # 271:Lesen kernel telah tamat

%
BOFH alasan # 272:Netscape telah terhempas

%
BOFH alasan # 273:tali melompat ke atas dan memukul suis kuasa.

%
BOFH alasan # 274:Ia adalah OK sebelum anda menyentuhnya.

%
BOFH alasan # 275:reput bit

%
BOFH alasan # 276:AS Perkhidmatan Pos

%
BOFH alasan # 277:Flux kapasitor anda telah menjadi buruk.

%
BOFH alasan # 278:Kristal Dilithium perlu diputar.

%
BOFH alasan # 279:Penyaluran elektrik statik bertindak up ...

%
BOFH alasan # 280:Traceroute mengatakan bahawa ada masalah routing dalam tulang belakang. Ia bukan masalah kami.

%
BOFH alasan # 281:Bersama-pencari tidak dapat mengesahkan pintu masuk frame-relay ke pelayan ISDN itu.

%
BOFH alasan # 282:pemeluwapan altitud tinggi daripada pesawat prototaip U.S.A.F telah tercemar topeng subnet utama. Matikan komputer anda untuk 9 hari untuk mengelakkan merosakkannya.

%
BOFH alasan # 283:Pemotong rumput bilah dalam kipas anda perlu mengasah

%
BOFH alasan # 284:Elektron pada Bender

%
BOFH alasan # 285:Telekomunikasi sedang menaik taraf.

%
BOFH alasan # 286:Telecommunications ialah merendahkan.

%
BOFH alasan # 287:Telecommunications ialah downshifting.

%
BOFH alasan # 288:Hard tidur drive. Biarkan ia bangun pada itu sendiri ...

%
BOFH alasan # 289:Gangguan antara papan kekunci dan kerusi.

%
BOFH alasan # 290:CPU telah berubah, dan menjadi tidak berpusat.

%
BOFH alasan # 291:Oleh kerana CDA, kita tidak lagi mempunyai akaun akar.

%
BOFH alasan # 292:Kami kehabisan nada dail dan kami dan menunggu syarikat telefon untuk menyampaikan botol lain.

%
BOFH alasan # 293:Anda must've melanda salah yang mana-mana kekunci.

%
BOFH alasan # 294:PCMCIA pemandu hamba

%
BOFH alasan # 295:Token jatuh daripada gelanggang. Hubungi kami apabila anda menemuinya.

%
BOFH alasan # 296:Bas perkakasan memerlukan tanda baru.

%
BOFH alasan # 297:Terlalu banyak sampukan

%
BOFH alasan # 298:sampukan tidak cukup

%
BOFH alasan # 299:Data pada cakera keras anda adalah tidak seimbang.

%
BOFH alasan # 300:Digital Manipulator melebihi parameter halaju

%
BOFH alasan # 301:muncul untuk menjadi sempit SCSI-0 masalah Slow / Muka

%
BOFH alasan # 302:mikroelektronik Riemann kesalahan melengkung-ruang dalam sistem fail hapus sahaja

%
BOFH alasan # 303:radiasi fraktal jamming tulang belakang

%
BOFH alasan # 304:masalah routing di internet neural

%
BOFH alasan # 305:IRQ-masalah dengan Un-Interruptible-Power-Supply

%
BOFH alasan # 306:CPU-sudut telah diselaraskan kerana getaran yang datang dari jalan berhampiran

%
BOFH alasan # 307:pelepasan daripada GSM-telefon

%
BOFH alasan # 308:server CD-ROM memerlukan recalibration

%
BOFH alasan # 309:firewall memerlukan penyejukan

%
BOFH alasan # 310:kegagalan inode tak segerak

%
BOFH alasan # 311:bas sementara protokol melanggar

%
BOFH alasan # 312:pengusaha bit-pendaftaran tidak serasi

%
BOFH alasan # 313:proses anda tidak ISO 9000 yang mematuhi

%
BOFH alasan # 314:Anda perlu menaik taraf bas tempatan VESA anda untuk bas tempatan MasterCard.

%
BOFH alasan # 315:Perkembangan baru-baru ini Ujian Nuklear

%
BOFH alasan # 316:Elves mogok. (Mengapa mereka memanggil EMAG Elf Magic)

%
BOFH alasan # 317:Internet melebihi paras luser, sila tunggu sehingga luser yang log off sebelum cuba untuk log masuk semula.

%
BOFH alasan # 318:EMAIL Anda sekarang sedang disampaikan oleh USPS.

%
BOFH alasan # 319:Komputer anda tidak kembali semua bit ia mendapat dari Internet.

%
BOFH alasan # 320:Anda telah dijangkiti oleh virus teleskop Hubble.

%
BOFH alasan # 321:Berjadual gangguan CPU global

%
BOFH alasan # 322:Pentium anda mempunyai masalah pemanasan - cuba penyejukan dengan air ais sejuk (Jangan menghidupkan komputer anda, anda tidak mahu untuk menyejukkan Pentium Chip manakala dia tidak bekerja, bukan?).

%
BOFH alasan # 323:pemproses anda telah diproses terlalu banyak arahan. Mematikannya dengan segera, tidak menaip apa-apa arahan !!

%
BOFH alasan # 324:paket anda telah dimakan oleh terminator

%
BOFH alasan # 325:pemproses anda tidak membangunkan haba yang cukup.

%
BOFH alasan # 326:Kami memerlukan juruelektrik berlesen untuk menggantikan mentol lampu di dalam bilik komputer.

%
BOFH alasan # 327:Pelayan POP adalah daripada Coke

%
BOFH alasan # 328:gentian optik disebabkan gas kebocoran utama

%
BOFH alasan # 329:Server tertekan, perlu Prozac

%
BOFH alasan # 330:decoherence kuantum

%
BOFH alasan # 331:mereka rakun sialan!

%
BOFH alasan # 332:pengalaman routing suboptimal

%
BOFH alasan # 333:tukang paip A diperlukan, longkang rangkaian tersumbat

%
BOFH alasan # 334:50% daripada pengguna adalah dalam fail readme .pdf

%
BOFH alasan # 335:bateri AA dalam wallclock menghantar gangguan magnetik

%
BOFH alasan # 336:paksi xy dalam bebola jejak diselaraskan dengan solstis musim panas

%
BOFH alasan # 337:butane ringan menyebabkan pincushioning yang

%
BOFH alasan # 338:kartrij inkjet lama berpunca wasap berdasarkan barium-

%
BOFH alasan # 339:pengurus di saluran kabel

%
BOFH alasan # 340:Well menetapkan bahawa dalam (upgrade, maklumat, melepaskan patch, pek perkhidmatan) akan datang.

%
BOFH alasan # 341:HTTPD Error 666: BOFH berada di sini

%
BOFH alasan # 342:HTTPD Ralat 4004: Intel cpu sangat lama - kuasa pemprosesan yang tidak mencukupi

%
BOFH alasan # 343:Lembaga ATM telah kehabisan 10 nota paun. Kami mempunyai satu pusingan cambuk untuk mengisi semula itu, berhati-hati untuk menyumbang?

%
BOFH alasan # 344:Kegagalan rangkaian - panggilan NBC

%
BOFH alasan # 345:Mempunyai untuk mengesan secara manual satelit.

%
BOFH alasan # 346:Komputer anda / kami (s) telah mengalami kebocoran memori, dan kami sedang menunggu untuk mereka yang akan ditambah.

%
BOFH alasan # 347:The band getah patah

%
BOFH alasan # 348:Kami dalam Token Ring, dan ia kelihatan seperti cara yang mendapat longgar.

%
BOFH alasan # 349:Stray Alpha Particles dari bungkusan ingatan disebabkan Ralat Memory Hard pada Server.

%
BOFH alasan # 350:anjakan paradigma ... tanpa klac

%
BOFH alasan # 351:PEBKAC (Masalah Wujud antara papan kekunci dan kerusi)

%
BOFH alasan # 352:Kabel tidak sama panjang.

%
BOFH alasan # 353:Kesan kedua-sistem.

%
BOFH alasan # 354:Gula-gula getah pada / dev / sd3c

%
BOFH alasan # 355:Kebosanan dalam Kernel.

%
BOFH alasan # 356:daemon! daemon! daemon dahsyat!

%
BOFH alasan # 357:Saya suka untuk membantu anda - ia hanya bahawa Boss tidak akan membiarkan saya berhampiran komputer.

%
BOFH alasan # 358:dipukul oleh virus Good Times

%
BOFH alasan # 359:ANDA MEMPUNYAI I / O ERROR -> ralat Operator tidak cekap

%
BOFH alasan # 360:daftar pariti anda terlebih keluar dan anda berada di luar cache.

%
BOFH alasan # 361:revolusi Komunis mengambil alih bilik server dan menuntut semua komputer di dalam bangunan atau mereka menembak pentadbir sistem ini. bodoh sesat miskin.

%
BOFH alasan # 362:Plasma saluran pelanggaran

%
BOFH alasan # 363:Daripada kad pada pemacu D:

%
BOFH alasan # 364:kutu Sand makan kabel Internet

%
BOFH alasan # 365:pemproses selari berjalan tegak lurus hari ini

%
BOFH alasan # 366:sel ATM tidak mempunyai ciri perayauan dihidupkan, komputer riba tidak boleh menyambung

%
BOFH alasan # 367:Webmaster diculik oleh kultus jahat.

%
BOFH alasan # 368:Kegagalan untuk menyesuaikan masa penjimatan waktu siang.

%
BOFH alasan # 369:Virus dihantar dari komputer ke sysadmins.

%
BOFH alasan # 370:Virus kerana komputer yang mempunyai hubungan seks yang tidak selamat.

%
BOFH alasan # 371:Dikonfigurasi dengan salah laluan statik pada corerouters.

%
BOFH alasan # 372:Terpaksa menyokong pelayan Perjanjian Baru; sysadmins berhenti.

%
BOFH alasan # 373:penunjuk mencurigakan rosak mesin maya

%
BOFH alasan # 374:Ia adalah kesilapan yang InterNIC ini.

%
BOFH alasan # 375:pelayan nama akar rosak.

%
BOFH alasan # 376:pemotongan bajet memaksa kita untuk menjual semua kord kuasa untuk pelayan.

%
BOFH alasan # 377:Seseorang ketagih wayar pasangan terpiuh ke dalam mesin menjawab.

%
BOFH alasan # 378:Operators dibunuh oleh tahun 2000 bug gigitan.

%
BOFH alasan # 379:Kami telah memilih COBOL sebagai bahasa pilihan.

%
BOFH alasan # 380:Operators terbunuh apabila timbunan besar pita sandaran roboh.

%
BOFH alasan # 381:Robotic pita changer tersalah anggap tie pengendali bagi pita sandaran.

%
BOFH alasan # 382:Seseorang merokok di dalam bilik komputer dan menolak sistem halon.

%
BOFH alasan # 383:pemproses anda telah mengambil perjalanan ke Pintu Syurga pada UFO belakang komet Hale-Bopp ini.

%
BOFH alasan # 384:ia adalah satu-10-T ID ralat

%
BOFH alasan # 385:Dyslexics penaipan semula tuan rumah fail pada pelayan

%
BOFH alasan # 386:Internet itu sedang diimbas untuk virus.

%
BOFH alasan # 387:kontrak kesatuan komputer anda akan tamat pada tengah malam.

%
BOFH alasan # 388:karma pengguna Bad.

%
BOFH alasan # 389:/ Dev / petunjuk dikaitkan dengan / dev / null

%
BOFH alasan # 390:Peningkatan aktiviti Tompok pd matahari.

%
BOFH alasan # 391:Kita sudah dihantar ke seluruh notis tentang itu.

%
BOFH alasan # 392:Ia peraturan kesatuan. Ada apa-apa yang boleh kita lakukan mengenainya. Maaf.

%
BOFH alasan # 393:Gangguan dari Van Allen Belt.

%
BOFH alasan # 394:Jupiter adalah sejajar dengan Marikh.

%
BOFH alasan # 395:ACL berlebihan.

%
BOFH alasan # 396:pelayan mel dilanda UniSpammer.

%
BOFH alasan # 397:T-1 sesak akibat trafik lucah kepada pelayan berita.

%
BOFH alasan # 398:Data untuk intranet mendapat disalurkan melalui extranet dan mendarat di internet.

%
BOFH alasan # 399:Kami adalah 100% Microsoft Shop.

%
BOFH alasan # 400:Kami adalah Microsoft. Apa yang anda alami tidak menjadi masalah; ia adalah ciri tanpa izin.

%
BOFH alasan # 401:kakitangan jualan menjual produk kami tidak menawarkan.

%
BOFH alasan # 402:Setiausaha menghantar surat rantaian kepada semua 5000 pekerja.

%
BOFH alasan # 403:Pentadbir sistem tidak mendengar pager pergi kerana muzik keras daripada penceramah bar bilik.

%
BOFH alasan # 404:Pentadbir sistem sengaja dimusnahkan pager dengan tukul besi yang besar.

%
BOFH alasan # 405:Sysadmins tersedia kerana mereka berada dalam mesyuarat bercakap tentang mengapa mereka tidak tersedia begitu banyak.

%
BOFH alasan # 406:makanan kafeteria Bad mendarat semua sysadmins di hospital.

%
BOFH alasan # 407:Route mengepak di NAP.

%
BOFH alasan # 408:Komputer di bawah air kerana SYN banjir.

%
BOFH alasan # 409:The vulcan-kematian-cengkaman ping telah digunakan.

%
BOFH alasan # 410:konduit elektrik dalam bilik mesin lebur.

%
BOFH alasan # 411:kesesakan lalu lintas di Lebuhraya Maklumat.

%
BOFH alasan # 412:Radial Telemetri penyusupan

%
BOFH alasan # 413:Lembu tippers disebut-sebut lembu ke pelayan.

%
BOFH alasan # 414:pelepasan tachyon muatan sistem

%
BOFH alasan # 415:tetingkap Maintenance patah

%
BOFH alasan # 416:Kami berada di luar slot pada pelayan

%
BOFH alasan # 417:bilik komputer dipindahkan. Sistem kami adalah ke bawah pada hujung minggu.

%
BOFH alasan # 418:Sysadmins pertempuran sibuk SPAM.

%
BOFH alasan # 419:but semula berulang sistem gagal untuk menyelesaikan masalah

%
BOFH alasan # 420:Ciri tidak beta diuji

%
BOFH alasan # 421:pengawal domain tidak bertindak balas

%
BOFH alasan # 422:Orang lain mencuri alamat IP anda, hubungi detektif Internet!

%
BOFH alasan # 423:Ia tidak RFC-822 Syariah.

%
BOFH alasan # 424:operasi gagal kerana: tiada mesej untuk kesilapan ini (# 1014)

%
BOFH alasan # 425:berhenti sedikit menerima

%
BOFH alasan # 426:internet diperlukan untuk menangkap etherbunny yang

%
BOFH alasan # 427:rangkaian ke bawah, paket IP dihantar melalui UPS

%
BOFH alasan # 428:Kemas kini perisian tegar dalam mesin kopi

%
BOFH alasan # 429:anomali temporal

%
BOFH alasan # 430:Mouse mempunyai out-of-cheese-error

%
BOFH alasan # 431:Borg implan gagal

%
BOFH alasan # 432:Borg nanites telah dipenuhi pelayan

%
BOFH alasan # 433:ralat: seorang pengguna jahat yang ditemui di hadapan skrin

%
BOFH alasan # 434:Sila nyatakan jenis kecemasan teknikal

%
BOFH alasan # 435:Internet ditutup akibat penyelenggaraan

%
BOFH alasan # 436:Daemon melarikan diri dari pentagram

%
BOFH alasan # 437:bulatan tanaman dalam shell jagung

%
BOFH alasan # 438:sedikit melekit sudah longgar

%
BOFH alasan # 439:Java panas telah pergi sejuk

%
BOFH alasan # 440:Cache miss - sila ambil lebih baik bertujuan kali

%
BOFH alasan # 441:jadual hash mempunyai Woodworm

%
BOFH alasan # 442:Trojan kuda kehabisan rumput kering

%
BOFH alasan # 443:proses Zombie dikesan, mesin adalah berhantu.

%
BOFH alasan # 444:ralat limpahan dalam / dev / null

%
BOFH alasan # 445:cookie pelayar rosak - seseorang sedang mengamalkan makan di atasnya.

%
BOFH alasan # 446:Mailer-daemon sibuk membakar mesej anda di dalam neraka.

%
BOFH alasan # 447:Menurut Microsoft, ia adalah oleh reka bentuk

%
BOFH alasan # 448:vi perlu dinaik taraf ke VII

%
BOFH alasan # 449:Greenpeace free'd yang mallocs

%
BOFH alasan # 450:Pengganas terhempas kapal terbang ke dalam bilik server, perlu membuang / bin / sarat. (Rm -rf / bin / sarat)

%
BOFH alasan # 451:ayunan astropneumatic dalam air penyejukan

%
BOFH alasan # 452:Somebody berlari sistem yang beroperasi melalui penyemak ejaan.

%
BOFH alasan # 453:Spider serangan di bahagian-bahagian kes hangat

%
