* SynrG menyatakan bahawa bilangan soalan konfigurasi untuk menjawab dalam  'hantar mel' adalah bukan remeh
		-- David Leimbach

%
* James akan lebih terkesan jika kuasa ajaib netgod ini dapat menghentikan  berpecah di tempat pertama ...* Netgod nota pemaju debian adalah terkenal sukar untuk menarik perhatian
		-- David Leimbach

%
<Sel> perlu bantuan: paket pertama saya ke pembekal saya akan hilang :-(<Netgod> sel: dont menghantar yang pertama, bermula dengan # 2
		-- David Leimbach

%
<James> menghina saya. Saya begitu lame saya menghantar laporan pepijat untuk        debian-devel-perubahan
		-- David Leimbach

%
Saya tidak pernah terfikir bahawa saya akan melihat hari di mana Netscape adalah perisian percuma danX11 adalah hak milik. Kita hidup dalam masa yang menarik.
		-- Matt Kimball <mkimball@xmission.com>

%
<Jim> Lemme memastikan saya tidak membuang masa di sini ... bcwhite akan mengeluarkan      PKGS yang havent telah ditetapkan yang mempunyai pepijat cemerlang keterukan      "Penting". Betul atau salah?<JHM> jim: "penting" atau lebih tinggi. Benar.<Jim> Kemudian kita kira-kira untuk kehilangan ftp.debian.org dan dpkg :)* Netgod akan terlepas dpkg - ia adalah kadang-kadang berguna<Joey> Kami masih mempunyai rpm ....
		-- Matt Kimball <mkimball@xmission.com>

%
<JHM> Sebagai beban adalah tanda yang Debian penyenggara benar.
		-- Matt Kimball <mkimball@xmission.com>

%
<Overfiend> partycle: Saya serius melakukan perlu bercuti dari pakej ini.            Saya sebenarnya mempunyai DREAM yang bertentang memperkenalkan bug baru bodoh            ke dalam XBase-preinst malam tadi. Itu satu Bad Sign.
		-- Matt Kimball <mkimball@xmission.com>

%
Menulis perisian tidak bebas tidak adalah aktiviti beretika yang sah, jadi jikaorang-orang yang melakukan larian ini ke dalam masalah, itulah yang baik! Semua perniagaan berasaskanpada perisian tidak bebas patut gagal, dan lebih cepat lebih baik.
		-- Richard Stallman

%
perkhidmatan DNS Microsoft menamatkan luar biasa apabila ia recieves jawapankepada pertanyaan DNS yang tidak pernah dibuat. Betulkan Maklumat: Main DNS andaperkhidmatan di platform yang berbeza.
		-- BugTraq

%
* Dpkg tangan STU segelas besar vbeer* Joey mengambil bir dari belajar, anda terlalu muda;)* Cylord mengambil bir dari Joey, anda terlalu mabuk.* Cylord memberikan bir untuk Muggles.
		-- BugTraq

%
Mari kita rakyat pengagihan Debian GNU / Linux, untuk membentuklebih sistem operasi sempurna, mewujudkan kualiti, memastikan pasarankepelbagaian, menyediakan keperluan biasa dari pengguna komputer, menggalakkankeselamatan dan privasi, menggulingkan kuasa monopoli dalam komputerindustri perisian, dan mendapat restu kebebasan kepada diri kita sendiri danketurunan kita, memerintahkan dan mengukuhkan Perlembagaan ini untuk DebianGNU / Sistem Linux.
		-- BugTraq

%
"Ini adalah struktur element_data untuk unsur-unsur yang * ELEMENT_TYPE =FORM_TYPE_SELECT_ONE, FORM_TYPE_SELECT_MULT. * / / * * Bersarang lebih mendalamdan lebih mendalam, lebih keras dan lebih keras, pergi, pergi, oh, OH, OHHHHH !! * Maaf, mendapatterbawa-bawa di sana. * Lo_FormElementOptionData_struct / struct. "
		-- Mozilla source code

%
Walaupun tahun 2000 (Y2K) bukan satu isu bagi kami, semua Linuxpelaksanaan akan menerima kesan daripada 2038 (y2.038k) terbitan tahun. TheDebian Projek komited untuk bekerjasama dengan industri mengenai isu inidan kami akan mempunyai rancangan penuh dan strategi yang dicatatkan pada suku pertama2020.
		-- Mozilla source code

%
... Di manakah Stac elektronik apabila Microsoft mencipta Doublespace? Di manaadalah Xerox dan Apple apabila Microsoft mencipta GUI? Di mana AppleQuickTime apabila Microsoft mencipta video untuk Windows? Di manakah SpyglassInc Mosaic apabila Microsoft mencipta Explorer Internet? Di mana Sunapabila Microsoft mencipta Java?
		-- Mozilla source code

%
Saya minta maaf jika berikut berbunyi agresif dan berlebihan peribadi,tetapi itu gaya umum saya. - Ian Jackson
		-- Mozilla source code

%
"Masalah terbesar saya dengan RH (dan terutamanya pakej contrib RH) adalah bahawamereka TIDAK mempunyai apa-apa seperti dasar kami. Itulah salah satu sebab utamamengapa pakej mereka begitu buruk sekali dan pecah. Debian mempunyai kerja berpasukansisi membina pengedaran yang turun ke seni halus. "
		-- Mozilla source code

%
"Pengguna slackware tidak perkara itu. Dalam pengalaman saya, pengguna slackware adalahsama ada newbies keliru dengan konsep yang akan mempunyai masalah walaupun dengan tar, atau merekafanatik do-it-yourselfers yang tidak akan memasang orang lain pra-disusunbinari walaupun mereka telah dibayar untuk melakukannya. "
		-- Mozilla source code

%
<XinkeT> "Tuhan memberikan saya ketenangan untuk menerima perkara yang saya tidak boleh         berubah, berani untuk mengubah perkara yang saya boleh, dan kebijaksanaan         untuk menyembunyikan mayat orang yang saya terpaksa membunuh kerana mereka         mabuk benar aku. "
		-- Mozilla source code

%
* Gelap telah menukar topik di saluran #debian kepada: Malam ini: Selepas  bulan penyejukan-hati, Debian 2.0 adalah cukup akhirnya sejuk untuk  pelepasan.
		-- Mozilla source code

%
Saya duduk ketawa snidely ke dalam buku nota saya sehingga mereka menunjukkan kepada saya berjalan PCLinux. Dan oh! Ia seolah-olah langit dibuka dan Allah menyerahkan ke bawahklien OS begitu indah, begitu anggun, dan elegan yang satu jutapemaju Microsoft tidak boleh mengada-adakannya sekiranya mereka mempunyai seratustahun dan seribu peti daripada Kegoncangan cola.
		-- LAN Times

%
Saya duduk ketawa snidely ke dalam buku nota saya sehingga mereka menunjukkan kepada saya berjalan PCLinux .... Dan adakah PC ini tercekik? Adakah ia gagap? Adakah ia, walaupun sekali,mengatakan bahawa program ini telah menunjukkan prestasi operasi haram dan mesti ditutupturun? No. Dan ini adalah hanya pada pelanggan.
		-- LAN Times

%
"Saya fikir bahawa kebanyakan pemaju debian agak" kuat semangat "orangdengan satu tahap penghormatan pemahaman dan tahap yang tinggi semangat untuk apayang mereka anggap sebagai penting dalam pembangunan sistem debian itu. "
		-- Bill Leach

%
"Sebenarnya, satu-satunya pengagihan Linux yang pernah saya digunakan yang lulusrootshell ujian di luar kotak (hit rootshell pada masa yang dist adalahdikeluarkan dan lihat jika anda boleh memecahkan OS dengan skrip dari sana) adalahDebian. "
		-- seen on the Linux security-audit mailing list

%
* Culus takut perl - bahasa dengan kesilapan pilihan
		-- seen on the Linux security-audit mailing list

%
<Stu> anda perlu takut untuk menggunakan KDE kerana RMS mungkin datang kepada anda      rumah serta pecah monitor anda dengan kapak atau sesuatu :)
		-- seen on the Linux security-audit mailing list

%
"Dan saya benar-benar seperti debian 2.0 yang banyak i dirombak sepenuhnya yangconfig lalai sistem linux syarikat kami menjual dan dipasang semula apa-apasistem linux di pejabat dan di sini di rumah .. "
		-- seen on the Linux security-audit mailing list

%
<Davide> bagaimana pertarungan dasar dasar kepolisan dengan dasar untuk menukar         dasar kepolisan polis
		-- seen on the Linux security-audit mailing list

%
<Gelap> "Mari kita membentuk Linux Standard Linux Standards Association        Lembaga. Tujuan forum ini akan menjadi untuk menyeragamkan Linux        Standardisasi Organizations. "
		-- seen on the Linux security-audit mailing list

%
<Overfiend> Jangan datang menangis kepada saya tentang "menyusun 30 minit" anda !! Saya            perlu membina X Uphill mereka! Dalam salji! dengan terdedah            kaki! Dan kita tidak mempunyai penyusun! Kami terpaksa menterjemahkan            kod C untuk mnemonik DIRI!<Overfiend> Dan saya 18 sebelum kita mempunyai pemasang!
		-- seen on the Linux security-audit mailing list

%
NEW YORK (CNN) - Pengguna Internet yang membelanjakan walaupun beberapa jam seminggu dalam taliandi rumah mengalami tahap tinggi kemurungan dan kesepian daripada jikamereka telah menggunakan rangkaian komputer yang kurang kerap, The New York Timesdilaporkan Ahad. hasilnya ... terkejut kedua-dua penyelidik danpenaja, termasuk Intel Corp., Hewlett Packard, AT & T Penyelidikan danApple Computer.
		-- seen on the Linux security-audit mailing list

%
"Apa yang menarik, bagaimanapun, adalah susun atur am dan integrasisistem. Debian adalah pengagihan Linux benar-benar elegan; berhati mempunyaitelah diambil dalam penyediaan pakej dan penempatan mereka dalamsistem. Bilangan semata-mata pakej yang disediakan juga menarik .... "
		-- seen on the Linux security-audit mailing list

%
Debian Linux adalah pepejal, produk yang komprehensif, dan keseronokan tulen untukgunakan. Ia juga adalah besar untuk terlibat dengan kolektif Debian,keramahan dan semangat yang mengimbas kembali hari-hari awal Internet danrasa amat terbuka dan kerjasama global.
		-- seen on the Linux security-audit mailing list

%
<Banjir> boleh saya menulis kernel unix seperti dalam perl?
		-- seen on the Linux security-audit mailing list

%
<Banjir> netgod: Saya juga mempunyai "Evil Di dalam" T-shirt (w / Intel logo) .. pada        belakang ia menyatakan: "Apabila Pengangkatan itu datang, anda akan mempunyai akar?"
		-- seen on the Linux security-audit mailing list

%
<Zarkov> "NT 5.0. Semua bug dan sepuluh kali saiz kod!"
		-- seen on the Linux security-audit mailing list

%
<Culus> terdapat 150 meg masuk / tmp dir! DEAR TUHAN
		-- seen on the Linux security-audit mailing list

%
<Toor> netgod: apa yang anda ada dalam kernel anda ??? Sumber disusun untuk       memandu kapal angkasa ???<Spoo> masa untuk membuat zip yang memandu pemacu liut anda kemudian. jika kernel       doesn patut pada itu, kernel merupakan AI
		-- seen on the Linux security-audit mailing list

%
Sekarang saya akhirnya dapat menjelaskan kepada semua orang mengapa saya melakukan ini. Saya hanya mendapat $ 7 bernilaibarangan percuma untuk bekerja di Debian!
		-- seen on the Linux security-audit mailing list

%
<Ultima> netgod: Kalkulator saya mempunyai lebih daripada daftar x86, dan
		-- thats- sad

%
* Boren lambungan MATLAB di seluruh bilik dan berharap ia pecah kepada nombor  aproaching Harga yang dipamerkan tidak terhingga
		-- thats- sad

%
"... Ia adalah jauh lebih cepat daripada yang saya fikir ia akan menjadi, lebih cepatdaripada NT. Jika kelajuan bertambah lagi dilakukan kepada pelayan untuk perlawanan akhirpelepasan, Oracle akan dapat menghapuskan pantat mereka dengan SQL SERVER danmenyerahkan kembali kepada M $ manakala pentadbir Oracle ... berhijrah pangkalan data merekakepada Linux! "
		-- thats- sad

%
Penguasaan dunia, sudah tentu. Dan hampir tdk berpakaian perempuan. Siapa yang peduli jikayang dua puluh di bawah? - Linus Torvalds
		-- thats- sad

%
<Flav> Win 98 edisi Psychic: Kami akan memberitahu anda di mana anda akan esok
		-- thats- sad

%
<Zpx> ia menakjubkan bagaimana "tidak-pecah" debian dibandingkan dengan kendur dan rh
		-- thats- sad

%
<Gelap> "Hey, saya daripada projek ini dipanggil Debian ... pernah anda dengar itu?       Nama anda seolah-olah berada di sekumpulan barangan kami. "
		-- thats- sad

%
"Dalam kejadian yang jika gagal percieved daripada #debian kepimpinan projek adalahkuasa untuk mengambil tindakan drastik dan descisive untuk membetulkan kegagalan yang,termasuk dengan tidak terhad kepada membuang pegawai-pegawai, apointing pegawai barudan secara amnya menyalahgunakan kuasa "
		-- proposed amendment to Debian Constitution

%
<Overfiend> kami memanggil 2,2 _POTATO_ ??
		-- proposed amendment to Debian Constitution

%
<SirDibos> tidak Johnie Ingram melepak sini IRC?
		-- proposed amendment to Debian Constitution

%
* Twilight1 perlu menggantung Mozilla beanie dinosaur dalam patung jika  Netscape menjual keluar kepada Alot Of Kaunter rugi ..
		-- proposed amendment to Debian Constitution

%
<Lux> jika MacOS adalah untuk buta huruf komputer, kemudian windoze adalah untuk      masochists komputer
		-- proposed amendment to Debian Constitution

%
<Gelap> Culus: Membina replika lima meter tinggi daripada Empire State       Bangunan dengan klip kertas mengesankan. Melakukannya ditutup mata adalah       eleet.
		-- proposed amendment to Debian Constitution

%
Saya nampak sekarang: pencalonan keganasan ;-)        - Manojhaha! i mencalonkan manoj.
		-- seeS

%
<JHM> Bagaimanapun saya dapat pemaju Debian lebih menghormati 14 tahun Perempuan daripada     Microsoft Certified serf 14 tahun.
		-- seeS

%
<Culus> Ben: Adakah anda solumly bersumpah untuk membaca e-mel anda debian sekali sehari dan        tidak membenarkan orang ramai untuk berfikir anda MIA?<Ben> Culus: i berbuat demikian bersumpah
		-- seeS

%
"Saya tertanya-tanya jika ini adalah perlembagaan pertama dalam sejarah manusiadi mana anda perlu untuk mengira punca kuasa untuk menentukan sama ada usulpas. :-) "
		-- Seen on Slashdot

%
Ini adalah penyelesaian untuk masalah Debian .. dan kerana satu-satunya cara sebenaruntuk mewujudkan lebih banyak saudara-mara pemaju adalah untuk mempunyai kanak-kanak, kita memerlukan lebih banyakseks! Ia adalah pelaburan jangka panjang ... ia kerja itu sendiri yangmemuaskan!
		-- Craig Brozefsky

%
<Marcus> Dunham: Anda tahu bagaimana nombor nyata dibina daripada rasional         nombor dengan kelas kesetaraan urutan tumpu?<Dunham> marcus: ya.
		-- Craig Brozefsky

%
<Culus> "Hello?" "Baybee Hi" "Adakah anda Johnie Ingram?" "Untuk anda saya akan menjadi        sesiapa "" ermm .. Adakah anda menjual CD mengendap-endap ini? "" Saya suka slinkies "
		-- Craig Brozefsky

%
<Overfiend> xhost + localhost hanya boleh dilakukan oleh orang-orang yang akan            cat nama hos dan kata akar mereka di antara negeri            melalaikan.
		-- Craig Brozefsky

%
<JHM> AIX - yang Unix dari alam semesta di mana Spock mempunyai janggut.
		-- Craig Brozefsky

%
<Knghtbrd> Kajian membuktikan bahawa kajian menyebabkan barah pada 43% daripada makmal           tikus<CQ> knghtbrd- yeah, tetapi 78% daripada mereka yang berada di luar statistik sebanyak 52% ...
		-- Craig Brozefsky

%
<Stu> apt: bug<Apt>! Bug bodoh<Dpkg> apt: bodoh? apa itu?<Apt> dpkg: saya tidak tahu<Dpkg> apt Beauty adalah di mata pemegang bir ...<Apt> i sudah mempunyai cara itu, dpkg.
		-- Craig Brozefsky

%
<Muggles> saya cuba untuk meyakinkan beberapa admin NETCOM i tahu untuk menukar          untuk Debian dari RH, netgod, tetapi mereka DAMN degil<Muggles> mengapa pengguna RH jadi terkutuk diketuai keras?<Espy> itu topi
		-- Craig Brozefsky

%
<Doogie> Debian - Semua kuasa, tanpa topi bodoh.
		-- Craig Brozefsky

%
Berapa bulan kita akan berada di belakang mereka [Redhat] dengan glibc yangmelepaskan? "
		-- Jim Pick, 8 months before Debian 2.0 is finally released

%
Tujuan mempunyai senarai mel daripada mempunyai kumpulan berita adalah untukmeletakkan halangan kepada kemasukan yang melindungi senarai dan pengguna mereka daripencerobohan oleh gerombolan yang tidak berpendidikan umum.
		-- Ian Jackson

%
Sebahagian besar daripada kita merasakan bahawa pemasaran jenis seperti senjata berbahaya - menyimpan'Em dipunggah dan dikurung di dalam almari, dan hanya membawa mereka keluar apabilaanda memerlukan mereka untuk melakukan pekerjaan.
		-- Craig Sanders

%
<BenC> Cerb: kita melanggan anda untuk Debian perjuangan sebagai moderator<BenC> Cerb: peraturan senarai adalah, 1) tiada e-mel yang baik, 2) tidak rasa bersalah
		-- Craig Sanders

%
<Teknix> syarikat telekomunikasi tempatan telah mengakui bahawa seseorang "yang disokong ke dalam         butang pada suis "dan mengambil rangkaian ATM keseluruhan ke bawah<Netgod> diharapkan kini router direka lebih baik, jadi "rangkaian         off "swtich adalah di belakang
		-- Craig Sanders

%
<Overfiend> Thunder-: apabila anda mendapat {MessagesLikeThisFromYourHardDrive}<Overfiend> Thunder-: sama ada cara {TheDriverIsScrewy}<Overfiend> atau<Overfiend> {YourDriveIsFlakingOut BackUpYourDataBeforeIt'sTooLate            PrayToGod}
		-- Craig Sanders

%
<Apt> ia telah berkata bahawa redhat adalah perkara yang Marc Ewing memakai pada      kepalanya.
		-- Craig Sanders

%
<MrCurious> oleh kuasa Greyskull<MrCurious> seseorang beritahu saya larangan untuk meletakkan<Sopwith> mrcurious: * .debian.org, * .novare.net<PhilX> * .debian.org. itu hebat.
		-- Seen on LinuxNet #linux

%
"Apakah ini beritahu saya? Bahawa jika Microsoft adalah perisian yang terakhirSyarikat dibiarkan di dunia, 13% daripada penduduk Amerika Syarikat akan mengerukjualan murah & Muhibah untuk lama TRS-80-an, mesin CPM & Apple] [ 's sebelummereka akan membeli Microsoft. Yang tidak betul-betul satu pengesahan dering. "
		-- Seen on Slashdot

%
"Bruce McKinney, pengarang daripada Tegar Visual Basic, telah mengumumkan bahawadia bosan dengan VB dan tidak akan menulis edisi ke-3 dari bukunya. Thequote terbaik adalah pada akhir: 'Saya tidak memerlukan bahasa yang direka oleh tumpuan yangkumpulan '. "
		-- Seen on Slashdot

%
<Cylord> ia boleh diterima dengan dasar debian jika kita dimasukkan crontab yang         secara lalai ke dalam kentang yang dihantar melalui email bill.gates@microsoft.com         setiap pagi dengan e-mel yang membaca, "Jangan bimbang, linux adalah         fad ... "
		-- Seen on Slashdot

%
* Overfiend Ponders melakukan satu NMU daripada asclock, di mana beliau hanya perubahan  keterangan tambahan kepada "Jika anda bengkok ke atas dan meletakkan kepala anda di antara  kaki anda, anda boleh membaca masa off assclock anda. "<Doogie> Overfiend: pergi ke tidur.
		-- Seen on Slashdot

%
<Reed> Adalah penting untuk ambil perhatian bahawa sebab utama Empayar Rom       gagal adalah bahawa mereka tidak mempunyai konsep sifar ... dengan itu mereka tidak dapat       menguji kejayaan atau kegagalan program C mereka.
		-- Seen on Slashdot

%
Sejak bila mempunyai tujuan debian adalah untuk menyenangkan hati kepentinganjisim pengguna tidak mahir? - Steve Shorter
		-- Seen on Slashdot

%
<Joeyh> netgod: er, adalah ini 2.2.0 pakej 2.0.0pre9 atau adakah anda mempunyai        talian terus dengan tuhan-tuhan?<Netgod> joeyh: i mempunyai talian terus
		-- Seen on Slashdot

%
<_Anarchy_> Argh .. siapa yang menyampaikan beg kertas 8)
		-- Seen on Slashdot

%
<Janggal> sesiapa sahaja di seluruh?<Flav> tidak, kita semua poligon yang tidak teratur
		-- Seen on Slashdot

%
<Culus> OH MY GOD BUKAN QUOTE GENERATOR RAWAK<Netgod> sesungguhnya anda didnt berfikir bahawa adalah statik? bagaimana tempang yang akan? :-)
		-- Seen on Slashdot

%
ketidakwujudan Mere adalah alasan yang lemah untuk mengisytiharkan sesuatu unseeable. anda* * Boleh melihat naga. Anda hanya perlu melihat ke arah yang betul.
		-- John Hasler

%
<Pasi> gcc adalah pemampat yang terbaik yang pernah dialihkan kepada linux. ia boleh bertukar         12MB sumber kernel (dan itu .debbed) ke dalam kernel 500k
		-- John Hasler

%
<Manoj> I * seperti * ayam
		-- John Hasler

%
 [] DOGBERT [2] Richard Stallman [3] Buffy SUMMERS [1] MANOJ Srivastava [4] NONE di atas
		-- Debian Project Leader 1999 ballot

%
<Oryn> ada orang yang mengetahui jika terdapat versi dpkg untuk redhat?
		-- Debian Project Leader 1999 ballot

%
Acme-meriam (3,1415) tidak stabil; segera = rendah  * Ditambah keselamatan untuk mengelakkan perceraian anggota pengendali, menutup: bug # 98765,    bug # 98713, # 98.714.  * Ditambah manpage. ditutup: # 98.725.
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
! Netgod: *! masa berlalu apabila youre menggunakan linux! Doogie: *! yeah, gelung tak terhingga dalam 5 saat.! Teknix: *! telah sesiapa semula diuji-bahawa dengan 2.2.x?! Netgod: *! yeah, 4 saat sekarang
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
* Gelap menyapa Liw dengan katak kuning kecil.* Liw mencium katak dan jam tangan ia mengubah kepada nerd yang indah  Perempuan, membawanya keluar untuk ais krim, dan hidup bahagia selama-lamanya selepas  dengan dia<Gelap> Liw: Umm-lama untuk mempunyai katak kembali?
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
* Culus difikirkan kita perlu pergi ke pameran perdagangan dan lihat berapa banyak orang yang kita  boleh membunuh dengan membuang cds debian pada mereka
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Gelap> "Ya, nama-Mu, Saya mempunyai RSA kod penyulitan Tattood pada saya        zakar. Boleh saya tunjukkan juri? "
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Knghtbrd> anda orang semua tidak siuman.<Joey> kuda: pasti, itulah sebabnya kita bekerja pada Debian.<JHM> Knghtbrd: berhubung dengan Nutcase dalaman anda.
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Culus> Saens menunjukkan ada bug kurang daripada 3 tcp / ip dalam 2.2.3
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Mercury> alexsh: Be / SANGAT / cairful, anda boleh, jika bernasib baik anda, goreng anda          papan induk ..<Knghtbrd> Mercury - bunyi seperti menyeronokkan
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<RCW> gelap: kaldera?<Knghtbrd> RCW - yang tidak pengedaran, ia adalah sumpahan<RCW> Knghtbrd: ia adalah satu pengagihan terkutuk
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
Perisian adalah seperti seks, lebih baik apabila ia percuma. - Linus Torvalds
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Gelap> Knghtbrd: Kami mempunyai banyak whatevers.<Knghtbrd> gelap - Dalam Debian? Hell yeah kita lakukan!
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
Saya melakukannya hanya untuk kencing perniagaan anda. :-P
		-- Branden Robinson in a message to debian-devel

%
perisian yang diperlukan Win95 atau lebih baik, jadi saya memasang Linux.
		-- Branden Robinson in a message to debian-devel

%
10) tidak ada 10, tetapi ia kelihatan seperti nombor yang bagus :)
		-- Wichert Akkerman

%
Eric Raymond: Saya mahu hidup dalam dunia di mana perisian tidak menghisap.Richard Stallman: Mana-mana perisian yang tidak bebas menghisap.Linus Torvalds: Saya berminat dalam bir percuma.Richard Stallman: Tidak mengapa, selagi saya tidak perlu meminumnya. Saya                   tidak suka bir.
		-- LinuxWorld Expo panel, 4 March 1999

%
Saya bukan orang waras ... - Bruce Perens
		-- LinuxWorld Expo panel, 4 March 1999

%
Secara peribadi, saya tidak sering bercakap tentang sosial yang baik kerana apabila saya mendengar lainorang bercakap tentang sosial yang baik, itulah apabila saya mencapai pistol saya.
		-- Eric Raymond

%
Jika kita mahu sesuatu yang baik untuk dilahirkan dalam tempoh sembilan bulan, maka seks perluberlaku. Kami mahu mempunyai jenis seks yang boleh diterima dan menyeronokkan untuk kedua-duaorang, bukan jenis yang mana seseorang itu mendapat diskrukan. Mari kita mendapatkan beberapa silangpersenyawaan, tetapi tidak seseorang mendapat diskrukan.
		-- Larry Wall

%
Kita semua tahu Linux besar ... ia gelung tak terhingga dalam 5 saat.
		-- Linus Torvalds

%
YES! YES! YES! Oh, YES! (Ooops, saya terdengar seperti Meg Ryan ;-)
		-- Ian Nandhra

%
<Knghtbrd> Jika saya mula menulis esei mengenai Software Percuma untuk slashdot,           sila menembak saya.
		-- Ian Nandhra

%
<RoboHak> hmm, makan tengah hari tidak bunyi seperti idea yang baik<Knghtbrd> akan rasa seperti satu idea yang baik juga
		-- Ian Nandhra

%
catatan tambahan: - I aku akan * ini * berhampiran dengan berjalan di dalam bilik server dengansepasang pemotong bolt, dan tukul kayu yang besar, ketawa seperti orang gila danmemotong semua i boleh muat pemotong bolt sekitar. dan memukul yangyang saya tidak boleh. jadi jika i seolah-olah separuh tidak keruan, atau hanya benar-benar benar-benar * * jahatpada masa-masa, sila memaafkan saya. tekanan tidak adalah satu perkara yang cantik. }; P
		-- Phillip R. Jaenke

%
Tiap-tiap syarikat mengadu mengenai amalan perniagaan Microsoft hanya satumeningkat belukar. Mereka kelihatan indah dan bau yang bagus. Setelah syarikat bertuah dethronesMicrosoft mereka akan menumpahkan kelopak mereka untuk mendedahkan duri di bawahnya. Aduri dengan nama lain akan menyakiti sebanyak.
		-- Phillip R. Jaenke

%
Sesuatu perlu SelesaiIni adalah sesuatu yangOleh itu, ini mesti Selesai
		-- The Thatcherite Syllogism

%
<Knghtbrd> xtifr - berhati-hati james apabila dia off ubatnya =>
		-- The Thatcherite Syllogism

%
Sikap acuh tak acuh pasti akan kejatuhan manusia, tetapi yang peduli?
		-- The Thatcherite Syllogism

%
Jangan sekali-kali memandang rendah kuasa kebodohan manusia.
		-- Robert A. Heinlein

%
Emas, n .:  A logam mudah dibentuk lembut agak sukar didapati di pengedaran. Ia dilombong  jauh di dalam bumi dengan orang miskin yang kemudian memberikannya kepada orang-orang kaya yang sebaik  menanamnya semula di bumi di penjara besar, walaupun emas telah tidak dilakukan  apa-apa kepada mereka.
		-- Mike Harding, "The Armchair Anarchist's Almanac"

%
* Lilo dengan ini mengisytiharkan OPN sakit maya dalam keldai :)
		-- Mike Harding, "The Armchair Anarchist's Almanac"

%
"Mereka adalah kedua-dua perniagaan - jika anda telah memberi mereka wang yang cukup, sayapasti mereka akan melakukan apa sahaja yang anda neraka bertanya: -> "
		-- David Welton

%
"Anda mempunyai hak untuk tidak asshole. Jika anda melepaskan hak yangsemua yang anda katakan dan jangan dalam sini akan diadakan terhadap anda. Jika anda tidak bolehmampu untuk berhenti menjadi satu asshole maka seseorang akan dilantik untuk menendanganda Segi di sini. "
		-- Your rights as an irc addict

%
* Simunye begitu gembira dia mempunyai ibu beliau gen<Dellaran> anda lebih baik memberikan mereka kembali sebelum dia rindukan mereka!
		-- Your rights as an irc addict

%
<Iambe> conning orang yang paling intellegent di planet itu tidak mudah
		-- Your rights as an irc addict

%
California, n .:    Dari Latin "calor", yang bermaksud "haba" (seperti yang dalam bahasa Inggeris "kalori" atauSepanyol "caliente"); dan "fornia" untuk "hubungan seks" atau"Zina." Oleh itu: Tierra de California, "tanah seks panas."
		-- Ed Moran

%
* Caytln slaps Lisa<Caytln> Catfight: P<LisaHere> Watch ia girl, saya suka itu.<LisaHere> :)<Caytln> angka: D
		-- Ed Moran

%
<MFGolfBal> rit / ara: Ada sesuatu yang benar-benar gila mengenai UNIX            seluar dalam ...
		-- Ed Moran

%
The X Window System:  UNIX persekitaran grafik standard. Dengan Linux, ini biasanya  XFree86 (http://www.xfree86.org). Anda boleh memanggil ia X, XFree, X  Window System, XF86, atau pelbagai perkara lain. Memanggilnya 'XWindows' dan  seseorang akan menampar anda dan anda akan berhak menerimanya.
		-- Ed Moran

%
<Knghtbrd> "The pengumpul mata wang di luar talian." "Saya mengalihkan walaupun           gandingan menengah. Jika kita semula menyelaraskan kita fasa manifold           harus dapat menggunakan plasma induktor matriks secara manual           melancarkan siri spinoff cheesy baru. "* Mengeluh ShadwDrgn<Fasa> anda meninggalkan pancarongga saya sahaja<Fasa>!
		-- Ed Moran

%
* Türken difikirkan anak-anak kecil benar-benar comel ... especialyy apabila  mereka seseorang lain.
		-- Ed Moran

%
* Mengeluh Overfiend<Overfiend> Netscape menghisap.<Overfiend> Ia adalah sebuah rumah kad berehat di atas katil daripada pasir hanyut.<Espy> semasa gempa bumi<Overfiend> dalam puting beliung
		-- Ed Moran

%
<SilverStr> etika media adalah oxymoron, sama seperti Udang Jumbo dan            Microsoft Works.<MonkAway> apatah NT Keselamatan
		-- Ed Moran

%
<Silvrbear> oxymorons? Aku melihat seorang semalam - risalah mengenai "Taco Bell            Maklumat Pemakanan "
		-- Ed Moran

%
* Knghtbrd melepaskan sepasang dua senapang berlaras snurf dan penutup  jesus dengan dart snurf<Jesus> Meany: P
		-- Ed Moran

%
<Jgoerzen> doogie: anda bunyi :-) sangat tidak stabil<Knghtbrd> jgoerzen - dia.* Doogie BOP Knghtbrd<Knghtbrd> Lihat? Menggunakan kekerasan = D
		-- Ed Moran

%
Saya juga telah menjadi peminat Unix besar sejak saya menyedari bahawa SCO tidakUnix. - Dennis Baker
		-- Ed Moran

%
<Dracus> Ctrl + Pilihan + Command + P + R<Knghtbrd> dracus - YE GODS! Yang lebih buruk daripada Emacs!<LauraDax> hehehehe<Dracus> tidak bertanya apa yang tidak: P
		-- Ed Moran

%
<Iambe> anda tidak Nutcase yang<Knghtbrd> Anda jelas tidak tahu saya cukup baik lagi. =>
		-- Ed Moran

%
* Aj difikirkan Kb ^ Zzz patut memilih perkara-perkara yang berbeza untuk bermimpi tentang daripada   resolusi dan perubahan dasar umum.<Kb ^ Zzz> aj - memberitahu saya mengenainya, ini adalah Bad Daftar
		-- Ed Moran

%
<Crow_> hmm, terdapat pilihan --now-keparat untuk exim?
		-- Ed Moran

%
<DarthVadr> Kira: SERTAI DARK SIDE, SATU MUDA.<Kira> darth, saya * saya * sisi gelap.
		-- Ed Moran

%
<Netgod> feanor: u tidak tahu kedalaman stupidty undang-undang amerika
		-- Ed Moran

%
Sesiapa yang berdiri di dalam tengah-tengah jalan yang kelihatan seperti mangsa jalanan kepada saya.
		-- Linus Torvalds

%
<Lilo> "PLEASE MENGHORMATI HAK INTELEK!"<Lilo> "Sila menunjukkan akal." ;)
		-- Linus Torvalds

%
<Knghtbrd> feanor - Isu-isu lesen adalah penting. Jika kita tidak menonton kami           keledai sekarang, akan seseorang datang dan menggigit kita kemudian ...
		-- Linus Torvalds

%
"Sekarang kita akan mempunyai untuk membunuh anda."
		-- Linus Torvalds

%
* Knghtbrd boleh sudah membayangkan: "Subject: [NAK MENYEDIAKAN UNTUK CADANGAN   PEMFAILAN LAPORAN BUG] kesilapan menaip dalam dokumen polisi "
		-- Linus Torvalds

%
<Netgod> heh thats tujuan yang hilang, seperti sebutan yang betul         "Perhiasan"<Netgod> memberikan sehingga :-)<Bijaksana> dan ejaan yang betul bagi "warna" :)<BenC> heh<Bijaksana> dan aluminium<BenC> atau senjata nuklear<Bijaksana> yang anda threating saya yankee?<Bijaksana> hanya kerana kita tidak mempunyai bom ...<BenC> back off ya perut kuning
		-- Linus Torvalds

%
<LauraDax>! Tuhan dilihat<Tabi-> LauraDax, saya tidak ingat melihat "tuhan"
		-- Linus Torvalds

%
<Kira> adalah perang pembedahan di mana anda pergi memberikan tentera asing pekerjaan hidung?
		-- Linus Torvalds

%
<Xtifr> Athena Persekitaran Desktop! Dalam hati anda, anda * tahu * ia adalah        pilihan yang tepat! :)* Xtifr Knghtbrd THWAPS
		-- Linus Torvalds

%
<Knghtbrd> shaleh - najis hanya WEIRD.<Espy> heh, bersih sejuk<Knghtbrd> Espy - dan pelik.<Espy> ya, pelik juga
		-- Linus Torvalds

%
<Xtifr> implan otak secara langsung :)<Knghtbrd> xtifr - yah, kemudian menggunakan komputer sebenarnya akan memerlukan beberapa           haprak ini untuk berfikir!<Knghtbrd>;>
		-- Linus Torvalds

%
<Knghtbrd> Overfiend - BTW, selepas kami telah menemui X mengambil semua 1.4 gig           untuk membina, adakah anda bersedia mengakui bahawa X adalah bloatware? =><Overfiend> KB: terdapat jurang 16 1/2 minit dalam jawapan saya<Fak> knghtbrd: bukti wujud bahawa X adalah hanya * 2 * windowing paling teruk      sistem;)
		-- Linus Torvalds

%
<Liw> celaka, pergerakan tetikus autonomi bermula biasanya selepas saya menggunakan      butang tetikus<Wichert> tidak menggunakan butang tetikus kemudian :)<Liw> yeah, betul :)
		-- Linus Torvalds

%
<Knghtbrd> anda tahu, Linux memerlukan permainan platform dibintangi Tux<Knghtbrd> agak Super Marioish, tetapi dengan Tux dan perkara-perkara seperti siber sedikit           bug dan borgs dan perkara seperti ...<Knghtbrd> Dan anda perlu melompat billgatus lalu dan tekan kekunci untuk menggugurkan beliau           ke dalam lava dan kemudian anda melihat beberapa lelaki yang kelihatan seperti RMS           atau seseorang berkata "Terima kasih kerana menyelamatkan saya Tux, tetapi Linus           Torvalds adalah di istana yang lain! "
		-- Linus Torvalds

%
<Thoth_> Ya, baik itulah sebabnya ia bernombor 2.3.1 ... ia adalah untuk orang-orang kita         yang terlepas uptime NT-suka
		-- Linus Torvalds

%
<Shinobi> Terdapat beberapa perkara yang lebih buruk daripada Perl .... ASP terlintas di fikiran
		-- Linus Torvalds

%
* M2 renungan pada monitor ... ia kelihatan seperti hamburger ...<Knghtbrd> m2 - itu adalah satu petanda yang tidak baik
		-- Linus Torvalds

%
<Knghtbrd> Serahkan kepada Manoj untuk memanggil procmail "lemah"
		-- Linus Torvalds

%
<Crow-> Manoj: baik, i cant memahami hal-hal seperti "s / 3 # $% ^% {]] [@ f245}"<Manoj> Crow: Itu tidak cukup undang-undang ;-)<Knghtbrd> Manoj - bagaimana seseorang akan membuat "s / 3 # $% ^% {]] [@ f245}" undang-undang           anyway? (Dan apa yang ia akan lakukan? Hehe)<Manoj> Knghtbrd: Anda perlu untuk menyelesaikan s /// bersuara.<Knghtbrd> oh, bahawa semua?
		-- Linus Torvalds

%
<Kira> Ada, satu-satunya bahasa bertulis kepada Milspec.<Mikster> <rasa tidak suka>
		-- Linus Torvalds

%
<BenC> -include ../../debian/el33t.h<BenC> 'hantar mel' build ... nama header pelik :)<Isildur> hahaha* Laffs netgod<Netgod> BenC: boleh u memberitahu i digunakan untuk mengekalkan 'hantar mel'? : P<BenC> heh :)
		-- Linus Torvalds

%
<Fasa> no ... Saya musn't mempunyai kopi lebih !!! ;)<Simunye> pasti yu melakukan Phase :)<Fasa> anda benar-benar mahu saya memantul dari siling?<Simunye> Yesh :)<Kira_> memantul dari siling adalah gewd<Fasa> ok, itu adalah satu soalan yang bodoh<Kira_> ia splatting di tingkat yang masalahnya.
		-- Linus Torvalds

%
<Kensey> RMS untuk Presiden ???<RelDrgn> ... atau ESR, dia mahu pekerjaan baru;)
		-- Linus Torvalds

%
Oh tidak, tidak lagi.
		-- Manoj Srivastava

%
<Knghtbrd> Diberikan, RMS ialah seorang fanatik, saya tidak menafikan ini. Saya juga akan mengatakan           dia sakit diraja dalam keldai kebanyakan masa. Tetapi dia           masih lebih kerap daripada tidak betul, dan dia berhak beberapa tahap           kredit dan menghormati pekerjaannya. Kami TIDAK akan berada di sini hari ini           tanpa dia.
		-- Manoj Srivastava

%
<Espy> esok akan ada gangguan yang besar dalam tenaga kerja
		-- May 18, 1999

%
Saya disleksia daripada Borg. Bersedia untuk mempunyai berlapis pantat anda.
		-- May 18, 1999

%
<NeonKttn> saya mempunyai rakan yang melekat saya dalam almari beliau semasa Highschool beacuse Saya           tidak akan percaya bahawa teman lelakinya tahu mengenai foreplay ...<NeonKttn> Saya Shoulda dibawa popcorn. :)
		-- May 18, 1999

%
<Knghtbrd> hardcopy adalah untuk wussies<Topher> penyenaraian program komputer .... depan, pada hardcopy
		-- May 18, 1999

%
<Kceee ^> Saya benci pengguna<Knghtbrd> anda bunyi seperti pentadbir sistem sudah!
		-- May 18, 1999

%
<Change_m2> Will LINUX pernah memotong roti dihiris sebagai pencapaian # 1            manusia?
		-- May 18, 1999

%
<Aph> manoj akan kacang pada perang salib bug penetapan! woo woo!<Knghtbrd> manoj pergi kacang lama dahulu. tetapi penetapan bug yang sejuk =>
		-- May 18, 1999

%
<RCW> mereka nampaknya-bakteria seperti cacing warna-warni yang keluar dari      backorifice microsoft ini<RCW> itulah logo backoffice yang
		-- May 18, 1999

%
* Simunye adalah pada oc3-> oc12<Daem0n> Simmy: menggigit saya. :)<Simunye> daemon: okay :)
		-- May 18, 1999

%
<Overfiend> lilo: baik maka, anda mungkin pemikir yang bertanggungjawab.            Selamat datang ke kelab yang sangat kecil.<Lilo> Overfiend: mengalu-alukan saya apabila anda menyertai :)
		-- May 18, 1999

%
Pada asasnya, saya mahu orang tahu bahawa apabila mereka menggunakan modul binari sahaja,ia adalah masalah MEREKA. Saya mahu orang tahu bahawa dalam tulang mereka, dan sayamahu ia berseru dari bumbung. Saya mahu orang ramai untuk bangun dalampeluh sejuk setiap sekali-sekala jika mereka menggunakan modul binari sahaja.
		-- Linus Torvalds

%
* Wichert_ membayangkan master tanpa MTA<James> Wichert: ehm? yang mungkin menghalang peformance daripada BTS: p
		-- Linus Torvalds

%
<Gecko> Hmm ... Saya tertanya-tanya apa lagi yang seperates Debian dari yang lain daripada        edaran Linux.<Knghtbrd> gecko - Kami Jangan menghisap<Gecko> Knghtbrd: anda tidak mengatakan bahawa apabila menangani sekumpulan orang        DARIPADA orang distro<Knghtbrd> gecko - mata.
		-- Linus Torvalds

%
Oleh kerana model pembangunan sumber tertutup XFree ia adalah mustahiluntuk menyokong, atau membuat spekulasi mengenai, ciri-ciri dalam siaran sebelum atau betadaripada XFree.
		-- Marcus Sundberg

%
>> Saya tidak benar-benar menganggap bible-KJV-teks sebagai dokumen teknikal,>> Tetapi ... :)> Ia manual - untuk hidup.Tetapi ia tidak dikemaskini dalam masa yang lama, ramai akan mengatakan bahawa itusedih ketinggalan zaman, dan penyelenggara hulu tidak bertindak balas kepada beliaue-mel. :-)        - Branden Robinson, Oliver Elphick, dan Chris Waters dalam           mesej kepada debian-dasar
		-- Marcus Sundberg

%
<Knghtbrd> Saya boleh memikirkan banyak orang yang memerlukan PENGGUNA = ID10T entah dimana!
		-- Marcus Sundberg

%
<Slashdot> geograpy US saya ialah buruk ... lol<Knghtbrd> jadi kepunyaan saya dan saya tinggal di sini
		-- Marcus Sundberg

%
Moonchild tanpa pendapat? Iblis skating untuk bekerja esok!
		-- Brett Manz

%
<Knghtbrd> saya benar-benar tidak mahu banyak pada semua ... Hanya perkataan yang baik, yang           wanita yang menarik, dan LEBAR JALUR UNLIMITED !!
		-- Brett Manz

%
<Knghtbrd> Jika kita berdua kanan (Saya meneka kami) Saya Bukan Sangat gembira.* Minupla tangan anda yang kurang benar anugerah tahun.
		-- Brett Manz

%
Kali terakhir saya mempunyai hubungan intim dengan manusia lain adalah lebih kepadapengalaman yang menyakitkan ... Saya lebih suka ...;)
		-- Brett Manz

%
<Apple_IIe> sesiapa yang melihat kad 80 ruangan saya?
		-- Brett Manz

%
<Slackware> uh oh, apa yang perlu saya mula :)<Debian> rofl ... distro nick peperangan.* Slackware hanya menunggu / nick Gnome, / nick KDE, dan kemudian perang dunia 4   untuk keluar<WinNT>: OP<OpenBSD> <itik><PalmOS> :)<Slackware> no'one akan berani / nick RedHat<Tru64> mew.
		-- Brett Manz

%
<Crow-> im fcucking druk* Knghtbrd memastikan untuk log semua Crow- berkata malam ini ...<MrBump> Heheh<MrBump> Dia kata dia akan berkahwin dengan saya! tak guna!!<Crow-> dude ada cara<Knghtbrd> MrBump - dia bukan BAHAWA mabuk<MrBump> Knghtbrd: Saya dihancurkan: o)
		-- Brett Manz

%
<Knghtbrd> aggh!<Knghtbrd> JADIKAN IT STOP!<Knghtbrd> JADIKAN IT STOP !!
		-- Brett Manz

%
<Knghtbrd> RoboHak - okay, patch tidak rosak, tetapi otak saya           nampaknya adalah<Wc> bahawa apa-apa yang baru (;<Knghtbrd> wc - diam.<Knghtbrd> =>
		-- Brett Manz

%
<DPG> rakyat Amerika yang pelik ....<Xtifr> Californians walaupun weirder<Knghtbrd> xtifr mempunyai mata ...
		-- Brett Manz

%
* Woot tersenyum tenang.<Woot> Saya tidak mahu kelihatan lebih bersemangat tentang mendapatkan ke dalam knghtbrd ini       siglist.
		-- Brett Manz

%
<Culus> DHD: R anda sebahagian daripada debian overstructure rahsia?<DHD> no. tidak ada debian overstructure rahsia.<Sinar kosmos> walaupun, sekarang bahawa seseorang membawa perkara ini, mari kita mulakan satu            :-)<Knghtbrd> Sinar kosmos - mengapa tidak, bunyi seperti cara yang menyeronokkan untuk menghabiskan           petang = D
		-- Brett Manz

%
<Xtifr> anda tidak perlu menjadi gila untuk bekerja di sini .... oh tunggu, ya anda lakukan!        :)
		-- Brett Manz

%
* O-o sentiasa seperti debmake kerana dia tahu betul-betul apa yang ia akan lakukan ...<Ibid> o-o: anda akan ;-)
		-- Brett Manz

%
2.3.1 telah dikeluarkan. Orang baru dalam permainan ini harus ingat bahawa2.3. * Siaran adalah biji pembangunan, tanpa jaminan bahawa merekatidak akan menyebabkan sistem anda untuk melakukan perkara yang dahsyat seperti rasuahcakera, terbakar, atau mula berjalan penanda aras Mindcraft.
		-- Slashdot

%
melakukan {    :} Semasa (HELL_FROZEN_OVER!);
		-- Slashdot

%
0 7 * * * echo "... Linux hanya trend" | mail billg@microsoft.com -s = "Dan ingatlah ..."
		-- Slashdot

%
<Hop> kb: Saya menuntut integriti dan kejujuran dalam orang-orang yang saya lakukan perniagaan dengan<Hop> i tahu permintaan saya adalah tidak munasabah, tetapi lelaki yang boleh bermimpi, boleh kan?
		-- Slashdot

%
<Jgoerzen> stu: ahh mesin itu. Jangan anda tidak berfikir bahawa sesuatu yang bernama           Stallman layak untuk menjadi Alpha? :-)<Stu> jgoerzen: tidak, sebenarnya, saya prolly lebih cenderung untuk menamakan 386      dengan 4 megs RAM dan 40 meg cakera keras Stallman.<Stu> dengan kes besar lemak yang membuat tan bunyi dan mainan kerincingan lantai* Knghtbrd jatuh ke lantai memegang sisinya ketawa<Belajar> dan ..<Stu> double ketinggian cakera keras
		-- Slashdot

%
Klingon panggilan fungsi tidak mempunyai 'parameter' - mereka mempunyai 'hujah'
		-- and they ALWAYS WIN THEM.

%
* Knghtktty tidak akan bertanya bagaimana zucchini mendapat ke dalam perbincangan ...
		-- and they ALWAYS WIN THEM.

%
<Knghtbrd> Subject: [GR CADANGAN] Sekiranya kita mengundi mengenai perkara-perkara yang remeh?
		-- and they ALWAYS WIN THEM.

%
<Woot> Letakkan * yang * di dalam kamu .sig dan asap itu, Knghtbrd.<Culus> Anda tahu dia akan membaca ini:><Woot> heheheheh.
		-- and they ALWAYS WIN THEM.

%
"Sebagai perjalanan anda melalui kehidupan mengambil satu minit setiap sekarang dan kemudian untuk memberiberfikir untuk rakan-rakan yang lain. Dia boleh merancang sesuatu. "
		-- Hagar the Horrible

%
<Knghtbrd> Okay, hai bangsa telah mula bercakap mengenai aplikasi BSDM daripada           perkakasan rangkaian ... Saya fikir saya akan lari dan melakukan sesuatu yang berguna           dan Debianish dan kekal OUT yang satu ini ...<Knghtbrd> (untuk perubahan)
		-- Hagar the Horrible

%
<Knghtbrd> mariab - tidak fikir Debian tidak mempunyai beberapa yang sangat bodoh dan           bug jelas sebelum<Knghtbrd> sudah tentu, kita biasanya menetapkan kita SEBELUM kita melepaskan = D
		-- Hagar the Horrible

%
<Knghtbrd> mariab - Saya pembangun Debian. Red Hat adalah "musuh" atau           sesuatu seperti itu saya rasa .. Namun, pengguna typecasting RH sebagai           bodoh atau pengedaran mereka sebagai sepenuhnya dipecahkan secara lalai           adalah FUD lengkap dan jumlah.
		-- Hagar the Horrible

%
>> Tetapi IANAL, sudah tentu.>> IANAL sama ada. Anak saya, tetapi jika saya bertanya kepada beliau, saya mungkin akan mendapat jawapan saya> Tidak mahu mendengar."Berikut adalah invois saya." ? = D
		-- Hagar the Horrible

%
> Ok, saya melihat anda tahu apa yang anda lakukan :-)Sama ada itu atau saya telah mendapat cukup baik berpura-pura ia.
		-- Hagar the Horrible

%
<Wichert> 08:00 adalah satu jam ungoldly menjadi :) terjaga* Gorgo biasanya bangun pada jam 11 pagi
		-- Hagar the Horrible

%
Ada Tiada Cabal.
		-- Hagar the Horrible

%
<_Anarchy_> Fak: mungkin April 1 tahun depan slashdot perlu berjalan "Rob Malda            menerima tugas baru sebagai ketua projek Debian "8)
		-- Hagar the Horrible

%
* Netgod membuka peti mel dan segera ingin dia hadnt
		-- Hagar the Horrible

%
<Frogbert> yang sukar menjadi lesbian withoutn dada ... orang tidak mengambil           anda serius
		-- Hagar the Horrible

%
Mungkin Debian bimbang lebih lanjut mengenai kecemerlangan teknikal dan bukankemudahan penggunaan dengan memecahkan perisian. Dalam bekas kita boleh mencapai kecemerlangan. Di dalamkedua kita perlu mengakui padang untuk Microsoft. Meneka di mana saya mahu pergihari ini?
		-- Manoj Srivastava

%
* PerlGeek adalah benar-benar asing ruang* Knghtktty percaya PerlGeek
		-- Manoj Srivastava

%
<Netgod> pelanggan saya telah dimiliki teruk<Netgod> lelaki ini mendapat akar, berlari sniffers paket, .rhosts dipasang danpintu belakang, meletakkan dir baru dalam / "" dipanggil lib /, yang mempunyaisuite penuh smurfing dan alat membunuh<Netgod> kesilapan yang tidak memotong fail log<Netgod> soalan adalah bagaimana telah akar digodam, dan bahawa saya couldnt memberitahu u<Netgod> ia adalah, sudah tentu, bukan kotak debian* Netgod nota kotak debian adalah satu-satunya yang tidak disentuh oleh penggodam
		-- wonder why

%
* Cvs joeyh melakukan direktori rumahnya. aaaaaa<Drow> eeeeeeek<Drow> joeyh: Itu adalah semata-mata jahat. Tempoh.
		-- wonder why

%
<Kethryvis> Gruuk: UFies berada di atas dan di luar umat manusia :)
		-- wonder why

%
Saya berhenti lama dahulu untuk cuba mencari apa-apa dalam senarai bug di dpkg.Kami perlu berjalan untuk catatan dalam Guinness Book of Records.
		-- Stephane Bortzmeyer

%
<Ahzz_> i digambarkan 17G oughta mencukupi.
		-- Stephane Bortzmeyer

%
<N3tg0d> telah / usr / bin / emacs dimasukkan ke dalam / etc / shells lagi? : P
		-- Stephane Bortzmeyer

%
* Joeyh mengambil kesempatan daripada keupayaan ajaib netscape untuk crash untuk menutup        10 tingkap dengan satu tekanan kekunci<Joeyh> kini itulah kemajuan!<Knghtbrd> ralat Bas =>
		-- Stephane Bortzmeyer

%
<Wordplay> Anda mengukur penggetar anda di "aksara per saat"? saya adaberita buruk untuk anda, C90, anda telah melancap denganpencetak dot-matriks.
		-- Stephane Bortzmeyer

%
Hi! Saya adalah seorang virus .signature! Hantar salinan ke dalam ~ / .signature anda untuk membantu saya sprea =d!
		-- Stephane Bortzmeyer

%
* Knghtktty membisikkan nothings manis untuk Thyla (perkara tentang penyusun dan            grafik dan upgrade ram dan pemacu keras yang besar ...)<Thyla> oooooooooOOOOOOOOOO<Infinitas> Knghtktty: itu positif lucah ...* Thyla padam ke sawan ekstasi ...
		-- Stephane Bortzmeyer

%
<Sanaya> anda semua tak sakit! sakit sakit sakit saya memberitahu ya;)
		-- Stephane Bortzmeyer

%
* Bma adalah yank yang* Knghtbrd adalah Knghtbrd* DHD juga yank yang* Espy jahat* Knghtbrd percaya Espy
		-- Stephane Bortzmeyer

%
* Keajaiban bma jika ini akan membuat .sig Knghtbrd yang
		-- Stephane Bortzmeyer

%
penyelesaian teknikal yang tidak suatu perkara yang mengundi. Dua undang-undang di Amerika Syarikatnegeri hampir memutuskan bahawa nilai Pi menjadi 3.14, betul-betul. Undi populartidak penyelesaian yang betul dilupakan.
		-- Manoj Srivastava

%
<Aj> <Knghtbrd> peningkatan dalam ketegangan di seluruh dunia (seperti yang dibuktikan oleh jenayah<Aj> dan barang kecil) ke atas tempoh masa itu kelihatan banyak seperti Linux<Aj> pertumbuhan sejak 1993<Aj> `` Linux dikaitkan dengan wabak jenayah di seluruh dunia !! ''
		-- Manoj Srivastava

%
<Teller> di mana saya dan apa yang saya lakukan di handbasket ini?
		-- Manoj Srivastava

%
Sejak pangkalan data ini tidak digunakan untuk keuntungan, dan kerana seluruh kerja-kerja tidakditerbitkan, ia jatuh di bawah penggunaan adil, seperti yang kita fahami. Walau bagaimanapun, jika adasetengah assed bodoh memutuskan untuk membuat keuntungan dari itu, mereka perlumemeriksa semua dua ...
		-- Notes included with the default fortunes database

%
Tiada butang tunda pada kucing yang mahu sarapan pagi.
		-- Notes included with the default fortunes database

%
Subjek: Bug # 42.432: debian-dasar: Cadangan CTV bagi Draf BuktiKonsep Draf Cadangan Cadangan CTV untuk CTV untuk membuat keputusan mengenaicadangan untuk CTV bagi CTV kepada sama ada atau tidak kita shoud mempunyai CTV pada/ Usr / doc ke / usr / share / peralihan doc sekarang, atau kemudian.
		-- Ed Lang

%
<Knghtbrd> Ia adalah satu bebola trek untuk satu<Wichert> jadi ia bukan tikus yang<Wichert> ia adalah satu turd dengan bola melekat keluar<Wichert> yang anda mengusap-ngusap sentiasa
		-- Ed Lang

%
* HomeySan menunggu pizza papa john untuk muncul<Ravenos> mm. papa john.<HomeySan> mudah-mudahan mereka menghantar pemandu penghantaran comel<Ravenos> mereka tidak mempunyai bahawa di sini.<Dr_Stein> mengapa? anda akan makan pemandu bukan?
		-- Ed Lang

%
<Netgod> adakah saya, atau Knghtbrd berdengkur?<Joeyh> mereka membunuh knghtbrd!<Netgod> Kysh: Wichert, gecko, joeyh, dan saya adalah di dalam bilik cuba untuk mengabaikan          Knghtbrd<Kysh> netgod: Knghtbrd adalah sukar untuk diabaikan.
		-- Ed Lang

%
<Woot> Man, saya ingin knghtbrd berada di sini untuk merebut bahawa untuk senarai sig beliau.[... Beberapa jam kemudian ...]<Knghtbrd> woot tidak mengenali saya vewy baik, melakukan dia?<Knghtbrd> muahahahaha
		-- Ed Lang

%
* Knghtbrd kulit bulu Wichert dengan dart NERF* Wichert nota tiada nerfs ICBM lagi dan mengabaikan kngtbrd<Knghtbrd> Wichert - hanya menunggu, selepas melihat NERF senjata gatling, ICBM           tidak jauh (hanya mengepam perkara yang terkutuk untuk satu atau dua jam           adalah semua ...)
		-- Ed Lang

%
Sistem Operasi dipasang:  * Debian GNU / Linux 2.1 4 CD Set ($ 20 dari www.chguy.net; harga termasuk    cukai, perkapalan, dan $ 3 sumbangan kepada FSF). 2 CD adalah binari, 2 CD    kod sumber lengkap;  * Windows 98 Second Edition Naik taraf Version ($ 136 melalui Megadepot.com,    harga tidak termasuk cukai / penghantaran). Yang menghairankan, tiada kod sumber    disertakan.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Mencuri slogan ini. Saya telah lakukan.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Bfextu> oh noooo, Knghtbrd punya pistol :)<Doogie> ^^ memasukkan muzik ^^<Knghtbrd> bfextu - o / ~ semua orang melarikan o / ~<Bfextu> o / ~ lari, ruuuuun dari gaji-ay-ain o / ~
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Mercury> emacs menghisap, secara literal, tidak menghina, hanya komen yang yang          cukup besar untuk mempunyai tarikan graviti ketara ...
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Seperti komputer, saya mendapati iman anda dalam teknologi lucu.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
* Knghtbrd memberikan 3 untuk Chris* Keajaiban ubah siapa lagi yang dinamakan chris di hadapan-Ku<Knghtbrd> berubah-ubah - anda. =>* Knghtbrd menunggu berubah-ubah secara mendadak mengatakan "Saya rasa SO digunakan!"<Pembolehubah> Knghtbrd: :)* Berubah-ubah ++<Pembolehubah> :)
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
* Espy ponders barisan yang uplad dipanggil 'neraka' jadi saya boleh lakukan dupload --to neraka
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Valkyrja> java, hon, kadang-kadang saya benar-benar mahu menampar anda.<Knghtbrd> Valkyrja - dia akan menikmati ia terlalu banyak<Reteo> Valkyrja: yah, teruskan dan melakukannya ... mengalahkan java ke dalam cappuccino! :-)
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Tali> menjadi vewwy vewwy qwuiet .. Saya ewwos wuntime huntin
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Red Hat baru-baru ini telah mengeluarkan satu Penasihat Keselamatan (RHSA-1999: 030-01)meliputi buffer overflow dalam pakej vixie cron. Debian mempunyaiditemui bug ini dua tahun yang lalu dan tetap ia. Oleh itu versi dalamkedua-duanya, yang stabil dan tidak stabil, pengagihan Debian tidakterdedah kepada masalah ini ..
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Mula-mula - Quake adalah semata-mata yang luar biasa. Ia membolehkan anda berkali-kali membunuh andabos di pejabat tanpa ditangkap. :)
		-- Signal 11, in a slashdot comment

%
Undang-undang Lucas ': yang baik akan sentiasa menang, kerana kejahatan mengupah _stupid_ yang             jurutera.
		-- Signal 11, in a slashdot comment

%
* TribFurry hanya mendapat mel spam dari UCSD ... saya pernah mendapat e-mel daripada            diri saya tetapi saya memutuskan saya tidak suka diri saya dan berhenti bercakap	    kepada saya
		-- Signal 11, in a slashdot comment

%
<Rain_work> nota pada peti sejuk asrama ... "Untuk orang yang makan kandungan            bekas yang dilabel 'James' - amaran, ia adalah biologi sayaeksperimen "
		-- Signal 11, in a slashdot comment

%
<KatanaJ> Nota pada lab chem fridge- "peti sejuk ini tidak explosion-          bukti ".
		-- Signal 11, in a slashdot comment

%
<KnaraKat> DALnet adalah seperti Sukan Olimpik khas IRC. Ada banyak           meleleh air liur goin 'pada dan semua orang adalah' pemenang '.
		-- Signal 11, in a slashdot comment

%
Tetapi mengubahsuai dpkg adalah infeasible, dan kami telah bersetuju untuk, antara lain,menjaga keperluan pengguna kami di barisan hadapan dalam fikiran kita. Dan dariperspektif pengguna, sesuatu yang menyimpan sistem kemas dalam biasakes, dan berfungsi * sekarang *, adalah jauh lebih baik daripada fantasi idealistik sepertidpkg bekerja.
		-- Manoj Srivastava

%
Untuk penglihatanpun terdapat semakan sama dan berlawanan.
		-- Manoj Srivastava

%
<Epsilon3> Knghtbrd, jika kita mahu kenyataan lameass kita akan berkata:           Hey, neckro
		-- Manoj Srivastava

%
<Tigah _-> i mempunyai 4gb untuk / tmp<Knghtbrd> Apa yang anda lakukan dengan 4G / tmp? Menyusun X?<Tigah _-> ya
		-- Manoj Srivastava

%
<KnaraKat> Bite saya.* TheOne mendapat sedikit garam, kemudian meneruskan untuk menggigit pada KnaraKat sedikit         sedikit ....
		-- Manoj Srivastava

%
* Knghtbrd mencatatkan dia telah lecek kentang untuk otak malam ini<Valkyrie> yum, boleh saya mempunyai beberapa?<Knghtbrd> um ...* Knghtbrd menyembunyikan dari Valkyrie
		-- Manoj Srivastava

%
<Knghtbrd> joeyh kini mempunyai terminal di sofa?<Knghtbrd> Bahawa lelaki adalah berwayar, saya bersumpah =><Doogie> Knghtbrd: komputer riba<Doogie> dan saya tidak bermaksud kucing.
		-- Manoj Srivastava

%
Memandangkan beberapa benang baru-baru ini, perbincangan interaktif mungkinperlu dilakukan pada kanvas, di hadapan pengadil, manakalamemakai sarung tangan empuk. ;-)
		-- Phil Hands

%
<James> tetapi, maka saya menggunakan Atari, saya lebih cenderung untuk memenangi loteri dalam        sepuluh negara serentak daripada mendapatkan dipercepatkan X
		-- Phil Hands

%
* Joeyh tertanya-tanya mengapa semua orang mahu tahu bagaimana tinggi dia<James> joeyh: ia membantu sniper
		-- Phil Hands

%
* BenC tertanya-tanya mengapa dia telah dinaik taraf kepada 3.3.5-1 sebelum teh X penyenggara
		-- Phil Hands

%
<Delenn> saya tidak akan membuat ia melalui 24 jam sebelum saya akan menembak sehingga         grill dan menampar beberapa orang kawan di barbie.<Spacemoos> Mengapa anda akan menampar rakan-rakan dengan Barbies, thats agak keriting
		-- Phil Hands

%
Malah .. berdasarkan model ini daripada apa yang NSA adalah dan tidak ... banyakorang yang membaca ini merupakan anggota NSA ... /. adalah afterall 'News untukNerds.NSA Isnin MORNING {di mesin kopi):NSA AGENT 1: Hey guys, adakah anda menyemak slashdot pada hujung minggu?    AGEN 2: Tidak, saya telah memasang Mandrake 6.1 dan saya coulnd't mendapatkan darn             ppp sambungan up ..    AGEN 1: Well website saya ... mereka kepada kita.
		-- Chris Moyer <cdmoyer@starmail.com>

%
Teknologi pertempuran constand antara pengeluar menghasilkan lebih besar danlebih sistem bodoh-bukti dan alam semula jadi menghasilkan bodoh lebih besar dan lebih baik.
		-- Slashdot signature

%
knghtbrd: mungkin tiada sudu, tetapi anda boleh melihat kelemahan dalameye_render_shiny_object.c?
		-- rcw

%
<Joy> wow ... matematik mudah menunjukkan bahawa pemaju Debian telah ditutup lebih      daripada * 31 * * * ribu laporan pepijat sejak BTS kami wujud!<Joy> yang kira-kira 30.999 lebih daripada Microsoft;)
		-- rcw

%
<Knghtbrd> NOTA YANG DI ATAS HANYA PENDAPAT AN DAN TIDAK PERLUDIAMBIL UNTUK TERMASUK APA-APA LANGKAH MAKLUMAT fakta. THE           SPEAKER MENAFIKAN SEMUA DAN SEMUA ORANG. BERURUSAN DENGAN IT.
		-- rcw

%
<James> sebarang gnome mengangkat tema sekitar?<Knghtbrd> bukan saya, saya hanya lain daripada yang lain
		-- rcw

%
<Madax> ahh<Madax> perhimpunan Geeks ....<Madax> Aku boleh bau sekarang
		-- rcw

%
<Knghtbrd> belajar untuk mengasihi Window Maker.<Knghtbrd> a Nextstep sedikit adalah baik untuk jiwa.
		-- rcw

%
Kaveat: ia GNOME, takut, sangat takut Depends garis
		-- James Troup

%
<Culus> Hhhmmmmmmmm<Culus> waterbeds untuk lembu<Culus> eleet<Cas> Culus: mengapa lembu memerlukan katil air yang?<Culus> cas: Untuk menjadi selesa hangat
		-- James Troup

%
Jika anda adalah apa yang anda makan, saya rasa yang membuatkan saya danish keju.
		-- Anonymous

%
<Hop> apabila anda mula membuat kesilapan hanya bodoh yang jelas, thats      apabila anda mula mendapat kompeten<Hop> kerana anda tidak melakukan kesilapan salah faham asas<Hop> dan thats * * petanda yang baik.
		-- Anonymous

%
<Lilo> ia pelik, apabila anda pergi pada safari ke Afrika untuk menangkap singa, anda       merasa hidup dan ia caj, dan kemudian anda membunuhnya<Lilo> apabila anda pergi pada safari ke South Bay untuk mencari seorang Palm Vx, anda mendapati       ia mati kemudian dibawa pulang dan ia caj selepas ia tiba :)
		-- Anonymous

%
<Lilo> saya boleh membaca manual * berdarah * seolah-olah ia semacam       saluran agama menggambarkan bentuk pencerahan anda boleh mencapai       selepas 10 tahun ke atas sebuah gunung :)
		-- Anonymous

%
Undang-undang Gates: Setiap 18 bulan, kelajuan bahagian perisian.
		-- Anonymous

%
<Knghtbrd> Solver_: menambah pengguna-pengguna yang perlu kerunsingan dengan bunyi untuk kumpulan           audio .. Pastikan peranti semua audio kumpulan (ls -l           / Dev / DSP akan memberikan anda petunjuk yang paling cepat jika ia mungkinterletak betul-betul) dan membina kernel dengan sokongan yang kukuh untuk kad anda<Knghtbrd> OR pilihan memasang sumber alsa dan membina modul untuk           dengan make-kpkg<Knghtbrd> OR (tidak digalakkan) mendapatkan dan memasang jahat OSS / Linux jahat           tidak bebas binari jahat pemandu hanya kejahatan --- tetapi orang-orang yang jahat.Dan adakah saya menyebut bahawa ia tidak digalakkan?
		-- Anonymous

%
Saya rasa irc tidak akan bekerja walaupun --- kami berjalan keluar dari ruang topik!
		-- Joseph Carter

%
"Pacific Bell Khidmat Pelanggan, ini adalah [..], bagaimana saya boleh menyediakan anda denganperkhidmatan pelanggan yang cemerlang hari ini? ""Hahahahaha !! Itulah yang baik, saya suka ..""Um, terima kasih, mereka membuat kita katakan itu."
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Danpat> Omnic: newzealanders berdarah<Omnic> danpat: meletakkan kaus kaki di dalamnya<Danpat> heh :)<Knghtbrd> mengejek .nz'ers adalah berbeza --- mereka semua pelik* Belulang knghtbrd<Omnic> hrmph
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Joy> Flinny: hitam crontab sihir agak barangan :)<Knghtbrd> Joy: adakah itu orang min mendapatkan menari telanjang di sekeliling unggun api           melaungkan perkara-perkara pelik dan melambai tangan mereka kira-kira dalam bodoh           cara?<RCW> knghtbrd: apa yang anda * fikir * orang lakukan di Novare?
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Knghtbrd> * snipsnip *<RCW> oh sayang, ialah bunyi editing tukang pangkalan data?<Joy> uh oh<Knghtbrd> Ya =>
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Joy> itu adalah satu kludge (TM)<Knghtbrd> Ia Berfungsi (tm)<Joy> AIX berfungsi (TM)<Knghtbrd> tiada ia tidak<Knghtbrd> =>
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
"Perbezaan antara genius dan kebodohan adalah bahawa genius telah iahad. "
		-- Albert Einstein

%
<Knghtbrd> Jika pengisian seseorang untuk melanggar undang-undang Amerika kripto akan mendapat           anda ketawa di luar mahkamah, hanya "menyiasat" mereka pada caj hte           pengkhianatan!<Knghtbrd> Teh, sesiapa sahaja?<Espy> saya lebih suka lemas ahli-ahli politik dan bukannya teh :)<Stu> menemani tiba-tiba: ahli politik mempunyai insang, duh<Espy> cerpelai tidak mempunyai insang
		-- Albert Einstein

%
Jika saya mempunyai masalah memasang Linux, sesuatu yang tidak kena. Sangat salah.
		-- Linus Torvalds

%
* Bma_home gropes anda<Bma_home> "oups, Saluran salah"<Bma_home> </ fak><Cerb> berhenti meraba-raba saya<Doogie> anda tahu anda suka.<Bma_home> sebenarnya, ia adalah "meraba-raba saya bayi"<Gecko-> sentuh anak saya dan anda mati, bma;)<Doogie> gecko- tetapi isteri anda ok?
		-- Linus Torvalds

%
Membaca manual komputer tanpa perkakasan seperti mengecewakan kerana membacamanual seks tanpa perisian.
		-- Arthur C Clarke

%
<Knghtbrd> (kali satu)<Espy> (ytitac)<Knghtbrd> (ntinac)<Espy> (ia)<Knghtbrd> (dalam)* Espy nota bercakap dalam acr ^ Winitialisms adalah menakutkan apabila sisi lain  memahami anda
		-- Arthur C Clarke

%
<Knghtbrd> ia terlalu buruk paling unices purba mematuhi y2k<| Rain |> terlalu buruk?<| Rain |> mengapa, kerana orang tidak akan menaik taraf sehingga 2038?
		-- Arthur C Clarke

%
<Espy_on_crack> "Saya memasang 'Linux 6.1', tidak yang membuat saya unix                guru? "<BenC> Espy_on_crack: tidak, anda perlu untuk memasang dua kali sebelum anda seorang       guru ... sekali untuk membuktikan anda boleh melakukannya, kedua untuk menetapkan perkara-perkara       anda patah kali pertama<Espy_on_crack> oh betul, bagaimana bodoh saya
		-- Arthur C Clarke

%
* Knghtbrd melakukan perkara ET<Knghtbrd> sesiapa mendapat bercakap-n-jampi?
		-- Arthur C Clarke

%
<Omnic> satu lagi tambahan .sig
		-- Arthur C Clarke

%
Saya mula berfikir kolam gen boleh menggunakan klorin sedikit.
		-- Arthur C Clarke

%
Ia seolah-BAD yang anda fikirkan, dan mereka keluar untuk mendapatkan anda.
		-- Arthur C Clarke

%
<Espy> berhati-hati, beberapa twit mungkin memetik anda<Espy> di luar konteks ...
		-- Arthur C Clarke

%
*** Topik untuk #redhat: Redhat adalah jawapan kepada semua masalah anda. ia    boleh menjadi permulaan juga!
		-- Arthur C Clarke

%
* Keajaiban cesarb jika dalam masa kurang dari seminggu yang Carmack akan berakhir menerima dalam  e-mail salinan ihsan versi sumber Quake yang empat  kali lebih cepat daripada apa yang keluar dari tangan maya beliau ...
		-- Arthur C Clarke

%
<Knghtbrd> JHM: Saya tidak meletakkan gempa dalam sumber kernel<Knghtbrd> tetapi kita perlu meletakkan gempa dalam cakera liut boot untuk satu-up           permainan tetris Caldera ini ..;>
		-- Arthur C Clarke

%
Guns tidak membunuh orang. Ia adalah orang-orang peluru celaka. Guns hanya membuat mereka pergibenar-benar benar-benar cepat.
		-- Jake Johanson

%
<Espy> kita perlu berpecah utama ke "teras" dan "wtf-kegunaan ini"
		-- Jake Johanson

%
<Culus-> libc6 tidak penting: |
		-- Jake Johanson

%
<DHD> terdapat christmas pek khas untuk gempa<DHD> di mana anda boleh menjadi seperti robot santa pada futurama?<Dunham> DHD: yang akan menjadi permainan yang agak tidak seimbang ...<Knghtbrd> Dunham: itulah idea. ;>
		-- Jake Johanson

%
<Knghtbrd> masalah dengan piawaian pengekodan GNU adalah mereka menganggap bahawasemua orang di dunia menggunakan emacs .. Jika itu berlaku, percuma           perisian akan mati kerana kita semua akan mempunyai masalah pergelangan tanganseperti RMS sekarang dan tidak lagi dapat memberi kod. ;>
		-- Jake Johanson

%
C'mon! protes politik! Sheesh. Di mana semangat anarkis? ;-)
		-- Decklin Foster

%
Kami telah upped standard kita, jadi sehingga anda!
		-- Decklin Foster

%
* Woot kini dikenali sebagai woot makan malam* Knghtbrd memercikkan sedikit garam pada woot<Knghtbrd> Saya tidak pernah mempunyai woot sebelum ... Hope mereka rasa baik<Woot-makan malam> noooo!<Woot-makan malam> jangan makan saya!* Knghtbrd memutuskan dia tidak mahu makan malam yang bercakap kepadanya ... hehe
		-- Decklin Foster

%
[Mengenai langkah-langkah untuk mengelakkan penipuan dalam gempa bumi]Maksud saya, selagi saya boleh membuat pelancar roket saya kelihatan seperti Twinkie besar,Saya akan gembira;)
		-- Qeyser <keyser@jhu.edu>

%
<Knghtbrd> r0bert: pendek, kita sedang bergerak beberapa perkara pelanggan           kini bertanggungjawab untuk memberitahu pelayan ke dalam perkara-perkara yang           cek pelayan untuk dirinya sendiri<Knghtbrd> Jika Neo berkata "Tidak ada sudu", The Matrix akan berkata "Oh ya           terdapat --- menipu tidak! "<Hollis> Tetapi dia tahu kung fu ...<Knghtbrd> Pasti dia lakukan, tetapi saya mempunyai pelancar roket.
		-- Qeyser <keyser@jhu.edu>

%
* Mercury tenang membuang lengan XT-Ream ini ..* Mercury kemudiannya menewaskan XT-Ream dengan lengan XT-Ream ini.<Knghtbrd> wow, semua hacking gempa ini ialah menjadikan Mercury ganas sini* Mao gembira projek gempa forge diuruskan dengan baik
		-- Qeyser <keyser@jhu.edu>

%
<Knghtbrd> CVS / Penyertaan mempunyai barisan yang aku perlukan untuk "mengubah"<Mercury> Knghtbrd: Adakah akan menyebut seperti .. <G><Mercury> Knghtbrd: Sekarang, bersedia untuk melakukan?<Knghtbrd> ingin saya nasib<Knghtbrd> Mercury: ia komited<Knghtbrd> Mercury: dan selepas semua itu, saya boleh terlalu.
		-- Qeyser <keyser@jhu.edu>

%
* Knghtbrd melintasi jari kakinya<Knghtbrd> (jika saya melintasi jari saya ia akan menjadi sukar untuk menaip)
		-- Qeyser <keyser@jhu.edu>

%
<Doogie> ada satu perkara yang tidak baik tentang mempunyai telefon bimbit.<Doogie> Saya boleh dihubungi pada bila-bila. : |<Wmono> sebab itu saya meninggalkan saya off pada setiap masa. ;>
		-- Qeyser <keyser@jhu.edu>

%
<Palisade> bagaimana kita akan mengucapkan '00 atau '01 atau '02 dan sebagainya?<Deek> Mengucapkan selamat tinggal kepada tahun sembilan puluhan, bertanya khabar kepada naughties. :)
		-- Qeyser <keyser@jhu.edu>

%
<Deek> Jika pengguna menunjuk pistol di kakinya dan menarik picu, ia       adalah tugas kita untuk memastikan peluru mendapat di mana ia sepatutnya.
		-- Qeyser <keyser@jhu.edu>

%
<Mercury> Diberi amaran, saya mempunyai papan kekunci yang boleh saya gunakan untuk memukul kepala luser ini          , dan kemudian terus menggunakan ... (=:]<Deek> Mercury: Oh, IBM. :)
		-- Qeyser <keyser@jhu.edu>

%
<Palisade> knght, Sheesh, adakah anda menampal kata-kata saya keluar dari konteks           #debian atau sesuatu?<Palisade>;)<Knghtbrd> tidak, tetapi saya mungkin perlu;><Palisade> d'oh!
		-- Qeyser <keyser@jhu.edu>

%
<Cas> Mercury: gpm tidak adalah pelayar web yang sangat baik. membaikinya.
		-- Qeyser <keyser@jhu.edu>

%
<Cas> baik di sana ya pergi. mengatakan sesuatu yang bodoh dalam irc dan ia      diabadikan selama-lamanya dalam fail .sig seseorang
		-- Qeyser <keyser@jhu.edu>

%
Microsoft adalah kacukan antara Borg dan Ferengi. Malangnya,mereka menggunakan Borg untuk melakukan pemasaran dan Ferengi mereka untuk melakukan merekapengaturcaraan.
		-- Simon Slavin

%
Saya lebih suka menghabiskan 10 jam membaca kod sumber orang lain daripada 10minit mendengar Musak menunggu sokongan teknikal yang tidak.
		-- Dr. Greg Wettstein, Roger Maris Cancer Center

%
Di manakah anda fikir anda akan hari ini?
		-- Dr. Greg Wettstein, Roger Maris Cancer Center

%
Saya telah mendengar pelbagai kesuraman dan azab ramalan untuk Y2K, jadi saya fikir saya akan mengendahkan beberapa nasihat yang pakar-pakar telah memberi: Mengisi tangki gas kereta, menyimpan pada barangan dalam tin, mengisi tab mandi dengan air, dan sebagainya.Saya rasa saya tidak sedar sepenuhnya apabila saya selesai persiapan saya lewat lalumalam. Pagi ini saya mendapati rak dapur direndam dalam petrol, airdalam tangki gas kereta, dan tab mandi saya penuh dengan kacang panggang.
		-- Dan Pearl in a message to rec.humor.funny

%
<Tarzan> hey kamu jatuh pirch atau sesuatu yang anda?<Knghtbrd> saya? heh.
		-- Dan Pearl in a message to rec.humor.funny

%
<Espy> anda sedang dibakar<Knghtbrd> Espy: hanya setengah begitu
		-- Dan Pearl in a message to rec.humor.funny

%
<Darkangel> Saya secara amnya tidak menggunakan apa-apa yang mempunyai "percubaan" dan            "Amaran" ditampal di seluruh ia<Darkangel> tidak, saya bukan yang bodoh ... hehe<Knghtbrd> ...* Darkangel menganggap memuat turun kernel tidak stabil terkini
		-- Dan Pearl in a message to rec.humor.funny

%
<Wichert> solaris adalah bsd, jadi ia harus bekerja* Espy mengambil paip retak Wichert dari sini
		-- Dan Pearl in a message to rec.humor.funny

%
<Knghtbrd> ia terlalu buruk unices paling lama ternyata patuh y2k<Knghtbrd> kerana ia bermakna orang ramai akan terus berjalan mereka dalam tempoh 30 tahun           = p<Knghtbrd> ia akan menjadi begitu banyak lebih bagus jika y2k berkesan membunuh           hpux, aix, sunos, dan lain-lain;><Espy> Knghtbrd: sejak bila berada PH-UX, sakit, dan solartus "lama"?
		-- Dan Pearl in a message to rec.humor.funny

%
* Gxam tertanya-tanya jika semua Globals ini adalah benar-benar perlu<Knghtbrd> kebanyakan mereka pada masa ini ya<Knghtbrd> kami perlu membersihkan mereka pada satu ketika<Knghtbrd> gxam: yang Globals perlu pergi jauh seperti yang kita berhijrah ke arah           suai dan kegilaan (iaitu, libtool)
		-- Dan Pearl in a message to rec.humor.funny

%
<Raptor> Adamel, saya fikir kod yang anda tetap saya tidak bekerja<Raptor> i tidak perlu telah komited kod kerja<Knghtbrd> raptor: seperti ia adalah kali pertama yang pernah terjadi = p
		-- Dan Pearl in a message to rec.humor.funny

%
<Mercury> Knghtbrd: Menggunakan -3dfx atau -svga?<Knghtbrd> Mercury akan melakukan sesuatu yang waras dengannya<Knghtbrd> Mercury: kedua-dua --- sig11 SVGA ini, sig4 -3dfx ini<Knghtbrd> Mercury: yang tidak betul baik? ;>
		-- Dan Pearl in a message to rec.humor.funny

%
<Knghtbrd> Percayalah kita, kita tahu apa yang kita lakukan ... Kita mungkin tidak tahu BAGAIMANA           yang kita lakukan, tetapi kita tahu apa yang kita lakukan.
		-- Dan Pearl in a message to rec.humor.funny

%
<Mercury> <CJ | Bizkit-0-> i boleh memuat naik ke pelayan linux tho<Mercury> <CJ | Bizkit-0-> i mendapat akaun shell pada satu<Mercury> <Mercury> Whats ia berjalan?<Mercury> <CJ | Bizkit-0-> umm<Mercury> <CJ | Bizkit-0-> apache i berfikir<Mercury> Bantuan, sila membantu ..* Chuckles Omni
		-- Dan Pearl in a message to rec.humor.funny

%
<Jt> perlu pepijat ditandakan kritikal jika ia hanya menjejaskan satu gerbang?<James-workaway> jt: rc untuk gerbang yang mungkin, tetapi orang-orang jenis gerbang                 bug tertentu jarang berlaku ...<Jt> tidak apabila ia disebabkan oleh pepijat dalam gcc<Doogie> jt: mendapatkan gcc dikeluarkan dari gerbang itu. :)
		-- Dan Pearl in a message to rec.humor.funny

%
<Edlin> LWE?<Edlin> Linux W ?? E ??<SEES> akan eatyou<JHM> Expo Dunia?<Edlin> i melihat
		-- Dan Pearl in a message to rec.humor.funny

%
"Yuran nominal". Apa hukuman hodoh. Ia adalah salah satu perkara-perkara yangmembayangkan bahawa jika anda perlu bertanya, anda tidak mampu.
		-- Linus Torvalds

%
<Deek> anda GPL kerja rumah anda? :)<Knghtbrd> yah = D<Knghtbrd> Sesiapa sahaja dibenarkan untuk menggunakan atau mengubah suai kerja rumah saya, tetapi jika mereka           mengedarkan perubahan yang mereka mesti termasuk mesin yang boleh dibaca penuh           kod sumber;>
		-- Linus Torvalds

%
* Knghtbrd adalah setiap hari lebih percaya bahawa kebanyakan C ++ coders tidak tahu apa yang           neraka yang mereka lakukan, yang adalah mengapa C ++ mempunyai apa-apa rap buruk<Culus> kb: Kebanyakan C coders tidak tahu apa yang mereka lakukan, ia hanya menjadikannya        lebih mudah untuk menyembunyikan: P<Culus> Lihat misalnya, proftpd: P
		-- Linus Torvalds

%
<Culus> Dan tidak dapat saya bermula pada perl!<Culus>:><Shaleh> perl adalah di luar jahat<Jim> anda tidak tahu perl lagi?<Netgod> Harus suka bahasa tanpa sintaks ditakrif
		-- Linus Torvalds

%
<Doogie> cat / dev / rawak | perl?<Shaleh> doogie: ia juga sendmail.cf yang sah<Doogie> :)* Tangan knghtbrd doogie anugerah yang tidak masuk akal digunakan-of-kucing* Shaleh mahu mencuba tetapi takut
		-- Linus Torvalds

%
<DHD> perl </ dev / bdsm<Knghtbrd> anda mempunyai / dev / bdsm?<DHD> pasti, ia adalah penjana nombor rawak pseudosadomasochistic
		-- Linus Torvalds

%
<Kysh_> Joey: Saya di atasnya sekarang .. 3 cakera 1.3GB, 128M ram, 50MHz dual        (Sehingga quad 250MHz)<Kysh_> Tangkapan adalah bahawa ia menarik 110v pada kira-kira 12A 8><Culus> 12A!<Culus> Okay, dapur saya ialah 3000W, matahari ini adalah 1320W<Culus> ANDA LIHAT MASALAH DI SINI<Kiraan> matahari 1320W, iaitu seperti pengering rambut :)
		-- Linus Torvalds

%
* Joeyh_ berjalan ps dan melihat 10 baris kod awk* Joeyh_ gerun dalam seram
		-- Linus Torvalds

%
<Knghtbrd> joeyh: saya turun sejak pertengahan sesi pagi semalam dan pacbell berkata           pagi ini bahawa AT & T adalah untuk menyalahkan dan hampir semua negeri           susut<RCW> dunno mengapa orang menegaskan internet boleh bertahan holocaust nuklear      apabila ia tidak boleh hidup jengkaut yang
		-- Linus Torvalds

%
Mesej ini telah ditulis dengan vi! (Tidak bahawa sesiapa sahaja di dunia mengambil berat)
		-- seen on an old message from an anon.penet.fi address

%
semula sambungan dengan beberapa dungu dengan jengkaut yang
		-- seen on an old message from an anon.penet.fi address

%
5 Feb 13:27:01 trinity lp0 terbakar        - Linux kernel, menyedarkan saya bahawa terdapat beberapa yang tidak diketahui           masalah dengan pencetak saya (iaitu, ia adalah daripada dakwat)
		-- seen on an old message from an anon.penet.fi address

%
Yang kurang anda tahu mengenai komputer lebih banyak anda mahu Microsoft!        - Kempen iklan Microsoft, sekitar tahun 1996(Bukti bahawa pengiklanan Microsoft _isn't_ tidak jujur!)
		-- seen on an old message from an anon.penet.fi address

%
Membuat satu keputusan yang bijak dan sejumlah besar orang-orang yang biasa-biasa tidak begitubaik kerana membuat sejumlah besar keputusan umumnya pintar di seluruhproses keseluruhan.
		-- John Carmack

%
Ia tidak biasanya kos masa yang berkesan bijak untuk pergi melakukannya. Tetapi jika sesuatu yangbenar-benar pissing anda di luar, anda hanya pergi mencari kod dan memperbaikinya dan itulahbenar-benar sejuk.
		-- John Carmack, on the advantages of open source

%
<Kiraan> yea ia kedengaran berguna untuk RE'ing USB<Kiraan> i mempunyai kamera usb 3com tidak berguna di sini :(<Knghtbrd> calc: 3Com, mereka mungkin akan ditangkap kerana melanggar undang-undang yang           tidak wujud 'hingga Oktober;><Kiraan> knghtbrd: i akan menyembunyikan :)<Knghtbrd> ... menentang penangkapan terlalu eh?<Kiraan> knghtbrd: tidak i akan menyembunyikan sebelum i mendapatkan disampaikan
		-- John Carmack, on the advantages of open source

%
<Mercury> Pada ketika itu ia akan menyusun, tetapi segfault, seperti yang sepatutnya ..
		-- John Carmack, on the advantages of open source

%
* Knghtbrd adalah FAR terlalu terdorong untuk .sig keseluruhan perbincangan ini ...
		-- John Carmack, on the advantages of open source

%
The Unixverse berakhir pada Tue, 19 Jan 2038 03:14:07 +0000
		-- John Carmack, on the advantages of open source

%
<Taniwha> Knghtbrd: kita harus melakukan episod gempa: lutut yang mendalam dalam kod ":          anda menjalankan sekitar menembak bug :)<Knghtbrd> taniwha: Saya akan lulus idea ke OpenQuartz;>
		-- John Carmack, on the advantages of open source

%
<Taniwha> i sedang menyelesaikan windows masalah utama dengan fdisk :)
		-- John Carmack, on the advantages of open source

%
<Endy> knghtbrd: netcode QW adalah melakukan perkara-perkara pelik kepada saya. : P<Knghtbrd> ini adalah luar biasa? ;><Endy> Tidak benar-benar. : P
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> RCW: Oh yay --- saya tidak pernah terlibat dalam flamewar yang baik dalam di           kurangnya ... 5 minit!
		-- John Carmack, on the advantages of open source

%
<Manoj> shaleh: Saya tidak, walaupun implikasi anda, Allah
		-- John Carmack, on the advantages of open source

%
<SlayR> i baru sahaja membeli MS Office 2000 untuk hanya $ 20 !!!<Knghtbrd> anda mendapat ripped off;><SlayR> i tahu;)
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> itu 06:00. Saya telah sehingga 24 jam<Knghtbrd> Bangun saya dan kehidupan risiko dan anggota badan.* Knghtbrd &; tidur<Tv> semua orang Okay, kita tunggu 10 minit dan kemudian mula membanjiri Knghtbrd     dengan ^ G. Seseorang, akar hack dan cat / dev / urandom> / dev / DSP.
		-- John Carmack, on the advantages of open source

%
*** Knghtbrd kini dikenali sebagai SirKewLDooD*** Mercury ditendang SirKewlDooD dari #quakeforge (* Memukul *)
		-- John Carmack, on the advantages of open source

%
<Mercury> Knghtbrd: Saya suka melihat sokongan untuk rerambut silang xor ..<Knghtbrd> Mercury: anda berada di dukun.<Mercury> Knghtbrd: Anda peniaga itu ... <G>*** Knghtbrd kini dikenali sebagai QuackDealer
		-- John Carmack, on the advantages of open source

%
* Dry-ais tidak boleh kod jalan keluar dari beg kertas<Coderjoe> kering ais: int main () {ExitPaperBag (); kembali 0; }<Knghtbrd> Adakah yang bagaimana yang dilakukan itu? * Mengambil nota *
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> Eek, tidak satu sama lain ...<Knghtbrd> Seolah-olah pernah pemaju dan ibu mereka kini mempunyai rawak           tandatangan menggunakan senarai irc ...<Knghtbrd> APA AKU TELAH BERMULA DI SINI ??
		-- John Carmack, on the advantages of open source

%
* Jangka menggunakan comments knghtbrd sebagai tandatangannya<Knghtbrd> melihat: sebaik sahaja saya menaip mereka saya sedar saya akan lebih baik snip mereka           diri saya sebelum orang lain lakukan;>
		-- John Carmack, on the advantages of open source

%
* Omnic kelihatan di pautan 33.6k dan kemudian melihat Joy* Mercury memeluk modem kabel beliau .. (=:]
		-- John Carmack, on the advantages of open source

%
Diberikan, rupa Win95 ini tidak semua yang baru sama ada - Apple cuba untuk menyamanMicrosoft untuk menyalin UI Macintosh / ikon tong sampah, sehingga Microsoftmenegaskan bahawa Apple mendapat banyak idea Mac (termasuk tong sampahicon) dari Xerox ParcPlace. Xerox adalah mungkin masih tertanya-tanya mengapasemua orang yang berminat dalam tong sampah mereka.
		-- Danny Thorpe, Borland Delphi R&R

%
<Knghtbrd> adakah ia satu tanda penyakit mental untuk bersiar-siar tanpa tujuan melalui           mula peta, mengumpul Thunderbolt anda, hop di kolam renang, dan gib           diri anda dengan ia hanya untuk melihat buouce kepala anda apabila ia jatuhmelalui bahagian bawah kolam? =><Knghtbrd> "Anda tahu anda seorang penagih Quake bila ..."
		-- Danny Thorpe, Borland Delphi R&R

%
<Zoid> saya masih rasa anda semua kacang Q penggabungan dan QW. : P<Knghtbrd> Sudah tentu kami kacang. Walaupun John berkata demikian. =><Taniwha> Zoid: kami kacang, tetapi kami kacang produktif :)
		-- Danny Thorpe, Borland Delphi R&R

%
<Taniwha> Zoid: kami kacang, tetapi kami kacang produktif :)* Taniwha tertanya-tanya apa kacang produktif rasa seperti
		-- Danny Thorpe, Borland Delphi R&R

%
<Endy> taniwha: Quote bahan :)<Taniwha> Endy: :)<Knghtbrd> Endy: Saya sudah snipped ia
		-- Danny Thorpe, Borland Delphi R&R

%
<Endy> Sebenarnya, saya fikir saya akan menunggu kentang dimuktamadkan sebelum       memasang debian.<Endy> Yang perlu tidak lama lagi, saya berharap. :)<Knghtbrd> Endy: Anda jelas mengetahui sedikit sahaja mengenai Debian.
		-- Danny Thorpe, Borland Delphi R&R

%
Tiada apa-apa masalah sekali anda debug kod.
		-- John Carmack

%
<Overfiend> The Unix cara - segala-galanya adalah fail<Overfiend> The Linux cara - segala-galanya adalah sistem fail yang :)
		-- John Carmack

%
<Devkev> yeah i melihat pistol kilat dan di mana anda telah pergi, berfikir         yang anda gonna menendang beberapa keldai :)<Devkev> didnt sedar ia akan menjadi :) anda sendiri
		-- John Carmack

%
"Jika tidak, sila bercakap dengan doktor tentang mengeluarkan kepala dari andaass, saya percaya ia akan memberi manfaat kepada semua yang terlibat. "
		-- Zephaniah E. Hull, flaming someone on a mailing list

%
Tagline, anda itu!
		-- Zephaniah E. Hull, flaming someone on a mailing list

%
Saya sedang mengamalkan titik halus etika. Ia boleh diterima untuk menembak kembali.Ia tidak boleh diterima untuk menembak pertama.
		-- Zed Pobre

%
<Coderjoe> gib, perl?<Gib> methinks perl adalah pengaturcara Swiss Army Chainsaw
		-- Zed Pobre

%
<Endy> taniwha: Adakah anda DIUJI satu ini? :)<Taniwha> Endy: sudah tentu tidak
		-- Zed Pobre

%
Itulah perkara yang paling lucu yang pernah saya dengar dan saya _not_ akan lindungi.
		-- DyerMaker, 17 March 2000 MegaPhone radio show

%
Ianya bukan? Adakah anda mengatakan bahawa anda perlu membenarkan orang (selain daripada WilliamWallace) untuk menangkap bolt kilat dari pantat mereka?
		-- Seth Galbraith

%
<Mercury> Anda tidak perlu menjadi gila untuk menjadi ahli projek, tetapi          anda akan .. <=:]
		-- Seth Galbraith

%
* Endy perlu berunding kopi: P<Endy> kopi orang bot, bukan kopi minuman :)<Knghtbrd> berunding minuman itu boleh membantu juga =>
		-- Seth Galbraith

%
<Mongoose> knghtbrd rendah hati, dan akan diwarisi oleh k-mart
		-- Seth Galbraith

%
<Knghtbrd> "Java untuk COBOL Programmer"<Knghtbrd> yang menulis perkara-perkara ini?<Raptor> orang pada retakpengaturcara <raptor> dan COBOL<Raptor> :)<Knghtbrd> itulah berlebihan.
		-- Seth Galbraith

%
<Evilkalla> heh, saya tidak pernah mengambil kelas pengekodan<Evilkalla> atau kelas grafik<Evilkalla> atau kelas reka bentuk perisian<Vegan> dan ia menunjukkan: P
		-- Seth Galbraith

%
* The_Answer_MD melemparkan spageti pada semua orang* Taniwha makan spageti* Coderjoe lambungan sekitar beberapa bebola daging* Knghtbrd mendapat keju* Taniwha menangkap merah
		-- Seth Galbraith

%
<Theoddone33> Apakah mesej ini pada skrin saya,<Theoddone33> jadi biru, jadi biru, apa yang boleh ia bermakna?<Theoddone33> Bolehkah anda, anda akan tekan Padam,<Theoddone33> Ctrl dan Alt dan kemudian mengulangi.
		-- Seth Galbraith

%
<Gorgo> apa yang anda dapat apabila retak seseorang mesin debian anda?<Gorgo> kentang lecek ...
		-- Seth Galbraith

%
<Aj> datang<Aj> ia klon pico<Aj> ia * bermakna * untuk menjadi menjengkelkan
		-- Seth Galbraith

%
<Espy> Aku memanggil undang-undang Espy, yang menyatakan bahawa anda semua menghisap: P
		-- Seth Galbraith

%
<Overfiend> Culus: wanna menggantung saya untuk itu? :)<Culus> Overfiend: Pergi niat jahat retak Severs sedikit dan kita akan bercakap<Overfiend> Culus: celaka, ia perlu berniat jahat?<Culus> Overfiend: Malangnya, ya
		-- Seth Galbraith

%
<Knghtbrd> 2fort5 menghisap cukup untuk mempunyai graviti sendiri ...
		-- Seth Galbraith

%
* Sinar kosmos ingin beliau mempunyai beberapa strippers sini ....<Sinar kosmos> err, strippers wayar
		-- Seth Galbraith

%
<WildTHing> lelaki ok .. jadi bila yang seterusnya melakukan: PP<Taniwha> apabila mereka datang untuk mendapatkan saya
		-- Seth Galbraith

%
<Mdorman> saya seorang gnus diri saya sendiri. Ia penyunting! Ia floorwax a!          Ia adalah satu topping pencuci mulut!
		-- Seth Galbraith

%
<Tausq> Q. Apakah perbezaan di antara Batman dan Bill Gates?<Tausq> A. Apabila Batman berjuang Penguin, dia menang.
		-- Seth Galbraith

%
Pada satu ketika, bit perlu pergi ke dalam paket dan router perlu membuatkeputusan mengenai mereka. Perubahan pada tahap itu adalah apa yang saya mahu mendengar mengenainya, tidakhubungan syarikat strategik.
		-- John Carmack

%
Kami menolak: raja, presiden, dan mengundi.Kami percaya dalam: konsensus kasar dan kod bekerja.
		-- Dave Clark

%
<Knghtbrd> QF akan mendapat sokongan zipfile hari ini<Coderjoe> heh ... infozip?<Knghtbrd> Jika saya bernasib baik ya<Deek> knghtbrd: Anda bergurau, bukan? ;)* Deek menghilangkan paip retak Knghtbrd ini. ;)
		-- Dave Clark

%
<Deek> mengubah semua cvar-> value = X untuk menggunakan Cvar_Set ()<Theoddone33> yang tidak berlaku dalam oldtree<Deek> Sebenarnya, ia tidak.<Knghtbrd> yeah - dua minggu kemudian.
		-- Dave Clark

%
=== Surat ini adalah Virus Sistem Honor ====Jika anda menjalankan Macintosh, OS / 2, Unix, atauLinux, sila memadamkan secara rawakbeberapa fail dari cakera keras anda danmengemukakan mesej ini kepada semua orang yang anda tahu.==============================================
		-- Dave Clark

%
* Shortc mahu mendapatkan salah satu daripada menggunakan tanda satu hari ini knghtbrd ini.
		-- Dave Clark

%
<Dr ^ Nick> SGI_Multitexture adalah voodoo buruk sekarang<Dr ^ Nick> ARB adalah voodoo baik<Witten> tidak, guna-guna tergesa-gesa adalah voodoo buruk :)
		-- Dave Clark

%
99 sedikit bug dalam kod, 99 bug dalam kod,        menetapkan satu bug, menyusun lagi ...        101 sedikit bug dalam kod ....
		-- Dave Clark

%
Hmm ... Yang akan melakukan kerja yang lebih baik pada memandu fizik gila? Travellebih cepat daripada cahaya, atau nilai boolean terapung-mata?
		-- Michael Mol

%
<Kiraan> knghtbrd: gnome 2.0 akan keluar dalam beberapa bulan, tidak pasti bagaimana ia       jika dibandingkan dengan KDE 2.0 walaupun<Knghtbrd> calc: Sama seperti kembung, sama seperti kereta, dan setiap aplikasi Gnome 2       akan bergantung kepada 30 perpustakaan.<Slimer> knghtbrd: jadi apa yang berubah dari 1.0?
		-- Michael Mol

%
<Ze0> ya, bagaimana segala-galanya dalam dunia Quack?<LordHavoc> just Ducky<Ze0> yang sangat baik, itik goreng itu perkasa denda lazat.
		-- Michael Mol

%
<FrikaC> saya mungkin perlu reboot ...<FrikaC> BRB ok<FrikaC> Jadi, apa yang selain bentuk mengelakkan virii, kebocoran memori, dan berleluasa         terhempas tidak Linux reallhy menawarkan :)<LordHavoc> multitasking boleh dipercayai?
		-- Michael Mol

%
<Tausq> jika (cb) ((cb-> obj) -> * (cb-> ui_func)) ();<Knghtbrd> tausq: siapa HELL menulis bahawa?<Tausq> saya :)* Knghtbrd flogs tausq
		-- Michael Mol

%
<Knghtbrd> glDisable (GL_BUGS);<Endy> heh<Endy> Adakah itu dalam 1.2? :)
		-- Michael Mol

%
<Mercury> knghtbrd: Eww, mencari nama yang lebih baik, filem ini disedut .. <G><Knghtbrd> Mercury: Enjin adalah lebih baik daripada filem
		-- Michael Mol

%
<LackOfKan> Apakah 'bots'?< `` Erik> rsg adalah bot, bukan manusia, bukan pelanggan boleh digunakan manusia, hanya bot.< `` Erik> lebih kurang sama dengan bot gempa, kecuali bots irc adalah (biasanya)         dibina untuk membantu, tidak menembak keldai anda penuh dengan lubang
		-- Michael Mol

%
jika (me = anda!) // FIXME: mungkin sentiasa benar, memadamkan?    untuk (n = 0; n <who_knows_what; n ++) {        answer = DoSomething (withthis [n]);        jika (jawapan == foobar) {            GetLost (n);            dipatahkan;        }    }
		-- Michael Mol

%
<Knghtbrd> Yorick: ada masalah dengan palet warna diindeks untuk imej, kerana           selagi anda boleh memilih palet<Yorick> Jelas sekali rakyat mewujudkan gempa adalah buta warna tetapi itu         tidak bermakna anda perlu
		-- Michael Mol

%
kunci <cesarb> Damn, setiap kali saya bertelur, QF-pelanggan-X11 keras<Zoid> Jangan mati?<Knghtbrd> insentif yang baik.
		-- Michael Mol

%
Kenapa semua instrumen mencari kehidupan pintar dialam semesta menunjuk jauh dari Bumi?
		-- Michael Mol

%
<Rebelpacket> hey, soalan cepat, ada apa-apa cara untuk mempercepatkan              prestasi uquake-x11?<Deek> rebelpacket: Jika anda ingin mempercepatkannya, membuang ia lebih keras.
		-- Michael Mol

%
<Netgod> anda tahu<Netgod> yang benar-benar sedih apabila InterNIC itu sendiri cant mengkonfigurasi DNS         pelayan betul<Netgod> ia hanya tidak mendapat apa-apa lebih menyedihkan daripada itu
		-- Michael Mol

%
<Knghtbrd> Walaupun dengan overbrights, palet warna Quake adalah penuh membosankan,           warna rata<LordHavoc> knghtbrd: palet gempa adalah sangat bertenaga melainkan jika anda menggunakan gamma            pembetulan<LordHavoc> juga sebenarnya saya bersetuju, ia adalah tempat berhampiran sebagai berdaya maju sebagai Unreal<Deek> Q3 pada tangan ... NEON lain.<LordHavoc> Q3 hanya masuk akal<Deek> Q3 mengambil zaman pertengahan gereja-penjara dan meletakkannya di Vegas.
		-- Michael Mol

%
"Saya mempunyai tulang untuk memilih, dan beberapa tempat untuk berehat."
		-- Anonymous

%
Z.O.I.D .: Zombie Dioptimumkan untuk penyusupan dan Kemusnahan
		-- Anonymous

%
<Deek> Ya, Amerika adalah sebuah negara yang berdasarkan bagaimana mabuk benar-off sekumpulan dikenakan cukai       orang ramai boleh mendapatkan.<Deek> Kami wujud sebagai sebuah negara kerana kami murah.
		-- Anonymous

%
<Oskuro> Overfiend: banyak tampalan pada bahagian atas 4.0.1 sudah?<Overfiend> Oskuro: beberapa<Overfiend> hanya 152 megs
		-- Anonymous

%
<Joeyh> oh saya, ia adalah satu UP P III.<Doogie> dos ia.* Joeyh berjalan dselect<Overfiend> yang seharusnya memadai :)
		-- Anonymous

%
<Barneyfu> knghtbrd: crap, SDL pasti menjadikan DGA yang helluva alot mudah terlalu           bukan? :)<Knghtbrd> barneyfu: apa DGA?<Barneyfu> tetikus DGA<Knghtbrd> barneyfu: (adakah itu menjawab soalan anda?)<Barneyfu> Hahahahaha YEAH! :)
		-- Anonymous

%
<Deek> "A programmer yang baik boleh naik FORTRAN dalam mana-mana bahasa."<Deek> knghtbrd telah membuktikan bahawa anda boleh menulis C ++ dalam mana-mana bahasa juga.       <Senyuman><Mercury> Kami sedang considdering jika kita berikan kepadanya atau hadiah, atau          bunuh dia..<Mercury> (Sudah tentu, dengan segala hak, ini bermakna kita berikan kepadanya          hadiah, dan kemudian membunuhnya .. <G>)
		-- Anonymous

%
A subversif adalah sesiapa sahaja yang boleh keluar ekspres berhujah kerajaan mereka.
		-- Anonymous

%
Kita mesti tahu, kita akan tahu.
		-- David Hilbert

%
<Knghtbrd> penapisan Internet. Oleh kerana anak-anak anda perlu           dilindungi daripada wanita telanjang, prosedur perubatan, pelbagaibudaya, dan permainan video ganas.<Knghtbrd> (tetapi maklumat mengenai bom bangunan, mencuri kabel dan           dadah pembuatan adalah okay ...)
		-- David Hilbert

%
Seorang rakan saya mempunyai kod bar pada tangannya.Beliau berdering sehingga sebagai $ 0,35 pek JuicyFruit.
		-- Seen on Slashdot

%
<NullC> saya suka kod benih untuk mengira lengkung pelekat.<NullC> Saya tidak pernah melihat kod yang dibuat akan mahu minum sebelum itu ...
		-- Seen on Slashdot

%
$ Anda = baru ANDA;membunyikan () jika $ anda-> cinta (perl)
		-- Seen on Slashdot

%
<Cj> tidak! masalah dalam M $ perisian?<Cj> "Teliti bugtested"* Dabb senyum.<LordHavoc> menulis semula itu sebagai 'Teliti buginfested'
		-- Seen on Slashdot

%
<Doogie> dpkg mempunyai bug? sama sekali tidak!
		-- Seen on Slashdot

%
"Debian: tidak topi atau reptilia telah dicederakan dalam pembuatan pengedaran ini =. "
		-- Paul Slootman

%
* Athener panggilan Amnesty International House of Pancakes
		-- Paul Slootman

%
<Elmo> haram sesat, pasukan admin tidak mengawal arkib, itulah       ftp bersekongkol<Elmo> mendapatkan cabals anda betul, persetan :-P
		-- Paul Slootman

%
<BenC> Sinar kosmos: anda melengkapkan saya<BenC> err ...<Sinar kosmos> heh* BenC kembali kepada pengekodan* Elmo melihat benc<Elmo> sesuatu yang kita perlu tahu mengenai anda dan Sinar kosmos, Ben? :)
		-- Paul Slootman

%
Tukar Kontrak Sosial? BWAHAHAHAHAHAHAHAHAHAHAHA.
		-- Branden Robinson

%
<Knghtbrd> Program menerima SIGSEGV isyarat, kesalahan Segmentasi.<Knghtbrd> 0x40095fb0 dalam memchr () dari /lib/libc.so.6<Knghtbrd> (Pra-Pemasangan) bt<Knghtbrd> # 0 0x40095fb0 dalam memchr () dari /lib/libc.so.6<Knghtbrd> # 1 0x0 dalam ?? ()<Knghtbrd> Well Itulah Really sedia membantu* Knghtbrd perdagangan Pra-Pemasangan bagi papan ouija bagus - ia akan membantu lebih
		-- Branden Robinson

%
Semua idea yang baik kelihatan seperti idea yang buruk untuk orang-orang yang rugi.
		-- Dilbert

%
RFC 882 meletakkan titik dalam .com, tidak Sun Microsystems
		-- Seen on Slashdot

%
* Joeyh_ tertanya-tanya jika linux sepatutnya mengunci apabila anda bertanya 100  memproses kepada kucing keseluruhan pemacu cd
		-- Seen on Slashdot

%
<Pretzelgod> knghtbrd: Quake harus menyokong visi xray, celaka<Knghtbrd> pretzelgod: ftp://ftp.cdrom.com/pub/quake/partial_conversions/           xrated / i_am_old_enough_to_look_at_this<Knghtbrd> ... anda bertanya ...<Sinar kosmos> haha, yang adalah direktori sebenar
		-- Seen on Slashdot

%
<Knghtbrd> Saya menyelinap ke BUN<Knghtbrd> HELP ME UNTUK KE dukun<Venom> kb: apa neraka yang anda bercakap tentang?<Knghtbrd> bwahahaha .. Ia adalah cerita lama.
		-- Seen on Slashdot

%
<WildCode> Mercury, tidak debugging X sedikit seperti mencari dengan sempurna           kod bugfree pada tingkap ??<Mercury> WildCode: Debugging X adalah seperti cuba untuk menjalankan garis lurus          melalui mez.<Mercury> Anda hanya perlu bengkok ruang-masa supaya sudut bergerak          anda dan anda tidak akan mempunyai sebarang masalah. (=:]
		-- Seen on Slashdot

%
<Miguel> `Anda telah dinyahlanggan dari tenaga yang tinggi peribadi         peranti perlindungan mailing list '<Miguel> Saya tidak ingat mendapat ke dalam senarai mel
		-- Seen on Slashdot

%
<Mitos> Saya mendapat sambungan yang enggan apabila menyambung ke port 25, sesiapa sahaja       tahu di mana log sialan itu?<Aj> Mitos: /var/log/damn.log?* Aj tertanya-tanya apa yang akan kelihatan seperti<Aj> Disember 18 05:32:30 blae SMTPD [123]: DAMN IT ALL TO HELL !!
		-- Seen on Slashdot

%
* Keajaiban weasel betapa bodohnya seseorang itu mestilah untuk alt.anonymous.messages spam<Knghtbrd> weasel: kira-kira separuh bodoh kerana seseorang perlu adalah untuk menuainya.
		-- Seen on Slashdot

%
* Wolfie ponders bagaimana banyak debianites yang diperlukan untuk skru dalam mentol lampu<Viiru> Wolfie: Di suatu tempat sekitar 600? Satu skru yang mentol, dan selebihnya        nyalaan beliau untuk lakukan salah.<Sebahagian> Wolfie: adalah perisian mentol percuma?<Tv> Bolehkah kita mengundi sama ada untuk skru atau tidak?
		-- Seen on Slashdot

%
<Culus_> Kami juga berharap untuk melepaskan versi linux mana shell         digantikan dengan perl tahap yang besar. Menambah itu, terdapat         sedikit daripada kita yang ingin melihat platform perl yang murni .. PerlOS :)* Culus_ kelihatan di dalam seram<Mstone> Culus_: di sebelah atas, anda boleh menaip sialan berhampiran apa-apa dalam di         arahan prompt :)
		-- Seen on Slashdot

%
<Mercury> LordHavoc: Sebab mengapa GL mempunyai terlebih adalah kerana ia hanya          menggunakan separuh daripada sistem yang mereka direka untuk vis.<Mercury> LordHavoc: Menembak dirinya di kaki.* Dabb melihat semua lubang peluru dalam kasut - sialan, banyak :)
		-- Seen on Slashdot

%
<Dabb> hehe, saya benar-benar benci laporan bug yang seperti memanggil api       jabatan dan berkata: "Terdapat api di sini, datang" :)<Dabb> (dan menggantung)* Dabb membunuh kira laporan dozen bug.
		-- Seen on Slashdot

%
<Xtifr> wow, saya rasa saya hanya digunakan libtool untuk menyelesaikan masalah - seseorang        Tolong saya! :><Luca> xtifr, langkah lagi KEYBOARD THE
		-- Seen on Slashdot

%
<Mao> mengapa mereka berkeras Ading -Werror ...<Misty-chan> Mesa tidak akan menyusun keluar dari kotak jika ia dilakukan oleh anda             semua;)<Knghtbrd> Uh, Mesa TIDAK menyusun keluar dari kotak kebanyakan masa.
		-- Seen on Slashdot

%
<Deek> nopcode: Tidak, ia tidak. Win32 kurang sama dengan garpu ().<Knghtbrd> Deek: windoze bukan untuk orang-orang yang perlu mempunyai akses kepada           objek tajam, dengan itu tiada garpu ()<Knghtbrd> sebaliknya, anda perlu bergantung pada sudu ()
		-- Seen on Slashdot

%
<Knghtbrd> Font ini mula keluar sangat baik<Stu> Knghtbrd: oh sayang, yang anda penggodaman satu lagi font gempa bumi di vi? :)
		-- Seen on Slashdot

%
<Pv2b> oh, selain itu, whats pendekatan terbaik jika saya ingin Quake yang       tahap direka dari bangunan yang sedia ada?<Knghtbrd> Dapatkan Pelan Lantai pejabat Brian? =)<Pv2b> Knghtbrd: im memandangkan sekolah saya.<Knghtbrd> Oh besar<Knghtbrd> Itu sahaja yang kami perlukan
		-- Seen on Slashdot

%
<Knghtbrd> simen Windoze: Kini dengan CrackGuard (TM)! Jangan bimbang tentang           retak hodoh dalam simen Windoze lagi! CrackGuard (TM) adalahbegitu kuat bahawa perkara yang keseluruhan akan runtuh sebelum ia akanretak. Order $ 200 versi naik taraf anda hari ini!
		-- Seen on Slashdot

%
<Doogie> Culus: bug saya dengan openssh nampaknya tetap dalam 2.5.2, tetapi         master berjalan 2.3.0<Culus> Jangan juga mula<Doogie> Saya hanya lakukan.<Culus> Kalian akan memandu saya untuk membina sebuah robot gergasi yang besar dan        memusnahkan semua texas, kan?
		-- Seen on Slashdot

%
<Shader> whats salah dengan rjing?<Rhamphoryncus> ia lumpuh: P<Rhamphoryncus> ia TIDAK perlu dibuat<Rhamphoryncus> shoving bom tangan sehingga keldai anda dan menggunakannya sebagai roket                propelant tidak seharusnya menjadi teknik yang berdaya maju: P
		-- Seen on Slashdot

%
 * Kod Setaraf boleh didapati daripada RSA Data Security, Inc. * Kod ini telah diuji terhadap itu, dan bersamaan, * Kecuali bahawa anda tidak perlu untuk memasukkan dua muka surat legalese * Dengan setiap salinan.
		-- public domain MD5 source

%
* Knghtbrd hilang - zzz - Mesej akan direbut seperti tuala basah di semua  orang-orang yang telah mencuri cap dagang knghtbrd jauh mesej<Coderjoe> ack* Coderjoe bersedia untuk mempertahankan dirinya daripada mesej yang basah
		-- public domain MD5 source

%
Jangan sekali-kali memandang rendah kuasa seseorang dengan kod sumber, editor teks,dan kesediaan untuk sama sekali hos sistem mereka.
		-- Rob Landley <telomerase@yahoo.com>

%
"Jadi, akan parti Andover mempunyai bar tunai?""Tidak, ada bir percuma.""Uh-oh, gonna Stallman yang dapat mabuk benar ..."
		-- overheard at the Bazaar, 1999

%
<Addi> Alter.net seolah-olah telah menggantikan salah satu router dengan yang zucchini.
		-- overheard at the Bazaar, 1999

%
<Mercury> Seseorang membaikinya.<Despair> komited<Knghtbrd> Despair: Mercury?<Despair> Knghtbrd: dia letih, membuat kesilapan, mahu seseorang untuk membuat asal.<Knghtbrd> berputus asa, maka anda telah dia komited?<Despair> Knghtbrd: baik, berdedikasi anyways.
		-- overheard at the Bazaar, 1999

%
<Taniwha> Knghtbrd: ia tidak mengasapi jika ia digunakan<Knghtbrd> taniwha: bagaimana anda menjelaskan windoze kemudian?<Taniwha> Knghtbrd: kebanyakan ia hanya digunakan sebagai balast memastikan anda          harddrive penuh<Knghtbrd> taniwha: ballast ... Bukankah itu apa yang membuat kapal selam tenggelam ke           bawah lautan?<Knghtbrd> taniwha: yang akan menjelaskan mengapa winboxes sentiasa akan turun.
		-- overheard at the Bazaar, 1999

%
inovasi / IN tiada Vait / vb .: 1. teknologi pihak ketiga sesuaimelalui pembelian, tiruan, atau kecurian dan untuk mengintegrasikan ke dalamde-facto, produk monopoli-kedudukan. 2. Untuk meningkatkan saiz atau kerumitantetapi tidak dalam utiliti; untuk mengurangkan keserasian atau saling boleh kendali. 3. Untuksekat masuk pesaing atau untuk mengunci masuk pengguna. 4. Untuk mengecas lebih banyak wang; kepadamenaikkan harga atau kos. 5. Untuk memperoleh keuntungan daripada pelaburan dalam lainsyarikat-syarikat tetapi bukan dari produk secara langsung atau jualan. 6. Untuk menyekat ataumemanipulasi pasaran bebas; untuk memperluas kuasa monopoli ke pasaran baru. 7.Untuk mengelakkan liabiliti disebabkan kezaliman; untuk turun. 8. Untuk pembelianundang-undang, undang-undang, badan perundangan, atau ketua-ketua negeri. 9.pengantara semua urus niaga dalam ekonomi global; untuk menggelapkan; kuasa untuk melantik(Rampasan kuasa). Cf. inovasi, penggunaan bahasa Inggeris (antonim).
		-- csbruce, in a Slashdot post

%
Kesunyian memekakkan telinga mengajar saya untuk tidak meminta sekumpulan Geeks untuk mendapatkan nasihatdari teman wanita mereka
		-- csbruce, in a Slashdot post

%
"Apa yang kita akan lakukan pada malam ini, Rang Undang-undang?""Perkara yang sama kita setiap malam Steve, cuba untuk mengambil alih dunia!"
		-- csbruce, in a Slashdot post

%
<Deek> Yang mengingatkan saya, kami akan perlu membeli rantai untuk pejabat. "Dalam       kes kecemasan, memecahkan kaca "
		-- csbruce, in a Slashdot post

%
<Knghtbrd> Dia separuh saiz yang bertentang yang lain.<Knghtbrd> Tetapi dia mendapat gergaji.
		-- csbruce, in a Slashdot post

%
<Deek> "Saya menyimpan data gpg peribadi saya dalam dikunci, membawa selamat dalam peti besi       dijaga oleh rednecks marah dan Dawgs mereka. Penceroboh akan menjadi       dilanggar, dan semua yang ... "
		-- csbruce, in a Slashdot post

%
<ExMachina> glQuakeIIIRendererMode (GL_TRUE)<Knghtbrd> ExMachina: tidak bahawa sebahagian daripada lanjutan yang menyediakan           glDriverBugs (GL_FALSE); ?<Siigron> Knghtbrd: tidak, glDriverBugs () adalah sebahagian daripada EXT_help_me.<Siigron> yang juga mengandungi glMakeItWork (GL_PLEASE);
		-- csbruce, in a Slashdot post

%
< `` Erik> 18.446.744.073.709.551.616 adalah satu jumlah yang besar
		-- csbruce, in a Slashdot post

%
<Xavvy> adalah yang benar-benar knghtbrd?<Knghtbrd> Tidak, saya seorang penyamar EVIL!<Knghtbrd> An penyamar jahat yang SUKA HYBRID!<Xavvy> haha<Xavvy> ok, ia kepadanya: P
		-- csbruce, in a Slashdot post

%
<| Rain |> I * cinta * SWB !!<| Rain |> Atau, tekan 5 untuk bercakap dengan bertulis oleh pihak Rentokil ..<| Rain |> * 5 *<| Rain |> Anda sedang dipindahkan, sila memegang ...<| Rain |> ...<| Rain |> ...<| Rain |> Kami memohon maaf, nombor ini tidak dapat diselesaikan seperti didail.<| Rain |> Periksa nombor tersebut dan cuba lagi.
		-- csbruce, in a Slashdot post

%
<| Rain |> # menentukan struct union / * penjimat ruang yang besar * /
		-- csbruce, in a Slashdot post

%
<Elric> tiada peminat BSD?<EvilTypeGuy> Elric: ia sukar untuk menjadi peminat permainan video dan peminat bsd: p
		-- csbruce, in a Slashdot post

%
<Marticus> Terdapat terlalu banyak darah dalam sistem kafein saya.
		-- csbruce, in a Slashdot post

%
<SirDibos> Culus: adakah anda terjaga?<Culus> no
		-- csbruce, in a Slashdot post

%
<WLI> Ya, saya melihat esd dan ia kelihatan seperti jenis kod C bahawa      bekas JOVIAL / Algol '60 alat sandi yang telah menghabiskan 20 tahun yang lalu melantun      antara Fortran-IV dan Fortran '77 akan menulis.
		-- csbruce, in a Slashdot post

%
<Linear> .net adalah microsofts short sesat daripada rangkaian java            persekitaran uglified untuk crap windows-khusus
		-- csbruce, in a Slashdot post

%
<Mercury> LordHavoc: Saya sudah tidak siuman.<Coderjoe> sialan lurus. atau curvy, bengkok, atau apa yang telah anda
		-- csbruce, in a Slashdot post

%
Unix adalah OS matang, tingkap masih dalam lampin dan mereka bau teruk.
		-- Rafael Skodlar <raffi@linwin.com>

%
<Midgar> Dari semua sterotypes mengenai Aussies, saya tahu anda semua         benar-benar sukar.<Midgar>; p<Krusto> kami akan membuang koala ini pada anda
		-- Rafael Skodlar <raffi@linwin.com>

%
<| Rain |> * mengangguk * Saya tidak gemar menggunakan smarthosts, diri saya sendiri<| Rain |> kerana ia bergantung kepada kedua-dua hos jauh dan tuan rumah anda menjadi pintar<| Rain |> dan terlalu kerap anda terlepas salah satu daripada kedua-dua matlamat tersebut
		-- Rafael Skodlar <raffi@linwin.com>

%
Pendekatan sourceforge adalah untuk meletakkan semua projek di beberapa hambar"Sumber surburbia terbuka", di mana setiap rumah adalah sama, dengan hanyawarna dan variasi gaya kecil (yang pelan bangunan telah digunakan yang manarumah tertentu) dibenarkan oleh perjanjian-perjanjian ketat dan tempatanzon undang-undang. Sourceforege bersamaan sumber terbukapecah bahagian dalam filem "Edward Scissorhands".
		-- Terry Lambert

%
<Kiraan> Knghtbrd: irc tidak menyusun kod c dengan baik;)
		-- Terry Lambert

%
* | Hujan | menyediakan untuk sup poligon<| Rain |> gula crap penyayang, ia berfungsi?* | Hujan | pengsan
		-- Terry Lambert

%
"Oleh kerana ia adalah satu kesimpulan diketepikan bahawa Microsoft akan menjadi sampah XML yangdengan petunjuk kepada komponen berasaskan Win32, yang terbaik yang boleh dikatakan tentangpenerimaannya XML adalah bahawa ia akan membuat ia lebih mudah untuk pelayar danaplikasi pada platform bukan Windows untuk memahami bahagian-bahagiandokumen yang boleh abaikan. "
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<Robert> i memahami terdapat beberapa had yang munasabah untuk bersuara dalam         Amerika, sebagai contoh saya tidak boleh menjerit api ke dalam teater yang sesak.. Tetapi saya boleh menjerit api ke dalam teater dengan hanya 5 atau 6 poeple	 di dalamnya ?
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<Aav> kopi dengan perut kosong adalah nasy cantik<Knghtbrd> Aav: masa untuk lari ke mesin layan diri untuk Cheetos<Aav> Cheetos? :)
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<| Rain |> dengan kod waras, mungkin saya dapat memikirkan pemapar :)<LordHavoc> hujan: saya mungkin akan menjadi orang yang menulis pemapar<| Rain |> baik, er, uh
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<| Rain |> Knghtbrd: biarlah saya memberikan anda akses kepada fail zon<Knghtbrd> oh tuhan - anda sedar saya tidak pernah bermain dengan hak mengikat?<| Rain |> Alamak :)
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<F00Dave> Lihat, menolak, ini adalah #OpenGL, tidak #GEEKSEX.
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
* TwingyAFK adalah membeli-belah untuk 17 "panel rata* Aav menjual TwingyAFK sekeping papan lapis
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
Bukankah ia memalukan apabila anda perlu pergi ke kedai ubat untuk beberapa"Barang-barang khas", dan apabila anda mendaftar keluar, juruwang memandang andaseperti, "oh, saya tahu apa yang anda lakukan malam ini ..."Yep, juruwang yang membaca semua sup ayam tanda-tanda ... tin, Theraflu,Halls, NyQuil, botol bigass daripada OJ dan jus limau gedang ... dia tahudan saya tahu bahawa saya mempunyai tarikh dengan teevee dan penghibur ke bawah. Awwwyeah.
		-- Elizabeth Kirkindall

%
Dalam sains ia sering berlaku bahawa saintis berkata, 'Anda tahu itulah yang benar-benarhujah yang baik; kedudukan saya adalah salah, dan kemudian mereka benar-benar mengubahfikiran mereka dan anda tidak pernah mendengar bahawa pandangan Perempuan daripada mereka lagi. mereka benar-benarlakukannya. Ia tidak berlaku sekerap seperti yang sepatutnya, kerana ahli-ahli sainsmanusia dan perubahan adalah kadang-kadang menyakitkan. Tetapi ia berlaku setiap hari. Saya tidak bolehingat kali terakhir sesuatu seperti yang berlaku dalam politik atau agama.
		-- Carl Sagan, 1987 CSICOP keynote address

%
<Knghtbrd> menambah / 3, cakera keras yang agak besar GF2, dan "panel rata 15 dan           anda telah mendapat satu mesin mudah alih yang cukup terkutuk.<Coderjoe> a GeForce Dua Pertiga?<Knghtbrd> Coderjoe: ya, GeForce dua pertiga, iaitu, apa-apa kad dari ATI.
		-- Carl Sagan, 1987 CSICOP keynote address

%
<Knghtbrd> Nintendo Isytihar GCN Kebanyakan Console Popular Ever<Knghtbrd> Siapa yang mereka bergurau?<Mercury> knghtbrd: Pemegang Saham?
		-- Carl Sagan, 1987 CSICOP keynote address

%
<LordHavoc> majoriti artis windoze tidak mempunyai keupayaan untuk            menyelamatkan xpm<Mercury> LordHavoc: Mereka tidak mempunyai notepad? * G, D & R *
		-- Carl Sagan, 1987 CSICOP keynote address

%
Linux menyokong tanggapan baris arahan atau shell atas sebab yang samabahawa hanya kanak-kanak membaca buku dengan hanya gambar-gambar di dalamnya. Bahasa, sama adaBahasa Inggeris atau sesuatu yang lain, adalah satu-satunya alat yang cukup fleksibel untuk mencapaipelbagai cukup luas tugas.
		-- Bill Garrett

%
## Rakam Keluar: pemberontak (razzin 'frazzin' motherfu ... DirectX bodoh ...)
		-- Bill Garrett

%
<Krogoth> Kgnghtbrd: Saya tidak akan Kow, saya melihat ada keperluan untuk pemeriksa ejaan yang belum<Knghtbrd> yang anda katakan?
		-- Bill Garrett

%
<Knghtbrd> Baik aku meletakkan barangan yang memberatkan ke dalam kod: ahfuiovka           ikperoa edfr ade 9 enbuw ejasxleme ka iena df4mesa<Knghtbrd> Jika anda boleh menyahsulitkan itu, anda pembacaan sandi yang lebih baik daripada yang saya           saya sedang. =)
		-- Bill Garrett

%
<RCW> liiwi: printk ( "CPU0 terbakar \ n");
		-- Bill Garrett

%
<Electro> komputer saya pernah menjadi salah satu blok bangunan yang besar          piramid
		-- Bill Garrett

%
NOTIS: sesiapa yang melihat merokok akan dianggap terbakar dan akan        secara terus meletakkan keluar.
		-- Bill Garrett

%
<Markm> c ++: kuasa, keanggunan dan kesederhanaan bom tangan
		-- Bill Garrett

%
<Knghtbrd> tetapi satu jenis setiap tab dan tiada bagi setiap senarai boleh dikatakan lebih baik daripada           O (n + n ** 2) bagi setiap tab dan O (n ** 2) bagi setiap senarai.<Knghtbrd> OMG, seseorang menembak saya.<Coderjoe2>?<Knghtbrd> Saya tidak boleh percaya saya hanya menggunakan besar angsa-telur untuk menjelaskan mengapa saya           cara mungkin yang terbaik dalam jangka masa panjang.
		-- Bill Garrett

%
<Hoponpop> berfungsi program saya jika saya mengambil bug.
		-- Bill Garrett

%
<Mercury> Knghtbrd: Hey, perl mempunyai rahmat kuasa dan keanggunan eretan a          tukul. (=:]<| Rain |> pasti rahmat dan keanggunan, anyway
		-- Bill Garrett

%
<DannyS> Hit monyet untuk memenangi $ 20 (*)!* Knghtbrd mendapat daripada tukul beliau.* Tumbuhan knghtbrd dengan kuat di kepala DannyS '.* Knghtbrd akan mengambil $ 20 beliau sekarang. = D
		-- Bill Garrett

%
<Gholam> baik saya kagum<Gholam> Win98 berjaya crash X dari dalam VMware.* Gholam memuji.
		-- Bill Garrett

%
"Nvidia pemandu OpenGL adalah saya" standard emas ", dan ia telah agaksementara kerana saya terpaksa melaporkan masalah kepada mereka, dan juga jenama merekasambungan baru bekerja sebagai didokumenkan kali pertama saya cuba mereka. Apabila saya mempunyaisatu masalah pada Nvidia, saya menganggap bahawa ia adalah kesilapan saya. Dengan orang lain yangpemandu, saya menganggap ia adalah salah mereka. Ini ternyata betul hampirsetiap masa."
		-- John Carmack

%
Libtool kongsi mudah alih perpustakaan hanya sedikit lebih dipercayai daripadamesin gerakan kekal. Terutamanya pada AIX :). "
		-- David Leimbach

%
<Overfiend> ini adalah Overfiend baru, pendakwah Cinta dan Toleransi
		-- David Leimbach

%
<Hoponpop> perbezaan antara NetBSD, FreeBSD dan OpenBSD, sebagai           orang dalam adalah freebsd berminat untuk mendapatkan perkara yang dilakukan, dantidak kisah menyakiti orang yang mendapat dengan cara mereka.<Hoponpop> NetBSD berminat untuk membuat apa-apa pasti akan dilakukan, dan           tidak kisah mencederakan orang-orang yang cuba untuk mencapai sesuatu.<Hoponpop> OpenBSD berminat untuk mencari yang baik, dan tidak menyakiti sesiapa           dalam komuniti mereka sendiri sedikit, tetapi melihat keluar orang lain!
		-- David Leimbach

%
<Liiwi> demikian, apakah cara yang rasmi untuk buildd untuk mencuba semula pakej? prod        ia dengan kayu?<Joey> neuro prod<Liiwi> dengan kayu?<Joey> ya.
		-- David Leimbach

%
<Knghtbrd> "... anda lebih daripada mungkin akan melihat semua jenis pengkompil           amaran menatal oleh pada skrin. Ini adalah normal dan bolehdiambil dengan selamat diabaikan. "<LordHavoc> Knghtbrd: adalah bahawa nota yang melekat pada beberapa M $ kod?<Knghtbrd> Tidak, ia adalah satu nota mengenai sekumpulan barangan GNU.
		-- David Leimbach

%
<Hidroksida> knightbrd: dari import knightbrd.brain * :)<Knghtbrd> tuhan Oh olah ia adalah yang mudah ..<Knghtbrd> dari OpenGL carmack.brain import
		-- David Leimbach

%
<LIM> mmmm, donat multitextured ....<Knghtbrd> LIM: dengan pengisian buah-buahan?<LIM> knghtbrd: coklat krim ...
		-- David Leimbach

%
<StevenK> Anda menulis semula bahagian Quake dalam * Python *?<Knghtbrd> MUAHAHAHA
		-- David Leimbach

%
## A_nick (nobody@c213-89-87-111.cm-upc.chello.se) telah menyertai #python<A_nick> bagaimana saya tambah kunci baru kepada kamus?<A_nick> nm<Dash> heh :)<Dash> lihatlah kuasa penyelesaian masalah daripada #python.
		-- David Leimbach

%
<Hop_> saya mempunyai sesuatu yang saya fikir adalah ayam yang telah disalut dengan merah       pes yang seolah-olah terdiri daripada lye berdasarkan berapa banyak saya       Lidah ia dibakar.<Hop_> kawan kita yang India berkata ini adalah mengapa kebanyakan kaum India adalah nipis       dan saya memetik "Ia tidak mengambil masa yang banyak makanan ini untuk mendapatkan anda       enoguh berpuas hati untuk berhenti makan. "
		-- David Leimbach

%
<Niat> "Ia adalah ekonomi meresap-up klasik, menyedari wang yang            adalah seperti baja: Ia amat berkesan sekiranya anda menyebarkan sekitar ".<Knghtbrd> Niat: korelasi Carter: Orang yang banyak sama ada           biasanya bau lucu<Niat> Knghtbrd: Anda SO menang.
		-- David Leimbach

%
