* SynrG konštatuje, že počet konfiguračných otázok odpovedať  sendmail je netriviálne
		-- David Leimbach

%
James by bol väčší dojem, ak magické sily netgod by mohol zastaviť  rozdeľuje na prvom mieste ...* Netgod poznamenáva, vývojári Debianu sú notoricky ťažké zapôsobiť
		-- David Leimbach

%
<Sel> potrebujú pomoc: môj prvý paket svojmu poskytovateľovi stratí :-(<Netgod> sel: dont poslať prvý, kto s # 2
		-- David Leimbach

%
<James> mňa posmechu. Som tak lame som poslal hlásenie o chybe na        debian-devel-changes
		-- David Leimbach

%
Nikdy by ma nenapadlo, že by som vidieť ten deň, keď Netscape je slobodný softvér aX11 je proprietárne. Žijeme v zaujímavých časoch.
		-- Matt Kimball <mkimball@xmission.com>

%
<Jim> Nechajte ma uistil, nebudem strácať čas tu ... bcwhite odstráni      PKGS že havent boli stanovené ktoré majú vynikajúcu chyby závažnosti      "Dôležité". Pravda alebo lož?<JHM> Jim: "dôležité" alebo vyšší. To je pravda.<Jim> Potom sa chystáme stratiť ftp.debian.org a dpkg :)* Netgod bude chýbať dpkg - to bol občas užitočný<Joey> Stále máme otáčok za minútu ....
		-- Matt Kimball <mkimball@xmission.com>

%
<JHM> preťaženia je znakom ozajstné Debian správcu.
		-- Matt Kimball <mkimball@xmission.com>

%
<Overfiend> partycle: Ja vážne potrebujeme dovolenku z tohto balíka.            Vlastne som mal sen o zavedení stupídny novej bug            do xbase-opätovnej minulú noc. To je zlé znamenie.
		-- Matt Kimball <mkimball@xmission.com>

%
Písanie non-free software nie je eticky legitímne činnosť, takže akľudia, ktorí tento beh do problémov, to je dobré! Všetky podniky založenéna non-slobodný softvér by mal zlyhať, a čím skôr, tým lepšie.
		-- Richard Stallman

%
Microsoft DNS služba skončí abnormálne, keď prijíma odpoveďna dotaz DNS, ktorý nebol nikdy vykonaná. Fix informácie: Spustite DNSslužba na iné platforme.
		-- BugTraq

%
* Dpkg ruky Stu obrovskú pohár vbeer* Joey vezme pivo z STU, si príliš mladý;)* Cylord berie pivo od Joey, si príliš opitý.* Cylord dáva pivo do muklov.
		-- BugTraq

%
My ľudia z distribúcie Debian GNU / Linux, za účelom vznikudokonalejší operačný systém, vytvoriť kvalitné, poistiť trhoviskorozmanitosť, zabezpečiť spoločný potrebám používateľov počítačov, propagovaťbezpečnosť a súkromie, zvrhnúť monopolné sily v počítačisoftvérový priemysel, a zabezpečiť požehnanie slobody pre seba anaše potomstvo, to vysvätiť a založiť túto Ústavu pre DebianGNU / Linux systém.
		-- BugTraq

%
"To je element_data štruktúra prvkov, ktorých * Prvok ELEMENT_TYPE =FORM_TYPE_SELECT_ONE, FORM_TYPE_SELECT_MULT. * / / * * Hniezdenie hlbšiea hlbšie, ťažšie a ťažšie, choď, choď, oh, OH, ohhhhh !! * Je nám ľúto, dostalvykonané tam preč. * / Struct lo_FormElementOptionData_struct. "
		-- Mozilla source code

%
Zatiaľ čo rok 2000 (Y2K) problém nie je problém pre nás všetkých Linuximplementácia bude ovplyvnený roka 2038 (y2.038k) vydanie.Debian sa zaviazala k spolupráci s priemyslom o tejto otázkea budeme mať našu plnú plány a stratégie vykázala v prvom štvrťrokuz roku 2020.
		-- Mozilla source code

%
... Kde bol Stac Electronics, kedy Microsoft vymyslel DoubleSpace? kdeboli Xerox a Apple pri Microsoft vynašiel GUI? Kde je AppleQuickTime, keď Microsoft vynašiel Video for Windows? Kde bol SpyglassInc. Mosaic kedy Microsoft vynašiel Internet Explorer? Kde je SunPri Microsoft vymyslel Java?
		-- Mozilla source code

%
Ospravedlňujem sa, či zvuky sa vkladá nový bojovný a príliš osobné,ale to je môj štýl generála. - Ian Jackson
		-- Mozilla source code

%
"Môj najväčší problém s RH (a najmä RH contrib balíky) je to, žeNemajú nič podobné našej politiky. To je jeden z hlavných dôvodov,prečo sa ich obaly sú tak mizerný a rozbité. Debian má tímovú prácuBočné budovanie distribúcie až do výtvarného umenia. "
		-- Mozilla source code

%
"Slackware užívatelia nevadí. Podľa mojich skúseností, Slackware používatelia súbuď nevie nováčikovia, ktorí budú mať problémy ani s dechtom, alebo súnahnevaná do-it-kutilovia, ktorí by sa inštalujú niekoho iného pre-zostavujúbinárne aj keď na to bolo zaplatené. "
		-- Mozilla source code

%
<XinkeT> "Pane, daj mi pokoj prijímať veci, ktoré nemôžem         zmeniť, odvahu zmeniť to, čo môžem, a múdrosť         skryť telá ľudí, musel som sa zabiť, pretože         nahnevalo ma."
		-- Mozilla source code

%
* Tmavý zmenil tému na #debian na: neskoro v noci: Potom,  mesiace starostlivého chladenie, Debian 2.0 je konečne v pohode stačí  uvoľňovanie.
		-- Mozilla source code

%
Sadla som smial posmešne do môjho notebooku, kým mi ukázal PC s operačným systémomLinux. A oh! Bolo to, ako by sa otvorila nebesá a Boh vyniesolna strane klienta OS tak krásne, tak elegantné a tak elegantné, že miliónvývojári spoločnosti Microsoft nemohol vymyslieť to, aj keby mali storokov a tisíc debny Jolt Cola.
		-- LAN Times

%
Sadla som smial posmešne do môjho notebooku, kým mi ukázal PC s operačným systémomLinux .... A vedeli to PC dusiť? Páčilo sa to koktať? To urobil, ani raz,hovoria, že tento program vykonal neplatnú operáciu a musia byť vypnutýdole? Nie. A to je len na klientovi.
		-- LAN Times

%
"Myslím, že väčšina Vývojári sú skôr" silnú vôľu "ľudís veľkou mierou pochopenie a vysokej úrovne vášňou pre to, čovnímajú ako dôležité v rozvoji debian systému. "
		-- Bill Leach

%
"Vlastne jediná distribúcia Linuxu som kedy použil, aby prešielrootshell skúška po vybalení z krabice (hit rootshell v čase, keď je distprepustený a uvidíme, či si môže zlomiť OS pomocou skriptov odtiaľ) jeDebian. "
		-- seen on the Linux security-audit mailing list

%
* CULus obáva perl - jazyk s voliteľnými chybami
		-- seen on the Linux security-audit mailing list

%
<Stu> by ste mali báť používať KDE, pretože RMS by mohlo prísť k obľúbeným      Dom a štiepi svoj monitor s sekerou alebo tak niečo :)
		-- seen on the Linux security-audit mailing list

%
"A ja naozaj rád Debian 2.0, že veľa aj kompletne prerobildefault config z linuxových systémov naša spoločnosť predáva a znova nainštalovať niektorýz linuxových systémov v kancelárii aj tu doma .. "
		-- seen on the Linux security-audit mailing list

%
<Davide>, ako zápas za politika policajná politiky s politikou pre zmenu         politika polícia policajná
		-- seen on the Linux security-audit mailing list

%
<Tma> "Poďme tvorí Linux Standard Linux Štandardizácia Association        Board. Účelom tejto dosky bude štandardizovať Linux        Normalizačných orgánov. "
		-- seen on the Linux security-audit mailing list

%
<Overfiend> Nechoď plač mi o vašich "30 minútových kompiláciami" !! ja            musieť stavať X do kopca v oboch smeroch! V snehu! s holé            nôh! A nemali sme kompilátory! Museli sme preložiť            C kód pre mnemotechnická pomôcky sami seba!<Overfiend> A ja som bol 18, ešte než sme mali montérov!
		-- seen on the Linux security-audit mailing list

%
NEW YORK (CNN) - Používatelia internetu, ktorí trávia aj niekoľko hodín týždenne on-linedoma zažiť vyššej úrovne depresie a osamelosti, než kebyoni použili počítačovú sieť menej často, The New York Timeshlásené v nedeľu. Výsledkom ... prekvapil obaja výskumníkmi asponzori, ktorý zahŕňal Intel Corp., Hewlett Packard, AT & T a výskumApple Computer.
		-- seen on the Linux security-audit mailing list

%
"Čo je pozoruhodné, však, je celkové usporiadanie a integráciuSystém. Debian je skutočne elegantný linuxová distribúcia; venovali veľkú starostlivosťBola prijatá v príprave balíkov a ich umiestnenie v rámciSystém. Samotné množstvo balíčky sú k dispozícii je tiež pôsobivý .... "
		-- seen on the Linux security-audit mailing list

%
Debian Linux je pevný, komplexný produkt, a skutočné potešeniepoužitia. Je to tiež skvelé zapojiť sa do systému Debian kolektívu,ktorého prívetivosť a duch pripomína prvých dní na internete ajeho zmysel pre otvorenosť a globálnej spolupráce.
		-- seen on the Linux security-audit mailing list

%
<Flood> môžem napísať unix-ako jadro v Perlu?
		-- seen on the Linux security-audit mailing list

%
<Flood> netgod: Mám tiež "Evil inside" tričko (w / Intel logo) .. na        back to hovorí: "Až príde vytržení, budete mať korene?"
		-- seen on the Linux security-audit mailing list

%
<Zarkov> "NT 5.0. Všetky chyby a desaťkrát väčšie kód!"
		-- seen on the Linux security-audit mailing list

%
<CULus> je 150 meg v adresári / tmp dir! DRAHÝ LORD
		-- seen on the Linux security-audit mailing list

%
<Toor> netgod: Čo máte vo svojom jadre ??? Zostavený zdroj pre       riadiť raketoplán ???<Spoo> čas, aby sa zips riadiť svoj disketovú mechaniku potom. -Li jadro       Nemá fit na to, že jadro je AI
		-- seen on the Linux security-audit mailing list

%
Teraz môžem konečne vysvetliť všetkým, prečo som to urobiť. Práve som dostal $ 7 v hodnotevoľného veci pre prácu na Debiane!
		-- seen on the Linux security-audit mailing list

%
<Ultima> netgod: Môj kalkulačka má viac registrov, ako x86, a
		-- thats- sad

%
* Boren hodí MATLAB cez celú miestnosť a dúfa, že sa rozbije na celej rade  blizi nekonečné peices
		-- thats- sad

%
"... Bolo to oveľa rýchlejšie, než som si myslel, že to bude oveľa rýchlejšínež NT. Ak sú ďalej zvyšuje rýchlosť vykonáva na server do finálevydanie, Oracle bude schopný vymazať svoj zadok s SQL Server aodovzdať ho späť na M $, zatiaľ čo správcovia Oracle ... preniesť svoje databázyviac než na Linux! "
		-- thats- sad

%
World Domination, samozrejme. A sporo odetá ženy. Koho zaujíma, čijeho dvadsať nižšie? - Linus Torvalds
		-- thats- sad

%
<Flav> Win 98 Psychic vydanie: My vám poviem zajtra, kam idete
		-- thats- sad

%
<ZPX> je to úžasné, ako "ne-zlomený" Debian je v porovnaní so stagnáciou a rh
		-- thats- sad

%
<Tma> "Hej, ja som od tohto projektu s názvom Debian ... počul si o tom?       Vaše meno sa zdá byť na veľa naše veci. "
		-- thats- sad

%
"V prípade vnímaný zlyhania na vedenie projektu #debian jeoprávnený prijať drastické a descisive kroky na odstránenie ak tak neurobí,vrátane bez obmedzenia na vyhnanie úradníkov, apointing nových úradníkova všeobecne zneužívanie moci "
		-- proposed amendment to Debian Constitution

%
<Overfiend> budeme volať 2.2 _POTATO_ ??
		-- proposed amendment to Debian Constitution

%
<SirDibos> nemá Johnie Ingram poflakovať tu na IRC?
		-- proposed amendment to Debian Constitution

%
* Twilight1 bude musieť zavesiť Mozilly čiapočku dinosaura v obraze, pokiaľ  Netscape predáva-out na veľa stratených ..
		-- proposed amendment to Debian Constitution

%
<Lux> -Li MacOS je pre počítačový analfabet, potom Windoze je pre      počítačové masochisti
		-- proposed amendment to Debian Constitution

%
<Dark> cULus: Budovanie päť metrov vysokú repliku Empire State       Budovanie s sponky je impozantný. Robiť to zaviazanými očami je       eleet.
		-- proposed amendment to Debian Constitution

%
Môžem len vidieť ho teraz: nominačnej proti terorizmu ;-)        - Manojhaha! aj nominovať Manoj.
		-- seeS

%
<JHM> Nejako som mať viac rešpektu pre 14 rokov staré vývojárov Debianu, než     14 rokov starý Certified Microsoft Nevoľníci.
		-- seeS

%
<CULus> Ben: Máte solumly prisahať, že vám prečítať debian-mail raz denne a        neumožňujú ľuďom, že ste MIA?<Ben> cULus: i to prisahám
		-- seeS

%
"Zaujímalo by ma, či sa jedná o prvý ústava v histórii ľudstvakde musíte počítať druhú odmocninu zistiť, či pohybomprejde. :-) "
		-- Seen on Slashdot

%
To je riešením Debianu problému .. a od tej doby jedinou reálnou cestouvytvárať viac príbuzné vývojárov je mať deti, potrebujeme viacsex! Je to dlhodobá investícia ... je to samo o sebe dielo, ktoré jeuspokojujúci!
		-- Craig Brozefsky

%
<Marcus> Dunham: Vieš, ako reálne čísla sú vyrobené z racionálnej         Čísla podľa tried rovnocennosti konvergentných postupností?<Dunham> Marcus: áno.
		-- Craig Brozefsky

%
<CULus> "Haló?" "Hi baybee" "Vy ste Johnie Ingram?" "Pre teba budem        niekto "" Ermm .. Predávate Drez diskov CD? "" Milujem slinkies "
		-- Craig Brozefsky

%
<Overfiend> xhost + localhost by malo byť vykonané len osoby, ktoré by            maľovať svoje hostiteľa a heslo používateľa root na diaľnici            nadjazd.
		-- Craig Brozefsky

%
<JHM> AIX - Unix z vesmíru, kde Spock má fúzy.
		-- Craig Brozefsky

%
<Knghtbrd> Štúdie dokazujú, že výskum spôsobuje rakovinu u 43% laboratória           krysy<CQ> knghtbrd- jo, ale 78% týchto štatistík sú posunuté o 52% ...
		-- Craig Brozefsky

%
<> STU: apt! Chyby<Apt>! Chyby sú hlúpi<Dpkg> apt: sú hlúpi? čo je to?<Apt> dpkg: neviem<Dpkg> apt: Krása je v očiach držiteľa piva ...<Apt> Už som mal to tak, dpkg.
		-- Craig Brozefsky

%
<Muklovia> Snažím sa presvedčiť niektoré Netcom, správcovi viem, že ku konverzii          pre Debian od RH, netgod, ale sakramentsky tvrdohlavý<Muklovia> prečo používatelia RH tak sakramentsky ťažké namierené?<Espy> je to klobúk
		-- Craig Brozefsky

%
<Doogie> Debian - Všetky sila, bez toho aby bolo hlúpe klobúka.
		-- Craig Brozefsky

%
Koľko mesiacov budeme mať za sebou [Redhat] s glibcuvoľniť? "
		-- Jim Pick, 8 months before Debian 2.0 is finally released

%
Účelom s e-mailovej konferencie, skôr než majú diskusné skupiny jeumiestnite prekážku vstupu, ktorá chráni zoznamy a ich používateľomInvázia všeobecnými nevzdelaných hordy.
		-- Ian Jackson

%
Väčšina z nás cíti, že marketing typy sú ako nebezpečné zbrane - držať'Em odľahčí a zamkol do skrine, a len priniesť ich von, keďbudete potrebovať robiť prácu.
		-- Craig Sanders

%
<BENČ> cerb: my vám pripojila k debian-bojovať ako moderátora<BENČ> cerb: Zoznam pravidlá sú 1) Nie pekné e-maily, 2) žiadne ospravedlnenia
		-- Craig Sanders

%
<Teknix> naše miestne telekomunikačné pripustil, že niekto "zahnaní do         Tlačidlo na prepínači "a vzal celú sieť bankomatov dole<Netgod> dúfajme, že teraz smerovače sú navrhnuté tak lepšie, takže "sieť         off "spínacie hodiny, je na zadnej strane
		-- Craig Sanders

%
<Overfiend> Thunder-: keď sa dostanete {} MessagesLikeThisFromYourHardDrive<Overfiend> Thunder-: it buď prostriedky {} TheDriverIsScrewy<Overfiend> alebo<Overfiend> {YourDriveIsFlakingOut BackUpYourDataBeforeIt'sTooLate            PrayToGod}
		-- Craig Sanders

%
<Apt> bolo povedané, že RedHat je vec, ktorú Marc Ewing nosí na      jeho hlava.
		-- Craig Sanders

%
<MrCurious> mocou greyskull<MrCurious> mi niekto povedať zákaz umiestniť<Sopwith> mrcurious: * .debian.org, * .novare.net<PhilX> * .debian.org. to je úžasné.
		-- Seen on LinuxNet #linux

%
"Čo mi to povedať? Že ak Microsoft bola posledná softvérSpoločnosť odišiel na svete, 13% americkej populácie bude drhnutiegaráže predaj a dobrej vôle pre staré TRS-80s, strojov CPM & Apple] [ 'S predoni budú kupovať Microsoft. To nie je práve vyzváňacie potvrdenie. "
		-- Seen on Slashdot

%
"Bruce McKinney, autor of Hardcore jazyka, oznámila, žeon je dosť VB a nebudú písať 3. vydanie jeho knihy.Najlepšie citácie je u konca: "Nepotrebujem jazyk navrhnutý zameranímskupina '. "
		-- Seen on Slashdot

%
<Cylord> Bolo by prijateľné pre Debian Policy keby sme vložili crontabu         V predvolenom nastavení do zemiakov, ktoré odoslať e-mailom bill.gates@microsoft.com         Každé ráno sa e-mailu, ktorý čítal, "Nebojte sa, Linux je         výstrelok ... "
		-- Seen on Slashdot

%
* Overfiend premýšľa robí nemu o asclock, v ktorom on jednoducho mení  rozšírený popis "Ak je vám ohnúť a dať si hlavu medzi  nohy, si môžete prečítať voľno vašej assclock. "<Doogie> Overfiend: ísť do postele.
		-- Seen on Slashdot

%
<Reed> Je dôležité si uvedomiť, že hlavným dôvodom, prečo Rímska ríša       Zlyhanie je, že nemajú predstavu o nula ... teda nemohli       otestovať úspech alebo neúspech svojich programov v jazyku C.
		-- Seen on Slashdot

%
Vzhľadom k tomu, keď má za účel debian bolo upokojiť jej záujmyhmotnosť nekvalifikovaných spotrebiteľa? - Steve Kratšie
		-- Seen on Slashdot

%
<Joeyho> netgod: er, sú tieto balíky 2.2.0 2.0.0pre9 alebo máš        Priame spojenie s bohmi?<Netgod> Joeyho: ja mať priamu linku
		-- Seen on Slashdot

%
<_Anarchy_> Argh .. kto rozdávať papierové vrecká 8)
		-- Seen on Slashdot

%
<Trápne> niekto okolo?<Flav> no, my sme všetky nepravidelných polygónov
		-- Seen on Slashdot

%
<CULus> Panebože nie je náhodné Citát generátor<Netgod> iste didnt myslím, že bola statická? Ako lame by to bolo? :-)
		-- Seen on Slashdot

%
Samotná neexistencia je chabá výhovorka pre vyhlásenie vecí unseeable. vy* * Môžu vidieť drakmi. Stačí sa pozrieť do správnym smerom.
		-- John Hasler

%
<Kriedovo> gcc je najlepšia kompresor vôbec portovaný na Linux. to môže obrátiť         12 MB zdroje jadra (a to je .debbed) do 500k jadra
		-- John Hasler

%
<Manoj> Aj * * ako kurča
		-- John Hasler

%
 [] DOGBERT [2] Richard Stallman [3] Buffy Summersová [1] Manoj Srivastava [4] Žiadna z uvedených
		-- Debian Project Leader 1999 ballot

%
<Oryn> niekto vedieť, či existuje verzia dpkg pre RedHat?
		-- Debian Project Leader 1999 ballot

%
Acme-delo (3,1415) nestabilná; naliehavosť = nízka  * Pridaná bezpečnosti, aby sa zabránilo rozkúskovaný operátora, uzatvára: bug # 98765,    bug # 98713, # 98714.  * Pridané manuálových stránok. uzatvára: # 98725.
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
! Netgod: *! Čas letí, keď ste používaní Linuxu! Doogie: *! jo, nekonečnej slučky v 5 sekúnd.! Teknix: *! má niekto znova testované, aby sa 2.2.x?! Netgod: *! jo, 4 sekundy teraz
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
* Tmavo pozdravia LIW s malým žltým žaba.* LIW pobozká žaba a sleduje ju transformovať do krásnej hlupáka  babu, vezme ju na zmrzlinu, a žije šťastne navždy  s ňou<Dark> LIW: Umm je to príliš neskoro na to mať žaba späť?
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
* CULus si myslí, že by sme mali ísť na veľtrhoch a zistiť, koľko ľudí, ktoré sme  môže zabiť tým, že hodí CD s Debianom na ne
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Tma> "Áno, vaša ctihodnosť, mám RSA šifrovací kód tattood na mojom        penis. Mám ti ukázať porote? "
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<> Knghtbrd vy ľudia sú duševne chorý.<Joey> rytier: istý, že je dôvod, prečo pracujeme na Debian.<JHM> Knghtbrd: dostať do kontaktu so svojím vnútorným cvok.
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<CULus> Saens dokazuje, nie menej ako 3 TCP / IP chyby v 2.2.3
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Mercury> alexsh: Buď / veľmi / cairful, mohli by ste, ak váš smolu, smažiť vaše          dosky ..<Knghtbrd> Mercury - Znie to ako legrace
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<RCW> tmavý: kaldera?<Knghtbrd> RCW - to nie je distribúcia, to je prekliatie<RCW> Knghtbrd: je to prekliaty distribúcia
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
Softvér je ako sex, to je lepšie, keď je to zadarmo. - Linus Torvalds
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Dark> Knghtbrd: Máme veľa whatevers.<Knghtbrd> tmavá - V distribúcii Debian? Hell yeah my!
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
Urobil som to len preto, aby ťa naštval. :-P
		-- Branden Robinson in a message to debian-devel

%
Požadovaný softvér Win95 alebo lepšie, takže som nainštaloval Linux.
		-- Branden Robinson in a message to debian-devel

%
10) nie je 10, ale znelo to ako pekná čísla :)
		-- Wichert Akkerman

%
Eric Raymond: chcem žiť vo svete, kde sa softvér nie je sať.Richard Stallman: Akýkoľvek softvér, ktorý nie je zadarmo nič.Linus Torvalds: Mám záujem o pivo zadarmo.Richard Stallman: To je v poriadku, tak dlho, kým nemám piť. ja                   nemajú radi pivo.
		-- LinuxWorld Expo panel, 4 March 1999

%
Nie som človek vyrovnaný ... - Bruce Perens
		-- LinuxWorld Expo panel, 4 March 1999

%
Osobne nemám často hovorí o sociálnej dobro, pretože keď počujem ostatníľudia hovoria o sociálnej dobro, to je, keď som sa dostať na môj revolver.
		-- Eric Raymond

%
Ak chceme niečo pekné, aby sa narodil v deviatich mesiacov, potom sex musídiať. Chceme mať ten druh sexu, ktorá je prijateľná a zábavné pre obaľudia, nie ten druh, kde je niekto stále priskrutkovaný. Poďme si niektoré krížhnojenie, ale nie niekto dostať skrutkované.
		-- Larry Wall

%
Všetci vieme, že Linux je veľkou prednosťou je ... to robí nekonečnej slučky na 5 sekúnd.
		-- Linus Torvalds

%
ÁNO! ÁNO! ÁNO! Ó áno! (Ooops, to znie ako Meg Ryan ;-)
		-- Ian Nandhra

%
<Knghtbrd> Ak začnem písať eseje o slobodnom software pre Slashdot,           prosím, zastreľ ma.
		-- Ian Nandhra

%
<RoboHak> hmm, obedy To znie ako dobrý nápad<Knghtbrd> bude chutiť ako dobrý nápad príliš
		-- Ian Nandhra

%
PS: - Chystám * tento * V jeho blízkosti je pobehovať v serverovej miestnosti sDvojica závitorezov a veľké drevené palice, smeje sa ako šialenec arezanie všetko, čo môžem sedieť kliešte okolo. a nárez, žektoré nemôžem. Takže keď som sa zdajú semi-nekoherentné, alebo len naozaj * naozaj * škaredév čase, prosím odpusť mi. stres nie je pekná vec. }; P
		-- Phillip R. Jaenke

%
Každá firma si sťažujú obchodné praktiky Microsoftu je jednoduchoruzovy krik. Vyzerajú krásne a príjemne vonia. Akonáhle šťastie spoločnosť dethronesMicrosoft budú zhodili ich okvetné lístky vystaviť tŕne pod ním.tŕň pod iným menom by bolieť toľko.
		-- Phillip R. Jaenke

%
Niečo sa musí urobiťTo je niečo,Z tohto dôvodu, to musí byť vykonané
		-- The Thatcherite Syllogism

%
<Knghtbrd> xtifr - pozor na Jamesa, keď je z jeho lieky =>
		-- The Thatcherite Syllogism

%
Ľahostajnosť bude iste pád ľudstva, ale koho to zaujíma?
		-- The Thatcherite Syllogism

%
Nikdy nepodceňujte silu ľudskej hlúposti.
		-- Robert A. Heinlein

%
Zlato, n.:  Mäkký poddajný kov pomerne vzácny v distribúcii. To je ťažený  hlboko v krajine zo strany chudobných ľudí, ktorí potom ho dať do bohatých mužov, ktorí okamžite  pochovať ho späť do krajiny vo veľkých väzniciach, hoci zlato neurobila  niečo k nim.
		-- Mike Harding, "The Armchair Anarchist's Almanac"

%
* Lilo prehlasuje OPN virtuálne osina v zadku, :)
		-- Mike Harding, "The Armchair Anarchist's Almanac"

%
"Oni sú oba podniky - ak ste im dal dosť peňazí, ja somistí, že urobia čokoľvek sakra pýtate: -> "
		-- David Welton

%
"Máte právo nebyť kretén. Dáte Ak sa toto právovšetko, čo hovoria a robia tu sa bude konať proti vám. Ak nemôžetedovoliť prestať byť kretén potom niekto bude vymenovaný na kickvy odtiaľto. "
		-- Your rights as an irc addict

%
* Simunye je tak šťastná, že má svoje matky gén je<Dellaran> radšej dať späť, než sa im cnie!
		-- Your rights as an irc addict

%
<Iambe> veliteľskú najviac intellegent ľudí na tejto planéte nie je ľahké
		-- Your rights as an irc addict

%
California, n.:    Z latinského "kal", čo znamená "teplo" (ako v angličtine "kalórie", aleboŠpanielsky "caliente"); a "skou '" pre "sexuálny styk" alebo"Smilstvo." Z toho dôvodu: Tierra de Kalifornia, "krajina horúci sex."
		-- Ed Moran

%
* Caytln capne Lisa<Caytln> Catfight: P<LisaHere> Pozor dievča, to sa mi páči.<LisaHere> :)<> Caytln čísla: D
		-- Ed Moran

%
<MFGolfBal> rit / ara: Je tu niečo naozaj dementné o UNIX            bielizeň ...
		-- Ed Moran

%
Systém X Window:  Štandardné UNIX grafické prostredie. S Linuxom, je to zvyčajne  XFree86 (http://www.xfree86.org). Môžete volať to X, XFree, X  Window System, XF86, alebo celý rad ďalších vecí. Nazvime to "XWindows" a  niekto vás třísknout a budete mať to zaslúžil.
		-- Ed Moran

%
<Knghtbrd> "Menové kolektory sú v režime offline." "Som presmerovanie hoci           sekundárne spojky. Ak budeme re-zarovnať sme fázy rozdeľovača           by mal byť schopný používať plazmové indukčné maticu ručne           začať novú ošuntělé spinoff série. "* ShadwDrgn vzdychy<Phase> necháte svoje kolektory sám<Phase>!
		-- Ed Moran

%
* Türken si myslí, že malé deti sú úplne rozkošný ... especialyy keď  sú to niekto elses.
		-- Ed Moran

%
* Overfiend vzdychy<Overfiend> Netscape naštve.<Overfiend> Jedná sa o dom z kariet odpočinku na lôžku z tekutých pieskov.<Espy> počas zemetrasenia<Overfiend> v tornádo
		-- Ed Moran

%
<SilverStr> etiku médií je protirečenie, podobne ako Jumbo krevety a            Microsoft Works.<MonkAway> nehovoriac NT zabezpečenia
		-- Ed Moran

%
<Silvrbear> oxymorons? Videl som, ako jeden včera - brožúru o "Taco Bell            Nutričné ​​informácie "
		-- Ed Moran

%
* Knghtbrd vypustí paru dvojitých barreled snurf delá a kryty  ježiš s snurf šípkami<Ježiš> Meany: P
		-- Ed Moran

%
<Jgoerzen> Doogie: zniete vysoko nestabilné :-)<Knghtbrd> jgoerzen - to je.* Doogie BOPS Knghtbrd<Knghtbrd> vidieť? Sa uchyľovať k násiliu = D
		-- Ed Moran

%
Tiež som bol veľký fanúšik Unix od chvíle, kedy som si uvedomil, že SCO neboloUnix. - Dennis Baker
		-- Ed Moran

%
<Dracus> Ctrl + Alt + Command + P + R<Knghtbrd> dracus - YE GODS! To je horšie ako Emacsu!<LauraDax> hehehehe<Dracus> nepýtajte sa, čo to robí: P
		-- Ed Moran

%
<Iambe> nie ste cvok<Knghtbrd> Zrejme ešte neviem ma dosť dobre. =>
		-- Ed Moran

%
* Hľa myslí Kb ^ Zzz mali vybrať rôzne veci snívať než   Všeobecne rozlíšenie a zmeny politiky.<Kb ^ Zzz> ai - povedz mi o tom, je to zlé znamenie
		-- Ed Moran

%
<Crow_> hmm, je tu možnosť --now-sakra za Exim?
		-- Ed Moran

%
<DarthVadr> Kira: pripojiť sa k temnej strane mláďaťom.<Kira> Darth, že ja som temnú stranu.
		-- Ed Moran

%
<Netgod> Fëanora: u nemajú ani poňatia o hĺbke Hlúposť amerického práva
		-- Ed Moran

%
Každý, kto vyniká uprostred cesty vyzerá ako roadkill ku mne.
		-- Linus Torvalds

%
<Lilo> "Prosím REŠPEKTUJTE práv duševného vlastníctva!"<Lilo> "Doložte intelekt." ;)
		-- Linus Torvalds

%
<Knghtbrd> Fëanora - problematika licenčných sú dôležité. Ak nebudeme pozerať na naše           somáre teraz niekto chcel prísť a uhryznúť nás neskôr ...
		-- Linus Torvalds

%
"Teraz budeme musieť zabiť."
		-- Linus Torvalds

%
* Knghtbrd môže už predstaviť: "Vec: [úmyslom pripraviť sa na navrhnúť   Podávanie hlásenie o chybe] Typos v politickom dokumente "
		-- Linus Torvalds

%
<Netgod> heh to je stratená vec, rovnako ako správnej výslovnosti všetkých         "Šperky"<Netgod> vzdaj to :-)<Šalvia> a správne hláskovanie "farba" :)<BENČ> heh<Šalvia> a hliníka<> BENČ alebo jadrových zbraní<Šalvia> sa mi zvyšuje kom- Yankee?<Šalvia> práve pretože sme nemajú bombu ...<BENČ> späť off ya žlté brucho
		-- Linus Torvalds

%
<LauraDax>! Videl boha<Tabi-> LauraDax, nepamätám si videl "boh"
		-- Linus Torvalds

%
<Kira> je chirurgická vojna, kam ísť dať cudzích vojsk nos pracovných miest?
		-- Linus Torvalds

%
<Xtifr> Athena Desktop Environment! Vo svojich srdciach, vy viete * *, že je to        správna voľba! :)* Knghtbrd THWAPS xtifr
		-- Linus Torvalds

%
<Knghtbrd> shaleh - nečistý je jednoducho divný.<Espy> heh, nečistý je v pohode<Knghtbrd> Espy - a divne.<Espy> áno, zvláštnu moc
		-- Linus Torvalds

%
<Xtifr> priame implantáty mozgu :)<Knghtbrd> xtifr - Jo, potom pomocou počítača by v skutočnosti vyžadujú niektoré           z týchto idiotov myslieť!<Knghtbrd>;>
		-- Linus Torvalds

%
<Knghtbrd> Overfiend - BTW, potom, čo sme objavili X vezme všetky 1,4 koncertov           stavať, ste ochotní pripustiť, že X je bloatware? =><Overfiend> KB: existuje medzera 16 1/2 minúty vo svojej odpovedi<ACF> knghtbrd: existujú dôkazy, že X je len * 2. * najhoršie oknami      systém;)
		-- Linus Torvalds

%
<LIW> sakra, autonómna pohyb myši začína spravidla po Používam      tlačidlo myši<Wichert> nepoužívajú potom na tlačidlo myši :)<LIW> jo, že jo :)
		-- Linus Torvalds

%
<Knghtbrd> viete, Linux potrebuje plošinovka hrať Tux<Knghtbrd> trochu Super Marioish, ale s Tux a veci ako malá cyber           chyby a Borgs a tak podobne ...<Knghtbrd> A budete musieť skočiť okolo billgatus a stlačte klávesu, aby ho klesnúť           do lávy a potom vidíte nejaký chlap, ktorý vyzerá ako RMS           alebo niekto povedať: "Ďakujem za záchranu mi Tux, ale Linus           Torvalds je v inom zámku! "
		-- Linus Torvalds

%
<Thoth_> Jo, to je dôvod, prečo to číslované 2.3.1 ... je to pre tých z nás,         ktorí si ujsť NT podobné doby používania
		-- Linus Torvalds

%
<Shinobi> Sú horšie veci než Perl .... ASP príde na myseľ
		-- Linus Torvalds

%
* M2 zíza na monitor ... to vyzerá ako hamburger ...<Knghtbrd> m2 - to je zlé znamenie
		-- Linus Torvalds

%
<Knghtbrd> Nechajte to na Manoj volať procmail "drobnosť"
		-- Linus Torvalds

%
<Crow-> Manoj: No, nemôžem pochopiť veci, ako je "s / 3 # $% ^% {]] [@ f245}"<Manoj> Crow: To nie je úplne legálne ;-)<Knghtbrd> Manoj - ako by sa dalo robiť "s / 3 # $% ^% {]] [@ f245}" legálne           vlastne je? (A čo by to bolo? Hehe)<Manoj> Knghtbrd: Je potrebné dokončiť S /// výraz.<Knghtbrd> ach, to je všetko?
		-- Linus Torvalds

%
<Kira> Ada, jediný jazyk písaný na MILSPEC.<Mikster> <chvenie>
		-- Linus Torvalds

%
<BENČ> -include ../../debian/el33t.h<BENČ> sendmail build ... podivný názov hlavičky :)<Isildur> hahaha* Netgod laffs<Netgod> Bence: môže u povedať, že používa na udržanie sendmail? : P<BENČ> heh :)
		-- Linus Torvalds

%
<Phase> no ... Ja nesmiem mať žiadne ďalšie kávu !!! ;)<Simunye> istý yu robiť fázy :)<Phase> čo naozaj chcete, aby som sa odráža od stropu?<Simunye> Yeshi :)<Kira_> odráža od stropu je gewd<Phase> ok, to bola hlúpa otázka<Kira_> to splatting na podlahe, to je ten problém.
		-- Linus Torvalds

%
<Kensey> RMS pre prezidenta ???<RelDrgn> ... alebo ESR, chce novú prácu;)
		-- Linus Torvalds

%
Ale nie, nie znovu.
		-- Manoj Srivastava

%
<Knghtbrd> Je pravda, že RMS je fanatik, to nepopieram to. Budem dokonca povedať,           je to kráľovská osina v zadku väčšinu času. ale je           Stále častejšie ako nie hneď, a zaslúži určitú mieru           úver a rešpekt k jeho práci. Neboli by sme tu dnes           bez neho.
		-- Manoj Srivastava

%
<Espy> zajtra tam bude veľká porucha pracovnej sily
		-- May 18, 1999

%
Som dyslektik Borg. Pripravte sa majú prdel laminované.
		-- May 18, 1999

%
<NeonKttn> Mal som kamaráta držať ma v šatni počas stredoškolského beacuse I           Neverili by ste, že jej priateľ vedel o predohru ...<NeonKttn> Mal som priniesol popcorn. :)
		-- May 18, 1999

%
<Knghtbrd> mapách je pre wussies<Topher> počítačové programové výpisy .... ďalšie, na Hardcopy
		-- May 18, 1999

%
<Kceee ^> Neznášam užívateľa<Knghtbrd> hovoríš ako správca systému už!
		-- May 18, 1999

%
<Change_m2> Will LINUX niekedy predbehnúť nakrájaný chlieb ako dosiahnutie # 1            ľudstva?
		-- May 18, 1999

%
<APH> manoj sa deje orechy o stanovení chyba ťahanie! woo woo!<Knghtbrd> manoj išiel orechy dávno. ale fixačné chyba je v pohode =>
		-- May 18, 1999

%
<RCW> tá zdanlivo-baktériám podobným viacfarebný červy vychádzajúce z      Microsoftu BackOrifice<RCW> to je backoffice logo
		-- May 18, 1999

%
* Simunye je dostupná podľa oc3-> OC12<Daem0n> Simma: skus ma. :)<Simunye> Démon: jo :)
		-- May 18, 1999

%
<Overfiend> lialo: No tak dobre, ste pravdepodobne zodpovedný mysliteľ.            Vitajte vo veľmi malom klube.<Lilo> Overfiend: vitajte mi, keď sa pripojíte :)
		-- May 18, 1999

%
V podstate chcem, aby ľudia vedeli, že keď sa používajú iba binárne moduly,je to ich problém. Chcem, aby ľudia vedeli, že v ich kostiach, a jachcem to vykríkol zo strechy. Chcem, aby ľudia prebudí vstudený pot každý raz za čas, ak používajú iba binárne moduly.
		-- Linus Torvalds

%
* Wichert_ predstaví pána bez MTA<James> Wichert: ehm? ktoré by mohli brániť Peformance z BTS: p
		-- Linus Torvalds

%
<Gekon> Hmm ... Zaujímalo by ma, čo iného oddeľuje Debian od zvyšku z        linuxové distribúcie.<Knghtbrd> gecko - Nemáme Suck<Gekon> Knghtbrd: nechcete povedať, že keď osloví veľa ľudí        Z týchto distribúciách<Knghtbrd> gecko - bod.
		-- Linus Torvalds

%
Vzhľadom na vývoj modelu uzavretý source XFree je nemožnépodporovať, alebo dokonca špekulovať o tom, funkcie v pre- alebo beta verziíof XFree.
		-- Marcus Sundberg

%
>> Nemám naozaj považovať Biblie KJV-text ako technický dokument,>> Ale ... :)> Je to príručka - bývanie.Ale to nebola aktualizovaná po dlhej dobe, mnoho by sa povedať, že je tosmutne zastaraný a upstream udržiavateľa nereaguje na jehoe-mail. :-)        - Branden Robinson, Oliver Elphick a Chris Waters v           Správa sa debian-policy
		-- Marcus Sundberg

%
<Knghtbrd> Neviem si predstaviť veľa ľudí, ktorí potrebujú user = ID10T niekam!
		-- Marcus Sundberg

%
<Slashdot> môj US geograpy je mizerný ... lol<Knghtbrd>, takže je moja a ja tu bývam
		-- Marcus Sundberg

%
Moonchild bez stanoviska? Satan je korčuľovanie zajtra do práce!
		-- Brett Manz

%
<Knghtbrd> Ja naozaj nechcem moc vôbec ... Len vľúdne slovo, čo           atraktívna žena, a neobmedzenú šírku pásma !!
		-- Brett Manz

%
<Knghtbrd> Ak budeme mať aj právo (Hádam, že sme) Ja nie som Very Happy.* Vy Minupla rúk podhodnotení roka ocenenie.
		-- Brett Manz

%
Minule som mal intímny styk s inou ľudskou bytosťou bolo skôrbolestivá skúsenosť ... Radšej to páčilo ...;)
		-- Brett Manz

%
<Apple_IIe> Videl niekto moju 80 stĺpec kartu?
		-- Brett Manz

%
<Slackware> uh oh, čo som začal :)<> Debian ROFL ... distro nick vojny.* Slackware len čaká na / nick Gnome, / nick KDE, a potom svetová vojna 4   vypuknúť<WinNT>: oP<OpenBSD> <kačica><PalmOS> :)<Slackware> no'one by sa odvážil / nick RedHat<Tru64> mňaukať.
		-- Brett Manz

%
<Crow-> im fcucking cvok* Knghtbrd dbá o prihlásenie všetko Crow- hovorí, že dnes v noci ...<MrBump> heheh<MrBump> Hovoril, že ma vziať! dočerta!!<Crow-> vole žiadny spôsob,<Knghtbrd> MrBump - že to nie je tak opitý<MrBump> Knghtbrd: Som drvený: o)
		-- Brett Manz

%
<Knghtbrd> aggh!<Knghtbrd> Zastav to!<Knghtbrd> Zastav to !!
		-- Brett Manz

%
<Knghtbrd> RoboHak - v poriadku, náplasť nie je rozbité, ale môj mozog           zrejme je<Wc> to nie je nič nové (;<Knghtbrd> wc - ticho.<Knghtbrd> =>
		-- Brett Manz

%
<> DPG Američania sú divný ....<Xtifr> Kalifornčania ešte divnejšie<Knghtbrd> xtifr má bod ...
		-- Brett Manz

%
* Woot usmieva sa pokojne.<Woot> Nechcem, aby sa zdajú byť príliš dychtivo, ako dostať do knghtbrd rokov       siglist.
		-- Brett Manz

%
<CULus> DHD: R ste súčasťou tajného debian overstructure?<DHD> no. nie je žiadnym tajomstvom, debian overstructure.<Kozmické žiarenie> hoci teraz, keď niekto priniesol to, začnime jeden            :-)<Knghtbrd> kozmické žiarenie - prečo nie, znie to ako zábavný spôsob, ako stráviť           Popoludní = D
		-- Brett Manz

%
<Xtifr> nemusíte byť blázon, aby tú prácu .... ach čakať, áno, vy!        :)
		-- Brett Manz

%
* O-O vždycky debmake, pretože presne vedel, čo to urobí ...<Tamtiež> o-O: by ste ;-)
		-- Brett Manz

%
2.3.1 bola uvoľnená. Ľudí na tento nový hry by si mal uvedomiť, že2.3. * Správy sú pre rozvoj jadra, bez záruky, ženespôsobí systém robiť hrozné veci, ako je poškodený jehodisky, vznietiť, alebo rozbehnú Mindcraft merítka.
		-- Slashdot

%
robiť {    :} While (HELL_FROZEN_OVER!);
		-- Slashdot

%
0 7 * * * echo "... Linux je len výstrelok" | mailová billg@microsoft.com -s = "A pamätajte ..."
		-- Slashdot

%
<Hop> KB: Žiadam integritu a poctivosť u tých, ktorí aj obchodovať s<Hop> Viem, že moje požiadavky sú nezmyselné, ale človek môže snívať, nemôže mu?
		-- Slashdot

%
<Jgoerzen> STU: ach tomto počítači. Nemyslíte si, že niečo s názvom           Stallman si zaslúži byť Alpha? :-)<Stu> jgoerzen: no, vlastne by som Pröll mať väčšiu motiváciu aby sme vymenovali aspoň 386      s 4 MB pamäte a 40 meg pevný disk Stallman.<Stu> s veľkým obsahom tuku prípade, že robí veľa hluku a hrkálky podlahu* Knghtbrd padá na zem drží bokom smeje<Stu> a ..<Stu> double-výška pevný disk
		-- Slashdot

%
Klingonští volanie funkcie nemajú 'parametre - majú "argumenty"
		-- and they ALWAYS WIN THEM.

%
* Knghtktty sa nebude pýtať, ako cuketa sa dostal do diskusie ...
		-- and they ALWAYS WIN THEM.

%
<Knghtbrd> Téma: [GR NÁVRH] Mali by sme hlasovať o triviálnych veciach?
		-- and they ALWAYS WIN THEM.

%
<Woot> Daj * *, ktoré vo vás .sig a dym ho, Knghtbrd.<CULus> Viete, že bude čítať toto:><Woot> hehehehehe.
		-- and they ALWAYS WIN THEM.

%
"Ako ste ceste životom sa chvíľu tu a tam sa získaMyslela pre ostatných kolegov. Mohol by spriada niečo. "
		-- Hagar the Horrible

%
<Knghtbrd> Dobre, ľudia začali hovoriť o BSDM aplikácií           sieťový hardvér ... Myslím, že utiekla a robiť niečo užitočného           a Debianish a nepleť sa do toho jeden ...<Knghtbrd> (pre zmenu)
		-- Hagar the Horrible

%
<Knghtbrd> mariab - nemyslím, že Debian nemal nejaké veľmi hlúpe, a           zjavné chyby pred<Knghtbrd> Samozrejme, máme zvyčajne opraviť naše, než sme sa uvoľniť = D
		-- Hagar the Horrible

%
<Knghtbrd> mariab - Som Debian vývojár. Red Hat je "nepriateľ", alebo           Niečo také myslím .. Napriek tomu sa užívatelia Obsadiť RH ako           idioti alebo ich distribúcie ako úplne zlomený v predvolenom nastavení           je úplná a totálna FUD.
		-- Hagar the Horrible

%
>> Ale IANAL, samozrejme.>> IANAL jeden. Môj syn je, ale keď som sa ho spýtal by som mohol dostať odpoveď, ktorú som> By nechcel počuť."Tu je moje faktúry." ? = D
		-- Hagar the Horrible

%
> Ok, vidím, že viete, čo robíte :-)Buď to, alebo som sa dostal celkom dobre predstierať ju.
		-- Hagar the Horrible

%
<Wichert> 8am je ungoldly hodinu byť hore :)* Gorgo zvyčajne dostane až na 11 hodín
		-- Hagar the Horrible

%
Neexistuje žiadny Cabal.
		-- Hagar the Horrible

%
<_Anarchy_> ACF: Možno 1.apríla budúci rok Slashdot musí bežať "Rob Malda            prijíma novú prácu ako vedúci projektu Debian "8)
		-- Hagar the Horrible

%
* Netgod otvára svoju schránku a ihneď si želá, aby hadnt
		-- Hagar the Horrible

%
<Frogbert> jeho ťažké byť lesbička withoutn prsia ... ľudí dont brať           ste vážne
		-- Hagar the Horrible

%
Možno, že Debian je znepokojený viac o technickej dokonalosti skôr nežjednoduchosť použitia rozbitím softvér. V prvom prípade môžeme vyniknúť. vTen musíme pripustiť poľa Microsoft. Hádajte, kde chcem ísťdnes?
		-- Manoj Srivastava

%
* PerlGeek je naozaj cudzinec priestoru* Knghtktty verí PerlGeek
		-- Manoj Srivastava

%
<Netgod> môj klient bol vo vlastníctve vážne<Netgod> ten chlap dostal koreň, bežal paketov plošticami, inštalované .rhosts abackdoory, dať úplne nový dir v nazýva / lib / "", ktorý máplná sada Smurfing a zabíjanie nástrojov<Netgod> jediná chyba nebola odstránením žurnálov<Netgod> Otázkou je, ako bol koreň hacknut, a to aj couldnt tell u<Netgod> to je, samozrejme, nie debian box* Netgod berie na vedomie debian box je ten jediný vľavo nedotknutý hackerom
		-- wonder why

%
* Joeyho CVS sa dopustia domovský adresár. aaaaaa<Drow> eeeeeeek<Drow> Joeyho: To je jednoducho zlo. Bodka.
		-- wonder why

%
<Kethryvis> Gruuk: UFies sú nad rámec ľudského rodu :)
		-- wonder why

%
Zastavil som pred dlhou dobou, aby sa pokúsili nájsť niečo v zozname chýb z dpkg.Mali by sme bežať na zápis do Guinessovej knihy rekordov.
		-- Stephane Bortzmeyer

%
<Ahzz_> Myslel som 17G Oughta stačiť.
		-- Stephane Bortzmeyer

%
<N3tg0d> je / usr / bin / emacs bol uvedený do súboru / etc / škrupiny ešte? : P
		-- Stephane Bortzmeyer

%
* Joeyho využíva úžasné schopnosti spoločnosti Netscape k zrážke zavrieť        10 okná s jediným stlačením tlačidla<Joeyho> teraz, keď je pokrok!<Knghtbrd> Chyba zbernice =>
		-- Stephane Bortzmeyer

%
<Wordplay> Môžete merať svoje vibrátory v "znakoch za sekundu"? mámZlou správou pre vás, C90, už ste bol masturbuje sihličkové tlačiarne.
		-- Stephane Bortzmeyer

%
Hi! Som vírus .podpis! Kopírovať ma do súboru ~ / .podpis, aby mi pomohol Sprea =d!
		-- Stephane Bortzmeyer

%
* Knghtktty šepká sladké nič do mínu (veci týkajúce sa prekladačov a            grafiky a upgrade RAM a veľké pevné disky ...)<Mínu> oooooooooOOOOOOOOOO<Infinitas> Knghtktty: to je pozitívne pornografický ...* Mínu zhasne do záchvatoch extázy ...
		-- Stephane Bortzmeyer

%
<Sanayaová> vy ste všetko zle! chorý chorý chorý Poviem vám;)
		-- Stephane Bortzmeyer

%
* BMA je trhnúť* Knghtbrd je Knghtbrd* DHD je tiež trhnúť* Espy je zlo* Knghtbrd verí Espy
		-- Stephane Bortzmeyer

%
* BMA divy či to bude robiť Knghtbrd .sig
		-- Stephane Bortzmeyer

%
Ich technických riešení nie sú predmetom hlasovania. Dva právne predpisy v USAstavy takmer rozhodnuté, že hodnota Pi byť 3,14, presne tak. ľudového hlasovanianeznamená, že pre správne riešenie.
		-- Manoj Srivastava

%
<Hľa> <Knghtbrd> zvýšenie napätia na celom svete (o čom svedčí trestný čin<Hľa> a ktovie čo ešte) v priebehu tejto doby sa veľmi podobá Linux<Hľa> rast od roku 1993<Hľa> `` Linux súvisí s celosvetovou epidémiu kriminality !! ''
		-- Manoj Srivastava

%
<Teller> kde som a čo robím v tomto, košík?
		-- Manoj Srivastava

%
Pretože táto databáza nie je používaný za účelom dosiahnutia zisku, a pretože celá práce nie súvydávaná, to spadá pod fair use, ako ju chápeme. Avšak, ak existujehalf-assed idiot rozhodne, aby sa zisk z toho budú musieťje potrebné skontrolovať všetko ...
		-- Notes included with the default fortunes database

%
Neexistuje žiadne tlačidlá Snooze na mačku, ktorá chce raňajkách.
		-- Notes included with the default fortunes database

%
Téma: Bug # 42432: debian-policy: Návrh CTV k návrhu na vykonanie dôkazu oKoncepcia pre návrh na návrhu Návrh CTV pre BTV rozhodnúť onávrh BTV pre CTV na tom, či máme mala mat CTV na/ Usr / doc / usr / share / doc prechodu teraz, alebo neskôr.
		-- Ed Lang

%
<Knghtbrd> Je to trackball pre jednu<Wichert>, takže to nie je hlodavec<Wichert> je to hovno s loptou trčí<Wichert>, ktoré ste maznať neustále
		-- Ed Lang

%
* HomeySan čaká na pizzu Papa Johnova sa ukázať<Ravenos> mm. papa John je.<HomeySan> dúfajme, že pošlú roztomilé vodič dodávky<Ravenos> oni dont mať, že tu.<Dr_Stein> prečo? budeš jesť ovládač miesto?
		-- Ed Lang

%
<Netgod> je to mnou, alebo je Knghtbrd chrápanie?<Joeyho> zabili knghtbrd!<Netgod> Kysh: Wichert, gekón, Joeyho a ja sme v izbe sa snaží ignorovať          Knghtbrd<Kysh> netgod: Knghtbrd je ťažké ignorovať.
		-- Ed Lang

%
<Woot> Man, prajem knghtbrd tu boli chytiť, že pre jeho zozname sig.[... Po niekoľkých hodinách ...]<Knghtbrd> Woot ma nepoznáš vewy dobre, že nie on?<Knghtbrd> muahahahaha
		-- Ed Lang

%
* Knghtbrd kožušín Wichert s NERF šípkami* Wichert berie na vedomie, nie sú tam žiadne ICBM nerfs a ešte sa ignoruje kngtbrd<Knghtbrd> Wichert - len čakať, potom, čo videl NERF Gatling zbrane, ICBM           nie sú ďaleko (len čerpadlo tú prekliatu vec za hodinu alebo dve           je všetko ...)
		-- Ed Lang

%
Operačných systémov:  * Debian GNU / Linux 2.1 4 CD Set ($ 20 od www.chguy.net; cene pobytu je zahrnuté    dane, doprava, a $ 3 Darovanie, aby FSF). 2 CD sú binárne súbory, 2 CD    kompletný zdrojový kód;  * Windows 98 Second Edition upgrade verzie (136 $ cez Megadepot.com,    Cena nezahŕňa daní / poštovné). Prekvapivo, žiadny zdrojový kód    je v cene.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Ukradnúť tento slogan. Urobil som.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Bfextu> oh noooo, Knghtbrd Má zbraň :)<Doogie> ^^ vložiť hudbu ^^<Knghtbrd> bfextu - o / ~ všetci sú na úteku O / ~<Bfextu> o / ~ utiecť, ruuuuun od pay-ay-ain o / ~
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Mercury> emacs saje, a to doslova, nie urážka, len poznámka, že jej          veľký dosť mať znateľný gravitácii ...
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Ako počítači, nájdem svoju vieru v technológii zábavné.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
* Knghtbrd priradí 3 Chrisovi* Variabilné kladie si otázku, kto iný je Chrisa okrem mňa<Knghtbrd> variabilné - môžete. =>* Knghtbrd čaká na premenné dramaticky povedať: "Cítim sa tak použiť!"<Variable> Knghtbrd: :)* Premenná ++<Variable> :)
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
* Espy uvažuje fronty uplad s názvom "peklo", takže môžem robiť dupload --to pekla
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Valkyrja> java, zlato, niekedy naozaj chcem ťa tresnúť.<Knghtbrd> Valkyrja - že by si to príliš veľa<Rete> Valkyrja: Jo, choďte do toho a urob to ... poraziť java do cappuccina! :-)
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<> Tali byť vewwy vewwy qwuiet .. Som Huntin wuntime ewwos
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Red Hat nedávno vydala Security Advisory (RHSA-1999: 030-01)pokrývajúci pretečeniu vyrovnávacej pamäte v balíčku VIXIA cron. debian máobjavil túto chybu pred dvoma rokmi a pripevnil ju. Preto verzia vako je stabilná a nestabilná, distribúcia Debian nie súnáchylné k tomuto problému ..
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Po prvé - Quake je jednoducho neuveriteľné. To vám umožní opakovane zabiť svojeboss v kancelárii, bez toho by bol zatknutý. :)
		-- Signal 11, in a slashdot comment

%
Lucasova Právo: Dobrý bude vždy vyhrať, pretože zlo najíma _stupid_             inžinieri.
		-- Signal 11, in a slashdot comment

%
* TribFurry dostane len nevyžiadanej pošty z UCSD ... Použil som sa dostať e-maily od            Sám ale rozhodol som nemal rád sám seba a prestala hovoriť	    mne
		-- Signal 11, in a slashdot comment

%
<Rain_work> poznámku na koľaji chladničky ... "Na človeka, ktorý jedol obsah            kontajnera označeného "James '- varovanie, bola to moja biológieexperiment "
		-- Signal 11, in a slashdot comment

%
<KatanaJ> Poznámka o chem laboratóriu chladničky a "Táto chladnička nie je proti výbuchu          proof ".
		-- Signal 11, in a slashdot comment

%
<KnaraKat> DALnet je ako špeciálnych olympiád IRC. Je tu veľa           slintanie deje a každý je "víťaz".
		-- Signal 11, in a slashdot comment

%
Ktoré však mení dpkg je nevykonateľné, a my sme súhlasili s, okrem iného,udržiavať potrieb našich užívateľov v popredí našich mysliach. azo autorovi perspektíva, niečo, čo udržuje systém poriadok v normálnejPrípad, a pracuje * teraz *, je oveľa lepší ako idealistických predstáv sa akopracovné dpkg.
		-- Manoj Srivastava

%
Pre každú videnia existuje rovnaká a opačná revízie.
		-- Manoj Srivastava

%
<Epsilon3> Knghtbrd, ak by sme chceli lameass poznámku by sme si povedali:           Hej, neckro
		-- Manoj Srivastava

%
<Tigah _-> mám 4 GB pre / tmp<Knghtbrd> Čo robíte s 4G / tmp? Kompilácia X?<Tigah _-> áno
		-- Manoj Srivastava

%
<KnaraKat> Bite ma.* Theon dostane trochu soli, potom pokračuje okusujú KnaraKat trochou         bit ....
		-- Manoj Srivastava

%
* Knghtbrd berie na vedomie, že má zemiakovú kašu miesto mozgu dnes večer<Valkyrie> yum, môžem mať nejaké?<Knghtbrd> um ...* Knghtbrd skrýva Valkyrie
		-- Manoj Srivastava

%
<Knghtbrd> Joeyho má teraz terminál na gauči?<Knghtbrd> Ten chlap je zapojená, prisahám =><Doogie> Knghtbrd: laptop<Doogie> a nemyslím mačky.
		-- Manoj Srivastava

%
Vzhľadom k tomu, niektoré z nedávnych nití, nemusí interaktívnych diskusiínutné vykonať na plátne, v prítomnosti rozhodcu, zatiaľ čonosenie polstrované rukavice. ;-)
		-- Phil Hands

%
<James>, ale potom som použil Atari, bol som viac pravdepodobné, že vyhrať v lotérii v        Desať krajín súčasne ako akcelerovaný X
		-- Phil Hands

%
* Joeyho sa čudujú, prečo každý chce vedieť, ako vysoký, že je<James> Joeyho: pomáha ostreľovača
		-- Phil Hands

%
* BENČ čuduje, prečo sa aktualizovaný na 3.3.5-1 pred výborne X udržovateľ
		-- Phil Hands

%
<Delennová> by som to robiť to cez 24 hodín, než by som sa streľby sa zriaďuje         gril a búchať pár priateľov na Barbie.<Spacemoos> Prečo by si facku priateľmi s bárbiny, to je trochu výstredný
		-- Phil Hands

%
V skutočnosti .. založené na tomto modeli, čo NSA je a nie je ... mnoho zľudia čítajú to sú členmi NSA ... /. Je koniec koncov "správou preNerds ".NSA pondelok ráno {u kávovaru):NSA AGENT 1: Ahoj chalani, ste check out Slashdot počas víkendu?    AGENT 2: Nie, bol som inštaláciu Mandrake 6.1 a ja coulnd't dostať sakramentsky             ppp spojenie up ..    AGENT 1: Tak pozrieť sa na to ... sú na nás.
		-- Chris Moyer <cdmoyer@starmail.com>

%
Technológia je constand bitka medzi výrobcami produkujúce väčší aViac idiot-dôkazové systémy a príroda vyrába väčšie a lepšie idioti.
		-- Slashdot signature

%
knghtbrd: nemusí existovať lyžice, ale môžete si všimnúť chybu zabezpečeniaeye_render_shiny_object.c?
		-- rcw

%
<Joy> wow ... jednoduché matematiky ukazujú, že vývojári Debianu majú uzavreté viac      než * 31 * * * tisíc hlásení o chybách, pretože naše BTS existuje!<Joy>, ktorý je o 30.999 viac ako na spoločnosti Microsoft;)
		-- rcw

%
<Knghtbrd> všimnúť toho hore je len o stanovisko a nemala by byťVzatý zahŕňať akúkoľvek mieru faktické informácie.           REPRODUKTORY NEUZNÁVÁ všetko a všetkých. ZMIER SA S TÝM.
		-- rcw

%
<James> akákoľvek gnome nadšenci okolo?<Knghtbrd> ja nie, ja som len šialenec
		-- rcw

%
<Madax> ahh<Madax> stretnutie mágov ....<Madax> Môžem to cítim teraz
		-- rcw

%
<Knghtbrd> naučiť milovať Window Maker.<Knghtbrd> trochu NeXTStep je dobré pre dušu.
		-- rcw

%
Upozornenie: je to GNOME, báť sa, byť veľmi bojí je závislá
		-- James Troup

%
<CULus> Hhhmmmmmmmm<> CULus vodných postelí pre kravy<CULus> eleet<Cas> cULus: prečo by krava potrebujeme vodná posteľ?<CULus> CAS: Ak chcete byť pohodlné teplo
		-- James Troup

%
Ak ste to, čo jete, myslím, že to zo mňa robí syr Danish.
		-- Anonymous

%
<Hop>, keď začnete robiť len hlúpe chyby, ktoré sú zreteľné, to je dôvod,      keď začnete dostať príslušný<Hop>, pretože si nerobia zásadné nepochopenie chyby<Hop> a to je súbor * Dobrý * znamenia.
		-- Anonymous

%
<Lilo> je to divné, keď idete na safari v Afrike chytiť leva, budete       Je to živý a nabíja, a potom ho zabiť<Lilo>, keď idete na safari do Južnej Bay nájsť Palm Vx, zistíte       je mŕtvy a vziať si ju domov a nabíja po príchode :)
		-- Anonymous

%
<Lilo> Dokážem čítať krvavý * manuál *, ako keby to bol nejaký druh       náboženské trakt opisuje formy osvietenie možno dosiahnuť       po 10 rokoch na hory :)
		-- Anonymous

%
Gatesa Právo: Každých 18 mesiacov, rýchlosť softvérových polovice.
		-- Anonymous

%
<Knghtbrd> Solver_: pridať užívateľov, ktorí by mali byť preberať sa zvukom do skupiny           audio .. Uistite sa, že zariadenia sú všetky skupiny audio (ls -l           / Dev / dsp vám poskytne najrýchlejší indikáciu, či je to zrejmeset vpravo) a vytvoriť jadro s podporou pre zvukovou kartou<Knghtbrd> alebo voliteľne nainštalovať alsa zdrojmi a kompilácií moduly pre ktoré           s make-kpkg<Knghtbrd> OR (neodporúča sa) získať a nainštalovať zlo OSS / Linux zlo           non-free zlo binárne len zlí vodiči --- ale tie sú zlí.A spomenul som sa, že to neodporúča?
		-- Anonymous

%
Myslím, že IRC je nebude fungovať, aj keď --- nám dochádza téme vesmíru!
		-- Joseph Carter

%
"Pacific Bell zákaznícky servis, to je [..], ako môžem poskytnúťvynikajúce služby zákazníkom dnes? ""Hahahahaha !! To je dobre, páči sa mi to ..""Hm, vďaka, robia nám hovoria, že."
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Danpat> Omnic: krvavé newzealanders<Omnic> danpat: dať ponožku v ňom<Danpat> heh :)<Knghtbrd> robiť žarty z .nz'ers sa líšia --- všetci sú podivné* Knghtbrd koža<Omnic> hrmph
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Joy> Flinn: black magic crontab trochu veci :)<Knghtbrd> Joy: Znamená to, že ľudia dostať k tancu nahý okolo ohňov           spievanie podivné veci a mávali rukami v hlúpe           spôsobom?<RCW> knghtbrd: Čo si myslíte, že * * ľudia v Novare?
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Knghtbrd> * snipsnip *<RCW> ach bože, je to, že zvuk editácia fortune-databázy?<Joy> uh oh<Knghtbrd> Áno =>
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Joy> to je Kludge (TM)<Knghtbrd> to funguje (tm)<Joy> AIX práce (TM)<Knghtbrd> no to nie je<Knghtbrd> =>
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
"Rozdiel medzi genialitou a hlúposť je, že génius je tolimitov. "
		-- Albert Einstein

%
<Knghtbrd> Ak nabíjanie niekoho za porušenie amerických zákonov kryptografických by sa           ste sa zasmial mimosúdne, iba "vyšetrovať" nimi na hte poplatku           zrady!<Knghtbrd> Čaj, niekto?<Espy> by som radšej utopiť politici namiesto čaju :)<Stu> postrehnúť: politici majú žiabre, duh<> Espy lasice nemajú žiabre
		-- Albert Einstein

%
Ak mám problémy s inštaláciou Linux, je niečo zle. Veľmi zle.
		-- Linus Torvalds

%
* Bma_home vás gropes<Bma_home> "oups, zlý kanál"<Bma_home> </ ACF><Cerb> quit ma tápanie<Doogie> viete, že ste to páči.<Bma_home> v skutočnosti, že to bolo "tápať ma dieťa"<Gecko-> dotknúť môjho syna a zomriete, BMA;)<Doogie> gecko-, ale vaša žena je v poriadku?
		-- Linus Torvalds

%
Čítanie počítačové manuály bez hardvér je rovnako frustrujúce ako čítaniesex manuály bez softvéru.
		-- Arthur C Clarke

%
<Knghtbrd> (Tincu)<Espy> (ytitac)<Knghtbrd> (ntinac)<Espy> (it)<Knghtbrd> (in)* Espy konštatuje hovorí v AČR ^ Winitialisms je desivé, keď na druhej strane  vám rozumie
		-- Arthur C Clarke

%
<Knghtbrd> Je to škoda Najstaršie Unix sú Y2K kompatibilné<| Dážď |> škoda?<| Dážď |> prečo, pretože ľudia nebudú inovovať až do roku 2038?
		-- Arthur C Clarke

%
<Espy_on_crack> "Nainstaloval som" Linux 6.1 ', nie je to mi robiť Unix                guru? "<BENČ> Espy_on_crack: nie, musíte ho dvakrát nainštalovať predtým, ako ste       guru ... raz dokázať, môžete to urobiť, druhá opraviť veci       Váš zlomil prvýkrát<Espy_on_crack> ach jo, ako hlúpe
		-- Arthur C Clarke

%
* Knghtbrd robí vec ET<Knghtbrd> niekto dostal hovoriť-n-kúzlo?
		-- Arthur C Clarke

%
<Omnic> ďalší prírastok .sig
		-- Arthur C Clarke

%
Začínam si myslieť, genofond by mohol použiť trochu chlóru.
		-- Arthur C Clarke

%
Je to tak zlé, ako si myslíte, a oni sú von dostať vás.
		-- Arthur C Clarke

%
<Espy> dávať pozor, niektoré hlupák vám môžu citovať<Espy> vytrhnuté z kontextu ...
		-- Arthur C Clarke

%
*** Téma pre #redhat: RedHat je odpoveď na všetky vaše problémy. to    by mohol byť začiatok taky!
		-- Arthur C Clarke

%
* Cesarb kladie otázku, či v čase kratšie ako týždeň Carmack skončí príjem v  e-mailom zdvorilostné kópiu verzie zdroje Quake, ktorá je štyri  krát rýchlejší ako to, čo vyšiel z jeho virtuálnych rúk ...
		-- Arthur C Clarke

%
<Knghtbrd> JHM: Nebudem dávať zemetrasenie v zdrojovom kóde jadra<Knghtbrd> ale mali by sme dať zemetrasenie v zavadzacími disketami k jednému-up           Caldera je Tetris hra ..;>
		-- Arthur C Clarke

%
Zbrane nezabíjajú ľudí. Je to tie zatratenie guľky. Zbrane stačí, aby ich ísťnaozaj rýchlo.
		-- Jake Johanson

%
<Espy> musíme rozdeliť Hlavným do "jadra" a "WTF-použitie-This"
		-- Jake Johanson

%
<Culus-> libc6 nie je podstatné: |
		-- Jake Johanson

%
<DHD> existuje špeciálny vianočný balíček pre zemetrasenie<DHD>, kde máte byť ako robot santa na Futurama?<Dunham> DHD: to by bolo trochu nevyvážená hra ...<Knghtbrd> Dunham: to je nápad. ;>
		-- Jake Johanson

%
<Knghtbrd> problém so štandardmi kódovania GNU oni predpokladajú, žekaždý na svete používa Emacs .. Ak by to tak bolo, zadarmo           softvér zomrie, pretože všetci by sme mať problémy zápästiaako RMS teraz a už nebude schopný kódovať. ;>
		-- Jake Johanson

%
No tak! politický protest! Sheesh. Kde je ten anarchistický duch? ;-)
		-- Decklin Foster

%
Zvýšili sme naše štandardy, takže sa vaše!
		-- Decklin Foster

%
* Woot je teraz známa ako Woot-večeru* Knghtbrd posype trochu soli na Woot<Knghtbrd> som nikdy nemal Woot pred ... Dúfam, že dobre chutia<Woot-večeru> noooo!<Woot-večeru> nejedia ma!* Knghtbrd rozhodne, že nechce večeru, ktorá hovorí k nemu ... hehe
		-- Decklin Foster

%
[Týkajúce sa opatrení na zabránenie podvádzanie v Quake]Myslím, že tak dlho, ako môžem, aby sa moje raketové odpaľovacie zariadenie vyzerať ako veľký TWINKIE,Budem rád;)
		-- Qeyser <keyser@jhu.edu>

%
<Knghtbrd> r0bert: Stručne povedané, ideme niekoľko vecí klienta           V súčasnej dobe je zodpovedný za hovorí servera do vecí na           server kontroluje pre seba<Knghtbrd> Ak Neo hovorí: "Neexistuje žiadny lyžice", The Matrix povie: "Ach áno           --- Nie je žiadny podvod! "<Hollis> Ale vie, kung-fu ...<Knghtbrd> Iste áno, ale mám raketomet.
		-- Qeyser <keyser@jhu.edu>

%
* Mercury pokojne odstraňuje XT-Ream ruku ..* Mercury potom pokračuje poraziť XT-Ream s XT-balíku paži.<Knghtbrd> wow, to všetko zemetrasenie hacking robí Mercury tu násilnej* Mao je rád, že zemetrasenie kováreň projekt je v dobrých rukách
		-- Qeyser <keyser@jhu.edu>

%
<Knghtbrd> CVS / Zápisy mal linku som potreboval "alter"<Mercury> Knghtbrd: Bol asi spomenúť napr .. <G><Mercury> Knghtbrd: Teraz, pripravený spáchať?<Knghtbrd> želajú mi šťastie<Knghtbrd> Mercury: je to spáchal<Knghtbrd> Mercury A po tom všetkom, že by som mal byť taky.
		-- Qeyser <keyser@jhu.edu>

%
* Knghtbrd krížia prsty na nohách<Knghtbrd> (ak som prekročil prsty by bolo ťažké písať)
		-- Qeyser <keyser@jhu.edu>

%
<Doogie> existuje jedna zlá vec, o ktoré majú mobilný telefón.<Doogie> Aj môže byť dosiahnutý kedykoľvek. : |<Wmono> to je dôvod, prečo som opustiť baňa off za všetkých okolností. ;>
		-- Qeyser <keyser@jhu.edu>

%
<Palisáda>, ako budeme vysloviť číslice 00 alebo '01 alebo '02 a tak ďalej?<Deek> Rozlúčte sa s deväťdesiatych rokov, pozdraviť naughties. :)
		-- Qeyser <keyser@jhu.edu>

%
<Deek> Ak používateľ poukazuje na pištoľ na svoje kopačky a stlačí spúšť, to       Našou úlohou je zabezpečiť, guľka dostane tam, kde to má.
		-- Qeyser <keyser@jhu.edu>

%
<Mercury> Byť upozornení, mám klávesnica môžem použiť na poraziť hlavy luser je          , A potom pokračovať v používaní ... (=:]<Deek> Mercury: Oh, IBM. :)
		-- Qeyser <keyser@jhu.edu>

%
<Palisáda> knght, Sheesh, ste vložením moje slová z kontextu, v           #debian alebo tak niečo?<Palisáda>;)<Knghtbrd> nie, ale asi by som mal byť;><Palisáda> d'oh!
		-- Qeyser <keyser@jhu.edu>

%
<Cas> Mercury: gpm nie je moc dobrý webový prehliadač. opraviť to.
		-- Qeyser <keyser@jhu.edu>

%
<Cas> aj tam ya go. povedať niečo hlúpe v IRC a majú ho      zvečnenie navždy v .sig súboru niečí
		-- Qeyser <keyser@jhu.edu>

%
Microsoft je hybrid medzi Borg a Ferengi. bohužiaľ,oni používajú Borg k tomu ich uvádzanie na trh a Ferengi, aby urobiliprogramovanie.
		-- Simon Slavin

%
Bol by som radšej trávia 10 hodín čítaním zdrojového kódu niekoho iného než 10minút počúvania Musaka čakania na technickú podporu, ktorá nie je.
		-- Dr. Greg Wettstein, Roger Maris Cancer Center

%
Kde si myslíš, že ideš dnes?
		-- Dr. Greg Wettstein, Roger Maris Cancer Center

%
Som bol počul najrôznejšie stiesnenosti a skazy predpovede pre Y2K, a tak som Myslel som, že by som dbať na niektoré z rád, aby experti dávať: Naplňte palivovú nádrž vozidla, zásobili konzervami, naplňte vaňu s vodou, a tak ďalej.Myslím, že som nebol úplne hore, keď som dokončil moje prípravky na konci minuléhonoc. Dnes ráno som zistil, kuchynské police namočené v benzíne, vodav plynovej nádrži vozidla, a moje vani naplnené s pečenými fazuľami.
		-- Dan Pearl in a message to rec.humor.funny

%
<Tarzan> hej si spadnúť svoju Pirch alebo tak niečo?<Knghtbrd> me? heh.
		-- Dan Pearl in a message to rec.humor.funny

%
<Espy> ste sa pečú<Knghtbrd> Espy: len z polovice tak
		-- Dan Pearl in a message to rec.humor.funny

%
<Čierny anjel> I obyčajne nepoužívajú čokoľvek, čo má "experimentálny" a            "Varovanie" vložiť všetko nad ním<Čierny anjel> nie, ja nie som tak hlúpy ... hehe<Knghtbrd> ...* Čierny anjel sa domnieva stiahnutie najnovšej nestabilné jadro
		-- Dan Pearl in a message to rec.humor.funny

%
<Wichert> Solaris je BSD, takže by to malo fungovať* Espy berie Wichert svoje trhlín rúrku preč
		-- Dan Pearl in a message to rec.humor.funny

%
<Knghtbrd> Je to škoda, väčšina starých UNIX ukázalo Y2K kompatibilný<Knghtbrd>, pretože to znamená, že ľudia budú aj naďalej prevádzkovať je za posledných 30 rokov           = p<Knghtbrd> by to bolo oveľa lepšie, keby Y2K účinne odrovnal           HPUX, Aix, SunOS, atď;><Espy> Knghtbrd: odkedy sú PH-UX, bolesti a solartus "staré"?
		-- Dan Pearl in a message to rec.humor.funny

%
* Gxam kladie otázku, či je naozaj nutné všetky tieto globálne premenné<Knghtbrd> väčšina z nich v túto chvíľu áno<Knghtbrd> Naozaj potrebujeme k ich vyčistenie v určitom okamihu<Knghtbrd> gxam: na globálne premenné bude musieť ísť preč, ako sme migrujú smerom           modularita a šialenstvo (tj libtool)
		-- Dan Pearl in a message to rec.humor.funny

%
<Raptor> Adamelo, myslím, že kód, ktorý pevne môj nefungoval<Raptor> Nesmiem mať spáchal pracovné kód<Knghtbrd> raptor: ako by to prvýkrát, čo sa nikdy nestalo = p
		-- Dan Pearl in a message to rec.humor.funny

%
<Mercury> Knghtbrd: Použitie -3dfx alebo -svga?<Knghtbrd> Mercury urobí niečo sane s ním<Knghtbrd> Mercury: obaja --- SVGA sig11'S, -3dfx sig4 je<Knghtbrd> Mercury: to nie je dobré nie? ;>
		-- Dan Pearl in a message to rec.humor.funny

%
<Knghtbrd> Verte, že vieme, čo robíme ... Môžeme mať tušenie, ako           robíme to, ale my vieme, čo robíme.
		-- Dan Pearl in a message to rec.humor.funny

%
<Mercury> <CJ | Bizkit-0-> môžem nahrať na server tho linux<Mercury> <CJ | Bizkit-0-> Mám účet shell na jednom<Mercury> <Mercury> Čo je to beží?<Mercury> <CJ | Bizkit-0-> umm<Mercury> <CJ | Bizkit-0-> apache myslím,<Mercury> Pomoc, prosím pomôžte ..* Omni smiech
		-- Dan Pearl in a message to rec.humor.funny

%
<Jt> by mal byť označený chyba kritická, ak to má vplyv iba jeden oblúk?<James-workaway> JT: rc pre tento oblúk Možno, ale tieto oblúka                 Konkrétne chyby sú zriedkavé ...<Jt> nie, keď je to spôsobené chybou v gcc<Doogie> JT: dostať gcc odstrániť z tohto oblúka. :)
		-- Dan Pearl in a message to rec.humor.funny

%
<EDLINE> LWE?<EDLINE> Linux W ?? E ??<Vidí> bude eatyou<JHM> World Expo?<EDLINE> vidím
		-- Dan Pearl in a message to rec.humor.funny

%
"Nominálne poplatok". Čo škaredé veta. Je to jedna z tých vecí, ktoréznamená, že ak máte opýtať, môžete si to nemôže dovoliť.
		-- Linus Torvalds

%
<Deek> GPL svoju domácu úlohu? :)<Knghtbrd> Jo = D<Knghtbrd> Každý, kto je povolené používať alebo pozmeniť svoju domácu úlohu, ale v prípade, že           distribuovať zmeny, ktoré musí obsahovať úplnú strojovo čitateľných           zdrojový kód;>
		-- Linus Torvalds

%
* Knghtbrd je každý deň viac presvedčený o tom, že väčšina C ++ kódery neviem čo           sakra robia, čo je dôvod, prečo C ++ má takú zlú reputáciu<CULus> KB: Most C kódery nevedia, čo robia, je to jednoducho robí to        ľahšie skryť: P<CULus> pozri napríklad proftpd: P
		-- Linus Torvalds

%
<CULus> A nie aby som začal na Perl!<CULus>:><Shaleh> perl je nad zlom<Jim> neviete perl ešte?<> Netgod musíš milovať jazyk s žiadnym definovateľný syntaxe
		-- Linus Torvalds

%
<Doogie> cat / dev / random | perl?<Shaleh> Doogie: to je tiež platný sendmail.cf<Doogie> :)* Knghtbrd ruky Doogie nezmyselný-use-of-mačky ocenenie* Shaleh chce to skúsiť, ale má strach
		-- Linus Torvalds

%
<DHD> perl </ dev / bdsm<Knghtbrd> máte / dev / BDSM?<DHD> istý, že je to pseudosadomasochistic generátor náhodných čísel
		-- Linus Torvalds

%
<Kysh_> Joey: Ja som na tom práve teraz .. 3 1.3Gb disky, 128M RAM, duálny 50MHz        (Až do quad 250MHz)<Kysh_> Háčik je v tom, že sa tiahne 110V 12A pri teplote asi 8><CULus> 12A!<CULus> Dobre, môj kachlí je 3000W, to je slnko 1320W<CULus> Vidíte tu problém<Vyp> a 1320W slnko, ktorý je ako sušič vlasov :)
		-- Linus Torvalds

%
* Joeyh_ beží ps a vidí 10 riadkov kódu awk* Joeyh_ odvracia s hrôzou
		-- Linus Torvalds

%
<Knghtbrd> Joeyho: Bol som dole, pretože včera dopoludnia a pacbell povedal:           Dnes ráno, že AT & T bol k vine a takmer všetci štátu           bol dole<RCW> neviem, prečo ľudia trvajú na tom, že internet môže prežiť jadrový holokaust      keď to nemôže prežiť rýpadlo
		-- Linus Torvalds

%
Táto správa bola napísaná s vi! (Nie, že niekto vo svete sa stará)
		-- seen on an old message from an anon.penet.fi address

%
resetovanie pripojenia nejaký debil s rýpadlo
		-- seen on an old message from an anon.penet.fi address

%
5. februára 13:27:01 trojica lp0 v ohni        - Linux kernel, ma upozorní, že tam bola nejaká neznáma           Problém s mojou tlačiarňou (tj bolo atrament)
		-- seen on an old message from an anon.penet.fi address

%
Čím menej viete o počítačoch tým viac budete chcieť Microsoft!        - Microsoft reklamná kampaň, circa 1996(Dôkaz, že Microsoft je reklama _isn't_ nečestné!)
		-- seen on an old message from an anon.penet.fi address

%
Výrobu jednej brilantné rozhodnutí a veľa tých priemerných nie je takdobrý, ako robiť veľa všeobecne inteligentné rozhodnutia v celomCelý proces.
		-- John Carmack

%
Nie je to zvyčajne stojí efektívnu dobu múdre ísť robiť to. Ale či sa niečonaozaj pissing off, jednoducho idete nájsť kód a opraviť, a to jenaozaj super.
		-- John Carmack, on the advantages of open source

%
<Vyp> áno znie to užitočné pre RE'ing USB<Vyp> mám k ničomu 3com kamera USB tu :(<Knghtbrd> vypočítané: 3Com mohli ste zatknutý za porušenie zákonov, ktoré           neexistujú 'do októbra;><Vyp> knghtbrd: budem skrývať :)<Knghtbrd> ... odpor pri zatýkaní tiež nie?<Vyp> knghtbrd: no budem skrývať, než sa dostanem slúžil
		-- John Carmack, on the advantages of open source

%
<Mercury> V tomto bode bude kompilovať, ale segfault, ako by mala ..
		-- John Carmack, on the advantages of open source

%
* Knghtbrd je príliš pokušenie .sig celú túto diskusiu ...
		-- John Carmack, on the advantages of open source

%
Unixverse končí dňa Ut, 19 január 2038 03:14:07 +0000
		-- John Carmack, on the advantages of open source

%
<Taniwha> Knghtbrd: by sme mali urobiť zemetrasenia epizódu: po kolená v kóde ":          budete pobehovať streľbe na chyby :)<Knghtbrd> taniwha: Odovzdám myšlienku na OpenQuartz;>
		-- John Carmack, on the advantages of open source

%
<Taniwha> by som vyriešiť s operačným systémom Windows kľúčový problém s fdisk :)
		-- John Carmack, on the advantages of open source

%
<Endy> knghtbrd: QW je netcode robí podivné veci ku mne. : P<Knghtbrd> Toto je nezvyčajné? ;><Endy> Nie tak celkom. : P
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> RCW: No hurá --- som nebol zapojený v dobrom flame war At           najmenších ... 5 minút!
		-- John Carmack, on the advantages of open source

%
<Manoj> shaleh: Nie som, a to napriek vašej implikácií, Bohom
		-- John Carmack, on the advantages of open source

%
<SlayR> Kúpil som si MS Office 2000 za pouhých 20 $ !!!<Knghtbrd> ste sa ošizené;><SlayR> ja viem;)
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> je to 6 hodín ráno. Už som až 24 hodín<Knghtbrd> Prebuď ma a život rizík a končatiny.* Knghtbrd &; spánok<Tv> Ok všetci, budeme čakať 10 minút a potom začať záplavy Knghtbrd     s ^ G je. Niekto, kopnutie koreň a cat / dev / urandom> / dev / dsp.
		-- John Carmack, on the advantages of open source

%
*** Knghtbrd je teraz známy ako SirKewLDooD*** Mercury kopol SirKewlDooD z #quakeforge (* prásk *)
		-- John Carmack, on the advantages of open source

%
<Mercury> Knghtbrd: Ja by som rád videl podporu XOR hľadáčika ..<Knghtbrd> Mercury: ste na šarlatán.<Mercury> Knghtbrd: Ty si ten dealer ... <G>*** Knghtbrd je teraz známy ako QuackDealer
		-- John Carmack, on the advantages of open source

%
* Suchý ľad nemôže kódovať cestu von z papierového vrecka<Coderjoe> suchého ľadu: int main () {ExitPaperBag (); return 0; }<Knghtbrd> Je to, ako sa to robí potom? * Berie na vedomie *
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> EEK, nie ešte jeden ...<Knghtbrd> Zdá sa, že niekedy developer a ich matka má teraz náhodné           podpis pomocou IRC citácie ...<Knghtbrd> Čo som ZAČAŤ TU ??
		-- John Carmack, on the advantages of open source

%
* Vidí využíva pripomienky knghtbrd ako jeho podpis<Knghtbrd> vidí: akonáhle som im napísal som si uvedomil, že by som radšej odstrihnúť im           Sám ako niekto iný áno;>
		-- John Carmack, on the advantages of open source

%
* Omnic sa pozerá na jeho 33.6km odkaz a potom sa pozrie na Joy* Mercury pomaznanie jeho káblový modem .. (=:]
		-- John Carmack, on the advantages of open source

%
Je pravda, že Win95 je pohľad nebolo všetko, že nové buď - Apple pokúsila zažalovaťMicrosoft pre kopírovanie užívateľského rozhrania Macintosh / ikonu koša, kým Microsoftpoukázal na to, že Apple dostal mnohé z jeho nápadov Mac (vrátane košaicon) od spoločnosti Xerox ParcPlace. Xerox je pravdepodobne stále premýšľal, prečokaždý má záujem o ich popolnice.
		-- Danny Thorpe, Borland Delphi R&R

%
<Knghtbrd> je to známka duševné choroby putovať bezcieľne prostredníctvom           spustiť mapy, zbierať vaše Thunderbolt, hop do bazéna, a gib           si s ňou jednoducho vidieť vaša hlava buouce keď to padáskrz dno bazéna? =><Knghtbrd> "Vieš, že si Quake narkoman, keď ..."
		-- Danny Thorpe, Borland Delphi R&R

%
<Zoid> Stále si myslím, vy ste orechy zlučovanie Q a QW. : P<Knghtbrd> Samozrejme, že sme orechy. Dokonca povedal John tak. =><Taniwha> Zoid: sme orechy, ale my sme produktívne orechy :)
		-- Danny Thorpe, Borland Delphi R&R

%
<Taniwha> Zoid: sme orechy, ale my sme produktívne orechy :)* Taniwha sa čuduje, čo produktívne orechy chutiť
		-- Danny Thorpe, Borland Delphi R&R

%
<Endy> taniwha: Citácia materiál :)<Taniwha> Endy: :)<Knghtbrd> Endy: Už som ju prestrihol
		-- Danny Thorpe, Borland Delphi R&R

%
<Endy> Vlastne, myslím, že budem čakať na zemiakov, ktoré majú byť dokončené pred       Inštalácia systému Debian.<Endy> To by malo byť čoskoro, dúfam. :)<Knghtbrd> Endy: Tie samozrejme vedia veľmi málo o Debiane.
		-- Danny Thorpe, Borland Delphi R&R

%
Nič nie je problém, akonáhle sa ladenie kódu.
		-- John Carmack

%
<Overfiend> Unix cestu - všetko je súbor<Overfiend> The Linux cesta - všetko je súborový systém :)
		-- John Carmack

%
<Devkev> Jo, ja videl blesk zbraň a kam ideš, myslenie         si chcel nakopať zadok :)<Devkev> didnt si uvedomiť, že to bude váš vlastný :)
		-- John Carmack

%
"V opačnom prípade, prosím, svojho lekára o odobratie hlavu zo svojhozadku, som presvedčený, že by bolo prospešné pre všetkých zúčastnených. "
		-- Zephaniah E. Hull, flaming someone on a mailing list

%
Fb, ty to ty!
		-- Zephaniah E. Hull, flaming someone on a mailing list

%
Som cvičí jemnú bod etiky. Je prijateľné, aby strieľať späť.Je neprijateľné, aby strieľať ako prvý.
		-- Zed Pobre

%
<Coderjoe> gib, perl?<Gib> Zdá sa mi perl je programátor Swiss Army motorovou pílou
		-- Zed Pobre

%
<Endy> taniwha: Už ste testovali tento? :)<Taniwha> Endy: samozrejme, že nie
		-- Zed Pobre

%
To je tá najzábavnejšia vec, akú som kedy počul a budem _neinstalujete_ ju prehliadať.
		-- DyerMaker, 17 March 2000 MegaPhone radio show

%
Nie je? Hovoríte, že by ste mali počítať ľudia (okrem WilliamWallace) strieľať blesky zo svojho zadku?
		-- Seth Galbraith

%
<Mercury> Nemusíte byť blázon, aby byť členom projektu, ale          budete mať .. <=:]
		-- Seth Galbraith

%
* Endy musí konzultovať kávu: P<Endy> káva topánok človek, nie káva nápoj :)<Knghtbrd> konzultácii s nápoj môže pomôcť príliš =>
		-- Seth Galbraith

%
<Mongoose> knghtbrd: a tíši dedične Kmart
		-- Seth Galbraith

%
<Knghtbrd> "Java pre COBOL Programátor"<Knghtbrd> kto píše tieto veci?<> Raptor ľudí na trhliny<Raptor> a COBOL programátori<Raptor> :)<Knghtbrd>, ktorá je nadbytočná.
		-- Seth Galbraith

%
<Evilkalla> heh, nikdy som vzal triedu kódovanie<Evilkalla> alebo trieda grafika<Evilkalla> alebo trieda dizajn softvér<Vegan> a je to vidieť: P
		-- Seth Galbraith

%
* The_Answer_MD hádže špagety na každého* Taniwha jej špagety* Coderjoe hodí okolo niektorých karbonátky* Knghtbrd dostane syr* Taniwha popadne červená
		-- Seth Galbraith

%
<Theoddone33> Čo je to správa na mojej obrazovke,<Theoddone33> tak modrá, tak modrá, čo by to mohlo znamenať?<Theoddone33> Mohli by ste, mali by ste kláves Delete,<Theoddone33> Ctrl a Alt a opakujte.
		-- Seth Galbraith

%
<Gorgo> čo dostanete, keď niekto praskliny svoju debian stroj?<Gorgo> zemiaková kaša ...
		-- Seth Galbraith

%
<Hľa> poď<Hľa> je to pico klon<Hľa> to znamenalo * * byť nepríjemné
		-- Seth Galbraith

%
<Espy> Vzývam postrehnúť zákon, ktorý stanovuje, že všetci sať: P
		-- Seth Galbraith

%
<Overfiend> cULus: chcem pozastaviť ma za to? :)<CULus> Overfiend: Ísť zákerne praskanie pár oddelí a porozprávame<Overfiend> cULus: sakra, to musí byť škodlivý?<CULus> Overfiend: Je smutné, že áno
		-- Seth Galbraith

%
<Knghtbrd> 2fort5 naštve dosť mať svoju vlastnú gravitáciu ...
		-- Seth Galbraith

%
* Kozmické žiarenie želá, aby mal nejaké striptérky tu ....<Kozmické žiarenie> ERR, drôt striptérky
		-- Seth Galbraith

%
<WildTHing> OK chlapci .. takže whens budúci commit: PP<Taniwha>, keď prídu, aby ma
		-- Seth Galbraith

%
<Mdorman> Som gnus človek sám. Je to editor! Je to floorwax!          Je to dezert zálievka!
		-- Seth Galbraith

%
<Tausq> Otázka: Aký je rozdiel medzi Batman a Bill Gates?<Tausq> A. Pri Batman bojovať Penguin, vyhral.
		-- Seth Galbraith

%
V určitom okamihu, bity musieť ísť do paketov a smerovača je potrebné vykonaťrozhodnutia o nich. Zmeny na tejto úrovni je to, čo chcem počuť, niestrategické firemné vzťahy.
		-- John Carmack

%
Odmietame: Kings, predsedov a hlasovanie.Veríme v: drsné konsenzu a pracovné kódu.
		-- Dave Clark

%
<Knghtbrd> QF dostane .zip archívu podporu dnes<Coderjoe> heh ... infozip?<Knghtbrd> Ak mám šťastie áno<Deek> knghtbrd: Robíš si srandu, že jo? ;)* Deek odnáša Knghtbrd svoje trhliny potrubia. ;)
		-- Dave Clark

%
<Deek> meniť všetky cvar-> value = X použiť Cvar_Set ()<Theoddone33> sa tak nestalo v oldtree<Deek> V skutočnosti to urobil.<Knghtbrd> jo - o dva týždne neskôr.
		-- Dave Clark

%
=== Tento list je Honor System Virus ====Ak sa systémom Macintosh, OS / 2, Unix, aleboLinux počítač, prosím náhodne odstrániťniekoľko súborov z pevného disku aodovzdá túto správu všetci poznáte.==============================================
		-- Dave Clark

%
* Možnosť Skratka sa chce dostať do jednej z knghtbrd je sigs jeden z týchto dní.
		-- Dave Clark

%
<Dr ^ Nick> SGI_Multitexture je zlé voodoo teraz<Dr ^ Nick> ARB dobrý voodoo<Witten> no, voodoo náhlenie je zlá voodoo :)
		-- Dave Clark

%
99 drobné chyby v kóde, 99 chýb v kóde,        opraviť jednu chybu, skompilovať znova ...        101 drobné chyby v kóde ....
		-- Dave Clark

%
Hmm ... Čo by robiť lepšiu prácu pri jazde fyziky blázon? cestovnérýchlejšie ako svetlo, alebo boolovská hodnota s plávajúcou desatinnou čiarkou?
		-- Michael Mol

%
<Vyp> knghtbrd: gnome 2.0 vyjde za pár mesiacov, nebol si istý, ako to       bude v porovnaní s KDE 2.0 hoci<Knghtbrd> vypočítalo: Rovnako ako nafúknutý, rovnako ako buggy, a každý Gnome 2 app       bude závisieť na 30 knižníc.<Slimer> knghtbrd: tak čo sa zmení od 1,0?
		-- Michael Mol

%
<Ze0> tak, ako to všetko vo svete Quack?<LordHavoc> jednoducho Drahoušek<Ze0> vynikajúci, vyprážané kačica je mocný jemný chutné.
		-- Michael Mol

%
<FrikaC> Asi by som mala reštartovať ...<FrikaC> ok BRB<FrikaC> Takže, čo od seba forma vyhnúť víri, úniky pamäte a nekontrolovateľná         zhadzovať robí Linux reallhy ponúkajú :)<LordHavoc> spoľahlivý multitasking?
		-- Michael Mol

%
<Tausq> if (cb) ((CB> obj) -> * (CB> ui_func)) ();<Knghtbrd> tausq: Kto sakra napísal, že?<Tausq> me :)* Knghtbrd flogs tausq
		-- Michael Mol

%
<Knghtbrd> glDisable (GL_BUGS);<Endy> heh<Endy> Je to v 1.2? :)
		-- Michael Mol

%
<Mercury> knghtbrd: eww, nájsť lepšie meno, film cucal .. <G><Knghtbrd> Mercury: Motor je lepšia ako film
		-- Michael Mol

%
<LackOfKan> Čo sú "topánky"?< `` Erik> RSG je topánok, nie človek, nie človek použiteľné klientom, len topánok.< `` Erik> zhruba rovnaká ako zemetrasenie topánok, s výnimkou IRC boti sú (zvyčajne)         postavený na pomoc, nestrieľajte váš zadok plný dier
		-- Michael Mol

%
if (me = vy!) // dorobiť: pravdepodobne vždy pravdivé, zmazať?    pre (n = 0; n <who_knows_what; n ++) {        answer = DoSomething (withthis [n]);        if (== odpoveď foobar) {            GetLost (n);            break;        }    }
		-- Michael Mol

%
<Knghtbrd> Yorick: žiadny problém s indexovaných farebných paliet pre obrázky, as           Kým si môžete vybrať paletu<Yorick> Je zrejmé, že ľudia vytvárajú zemetrasenia boli farboslepý, ale že         neznamená, že musíte byť
		-- Michael Mol

%
<Cesarb> Sakra, zakaždým, keď sa trú, QF-client-X11 zámky tvrdé<Zoid> Neumírej?<Knghtbrd> dobrú motiváciu.
		-- Michael Mol

%
Prečo je to, že všetky nástroje hľadá inteligentný život v mestevesmír sú zamerané preč od Zeme?
		-- Michael Mol

%
<Rebelpacket> hej, rýchly dotaz, existuje nejaký spôsob, ako urýchliť              Výkon uquake-x11?<Deek> rebelpacket: Ak chcete ju zrýchliť, hodiť to ťažšie.
		-- Michael Mol

%
<Netgod> vieš<Netgod> je to naozaj smutné, keď Internic sám prevýšenie nakonfigurovať DNS         servery pravý<Netgod> to len doesnt dostať nič viac než to patetické
		-- Michael Mol

%
<Knghtbrd> Aj s overbrights, farebná paleta Zemetrasenie je plný nudné,           ploché farby<LordHavoc> knghtbrd: paleta Quake je veľmi živé, ak nepoužijete gama            oprava<LordHavoc> no vlastne súhlasím, je to zďaleka tak žiarivé ako Unreal<Deek> Q3 na druhej strane ... NEON.<LordHavoc> Q3 je jednoducho smiešne<Deek> Q3 berie stredovekého kostola-žalár a vloží ho do Vegas.
		-- Michael Mol

%
"Mám kosť k nástupu a málo sa zlomiť."
		-- Anonymous

%
Z.O.I.D.: Zombie Optimalizované pre infiltráciu a zničenie
		-- Anonymous

%
<Deek> Áno, Amerika je krajina, podľa toho, ako naštvaný-off skupina zdanené       ľudia môžu dostať.<Deek> Žijeme ako krajina, pretože sme lacné.
		-- Anonymous

%
<Oskuro> Overfiend: mnoho škvrny na hornej časti 4.0.1 už?<Overfiend> Oskuro: málo<Overfiend> púhych 152 mega
		-- Anonymous

%
<Joeyho> oh my, je to UP P III.<Doogie> ju DOS.* Joeyho beží dselect<Overfiend>, ktoré by mali byť dostačujúce :)
		-- Anonymous

%
<Barneyfu> knghtbrd: blbosť, SDL, či je DGA sakramentsky veľa jednoduchšie príliš           viď? :)<Knghtbrd> barneyfu: čo DGA?<Barneyfu> Myš DGA<Knghtbrd> barneyfu: (to, že odpoveď na vašu otázku?)<Barneyfu> Hahahahaha YEAH! :)
		-- Anonymous

%
<Deek> "Dobrý programátor môže písať FORTRAN v akomkoľvek jazyku."<Deek> knghtbrd ukázala, že môžete písať C ++ v akomkoľvek jazyku taky.       <Škleb><Mercury> V súčasnej dobe considdering ak by sme ho mali dávať alebo cenu, alebo          zabiť ho..<Mercury> (Samozrejme tým, že všetky práva, to znamená, že by sme mu mali dať          Cenu, a potom ho zabiť .. <G>)
		-- Anonymous

%
Podvratný je niekto, kto môže tvrdiť, mimo svoju vládu.
		-- Anonymous

%
Musíme vedieť, budeme vedieť.
		-- David Hilbert

%
<Knghtbrd> Cenzúra internetu. Vzhľadom k tomu, vaše deti potrebujú byť           chránená pred nahých žien, liečebných postupov, rôznorodékultúr a násilné videohry.<Knghtbrd> (ale informácie o budovaní bomby, krádeže kábla, a           výrobe drog je v poriadku ...)
		-- David Hilbert

%
Môj kamarát má čiarový kód na paži.On prstene sa ako $ 0,35 balenia JuicyFruit.
		-- Seen on Slashdot

%
<NullC> Páči sa mi kód osiva pre výpočet maskovacie krivky.<NullC> Nikdy som nevidel kódu, ktoré robili sa chcete piť pred tým ...
		-- Seen on Slashdot

%
$ Vy = new YOU;zatrúbenia () ak je $ Knižný> love (perl)
		-- Seen on Slashdot

%
<Cj> nie! Problémy v M $ softvéru?<Cj> "Dôkladne bugtested"* Dabba škerí.<LordHavoc> prepísať, že ako "Dôkladne buginfested"
		-- Seen on Slashdot

%
<Doogie> dpkg má chyby? v žiadnom prípade!
		-- Seen on Slashdot

%
"Debian: bez pokrývky hlavy alebo plazy boli poškodené pri tvorbe tejto distribúcie =".
		-- Paul Slootman

%
* Athener žiada Amnesty International House of Pancakes
		-- Paul Slootman

%
<Elmo> nečisté: err, admin tím nekontrolujú archívu, to je       ftp kľučka<Elmo> dostať svoje cabals pravdu, sakramentsky :-P
		-- Paul Slootman

%
<BENČ> kozmické žiarenie: si ma dokončiť<BENČ> ehm ...<Kozmické žiarenie> heh* BENČ siaha až do kódovania* Elmo sa pozerá na Bence<Elmo> niečo, čo by sme mali vedieť o vás a kozmické žiarenie, Ben? :)
		-- Paul Slootman

%
Zmeniť Spoločenská zmluva? BWAHAHAHAHAHAHAHAHAHAHAHA.
		-- Branden Robinson

%
<Knghtbrd> Program prijímaného signálu SIGSEGV, segmentácia poruchu.<Knghtbrd> 0x40095fb0 v memchr () z /lib/libc.so.6<Knghtbrd> (gdb) bt<Knghtbrd> # 0 0x40095fb0 v memchr () z /lib/libc.so.6<Knghtbrd> # 1 0x0 v ?? ()<Knghtbrd> No to je skutočne užitočný* Knghtbrd obchoduje gdb na pekný Ouija palube - to pomôže viac
		-- Branden Robinson

%
Všetky dobré nápady vyzerať zlé myšlienky k tým, ktorí sú porazení.
		-- Dilbert

%
RFC 882 dal bodku na .com, nie Sun Microsystems
		-- Seen on Slashdot

%
* Joeyh_ premýšľa, či linux má zamknúť, keď sa spýtate 100  spracuje na mačku celý CD-ROM
		-- Seen on Slashdot

%
<Pretzelgod> knghtbrd: Quake by mali podporovať röntgen víziu, sakra<Knghtbrd> pretzelgod: ftp://ftp.cdrom.com/pub/quake/partial_conversions/           xrated / i_am_old_enough_to_look_at_this<Knghtbrd> ... ste chcela ...<Kozmické žiarenie> haha, to je skutočný adresár
		-- Seen on Slashdot

%
<Knghtbrd> Aj Sneak TO BUN<Knghtbrd> HELP ME PRE TO šarlatán<Venom> KB: o čom to sakra hovoríš?<Knghtbrd> bwahahaha .. Je to dlhý príbeh.
		-- Seen on Slashdot

%
<WildCode> Mercury, nie je ladenie X trochu ako nájsť dokonale           bezchybnější kód v oknách ??<Mercury> WildCode: Ladenie X je ako pokuse o spustenie priamku          bludiskom.<Mercury> stačí ohýbať časopriestor tak, že rohy pohybovať          vy a nebudete mať žiadne problémy. (=:]
		-- Seen on Slashdot

%
<Miguel> `Bol ste odhlásený z vysokej energii osobného         ochranné zariadenia mailing list '<Miguel> I dont pamätať dostať sa do mailing listu
		-- Seen on Slashdot

%
<Mýtus> Začínam Spojenie odmietnuté pri pripájaní k portu 25, ktokoľvek       viem, kde tá prekliata protokolu je?<Hľa> Mýtus: /var/log/damn.log?* Hľa čuduje, čo to by vyzerať<Hľa> 18.prosince 05:32:30 blae smtpd [123]: Sakra to všetko PEKLO !!
		-- Seen on Slashdot

%
* Lasička si kladie otázku, ako hlúpy človek musí byť, aby spam alt.anonymous.messages<Knghtbrd> lasička: asi z polovice tak hlúpa, ako človek musí byť, aby ju žať.
		-- Seen on Slashdot

%
* Wolfie premýšľa, koľko debianites je potreba k zaskrutkovaniu žiarovky<Viiru> Wolfie: Niekde okolo 600? Jeden skrutku je žiarovka, a zvyšok        plameň ho robí zle.<Časť> Wolfie: je žiarovka slobodný softvér?<Tv> Môžeme hlasovať o tom, či je skrutka alebo nie?
		-- Seen on Slashdot

%
<Culus_> Sme tiež dúfajú, že sa uvoľní verziu Linuxu, kde je shell         nahradený perl do značnej miery. Pridávať sa, že existuje         Niekoľko z nás, ktorí by radi videli čistý perl platformu .. PERLOS :)* Culus_ vyzerá na v hrôze<Mstone> Culus_: na strane hore, môžete zadať skoro čokoľvek u         príkazový riadok :)
		-- Seen on Slashdot

%
<Mercury> LordHavoc: Dôvod, prečo GL má prečerpať je, pretože to je jediný          použitie polovice systému, ktorý určený pre vis.<Mercury> LordHavoc: Streľba sa v nohách.* Dabba sa pozerá na všetky tie diery po guľkách v topánkach - Sakra, veľa :)
		-- Seen on Slashdot

%
<Dabba> hehe, ja naozaj neznášam hlásení o chybách, ktoré sú ako volanie oheň       Oddelenie a hovorí: "Tam je oheň sem, poď" :)<Dabba> (a zavesí)* Dabba zabíja desiatky hlásení o chybách.
		-- Seen on Slashdot

%
<Xtifr> wow, myslím, že som len používa libtool vyriešiť problém - niekto        pomôž mi! :><Luca> xtifr, odstúpte od klávesnice
		-- Seen on Slashdot

%
<Mao> prečo trvajú na ading -Werror ...<Misty-chan> Mesa nebude zostavovať po vybalení z krabice, ak by bolo vykonané vy             chlapi;)<Knghtbrd> Uh, Mesa nekompilujú po vybalení z krabice väčšinu času.
		-- Seen on Slashdot

%
<Deek> nopcode: Nie, to nie je. Win32 postráda ekvivalent vidlice ().<Knghtbrd> deek: Windoze nie je určený pre ľudí, ktorí by mali mať prístup k           ostré predmety, teda nie fork ()<Knghtbrd> miesto, musí sa spoľahnúť na lyžicu ()
		-- Seen on Slashdot

%
<Knghtbrd> Toto písmo sa začína vyjsť pekne<Stu> Knghtbrd: Ach, tie nabúranie do ďalšej Quake písmo v vi? :)
		-- Seen on Slashdot

%
<Pv2b> oh, okrem toho, čo je najlepší prístup, ak chcem, aby zemetrasenie       Úroveň navrhnutý od existujúceho objektu?<Knghtbrd> Získajte plánik kancelárie Briana? =)<Pv2b> Knghtbrd: im vzhľadom na svoju školu.<Knghtbrd> Skvelé<Knghtbrd> To je všetko, čo potrebujeme
		-- Seen on Slashdot

%
<Knghtbrd> Windoze cement: Teraz sa CrackGuard (TM)! Nikdy sa obávať           nevzhľadné trhliny v Windoze cement znova! CrackGuard (TM) jetak silný, že celá vec bude rozpadať pred tým, než budeprasknúť. Objednajte si $ 200 upgrade verziu ešte dnes!
		-- Seen on Slashdot

%
<Doogie> cULus: moja chyba s openssh sa zdá byť stanovená v 2.5.2, ale         master beží 2.3.0<CULus> Ani spustiť<Doogie> Práve som urobil.<CULus> Vy ste ma riadiť vybudovať obrovské obrieho robota a        zničiť všetky Texase, však?
		-- Seen on Slashdot

%
<Shader> čo je zle s rjing?<Rhamphoryncus> je to lame: P<Rhamphoryncus> Nemalo by byť možné,<Rhamphoryncus> strkať granát do riti a používať to ako raketa                strelivín by nemala byť životaschopný technika: P
		-- Seen on Slashdot

%
 * Ekvivalentná kód je k dispozícii od RSA Data Security, Inc. * Tento kód bol testovaný proti tomu, a je ekvivalentná, * Okrem toho, že nie je nutné, aby zahŕňal dve stránky legalese * S každú kópiu.
		-- public domain MD5 source

%
* Knghtbrd je preč - zzz - správy budú prudko ako mokré uteráky na všetkých  ľudí, ktorí majú odcudzených ochranná známka knghtbrd preč správu<Coderjoe> ack* Coderjoe pripravuje sa brániť z mokrých správ
		-- public domain MD5 source

%
Nikdy nepodceňujte silu niekoho so zdrojovým kódom, textový editor,a ochota úplne hadice svoj systém.
		-- Rob Landley <telomerase@yahoo.com>

%
"Takže, bude Andover strana majú v hotovosti bare?""Nie, tam to zadarmo pivo.""Uh-oh, Stallmanův to bude naštvaný ..."
		-- overheard at the Bazaar, 1999

%
<Addi> Alter.net Zdá sa, že nahradiť jeden z jeho routera s cuketou.
		-- overheard at the Bazaar, 1999

%
<Mercury> Niekto to opraviť.<Zúfalstvo> spáchal<Knghtbrd> Zúfalstvo: Mercury?<Zúfalstvo> Knghtbrd: on je unavený, urobil chybu, chcel niekoho, kto by ju vrátiť späť.<Knghtbrd> Zúfalstvo: takže si ho nechal spáchal?<Zúfalstvo> Knghtbrd: No, venovaný kdekoľvek.
		-- overheard at the Bazaar, 1999

%
<Taniwha> Knghtbrd: to nie je údiť, ak je použitý<Knghtbrd> taniwha: Ako si vysvetľujete Windoze potom?<Taniwha> Knghtbrd: väčšina z nich sa používa iba ako záťaž, aby sa ubezpečil svojho          pevný disk je plný<Knghtbrd> taniwha: predradník ... Nie je to to, čo robí ponorky potopiť do           Dno oceánu?<Knghtbrd> taniwha: to by vysvetľovalo, prečo winboxes sú vždy ísť dole.
		-- overheard at the Bazaar, 1999

%
inovovať / IN žiadnom Vait / VB.: 1. Ak chcete vhodnou technológiou tretích stránkúpi, imitácia, alebo odcudzenia a integrovať do svojhode-facto monopolné-position produkt. 2. Pre zvýšenie veľkosti a zložitostiale nie v nástroji; k zníženiu kompatibility alebo interoperabilitu. 3. Ak chcetelock-out konkurenti alebo zamknúť-in užívateľom. 4. Ak chcete účtovať viac peňazí; nazvýšia ceny alebo náklady. 5. Ak chcete získať zisky z investícií v inýchpodniky, ale nie z priameho predaja produktu či služby. 6. Ak chcete potlačiť alebomanipulovať voľný trh; rozšíriť právomoc monopolu na nové trhy. 7.Vyhnúť sa zodpovednosti za previnenie činov; vystúpiť. 8. Ak chcete nákupulegislatíva, zákonodarcovia, zákonodarcovia, alebo šéfovia štátov. 9.sprostredkovávať všetky transakcie v globálnej ekonomike; k spreneveriť; kooptovať sila(Prevrat). porov inovovať, anglickej použitie (antonymum).
		-- csbruce, in a Slashdot post

%
Ohlušujúci ticho ma naučil neklásť banda mágov o raduzo svojich priateliek
		-- csbruce, in a Slashdot post

%
"Čo budeme robiť dnes večer, Bill?""Rovnaká vec, ktorú robíme každý večer Steve, snaží sa ovládnuť svet!"
		-- csbruce, in a Slashdot post

%
<Deek> To mi pripomína, že budeme musieť kúpiť pílu pre kanceláriu. "V       prípad núdze, rozbitie skla "
		-- csbruce, in a Slashdot post

%
<Knghtbrd> Je to asi polovičnej veľkosti ostatných.<Knghtbrd> Ale on má motorovú pílu.
		-- csbruce, in a Slashdot post

%
<Deek> "Držím osobné údaje GPG v uzamknutej viesť bezpečí v trezore       stráži nahnevaných burani a ich Dawgs. votrelci budú       porušované, a všetko, čo ... "
		-- csbruce, in a Slashdot post

%
<ExMachina> glQuakeIIIRendererMode (GL_TRUE)<Knghtbrd> ExMachina: nie je tá časť predĺženia, ktorá poskytuje           glDriverBugs (GL_FALSE); ?<Siigron> Knghtbrd: nie, glDriverBugs () je súčasťou EXT_help_me.<Siigron>, ktorý tiež obsahuje glMakeItWork (GL_PLEASE);
		-- csbruce, in a Slashdot post

%
< `` Erik> 18.446.744.073.709.551.616 je veľké číslo
		-- csbruce, in a Slashdot post

%
<Xavvy> je, že v skutočnosti knghtbrd?<Knghtbrd> Nie, ja som zlý podvodník!<Knghtbrd> zlé podvodník, ktorý má rád HYBRID!<Xavvy> haha<Xavvy> ok, je to on: P
		-- csbruce, in a Slashdot post

%
<| Dážď |> Aj * * milostný SWB !!<| Dážď |> Alebo stlačte 5 hovoriť s representitive ..<| Dážď |> * 5 *<| Dážď |> Tie sú prevedené, prosím držať ...<| Dážď |> ...<| Dážď |> ...<| Dážď |> Je nám ľúto, toto číslo nemôže byť dokončená za vytočí.<| Dážď |> Skontrolujte číslo a skúste to znova.
		-- csbruce, in a Slashdot post

%
<| Dážď |> #define struct únii / * veľký priestor šetrič * /
		-- csbruce, in a Slashdot post

%
<Elrik> žiadne BSD fanúšikovia?<EvilTypeGuy> Elrik: je to ťažké byť hráč a BSD fanúšikom: p
		-- csbruce, in a Slashdot post

%
<Marticus> Je tu príliš veľa krvi v mojom kofeínu systému.
		-- csbruce, in a Slashdot post

%
<SirDibos> cULus: si hore?<CULus> no
		-- csbruce, in a Slashdot post

%
<WLI> Jo, som sa pozrel na ESD a vyzeralo to druh kódu C, že      ex-žoviálny / Algol '60 kodér ktorý strávil posledných 20 rokov poskakovanie      Medzi Fortran-IV a Fortran 77, bude písať.
		-- csbruce, in a Slashdot post

%
<Nelineárny> .net je microsofts zvrátený verziu java Networked            Prostredie uglified pre windows-špecifickú kecov
		-- csbruce, in a Slashdot post

%
<Mercury> LordHavoc: Už som blázon.<Coderjoe> sakra rovno. alebo krivky, krivé, alebo čo ťa mať
		-- csbruce, in a Slashdot post

%
Unix je zrelý OS, Windows je stále ešte v plienkach a vonia zle.
		-- Rafael Skodlar <raffi@linwin.com>

%
<Midgar> Zo všetkých sterotypes o Austrálčanov, som prísť vy ste         naozaj ťažké.<Midgar> p<Krusty> budeme hádzať Koala na vás
		-- Rafael Skodlar <raffi@linwin.com>

%
<| Dážď |> * nod * Nie som rád používať Inteligentné hostitelia, sám<| Dážď |>, ako to sa spolieha na oboch vzdialeného hostiteľa a hostiteľ šikovný<| Dážď |> a príliš často ste vynechal jeden z oboch cieľov
		-- Rafael Skodlar <raffi@linwin.com>

%
Prístup SourceForge je umiestniť všetky projekty v niektorých nijaký"Open source surburbia", kde všetky domy sú podobné, len sfarby a drobné odchýlky v štýle (čo stavba plán bol použitý pre ktorýchNajmä dom) sú povolené obmedzujúcich zmlúv a miestnezákony o stavbe. Sourceforege je open-source ekvivalent zčlenenie vo filme "Nožnicovoruký Edward".
		-- Terry Lambert

%
<Vyp> Knghtbrd: IRC nezkompiluje C kód veľmi dobre;)
		-- Terry Lambert

%
* | Dážď | sa pripravuje na polygóne polievku<| Dážď |> sladký milosrdný blbosť, to funguje?* | Dážď | mdloby
		-- Terry Lambert

%
"Vzhľadom k tomu, že je to hotová vec, že ​​Microsoft bude odhadzovanie jeho XMLs ukazovateľmi na komponenty založené na Win32, to najlepšie, čo možno povedať ojeho prijatie XML je, že bude robiť to jednoduchšie pre prehliadače aaplikácie na platformách Windows porozumieť, ktoré častidokumentovať to musí ignorovať. "
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<Robert> aj pochopiť, existujú niektoré rozumné medze slobody prejavu v         ameriky, napríklad nemôžem kričať oheň do preplnenom divadle.. Ale môžem kričať oheň do divadla len s 5 alebo 6 poeple	 v tom ?
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<AAV> kávu na lačný žalúdok je celkom nasya<Knghtbrd> AAV: čas bežať do automatu pre Cheetos<AAV> Cheetos? :)
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<| Dážď |> s zdravému kódu, možno by som mohol prísť na vykresľovací :)<LordHavoc> dážď: Asi by som byť tým, kto píše pre vykreslenie<| Dážď |> no, ehm, ehm
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<| Dážď |> Knghtbrd: dovoľte mi, aby som vám umožní prístup k súborom zóny<Knghtbrd> oh bohovia - vy si uvedomiť, nikdy som hral s bind v poriadku?<| Dážď |> uhoh :)
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<F00Dave> Pozrite sa, odmieta, je to #OpenGL, nie je #GEEKSEX.
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
* TwingyAFK je nakupovanie pre 17 "plochý panel* AAV predáva kus preglejky TwingyAFK
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
Nie je to trápne, keď máte ísť do drogérie pre prístup k niektorým"Osobitnej položky", a keď ste mimo kontrolu, pokladničné na teba pozeráako: "Ja viem, čo robíš dnes večer ..."Jo, že pokladník prečítať všetky značky ... Konzervované kuracie polievku, TheraFlu,Haly, NyQuil sa bigass fľaše OJ a grapefruitový džús ... vedel,a ja som vedel, že som mal schôdzku s teevee a dole cumlík. awwwjo.
		-- Elizabeth Kirkindall

%
Vo vede sa často stáva, že vedci hovoria: "Ty vieš, že to naozajdobrý argument; môj postoj sa mýli, "a potom sa skutočne zmeníich myseľ a nikdy počuť, že starý pohľad z nich znovu. naozajurob to. Nestáva sa tak často, ako by mal, pretože vedcičlovek a zmena je niekedy bolestivé. Ale to sa stáva každý deň. Nemôžemspomenúť, kedy naposledy sa niečo také stalo v politike alebo náboženstva.
		-- Carl Sagan, 1987 CSICOP keynote address

%
<Knghtbrd> pridať GF2 / 3, značný pevný disk a 15 "plochý panel a           máte sakramentsky prenosný počítač.<Coderjoe> a GeForce dve tretiny?<Knghtbrd> Coderjoe: Áno, GeForce dve tretiny, teda akákoľvek karta od ATI.
		-- Carl Sagan, 1987 CSICOP keynote address

%
<Knghtbrd> Nintendo Prehlasuje GCN Najobľúbenejší Console Ever<Knghtbrd> Kto sú oni srandu?<Mercury> knghtbrd: Držitelia akcií?
		-- Carl Sagan, 1987 CSICOP keynote address

%
<LordHavoc> väčšina Windoze umelci nemajú schopnosť            uložiť XPM<Mercury> LordHavoc: Nemajú poznámkový blok? * G, D & R *
		-- Carl Sagan, 1987 CSICOP keynote address

%
Linux podporuje predstavu príkazového riadku alebo shell z rovnakého dôvoduže iba deti čítať knihy s obrázkami iba v nich. Jazyk, či už sa jednáAngličtina alebo niečo iné, je jediný nástroj dostatočne pružný, aby dosiahnuťdostatočne široký rozsah úloh.
		-- Bill Garrett

%
## Signoff: povstalec (razzin "frazzin" motherfu ... hlúpy DirectX ...)
		-- Bill Garrett

%
<Krogoth> Kgnghtbrd: Ja by som Ko, nevidím potrebu pravopisu doteraz<Knghtbrd> ste hovoril?
		-- Bill Garrett

%
<Knghtbrd> Radšej dal usvedčujúce veci do kódu: ahfuiovka           ikperoa edfr ade 9 enbuw ejasxleme ka Iena df4mesa<Knghtbrd> Ak možno dešifrovať, že si lepší ako ja kryptograf           am. =)
		-- Bill Garrett

%
<RCW> liiwi: printk ( "CPU0 o požiarnej \ n");
		-- Bill Garrett

%
<Elektro> môj počítač bol kedysi jedným zo stavebných kameňov skvelý          pyramída
		-- Bill Garrett

%
UPOZORNENIE: Videl niekto fajčiť bude predpokladať, že je na ohni a bude        sumárne uhasiť.
		-- Bill Garrett

%
<MARK> c ++: sila, elegancia a jednoduchosť ručný granát
		-- Bill Garrett

%
<Knghtbrd> ale jeden druh na karte a nikto na zozname je pravdepodobne lepší ako           O (n + n ** 2) na karte a O (n ** 2) na zozname.<Knghtbrd> OMG, niekto ma zastreliť.<Coderjoe2>?<Knghtbrd> Nemôžem uveriť, len som použil veľkú husacie vajcia vysvetliť, prečo my           cesta je pravdepodobne najlepšie v dlhodobom horizonte.
		-- Bill Garrett

%
<Hoponpop> môj program funguje, ak vezmem von chyby.
		-- Bill Garrett

%
<Mercury> Knghtbrd: Hej, perl má napájací pôvab a eleganciu saniach          kladivo. (=:]<| Dážď |> iste milosť a elegancie, rovnako
		-- Bill Garrett

%
<Dannys> Hit opice vyhrať $ 20 (*)!* Knghtbrd dostane svoj paličku.* Knghtbrd rastliny pevne na hlave Dannys.* Knghtbrd bude trvať jeho 20 $ teraz. = D
		-- Bill Garrett

%
<Gholam> dobre Som ohromený<Gholam> win98 podarilo núdzovo X zvnútra VMware.* Gholam tlieska.
		-- Bill Garrett

%
"Ovládače NVIDIA OpenGL sú moje" zlatý štandard ", a to bolo celkomčo som musel nahlásiť problém pre nich, a dokonca aj ich značkaNové rozšírenie pracovať ako zdokumentované, keď som prvýkrát vyskúšať. keď mámproblém na Nvidia, predpokladám, že je to moja vina. S niekto iný tovodičov, predpokladám, že je to ich vina. To sa ukázalo správne takmercelý čas."
		-- John Carmack

%
Libtool zdieľaná knižnica prenositeľnosť je len o málo viac ako uveriteľnýStroje typu perpetuum mobile. Zvlášť v systéme AIX :). "
		-- David Leimbach

%
<Overfiend> Toto je nový Overfiend, kazateľom lásky a tolerancie
		-- David Leimbach

%
<Hoponpop> rozdiel medzi NetBSD, FreeBSD, OpenBSD a ako           insider je FreeBSD je záujem začať robiť veci, aNevadí zranené ľudí, ktorí dostanú v ceste.<Hoponpop> NetBSD má záujem na zabezpečení toho, aby sa nič robiť, a           Nevadí zranené ľudí, ktorí sa snažia dosiahnuť vecí.<Hoponpop> OpenBSD má záujem o vyzerá dobre, a nemá nikoho nebolí           vo svojej vlastnej malej komunite, ale pozor všetci ostatní!
		-- David Leimbach

%
<Liiwi> áno, aký je oficiálny spôsob, ako sa buildd k opakovaniu balíček? prod        to s palicou?<Joey> prod neuro<Liiwi> s palicou?<Joey> áno.
		-- David Leimbach

%
<Knghtbrd> "... budete viac než pravdepodobné, že vidieť všetky druhy prekladače           upozornenie posúvanie na obrazovke. To je normálne a môžebude ignorovať. "<LordHavoc> Knghtbrd: je, že poznámka pripojená k nejakému M $ kódu?<Knghtbrd> Nie, to je zmienka o veľa vecí GNU.
		-- David Leimbach

%
<Hydroxid> knightbrd: od knightbrd.brain import * :)<Knghtbrd> bohmi Oh keby to bolo tak jednoduché ..<Knghtbrd> od carmack.brain dovozu OpenGL
		-- David Leimbach

%
<LIM> mmmm, multitextured šišky ....<Knghtbrd> LIM: s ovocnou náplňou?<LIM> knghtbrd: čokoládovým krémom ...
		-- David Leimbach

%
<StevenK> Tie prepisovanie častí Quake v Pythone * *?<Knghtbrd> MUAHAHAHA
		-- David Leimbach

%
## A_nick (nobody@c213-89-87-111.cm-upc.chello.se) nastúpil #python<A_nick> Ako môžem pridať nový kľúč do slovníka?<A_nick> nm<Čiarka> heh :)<Pomlčka> uvidieť riešenie problémov silu #python.
		-- David Leimbach

%
<Hop_> som mal niečo, čo by bolo, myslím, kuracie, ktorá bola potiahnutá červenou       pasta, ktorá sa zdalo, že je zložený z lúhu podľa toho, koľko z mojich       Lingo to zhoreli.<Hop_> náš kamarát, ktorý je Ind hovoril, že toto je dôvod, prečo väčšina Indov sú tenké       citujem "Neznamená to však trvať veľa z tejto potraviny, aby vám       spokojných enoguh prestať jesť. "
		-- David Leimbach

%
<Zámer> "Je to klasický presakovať-up ekonomiku s vedomím, že peniaze            je ako hnoj: To funguje najlepšie, ak ju šíriť okolo ".<Knghtbrd> Zámer: Carter korelačný: Ľudí s množstvom buď           zvyčajne cítiť vtipné<Zámer> Knghtbrd: Je SO vyhrať.
		-- David Leimbach

%
