* SynrG Notes cewa yawan sanyi tambayoyi da amsa, a  sendmail ne wadanda ba maras muhimmanci
		-- David Leimbach

%
* James zai zama mafi burge idan netgod ta sihiri iko iya dakatar da  tsãgewar ƙwãyar da fari ...* Netgod Notes Debian developers ne notoriously wuya a yaba
		-- David Leimbach

%
<Sel> bukatar taimako: na farko fakiti to my bada samun rasa :-(<Netgod> sel: dont aika na farko daya, fara da # 2
		-- David Leimbach

%
<James> cũtar da ni. Ina haka guragu na aika wani kwaro rahoton zuwa        Debian-takiya-canje-canje
		-- David Leimbach

%
Ban taba tunanin cewa zan so ga rana, inda Netscape ne free software da kumaX11 ne mallakar tajirai. Muna zaune a cikin m sau.
		-- Matt Kimball <mkimball@xmission.com>

%
<Jim> Lemme tabbatar Ina ba wasting lokaci a nan ... bcwhite zai cire      pkgs cewa havent aka gyarawa da cewa suna da fice a kwari na tsanani      "Muhimmanci". Gaskiya ko arya?<JHM> Jim: "m" ko mafi girma. Gaskiya.<Jim> Sai muka yi game da rasa ftp.debian.org da dpkg :)* Netgod zai buga dpkg - shi ne lokaci-lokaci amfani<Joey> Har yanzu muna da rpm ....
		-- Matt Kimball <mkimball@xmission.com>

%
<JHM> Yin dora ne alamar gaskiya Debian tsaye.
		-- Matt Kimball <mkimball@xmission.com>

%
<Overfiend> partycle: Na tsanani yi bukatar wani vacation daga wannan kunshin.            Na zahiri yi mafarki game da gabatar da wani wawa sabon kwaro            cikin xbase-preinst karshe dare. Wannan wani Bad ãyã.
		-- Matt Kimball <mkimball@xmission.com>

%
Rubutu ba-free software ba wani ethically istinbadi aiki, don haka idanmutanen da suka yi wannan gudu cikin matsala, shi ke mai kyau! All harkokin kasuwanci bisaa kan wadanda ba-free software kamata ya kasa, da kuma jima da mafi alhẽri.
		-- Richard Stallman

%
Microsoft DNS sabis terminates abnormally a lõkacin da ta recieves a mayar da martanizuwa DNS query da aka taba yi. Gyara Information: Run your DNSsabis a kan wani daban-daban dandamali.
		-- BugTraq

%
* Dpkg hannun stu wata babbar gilashin vbeer* Joey daukan giya daga stu, kana kuma matasa;)* Cylord daukan giya daga Joey, kana kuma bugu.* Cylord bada giya to muggles.
		-- BugTraq

%
Mun mutanen Debian GNU / Linux rarraba, domin samar da watamore cikakken tsarin aiki, kafa quality, inshora kasuwabambancin, samar da kowa bukatun kwamfuta users, ingantatsaro da kuma tsare sirri, kifar monopolistic sojojin a kwamfutasoftware masana'antu, da kuma amince da albarka 'yanci ga kanmu damu zurriyar, kada Ka rubũta kuma suka tsayar da wannan kundin tsarin mulki ga DebianGNU / Linux System.
		-- BugTraq

%
"Wannan shi ne element_data tsarin domin abubuwa wanda * element_type =FORM_TYPE_SELECT_ONE, FORM_TYPE_SELECT_MULT. * / / * * Nesting zurfida kuma zurfi, wuya da wuya, ya tafi, ya tafi, oh, OH, OHHHHH !! * Yi hakuri, ya samukwashe can. * / Struct lo_FormElementOptionData_struct. "
		-- Mozilla source code

%
Duk da yake shekara ta 2000 (y2k) matsalar ba wani batun a gare mu, duk Linuximplementations zai yi tasiri da shekara 2038 (y2.038k) batu. TheDebian Project ta jajirce wajen yin aiki tare da masana'antu a kan wannan batukuma za mu yi mu full da tsare-tsaren da kuma dabarun posted by na farko kwatana 2020.
		-- Mozilla source code

%
... Ina ne Stac Electronics lõkacin Microsoft ƙirƙira Doublespace? inakasance Xerox da Apple lõkacin Microsoft ƙirƙira Gui? Ina ne Apple taQuickTime lõkacin Microsoft ƙirƙira Video for Windows? Ina ne SpyglassInc. ta Mosaic lõkacin Microsoft ƙirƙira Internet Explorer? Ina ne Suna lõkacin da Microsoft ƙirƙira Java?
		-- Mozilla source code

%
Yi hakuri, idan da wadannan sauti combative da ɓarna, sirri,amma shi ke ta general style. - Ian Jackson
		-- Mozilla source code

%
"My babbar matsalar da RH (kuma musamman RH contrib kunshe-kunshe) shi ne cewasu ba su da wani abu kamar mu da manufofin. Shi ke daya daga cikin manyan dalilan dadalilin da ya sa su kunshe-kunshe ne don haka crappy kuma karye. Debian yana da aikin gayyagefen gina rarraba ƙasa don tarar art. "
		-- Mozilla source code

%
"Slackware masu amfani ba kome. A gwaninta, slackware users neko dai clueless newbies suka yi wahala har ma da kwalta, ko suRABiD yi-da-yourselfers wanda ba zai shigar da wani ta pre-harhadabinary har idan suka biya su yi shi. "
		-- Mozilla source code

%
<XinkeT> "Ya Ubangiji Ka ba ni da ni'ima yarda da abin da na iya ba         canja, da ƙarfin hali da canja abin da na iya, da hikima         boye gawawwakin mutane waɗanda na ya kashe saboda sun         ji haushi da ni a kashe. "
		-- Mozilla source code

%
* Duhu ya canza topic a tashar #debian zuwa: Daga baya yau da dare: Bayan  watanni da hankali refrigeration, Debian 2.0 ne a karshe sanyi isa ya  release.
		-- Mozilla source code

%
Na zauna dariya snidely zuwa cikin rubutu, sai sun nuna mini wani PC GudunLinux. Kuma oh! Shi ne kamar yadda yake cikin sammai bude, kuma Allah ya mika saukar da wataabokin ciniki-gefe OS kyau sosai, don haka m, kuma haka m cewa miliyanMicrosoft developers ba zai iya ƙirƙira shi lalle dã sunã da wata da ɗarishekaru da kuma dubu dora akwakun na jolt Cola.
		-- LAN Times

%
Na zauna dariya snidely zuwa cikin rubutu, sai sun nuna mini wani PC GudunLinux .... Kuma yasa wannan PC shaƙa? Ashe shi yi i'ina? Aikata shi, ko da sau daya,cewa wannan shirin ya yi wani ba bisa doka ba aiki da kuma dole ne a rufesaukar? No. Kuma wannan shi ne kawai a kan abokin ciniki.
		-- LAN Times

%
"Ina ganin cewa, mafi yawan Debian developers ne m" karfi so "mutanetare da mai girma mataki na hankali da kuma wani babban matakin da sha'awar ga abin dasũ ba su sani na da muhimmanci ci gaba da Debian tsarin. "
		-- Bill Leach

%
"A gaskiya, kadai rarraba Linux Na taba amfani da ya wuce narootshell gwajin daga cikin akwatin (doka rootshell a lokacin da dist nefito da kuma ganin idan za ka iya karya da OS da rubutun daga can) anDebian. "
		-- seen on the Linux security-audit mailing list

%
* Culus ji tsõron Perl - harshen da ba na tilas ba kurakurai
		-- seen on the Linux security-audit mailing list

%
<Stu> kamata ka ji tsoro ka yi amfani da KDE saboda RMS yiwuwa zo to your      gidan da manne ka duba da gatari ko wani abu :)
		-- seen on the Linux security-audit mailing list

%
"Kuma i zahiri kamar Debian 2.0 cewa da yawa i gaba daya revamped datsoho jeri na Linux tsarin mu kamfanin sayar da reinstalled wanina Linux tsarin a cikin ofishin da kuma a nan a gida .. "
		-- seen on the Linux security-audit mailing list

%
<Davide> yadda fadan a siyasa sanda siyasa da siyasa domin canza         'yan sanda sanda siyasa
		-- seen on the Linux security-audit mailing list

%
<M> "Bari mu samar da Linux Standard Linux Standardization Association        Board. Manufar wannan jirgin zai zama su ne na daidai Linux        Standardization Organizations. "
		-- seen on the Linux security-audit mailing list

%
<Overfiend> Kada ka zo kira a gare ni game da "30 minti tattara" !! I            da gina X Uphill biyu hanyoyi! A cikin snow! tare da danda            feet! Kuma ba mu da compilers! Mun ya fassara            C code to mnemonics kanmu!<Overfiend> Kuma ina 18 kafin mu ma yana da assemblers!
		-- seen on the Linux security-audit mailing list

%
NEW YORK (CNN) - Internet masu amfani da suka kashe har da 'yan sa'o'i a mako onlinea gida fuskanci mafi girma matakan ciki da kuma Loneliness fiye da idansuka yi amfani da kwamfuta na cibiyar sadarwa kasa akai-akai, The New York Timesruwaito Lahadi. A sakamakon ... mamaki biyu masu bincike da kumatallafawa, wanda ya hada Intel hukuma, Hewlett Packard, AT & T Research kumaApple Computer.
		-- seen on the Linux security-audit mailing list

%
"Abin da aka karin, duk da haka, shi ne general layout da hadewa datsarin. Debian ne da gaske m Linux rarraba. mai girma kulawa daaka dauka a cikin shirye-shiryen da kunshe-kunshe da jeri a cikintsarin. The aras yawan kunshe-kunshe samuwa ne kuma m .... "
		-- seen on the Linux security-audit mailing list

%
Debian Linux ne mai m, m samfur, da fatan yardarsa zuwaamfani da. Shi ne kuma mai girma su shảfe da Debian gama,wanda friendliness da ruhu tuna farkon zamanin da yanar-gizo da kumada ji na gaskiya, da kuma duniya hadin kai.
		-- seen on the Linux security-audit mailing list

%
<Ambaliyar> zan iya rubuta wani UNIX-kamar kwaya a Perl?
		-- seen on the Linux security-audit mailing list

%
<Ambaliyar> netgod: Ina da wani "Tir tu" T-shirt (w / Intel logo) .. a kan        baya shi ya ce: "A lokacin da fyaucewa ta zo, za ku yi tushen?"
		-- seen on the Linux security-audit mailing list

%
<Zarkov> "NT 5.0. Dukan kwari da kuma sau goma da code size!"
		-- seen on the Linux security-audit mailing list

%
<Culus> akwai 150 Meg a / tmp dir! Dear Ubangiji
		-- seen on the Linux security-audit mailing list

%
<Toor> netgod: abin da kike da shi a your kwaya ??? The harhada source for       tuki a sarari motar ???<Spoo> lokaci don yin wani zip fitar your floppy drive to. idan kwaya       ba ya fit a, da kwaya ne mai AI
		-- seen on the Linux security-audit mailing list

%
Yanzu zan iya karshe bayyana ga kowa da kowa da ya sa na yi wannan. I just samu $ 7 darajafree stuff for aiki a kan Debian!
		-- seen on the Linux security-audit mailing list

%
<Ultima> netgod: My kalkuleta yana more rajista fiye da x86, kuma
		-- thats- sad

%
* Boren tosses matlab fadin dakin da fatan shi karya a cikin wani lamba  aproaching iyaka peices
		-- thats- sad

%
"... Sai ya mai yawa fiye da na yi tunani da aka faruwa a, da yawa saurifiye da NT. Idan m gudun ƙaruwa da ake yi wa uwar garken na karsherelease, Oracle da yake faruwa a iya goge su ass da SQL Server damika shi a mayar M $ yayin da Oracle admins ... ƙaura su databasesbisa ga Linux! "
		-- thats- sad

%
Duniya mamayar, ba shakka. Kuma wahala sanye mace. Wanda ya kula idanda ashirin a kasa? - Linus Torvalds
		-- thats- sad

%
<Flav> Win 98 qwaqwalwa ne qwarai edition: Za mu gaya muku, inda kana za gobe
		-- thats- sad

%
<Zpx> yana da ban mamaki yadda "ba-karya" Debian ne idan aka kwatanta da ku yi rauni, kuma RH
		-- thats- sad

%
<M> "Hey, Ina daga wannan shiri da ake kira Debian ... ka ji shi?       Your name ya zama alama a kan wani gungu na mu kaya. "
		-- thats- sad

%
"A taron na a percieved kasawa na aikin shugabanci #debian nekarfafuwa ya dauki m kuma descisive mataki don gyara kasawa,ciki har da ta bai iyakance don korar jami'an apointing sabon jami'anda kullum waxansu ikon "
		-- proposed amendment to Debian Constitution

%
<Overfiend> muna kira 2.2 _POTATO_ ??
		-- proposed amendment to Debian Constitution

%
<SirDibos> bai Johnie Ingram rataya fita a nan a kan IRC?
		-- proposed amendment to Debian Constitution

%
* Twilight1 za su rataya da Mozilla beanie dinosaur a effigy idan  Netscape sayar da-fita a da yawa Of Hasara ..
		-- proposed amendment to Debian Constitution

%
<Lux> idan macOS ne ga kwamfuta jahilci, sa'an nan windoze ne ga      kwamfuta masochists
		-- proposed amendment to Debian Constitution

%
<M> Culus: Gina biyar mita-high replica na Empire State       Gina tare kilif na rike takarda tana da ban sha'awa. Yin shi rufe musu idanu ne       eleet.
		-- proposed amendment to Debian Constitution

%
Zan iya kawai ga shi yanzu: gabatarwa-ta'addanci ;-)        - Manojhaha! i gabatar da manoj.
		-- seeS

%
<JHM> Ko ta yaya zan iya samun karin daraja 14 year old Debian developers fiye da     14 year old Certified Microsoft serfs.
		-- seeS

%
<Culus> Ben: Shin, ba ka solumly rantsuwa a karanta ka Debian email sau daya a rana, kuma        ba yarda mutane su yi tunanin kana MIA?<Ben> Culus: i yin haka rantsuwa
		-- seeS

%
"Ina mamaki idan wannan shi ne na farko tsarin mulki a tarihin 'yan adaminda kana da yin lissafi a square tushen domin sanin idan wani motsiwuce. :-) "
		-- Seen on Slashdot

%
Wannan shi ne bayani a Debian matsalar .. kuma tun kadai real hanyadon ƙirƙirar more dangi na developers ne da 'ya'ya, muna bukatar karinjima'i! Yana da wani dogon lokaci zuba jari ... yana da aiki kanta da kegamsarwa!
		-- Craig Brozefsky

%
<Marcus> dunham: Za ka san yadda za real lambobin suna gina daga m         lambobin da daidaitawa ajujuwa convergent jerin?<Dunham> Marcus: a.
		-- Craig Brozefsky

%
<Culus> "Hello?" "Hi baybee" "Ashe, kai Johnie Ingram?" "Domin ku zan zama        kowa "" Ermm .. Kuna sayar slink CD ta? "" Ina son slinkies "
		-- Craig Brozefsky

%
<Overfiend> xhost + localhost ya kamata kawai a yi da mutanen da suka yi            fenti da sunan mai masauki da kuma tushen kalmar sirri a kan wani babbar hanyar            ƙetare haddi.
		-- Craig Brozefsky

%
<JHM> AIX - da Unix daga sararin samaniya, inda Spock yana da gemu.
		-- Craig Brozefsky

%
<Knghtbrd> Nazarin tabbatar da cewa binciken da ya haddasa ciwon daji a 43% na awon           berayen<CQ> knghtbrd- yeah, amma 78% na wadanda statistics ne a kashe ta 52% ...
		-- Craig Brozefsky

%
<Stu> dace:! Kwari<Dace>! Kwari ne wawa<Dpkg> dace: su ne wawa? abin da ke cewa?<Dace> dpkg: ban sani ba<Dpkg> dace: Beauty da yake a cikin ido na giya mariƙin ...<Dace> i riga da shi ta wannan hanya, dpkg.
		-- Craig Brozefsky

%
<Muggles> Ina kokarin shawo wasu netcom admins na sani maida          to Debian daga RH, netgod, amma sun kasance tsine m<Muggles> dalilin da ya sa RH users haka tsine wa m gangarawa?<Jira> yana da hat
		-- Craig Brozefsky

%
<Doogie> Debian - All da iko, ba tare da wauta hat.
		-- Craig Brozefsky

%
Yaya mutane da yawa watanni za mu zama a baya su Redhat] da glibcsaki? "
		-- Jim Pick, 8 months before Debian 2.0 is finally released

%
Dalilin da ciwon aikawasiku lists maimakon ciwon Majalisun Tattaunawa nesanya wani shãmaki a shigarwa da kare lists da masu amfani dagamamayewa da general m hordes.
		-- Ian Jackson

%
Yawancin mu jin cewa marketing iri ne kamar hatsari makami - ajiye'Em unloaded kuma kulle a cikin wani kabad, da kuma kawai fitar da su daga lokacin dakana bukatar su yi aiki.
		-- Craig Sanders

%
<BenC> cerb: mu shiga ka ka Debian-yaki a matsayin GABATARWA<BenC> cerb: list dokoki ne, 1) ba nice imel, 2) ba rokon gafara
		-- Craig Sanders

%
<Teknix> gida Telco ya yarda cewa wani "goyon baya a cikin wani         button a kan wani canji "kuma ya dauki dukan ATM cibiyar saukar<Netgod> fatan yanzu magudanar an tsara mafi alhẽri, don haka "cibiyar         off "swtich ne a baya
		-- Craig Sanders

%
<Overfiend> Thunder-: lokacin da ka samu {MessagesLikeThisFromYourHardDrive}<Overfiend> Thunder-: shi dai wajen {TheDriverIsScrewy}<Overfiend> ko<Overfiend> {YourDriveIsFlakingOut BackUpYourDataBeforeIt'sTooLate            PrayToGod}
		-- Craig Sanders

%
<Dace> an ce cewa redhat ne abu Marc Ewing sa a kan      kansa.
		-- Craig Sanders

%
<MrCurious> ta ikon greyskull<MrCurious> wani gaya mini ban sanya<Sopwith> mrcurious: * .debian.org, * .novare.net<PhilX> * .debian.org. wanda ke madalla.
		-- Seen on LinuxNet #linux

%
"Menene wannan ya gaya mini? Wancan idan Microsoft su ne na karshe softwarekamfanin ragu a duniya, 13% na US yawan za a scouringgareji tallace-tallace & lumanar ga tsohon TRS-80s, CPM inji & Apple] [ 's daza su saya Microsoft. Wannan ba daidai a ringing yarda. "
		-- Seen on Slashdot

%
"Bruce McKinney, marubucin na hardcore Kayayyakin Basic, ya sanar da cewaya ke ciyar da sama da VB kuma ba za a rubuta a 3rd edition na littafinsa. TheMafi quote ne a karshen: 'Ba na bukatar a harshen tsara da a mayar da hankalikungiyar '. "
		-- Seen on Slashdot

%
<Cylord> Za ta zama yarda da Debian siyasa idan muka saka a crontab         by default cikin dankalin turawa, wanda i-mel bill.gates@microsoft.com         kowace safiya da wani email wanda karanta, "Kada ku damu, Linux ne mai         fad ... "
		-- Seen on Slashdot

%
* Overfiend yana tunani yin wani NMU na asclock, a cikin abin da ya kawai ya canjãwa  da Extended description to "Idan ka tanƙwara kan kuma sa ka kai tsakanin  your kafafu, za ka iya karanta lokaci kashe your assclock. "<Doogie> Overfiend: je ka kwanta.
		-- Seen on Slashdot

%
<Reed> Yana da muhimmanci a lura da cewa na farko da dalilin da Roman Empire       kasa shi ne cewa ba su da manufar sifili ... haka ba su iya ba       gwada nasara ko rashin cin nasara da C shirye-shirye.
		-- Seen on Slashdot

%
Tun lokacin da na da manufar Debian kasance ga kwantad da hankali da bukatun nataro na unskilled masu amfani? - Steve Guntu
		-- Seen on Slashdot

%
<Joeyh> netgod: er, su ne wadannan 2.2.0 kunshe-kunshe 2.0.0pre9 ko kina da        kai tsaye line tare da abũbuwan bautãwa?<Netgod> joeyh: i da kai tsaye line
		-- Seen on Slashdot

%
<_Anarchy_> Argh .. wanda ke bada fitar da takarda bags 8)
		-- Seen on Slashdot

%
<M> kowa a kusa?<Flav> babu, muna dukan sababbu polygons
		-- Seen on Slashdot

%
<Culus> OH MY ALLAH BA A bazuwar QUOTE Generator<Netgod> lalle ne, kai didnt zaton yana tsaye? yadda gurgu zai kasance? :-)
		-- Seen on Slashdot

%
Mere rashin wanzuwa ne a m uzuri ga furta wani abu unseeable. ka* Iya * ga dodo. Za ka yi kawai ya dubi a kan hanya.
		-- John Hasler

%
<Chalky> GCC ne mafi kwampreso kullum ported to Linux. shi iya juya         12MB na kwaya source (kuma da ke .debbed) a cikin wani 500k kwaya
		-- John Hasler

%
<Manoj> I * kamar * kaza
		-- John Hasler

%
 [] DOGBERT [2] Richard STALLMAN [3] Buffy Summers [1] MANOJ SRIVASTAVA [4] Babu na sama
		-- Debian Project Leader 1999 ballot

%
<Oryn> kowa sani idan akwai wani version of dpkg for redhat?
		-- Debian Project Leader 1999 ballot

%
acme-igwa (3.1415) m. gaggawa = low  * Added aminci su hana sadarwarka dismemberment, rufe: kwaro # 98765,    kwaro # 98713, # 98714.  * Added manpage. rufe: # 98725.
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
! Netgod: *! lokaci kwari lokacin youre amfani Linux! Doogie: *! yeah, iyaka madaukai a 5 seconds.! Teknix: *! Ya kowa sake gwada abin da 2.2.x?! Netgod: *! yeah, 4 seconds yanzu
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
* Duhu gaishe liw da karamin yellow rana.* Liw sumbanta kwãɗi, gani shi fasalin wata kyakkyawar nerd  girl, daukan ta fita zuwa ice cream, da kuma na zaune da farin ciki har abada, bayan  tare da ita<M> liw: Umm yana da latti to suna da rana baya?
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
* Culus tunani ya kamata mu je ciniki shows da kuma ganin yadda mutane da yawa da muke  iya kashe ta amai Debian CDs a gare su
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<M> "Na'am, your daraja, ina da RSA boye-boye code tattood on my        azzakari. Shin, in nũna juri? "
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Knghtbrd> ku mutane ne duk mahaukaci.<Joey> jarumi: tabbata, cewa dalilin da ya sa muke aiki a kan Debian.<JHM> Knghtbrd: samu a touch tare da ciki nutcase.
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Culus> Saens nuna babu kasa da 3 TCP / IP kwari a 2.2.3
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Mercury> alexsh: Ku / SOSAI / cairful, kana iya, idan ka m, soya your          motherboards ..<Knghtbrd> Mercury - sauti kamar fun
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<Rcw> duhu: caldera?<Knghtbrd> rcw - wanda ke ba a rarraba, yana da la'ana<Rcw> Knghtbrd: yana da wani la'anta rarraba
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
Software ne kamar jima'i, yana da mafi alhẽri a lõkacin da ta ke free. - Linus Torvalds
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
<M> Knghtbrd: Muna da kuri'a na whatevers.<Knghtbrd> duhu - A Debian? Jahannama yeah mu yi!
		-- Wile E. Coyote <genius@debian.org>  Sun, 31 Jan 1999 07:49:57 -0600

%
Na aikata shi kawai don piss ka kashe. :-P
		-- Branden Robinson in a message to debian-devel

%
The software da ake bukata Win95 ko mafi alhẽri, don haka sai na shigar Linux.
		-- Branden Robinson in a message to debian-devel

%
10) babu wani 10, amma busa kamar nice number :)
		-- Wichert Akkerman

%
Eric Raymond: Ina son in rayuwa a duniya da inda software ba tsotse.Richard Stallman: Duk wani software da cewa ba free tsotsa.Linus Torvalds: Ina sha'awar free giya.Richard Stallman: Wannan lafiya, muddin ba ni da sha da shi. I                   ba na son giya.
		-- LinuxWorld Expo panel, 4 March 1999

%
Ba ni da wani matakin-gangarawa mutum ... - Bruce Perens
		-- LinuxWorld Expo panel, 4 March 1999

%
Kaina, ina ba sau da yawa magana game da zamantakewa mai kyau, domin a lokacin da na ji wasumutane magana game da zamantakewa mai kyau, shi ke lokacin da na kai ga ta revolver.
		-- Eric Raymond

%
Idan muna son wani abu mai kyau ka sami haife shi a watanni tara, to, jima'i yafaru. Muna so a yi irin na jima'i da yake yarda da kuma fun duka biyumutane, ba da irin inda wani yana yin ci da gumi. Bari mu samu wasu giciyehadi, amma ba wani ya yin ci da gumi.
		-- Larry Wall

%
Dukanmu mun san Linux ne mai girma ... shi ya aikata iyaka madaukai a 5 seconds.
		-- Linus Torvalds

%
YES! YES! YES! Oh, YES! (Ooops, na sauti kamar Meg Ryan ;-)
		-- Ian Nandhra

%
<Knghtbrd> Idan na fara rubuta makala game Free Software for slashdot,           don Allah harba ni.
		-- Ian Nandhra

%
<RoboHak> Hmm, abincin rana ya sauti kamar mai kyau ra'ayin<Knghtbrd> zai dandana kamar mai kyau ra'ayin ma
		-- Ian Nandhra

%
p.s. - Ina game * wannan * kusa yanã gudãna a kusa a cikin uwar garken daki maibiyu daga aron kusa cutters, da kuma babban katako mallet, dariya kamar maniac dayankan kome i iya shige tsawar cutters kusa. kuma whacking cewada zan iya ba. don haka idan i ze Semi-incoherent, ko kawai gaske * gaske * ma sau, don Allah yi mini gãfara. danniya ba wani kyakkyawan abu. }. P
		-- Phillip R. Jaenke

%
Kowane kamfanin gunaguni game Microsoft ta kasuwanci ne kawai aya tashi daji. Suka kama kyakkyawa da kuma jin warin m. Da zarar wani m kamfanin dethronesMicrosoft za su zubar da petals to bijirar da ƙayayuwa a ƙasa. Aƙaya da wani sunan za m da yawa.
		-- Phillip R. Jaenke

%
Wani abu dole ne a yiWannan wani abu neSaboda haka, wannan dole ne a yi
		-- The Thatcherite Syllogism

%
<Knghtbrd> xtifr - hattara da james a lõkacin da ya ke kashe wa magani =>
		-- The Thatcherite Syllogism

%
Rashin tunani, lalle zã zama downfall mutãne, kuma amma wa ya kula?
		-- The Thatcherite Syllogism

%
Kada rashin sanin cikakken farashi da ikon mutum wawanci.
		-- Robert A. Heinlein

%
Gold, n .:  A m malleable karfe gwada wanda bai isa a rarraba. An mined  zurfi, a cikin ƙasa da matalauta waɗanda suka to ba da ita ga m mutanen da suka nan da nan  rufe shi a cikin ƙasa a cikin babban kurkuku, ko da yake na zinariya bai yi  wani abu a gare su.
		-- Mike Harding, "The Armchair Anarchist's Almanac"

%
* Lilo yanzu ya furta OPN a rumfa zafi a cikin ass :)
		-- Mike Harding, "The Armchair Anarchist's Almanac"

%
"Su ne duka harkokin kasuwanci - idan ka ba su da isasshen kudi, Inatabbata za su yi dukan abin da Jahannama ka tambaye: -> "
		-- David Welton

%
"Kana da dama ba su zama wani dubura. Idan ka daina cewa damaduk abin da ka ce, kuma suka aikata a nan za a gudanar da ku. Idan ba za ka iyaiya daina kasancewa wani dubura to wani za a nada shuranaku outta a nan. "
		-- Your rights as an irc addict

%
* Simunye ne don haka m tana da nata uwãyensu gene ta<Dellaran> muku mafi alhẽri ba su mayar da ita kuskure da su!
		-- Your rights as an irc addict

%
<Iambe> conning mafi intellegent mutane a duniya ba sauki
		-- Your rights as an irc addict

%
California, n .:    Daga Latin "calor", ma'ana "zafi" (kamar yadda a cikin Turanci "kalori" koMutanen Espanya "caliente"). da kuma "fornia" for "jima'i" ko"Fasikanci." Saboda haka: Tierra de California, "ƙasar zafi jima'i."
		-- Ed Moran

%
* Caytln mare Lisa<Caytln> catfight: P<LisaHere> Watch ta girl, ina son cewa.<LisaHere> :)<Caytln> Figures: D
		-- Ed Moran

%
<MFGolfBal> rit / ara: Akwai wani abu da gaske demented game UNIX            tufafi ...
		-- Ed Moran

%
The X Window System:  A misali UNIX zana muhalli. Da Linux, wannan shi ne kullum  XFree86 (http://www.xfree86.org). Za ka iya kira shi X, XFree, da X  Window System, XF86, ko da rundunar sauran abubuwa. Kira da shi 'XWindows' da kuma  wani zai smack ku kuma za ku yi cancanci da shi.
		-- Ed Moran

%
<Knghtbrd> "The kudin haraji ne offline." "Ina rerouting ko           sakandare couplings. Idan muka sake tsara a layi da lokaci da yawa da muke           ya kamata su iya amfani da jini inductor matrix da hannu           kaddamar da wani sabon cheesy spinoff jerin. "* ShadwDrgn waccan magana<Phase> ka bar ta manifolds kadai<Phase>!
		-- Ed Moran

%
* Turken zaton kananan yara ba su da cikakken kyakkyawa ... especialyy lõkacin  sun yi wani elses.
		-- Ed Moran

%
* Overfiend waccan magana<Overfiend> Netscape tsotsa.<Overfiend> Yana da wani gidan katunan Allaha a kan gado na yashi mai motsawa.<Jira> a lokacin wani girgizar kasa<Overfiend> a cikin wani babban hadari
		-- Ed Moran

%
<SilverStr> Mai jarida xa'a ne oxymoron, da yawa kamar mahaukatan jatan lande da            Microsoft Works.<MonkAway> ba a ma maganar NT Tsaro
		-- Ed Moran

%
<Silvrbear> Oxymorons? Na ga daya jiya - ƙasida on "Taco Bell            Sinadirai Information "
		-- Ed Moran

%
* Knghtbrd unleashes biyu na biyu barreled snurf bindigogi da kuma maida hankali ne akan  jesus da snurf darts<Jesus> meany: P
		-- Ed Moran

%
<Jgoerzen> doogie: ku sauti sosai m :-)<Knghtbrd> jgoerzen - yake.* Doogie bops Knghtbrd<Knghtbrd> gani? Resorting to tashin hankali = D
		-- Ed Moran

%
Na kuma kasance wata babbar Unix fan taba tun lokacin da na fahimci cewa kungiyar SCO da aka baUnix. - Dennis Baker
		-- Ed Moran

%
<Dracus> Ctrl + Option + umurnin + P + R<Knghtbrd> dracus - YE abũbuwan bautawarku. Wannan ya fi muni da EMACS!<LauraDax> hehehehe<Dracus> kada ka tambaye abin da ya aikata: P
		-- Ed Moran

%
<Iambe> kun kasance ba a nutcase<Knghtbrd> Ka fili ba su sani ba ni da kyau isa yet. =>
		-- Ed Moran

%
* AJ zaton Kb ^ Zzz kamata ya tara daban-daban abubuwa to mafarki game da fiye da   general shawarwari da kuma siyasa canje-canje.<Kb ^ Zzz> AJ - gaya mani game da shi, wannan shi ne a Bad Sign
		-- Ed Moran

%
<Crow_> Hmm, akwai wata --now-dammit zaɓi don exim?
		-- Ed Moran

%
<DarthVadr> Kira: shiga DARK gefe, MATASA DAYA.<Kira> Anakin, I * ni * duhu gefe.
		-- Ed Moran

%
<Netgod> Feanor: u da wani ra'ayin na zurfin da stupidty na american doka
		-- Ed Moran

%
Duk wanda tsaye a waje a tsakiyar hanya kama kade a titi a gare ni.
		-- Linus Torvalds

%
<Lilo> "PLEASE Mutunta ilimi HAKKOKIN!"<Lilo> "Don Allah nuna hankali." ;)
		-- Linus Torvalds

%
<Knghtbrd> Feanor - lasisi al'amurran da suka shafi suna da muhimmanci. Idan ba mu duba mu           jakai yanzu, wani ya za zo da ciji mu daga baya ...
		-- Linus Torvalds

%
"Yanzu za mu yi su kashe ka."
		-- Linus Torvalds

%
* Knghtbrd iya riga ganin: "Subject: [MANUFAR TO SHIRI da shawara   Jerawa OF BUG Rahoton] Typos a manufofin daftarin aiki "
		-- Linus Torvalds

%
<Netgod> heh Thats a batattu hanyar, kamar daidai pronounciation na         "Kayan ado"<Netgod> ba shi :-)<Sage> kuma daidai haruffan "launi" :)<BenC> heh<Sage> kuma aluminum<BenC> ko makaman nukiliya<Sage> kake threating ni yankee?<Sage> kawai hanyar da ba mu da bam ...<BenC> baya kashe ya yellow ciki
		-- Linus Torvalds

%
<LauraDax>! Ganin Allah<Tabi-> LauraDax, ba na tuna ganin "Allah"
		-- Linus Torvalds

%
<Kira> mai m yaki inda ka tafi ba da dakarun kasashen waje hanci jobs?
		-- Linus Torvalds

%
<Xtifr> Athena Desktop muhalli! A cikin zukãtanku, ku * sani * yana da        yancin ya zabi! :)* Knghtbrd THWAPS xtifr
		-- Linus Torvalds

%
<Knghtbrd> Shaleh - ƙazantu ne kawai m.<Jira> heh, ƙazantu ne mai sanyi<Knghtbrd> jira - kuma m.<Jira> a, m kuma
		-- Linus Torvalds

%
<Xtifr> kai tsaye kwakwalwa implants :)<Knghtbrd> xtifr - yah, to, ta yin amfani da kwakwalwa zai zahiri bukatar wasu           daga cikin wadannan idiots tunani!<Knghtbrd>;>
		-- Linus Torvalds

%
<Knghtbrd> Overfiend - BTW, bayan mun gano X daukan duk 1.4 gigs           gina, ku shirye yarda cewa X ne bloatware? =><Overfiend> KB: akwai 16 1/2 minti rata a amsa<ACF> knghtbrd: shaida wanzu cewa X ne kawai * 2nd * m windowing      tsarin;)
		-- Linus Torvalds

%
<Liw> tsine, da m linzamin kwamfuta motsi fara yawanci bayan da na yi amfani da      maballin linzamin kwamfuta<Wichert> kada ka yi amfani da wata linzamin kwamfuta button to :)<Liw> yeah, dama :)
		-- Linus Torvalds

%
<Knghtbrd> ka sani, Linux bukatar wani dandali game starring Tux<Knghtbrd> kamar Super Marioish, amma tare da Tux da abubuwa kamar kadan cyber           kwari da kuma borgs da kuma cewa irin abu ...<Knghtbrd> Kuma ka yi tsalle da billgatus da kuma buga kewayawa don sauke shi           a cikin lawa, sa'an nan ka ga wasu Guy cewa ya dubi kamar RMS           ko wani ya ce "Na gode domin ceto Sinawan da ni Tux, amma Linus           Torvalds ne a wani sansani. "
		-- Linus Torvalds

%
<Thoth_> Yeah, da cewa shi ya sa shi ke ƙidaya 2.3.1 ... yana da wadanda mu         wanda miss NT-kamar uptimes
		-- Linus Torvalds

%
<Shinobi> Akwai m abubuwa fiye da Perl .... ASP zo hankali
		-- Linus Torvalds

%
* M2 stares a duba ... shi ya dubi kamar hamburger ...<Knghtbrd> m2 - shi ke da mummunan ãyã
		-- Linus Torvalds

%
<Knghtbrd> bar shi a manoj kira procmail "puny"
		-- Linus Torvalds

%
<Crow-> Manoj: da kyau, i Cant fahimta kaya kamar "s / 3 # $% ^% {]] [@ f245}"<Manoj> Crow: Abin da ya ba quite shari'a ;-)<Knghtbrd> Manoj - ta yaya za daya yi "s / 3 # $% ^% {]] [@ f245}" shari'a           ta wata hanya? (Da abin da zai yi? Hehe)<Manoj> Knghtbrd: Kana bukatar ka gama da s /// magana.<Knghtbrd> oh, shi ne cewa duk?
		-- Linus Torvalds

%
<Kira> Ada, kadai harshen rubuta milspec.<Mikster> <shudder>
		-- Linus Torvalds

%
<BenC> -include ../../debian/el33t.h<BenC> sendmail ginawa ... m BBC name :)<Isildur> hahaha* Netgod laffs<Netgod> BenC: iya u gaya i amfani da su kula da sendmail? : P<BenC> heh :)
		-- Linus Torvalds

%
<Phase> babu ... Na musn't da wani more kofi !!! ;)<Simunye> tabbata yu yi Phase :)<Phase> kana son ni bouncing kashe rufi?<Simunye> yesh :)<Kira_> bouncing kashe rufi ne gewd<Phase> ok, abin da yake a wauta tambaya<Kira_> shi ke splatting a kasa shi ke da matsala.
		-- Linus Torvalds

%
<Kensey> RMS ga shugaban kasar ???<RelDrgn> ... ko ESR, ya so wani sabon aiki;)
		-- Linus Torvalds

%
Oh ba, ba kuma.
		-- Manoj Srivastava

%
<Knghtbrd> Hakika, RMS ne m, ba na yi musu wannan. Zan ma ce           da ya ke a sarauta zafi a cikin ass mafi yawan lokaci. Amma da ya ke           har yanzu more sau da yawa dama fiye da ba, kuma ya cancanci wata matakin           bashi da girmama aikinsa. Ba za mu kasance a nan yau           ba tare da shi.
		-- Manoj Srivastava

%
<Jira> gobe za a yi babban hargitsi a cikin ma'aikata
		-- May 18, 1999

%
Ni dyslexic na Borg. Yi a yi your ass laminated.
		-- May 18, 1999

%
<NeonKttn> ina da wani aboki tsaya mini a cikin ta kabad lokacin in black beacuse I           ba zai yi imani da cewa ta saurayi san game da wasan share fage ...<NeonKttn> I shoulda kawo popcorn. :)
		-- May 18, 1999

%
<Knghtbrd> hardcopy ne ga wussies<Topher> kwamfuta shirin listings .... gaba, a HardCopy
		-- May 18, 1999

%
<Kceee ^> I ƙi users<Knghtbrd> ku sauti kamar sysadmin riga!
		-- May 18, 1999

%
<Change_m2> Will Linux kullum cimma sliced ​​gurasa a matsayin # 1 nasara            'yan adam?
		-- May 18, 1999

%
<Aph> manoj yake faruwa kwayoyi a kan kwaro kayyade jihadi! woo woo!<Knghtbrd> manoj tafi kwayoyi dogon lokaci da suka wuce. amma kwaro kayyade ne m =>
		-- May 18, 1999

%
<Rcw> wadanda a fili-kwayoyin-kamar multicolor tsutsotsi fitowa daga      microsoft ta backorifice<Rcw> ke da Backoffice logo
		-- May 18, 1999

%
* Simunye ne a kan wani oc3-> oc12<Daem0n> simmy: ciji ni. :)<Simunye> daemon: lafiya :)
		-- May 18, 1999

%
<Overfiend> lilo: To, kai ne mai yiwuwa a alhakin thinker.            Barka da zuwa mai karamin kulob din.<Lilo> Overfiend: maraba da ni, sa'ad da ka shiga :)
		-- May 18, 1999

%
Amma, ina so mutane su san cewa a lokacin da suka yi amfani da binary kawai kayayyaki,yana da MUSU matsala. Ina so mutane su san cewa a cikin ƙasusuwansa, kuma naso da shi ihu daga rooftops. Ina so mutane su tashi a cikin wanisanyi gumi kowace sau daya a cikin wani lokaci, idan sun yi amfani da binary kawai kayayyaki.
		-- Linus Torvalds

%
* Wichert_ shayi master ba tare da MTA<James> wichert: ehm? da zai hana peformance na BTS: p
		-- Linus Torvalds

%
<Gecko> Hmm ... Ina mamaki da abin kuma seperates Debian daga sauran        Linux rabawa.<Knghtbrd> gecko - ba mu tsotse<Gecko> Knghtbrd: ba ka ce cewa a lokacin da magance wani gungu na mutane        DAGA wadanda distros<Knghtbrd> gecko - batu.
		-- Linus Torvalds

%
Saboda da rufaffiyar source ci gaba model na XFree ba shi yiwuwadon taimaka wa, ko ma yayata game, fasali a mu- ko beta sakena XFree.
		-- Marcus Sundberg

%
>> Na yi ba sosai ganin Littafi Mai Tsarki-KJV-rubutu a matsayin sana'a daftarin aiki,>> Amma ... :)> Yana da wani manual - for rai.Amma ya ba da aka sabunta a cikin wani dogon lokaci, da yawa za su ce cewa yana daAbin ba in ciki daga ranar, da kuma cirewa tsaye ba ya amsa waemail. :-)        - Branden Robinson, Oliver Elphick, kuma Chris Waters a           sako ga Debian-siyasa
		-- Marcus Sundberg

%
<Knghtbrd> zan iya tunanin kuri'a na mutanen da suke bukatar AMFANIN = ID10T someplace!
		-- Marcus Sundberg

%
<Slashdot> ta Amurka geograpy ne lousy ... lol<Knghtbrd> haka ke mine kuma ina zaune a nan
		-- Marcus Sundberg

%
Moonchild ba tare da wani ra'ayi? Shai an patines aiki gobe!
		-- Brett Manz

%
<Knghtbrd> I gaske ba sa so da yawa a duk ... Just a irin kalmar, an           m mace, kuma Unlimited bandwidth !!
		-- Brett Manz

%
<Knghtbrd> Idan muka yi duka daidai (Ina yin cinta muna) Ba na Very Happy.* Minupla hannãye muku rashin faɗi na shekara kyautar.
		-- Brett Manz

%
Last lokaci ina da m lamba tare da wani mutum ya m wanim kwarewa ... Na wajen son shi ....)
		-- Brett Manz

%
<Apple_IIe> kowa gani ta 80 shafi katin?
		-- Brett Manz

%
<Slackware> uh oh, abin da na fara :)<Debian> rofl ... distro nick yaƙe-yaƙe.* Slackware kawai jira a gare / nick GNOME, / nick KDE, sa'an nan kuma yakin duniya 4   to karya fita<WinNT>: OP<OpenBSD> <duck><PalmOS> :)<Slackware> no'one zai kuskure / nick RedHat<Tru64> mew.
		-- Brett Manz

%
<Crow-> im fcucking druk* Knghtbrd sa tabbata ka shiga duk abin da Crow- ce yau da dare ...<MrBump> heheh<MrBump> Ya ce ya son ya aure ni! damnit !!<Crow-> mutum wata hanya<Knghtbrd> MrBump - ya ke ba CEWA bugu<MrBump> Knghtbrd: Ina niƙa: o)
		-- Brett Manz

%
<Knghtbrd> aggh!<Knghtbrd> MAKE IT daina!<Knghtbrd> MAKE IT DAINA !!
		-- Brett Manz

%
<Knghtbrd> RoboHak - lafiya, da faci ba karya, amma kwakwalwa           a fili shi ne<WC> cewa kome ba sabon (;<Knghtbrd> WC - Hush.<Knghtbrd> =>
		-- Brett Manz

%
<Dpg> Amirkawa ne wierd ....<Xtifr> Californians har weirder<Knghtbrd> xtifr yana da ma'ana ...
		-- Brett Manz

%
* Woot murmushi serenely.<Woot> Ba ni so in ze kan m game da samun a cikin knghtbrd ta       siglist.
		-- Brett Manz

%
<Culus> dhd: R ku da wani ɓangare na m Debian overstructure?<Dhd> ba. babu wani m Debian overstructure.<CosmicRay> ko da yake, yanzu da wani ya kawo shi, bari mu fara daya            :-)<Knghtbrd> CosmicRay - me ya sa ba, sauti kamar fun hanyar ciyar da           rana = D
		-- Brett Manz

%
<Xtifr> ba ka da ya zama mahaukaci aiki a nan .... oh jira, a ka yi!        :)
		-- Brett Manz

%
* O-o ko da yaushe kamar debmake domin ya san daidai abin da zai yi ...<Ibid> o-o: za ka ;-)
		-- Brett Manz

%
2.3.1 An saki. Goyon baya sabon zuwa wannan wasan ya kamata ka tuna cewa2.3. * Sake su ne ci gaban kernels, ba tare da wani tabbacin cewa suba zai haifar da tsarin yi m abubuwa kamar cin hanci da rashawa daDISKs, kama wuta, ko fara gudu Mindcraft asowar.
		-- Slashdot

%
yi {    :} Lokaci (! HELL_FROZEN_OVER);
		-- Slashdot

%
0 7 * * * amsa kuwwa "... Linux ne kawai a fad" | mail billg@microsoft.com -S = "Kuma ku tuna a ..."
		-- Slashdot

%
<Hop> kb: Na bukaci mutunci da gaskiya a cikin wadanda suka i yi aiki tare da<Hop> i san bukatar ne m, amma a Guy iya mafarki, ba zai iya ya?
		-- Slashdot

%
<Jgoerzen> stu: ahh cewa na'ura. Kada ka yi tunanin cewa wani abu mai suna           stallman cancanci ya zama wani Alpha? :-)<Stu> jgoerzen: babu, a zahiri, Ina prolly zama mafi karkata to suna da 386      da 4 megs na ragon kuma a 40 Meg rumbun kwamfutarka stallman.<Stu> da babban mai harka da ta sa ton na amo da wasan yara masu kara bene* Knghtbrd dama zuwa bene rike da bangarorin dariya<Stu> kuma ..<Stu> biyu-tsawo rumbun kwamfutarka
		-- Slashdot

%
Klingon aiki kira ba su da 'sigogi' - suna da 'muhawara'
		-- and they ALWAYS WIN THEM.

%
* Knghtktty ba za su tambaye yadda zucchini samu a cikin tattaunawa ...
		-- and they ALWAYS WIN THEM.

%
<Knghtbrd> Subject: [GR tsari] Ya kamata mu zabe a kan maras muhimmanci al'amura?
		-- and they ALWAYS WIN THEM.

%
<Woot> Saka * cewa * a kai .sig da hayaki da shi, Knghtbrd.<Culus> Ka sani zai karanta wannan:><Woot> heheheheh.
		-- and they ALWAYS WIN THEM.

%
"Kamar yadda ka yi tafiya ta rayuwa a minti kowane yanzu, sa'an nan su bayar datunani ga sauran 'yan'uwanmu. Ya za a iya mãkirci wani abu. "
		-- Hagar the Horrible

%
<Knghtbrd> To, ku mutane sun fara magana ne game da aikace-aikace na BSDM           cibiyar sadarwa hardware ... Ina ganin zan gudu kashe, kuma suka aikata wani abu da amfani           kuma Debianish kuma zauna daga wannan ...<Knghtbrd> (ga wani canji)
		-- Hagar the Horrible

%
<Knghtbrd> mariab - kada ka yi zaton Debian ya ba da wasu sosai wawa da           bayyane kwari da<Knghtbrd> mana, mu kullum gyara namu kafin mu saki = D
		-- Hagar the Horrible

%
<Knghtbrd> mariab - ni mai Debian developer. Red Hat ne "maƙiyi" ko           wani abu kamar cewa Ina tsammani .. Duk da haka, typecasting RH users kamar yadda           idiots ko rarraba kamar yadda gaba daya karya da tsoho           shi ne cikakken da total FUD.
		-- Hagar the Horrible

%
>> Amma IANAL, ba shakka.>> IANAL ko dai. Ɗana ne, amma idan na tambaye shi na iya samun wani amsar da zan> Ba zai so ya ji."Ga ta daftari." ? = D
		-- Hagar the Horrible

%
> Ok, na ga ka san abin da kana yin :-)Ko dai cewa ko Na gotten kyawawan mai kyau a faking shi.
		-- Hagar the Horrible

%
<Wichert> 8am sigar ungoldly hour zama a farke :)* Gorgo yawanci samun sama a 11am
		-- Hagar the Horrible

%
Babu Cabal.
		-- Hagar the Horrible

%
<_Anarchy_> ACF: watakila Afrilu 1 gaba shekara slashdot bukatar ya gudu "Rob Malda            yarda da sabon aiki a matsayin shugaban Debian aikin "8)
		-- Hagar the Horrible

%
* Netgod bude akwatin gidan waya da kuma nan da nan nufin ya hadnt
		-- Hagar the Horrible

%
<Frogbert> da wuya kasancewa a 'yan madigo withoutn ƙirãza ... mutane dont yi           ku tsanani
		-- Hagar the Horrible

%
Zai yiwu Debian ne damu game da fasaha kyau maimakon'yanci na amfani da karya software. A cikin tsohon mu Excel. a cikinkarshen dole mu yarda da filin don Microsoft. Tsammani inda ina so in tafia yau?
		-- Manoj Srivastava

%
* PerlGeek yake a sarari hanya* Knghtktty ĩmãni PerlGeek
		-- Manoj Srivastava

%
<Netgod> ta abokin ciniki an mallakar mai tsanani<Netgod> wannan Guy samu tushe, gudu fakiti sniffers, shigar .rhosts dabackdoors, ya sa dukan sabon dir a kira / lib / "", wanda yana dafull suite na smurfing kuma kashe kayayyakin aiki<Netgod> kadai kuskure ba share da logfiles<Netgod> tambaya shi ne yadda aka tushen hacked, da kuma cewa i couldnt gaya u<Netgod> shi ne, ba shakka, ba a Debian akwatin* Netgod Notes da Debian akwatin ne kaɗai bar untouched da gwanin kwamfuta
		-- wonder why

%
* Joeyh cvs aikata gidansa directory. Aaaaaa<Drow> eeeeeeek<Drow> joeyh: Wannan shi ne kawai sharri. Period.
		-- wonder why

%
<Kethryvis> Gruuk: UFies ne sama da kuma bayan 'yan adam :)
		-- wonder why

%
Na tsayar dogon lokaci da suka wuce ya yi kokarin gano wani abu a cikin kwaro jerin dpkg.Ya kamata mu gudu ga wani shigarwa a cikin Guinness littafin Records.
		-- Stephane Bortzmeyer

%
<Ahzz_> i siffa 17G oughta zama isa.
		-- Stephane Bortzmeyer

%
<N3tg0d> ya / usr / bin / emacs aka sa a cikin / sauransu / bawo yet? : P
		-- Stephane Bortzmeyer

%
* Joeyh daukan amfani da Netscape ta m ikon fadi don rufe        10 windows da guda keypress<Joeyh> yanzu ke ci gaba!<Knghtbrd> Bus kuskure =>
		-- Stephane Bortzmeyer

%
<Wordplay> Ka auna your vibrators a "characters da biyu"? ina dabad news a gare ku, c90, ka An tabawan al'aurar dadot-matrix firintar.
		-- Stephane Bortzmeyer

%
Hi! Ni .signature cutar! Kwafi ni cikin your ~ / .signature taimake ni sprea =d!
		-- Stephane Bortzmeyer

%
* Knghtktty rada zaki nothings to Thyla (stuff game compilers kuma            graphics da rago kyautayuwa da kuma babban wuya tafiyarwa ...)<Thyla> oooooooooOOOOOOOOOO<Infinitas> Knghtktty: shi ke ma batsa ...* Thyla ke kashe a cikin yi daidai da bugu zuwa ɗaguwar ruhaniya ...
		-- Stephane Bortzmeyer

%
<Sanaya> ku mutane ne duk da lafiya! m m m ina gaya ya;)
		-- Stephane Bortzmeyer

%
* Bma ne mai Yank* Knghtbrd ne mai Knghtbrd* Dhd ne kuma mai Yank* Jira ne mugu* Knghtbrd ĩmãni jira
		-- Stephane Bortzmeyer

%
* Bma abubuwan al'ajabi idan wannan zai sa Knghtbrd .sig
		-- Stephane Bortzmeyer

%
Techical mafita ba wani al'amari na zabe. Biyu xaukaka a Amurkajihohin kusan yanke shawarar cewa, darajar PI zama 3.14, daidai. popular kuri'abai sa a daidai bayani.
		-- Manoj Srivastava

%
<Abubakar> <Knghtbrd> karuwa a tashin hankali a duniya (kamar yadda evidenced by laifi<Abubakar> kuma whatnot) a kan cewa lokaci lokaci ya dubi mai yawa kamar Linux<Abubakar> girma tun 1993<Abubakar> `` Linux nasaba da duniya laifi annoba !! ''
		-- Manoj Srivastava

%
<Teller> inda ni da abin da nake yi a wannan handbasket?
		-- Manoj Srivastava

%
Tun da yake wannan database ba a amfani da amfãni ga, kuma tun dukan ayyukansu, babuga, shi dama a karkashin m amfani, kamar yadda muka fahimta shi. Duk da haka, idan wanirabin assed wawa yanke shawarar da ya yi wani riba kashe wannan, za su bukatarbiyu duba shi duka ...
		-- Notes included with the default fortunes database

%
Babu gajeren barcin button a kan wani cat wanda yake so karin kumallo.
		-- Notes included with the default fortunes database

%
Subject: Bug # 42432: Debian-siyasa: shawara ga CTV for Daftarin for TabbacinConcept for Daftarin for shawara ga shawara ga CTV a CTV yanke shawara a kanwani tsari ga wani CTV ga CTV kan ko mu shoud da CTV ada / usr / doc to / usr / share / doc mika mulki yanzu, ko kuma daga baya.
		-- Ed Lang

%
<Knghtbrd> Yana da wani trackball daya<Wichert> saboda haka yana da ba a rodent<Wichert> yana da wani turd da ball mai danko fitar<Wichert> abin da za ka fondle kullum
		-- Ed Lang

%
* HomeySan jira domin Papa Yahaya pizza ya nuna sama<Ravenos> mm. Papa Yahaya.<HomeySan> fatan su aika da cute delivery direba<Ravenos> su sani da cewa a nan.<Dr_Stein> me ya sa? ku za ku ci da direba a maimakon?
		-- Ed Lang

%
<Netgod> ne ni, ko kuma yana da Knghtbrd snoring?<Joeyh> suka kashe knghtbrd!<Netgod> Kysh: wichert, gecko, joeyh, kuma ina ne a cikin wani daki kokarin watsi          Knghtbrd<Kysh> netgod: Knghtbrd da wuya ya yi watsi.
		-- Ed Lang

%
<Woot> Man, ina so knghtbrd kasance a nan ansu rubuce-rubucen da ya sig list.[... Dama hours daga baya ...]<Knghtbrd> woot ba su sani ba ni vewy da kyau, yi shi?<Knghtbrd> muahahahaha
		-- Ed Lang

%
* Knghtbrd pelts wichert da NERF darts* Wichert Notes akwai wani ICBM nerfs yet kuma watsi kngtbrd<Knghtbrd> wichert - just jira, bayan ganin NERF gatling bindigogi, ICBMs           suna ba da nĩsa ba (kawai Pump da tsine wa abu don awa daya ko biyu           shi ne duk ...)
		-- Ed Lang

%
Operating Systems Installed:  * Debian GNU / Linux 2.1 4 CD Sa ($ 20 daga www.chguy.net. Price hada    haraji, shipping, da kuma $ 3 kyauta to FSF). 2 CDs ne binaries, 2 CDs    complete source code.  * Windows 98 Na biyu Edition Inganci Version ($ 136, ta hanyar Megadepot.com,    price ba sun hada da haraji / shipping). Abin mamaki, babu source code    aka hada da.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Sata wannan tagline. Na yi.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Bfextu> oh noooo, Knghtbrd ta samu a gun :)<Doogie> ^^ sa music ^^<Knghtbrd> bfextu - o / ~ kowa ne a kan gudu o / ~<Bfextu> o / ~ gudu, ruuuuun daga albashi-ay-ain o / ~
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Mercury> emacs tsotsa, a zahiri, ba a zagi, kamar wani comment da cewa ta          babban isa a yi m gravitational Pull ...
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Kamar yadda a kwamfuta, na sami bangaskiyarka a cikin fasaha m.
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
* Knghtbrd sanya 3 zuwa Chris* M abubuwan al'ajabi wanda kuma aka mai suna Chris kuma ni<Knghtbrd> m - ku. =>* Knghtbrd jira a gare m to da cika fuska ce "Ina jin SO amfani!"<M> Knghtbrd: :)* M ++<M> :)
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
* Jira yana tunani wani uplad jerin gwano da ake kira 'jahannama' don haka sai na iya yi dupload --to jahannama
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Valkyrja> java, Hon, wani lokacin ina son ka smack ku.<Knghtbrd> Valkyrja - ya son a ji dadin shi da yawa<Reteo> Valkyrja: yah, ci gaba da yi shi ... doke java cikin cappuccino! :-)
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
<Tali> zama vewwy vewwy qwuiet .. Ina huntin wuntime ewwos
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Red Hat ta kwanan nan fito da wani Tsaro Bada Shawara (RHSA-1999: 030-01)rufe a buffer ambaliya a vixie cron kunshin. Debian yanagano wannan kwaro shekaru biyu da suka wuce da kuma gyarawa shi. Saboda haka versions abiyu, da barga da m, rabawa da Debian bam ga wannan matsala ..
		-- Bill Stilwell, http://linuxtoday.com/stories/8794.html

%
Na farko off - Quake ne kawai m. Yana baka damar akai-akai kasheKocin a cikin ofishin ba tare da an kama su. :)
		-- Signal 11, in a slashdot comment

%
Lucas 'Law: Good ko da yaushe za ta lashe, domin mugunta hires da _stupid_             injiniyoyi.
		-- Signal 11, in a slashdot comment

%
* TribFurry kawai samun spam mail daga ucsd ... Ina amfani da su samun email daga            kaina amma na yanke shawarar ban son kaina kuma tsaya maganazuwa gare ni
		-- Signal 11, in a slashdot comment

%
<Rain_work> rubutu a kan wani mazaunin dalibai firiji ... "Don mutumin da ya ci da abinda ke ciki            na ganga labeled 'James' - gargadi, shi ne ta ilmin halittagwaji "
		-- Signal 11, in a slashdot comment

%
<KatanaJ> Note a kan wani chem Lab fridge- "Wannan firiji ba explosion-          hujja ".
		-- Signal 11, in a slashdot comment

%
<KnaraKat> DalNet kamar na musamman gasar Olympics na IRC. Akwai mai yawa           drooling goin 'on da kowa da kowa ne a' lashe '.
		-- Signal 11, in a slashdot comment

%
Amma gyaggyarawa dpkg ne infeasible, kuma mun amince da su, tsakanin sauran abubuwa,ci gaba da bukatun mu masu amfani a kan gaba wajen zukatanmu. Kuma dagamai amfani da hangen zaman gaba, wani abu da rike da tsarin shirya a cikin al'adayanayin, kuma ya aikata aiki * yanzu *, mai yawa fiye ƙunshe rudu kamaraiki dpkg.
		-- Manoj Srivastava

%
Domin kowane wahayi akwai wani daidai da m bita.
		-- Manoj Srivastava

%
<Epsilon3> Knghtbrd, idan muna so a lameass ra'ayi mu dã sun ce:           Hey, neckro
		-- Manoj Srivastava

%
<Tigah _-> i da 4GB for / tmp<Knghtbrd> Me kuke yi da 4G / tmp? Tara X?<Tigah _-> i
		-- Manoj Srivastava

%
<KnaraKat> cizon ni.* TheOne samun dan gishiri, to, Saide to nibble a KnaraKat kadan         bit ....
		-- Manoj Srivastava

%
* Knghtbrd Notes ya mashed dankali for tarar da kwakwalwarmu yau da dare<Valkyrie> Yum, zan iya samun?<Knghtbrd> Um ...* Knghtbrd boyewa daga Valkyrie
		-- Manoj Srivastava

%
<Knghtbrd> joeyh yanzu yana da m a shimfiɗa ba?<Knghtbrd> Wannan Guy ne mai waya, na rantse =><Doogie> Knghtbrd: kwamfyutan<Doogie> kuma ba ni nufin Cats.
		-- Manoj Srivastava

%
Ganin wasu daga cikin 'yan zaren, da m tattaunawa cikakken mulkibukatar da za a gudanar a ranar zane, a gaban wani alkalin wasa, yayin dasanye padded safar hannu. ;-)
		-- Phil Hands

%
<James> amma, sa'an nan na yi amfani da wani Atari, na mafi kusantar su lashe tambola a        goma kasashen lokaci guda fiye sami kara X
		-- Phil Hands

%
* Joeyh abubuwan al'ajabi da ya sa kowa da kowa yana so ya san yadda tsayi shi ne<James> joeyh: yana taimaka da maharbi
		-- Phil Hands

%
* BenC abubuwan al'ajabi da ya sa ya kyautata zuwa 3.3.5-1 da teh X tsaye
		-- Phil Hands

%
<Delenn> ba zan yi da shi ta hanyar 24 hours kafin in so a harbe-harben sama da         gasa da kuma slapping 'yan friends a barbie.<Spacemoos> Me ya sa za ka mara abokai da barbies, Thats kamar kinky
		-- Phil Hands

%
A gaskiya .. dogara ne a kan wannan model daga abin da NSA ne da ba ... da dama daga cikinmutanen da suke karanta wannan akwai mambobi ne na NSA ... /. ne afterall 'News forNerds '.NSA Litinin da safe {a kofi na'ura):NSA wakili 1: Hey mutane, ba ku duba fitar slashdot a karshen mako?    Agent 2: A'a, ina aka installing manta uwa 6.1 da kuma na coulnd't samun darn             PPP dangane up ..    Agent 1: Well duba shi daga ... da suka yi a kan mu.
		-- Chris Moyer <cdmoyer@starmail.com>

%
Technology ne a constand yaƙi tsakanin masana'antun samar da girma da kumamore wawa-hujja da kuma tsarin yanayi samar girma, kuma mafi alhẽri idiots.
		-- Slashdot signature

%
knghtbrd: akwai iya zama wani cokali, amma za ku iya suma da yanayin shigewa aeye_render_shiny_object.c?
		-- rcw

%
<Joy> wow ... m maths nuna cewa Debian developers sun rufe more      fiye * 31 * * * dubu kwaro rahotanni tun da BTS wanzu!<Joy> cewa ne game 30999 fiye Microsoft;)
		-- rcw

%
<Knghtbrd> NOTE cewa sama NE JUST wani ra'ayi da ba za aRiƙi HADA KOWANE ma'aunin gaskiyane BAYANIN. THE           Majalisa disclaims duk abin da kowa da kowa. Magance shi.
		-- rcw

%
<James> wani GNOME freaks kusa?<Knghtbrd> ba ni ba, ni kawai Freak
		-- rcw

%
<Madax> ahh<Madax> wani taro na geeks ....<Madax> zan iya sansana shi yanzu
		-- rcw

%
<Knghtbrd> koyi son Window Mahaliccina.<Knghtbrd> kadan NeXTStep ne mai kyau ga rai.
		-- rcw

%
Caveats: yana da GNOME, ka ji tsoro, zama sosai tsoron dogara line
		-- James Troup

%
<Culus> Hhhmmmmmmmm<Culus> waterbeds for shanu<Culus> eleet<CAS> Culus: me ya sa za a saniya bukatar a waterbed?<Culus> CAS: To zama comfy dumi
		-- James Troup

%
Idan kun kasance abin da kuke ci, ina tsammani cewa, ya sa ni a cuku Danish.
		-- Anonymous

%
<Hop> lokacin da ka fara yin kawai wawa kuskure da cewa su ne bayyananne, Thats      lokacin da ka fara samun m<Hop> domin ba ka yin muhimman hakkokin rashin fahimta kuskure<Hop> kuma Thats a * mai kyau * ãyã.
		-- Anonymous

%
<Lilo> yana da ban mamaki, a lokacin da ka je a kan wani safari zuwa Afirka a kama zaki, ka       same shi da rai kuma yana da zargin, sa'an nan kuma ku kashe shi<Lilo> lokacin da ka je a kan wani safari ta Kudu Bay a samu Palm Vx, za ka sami       shi matattu da kuma kai shi gida kuma zargin bayan ta zo :)
		-- Anonymous

%
<Lilo> zan iya karanta jini * manual * kamar dai shi ne wani irin       addini fili ya bayyana siffofin haskaka za ka iya cimma       bayan shekaru 10 a kan wani dutse :)
		-- Anonymous

%
Gates 'Law: Kowane watanni 18, da gudun software halves.
		-- Anonymous

%
<Knghtbrd> Solver_: ƙara masu amfani da suka kamata a messing da sauti zuwa rukuni           audio .. Tabbatar da na'urorin duk kungiyar audio (LS -L           / Dev / DSP zai ba ku cikin gaggawa nuni idan yana da tabbassaita dama) da kuma gina kwaya tare da sauti goyon baya ga your katin<Knghtbrd> KO optionally shigar alsa source kuma gina kayayyaki ga cewa           da suke kpkg<Knghtbrd> KO (ba da shawarar) sa da kuma shigar da mugunta OSS / Linux mugunta           ba-free mugunta binary kawai sharri direbobi --- amma waɗanda mugaye ne.Kuma ban ambaci cewa shi ke ba da shawarar?
		-- Anonymous

%
Ina ganin IRC ba zai yi aiki ko --- muna yanã gudãna daga topic sarari!
		-- Joseph Carter

%
"Pacific Bell Abokin ciniki Service, wannan shi ne [..], yadda zan iya samar maka dam abokin ciniki sabis a yau? ""HAHAHAHAHA !! Wannan da kyau, ina so shi ..""Um, godiya, suka yi mana ce."
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Danpat> Omnic: jini newzealanders<Omnic> danpat: saka sock da shi<Danpat> heh :)<Knghtbrd> yin ba'a .nz'ers ne daban-daban --- sun yi dukan m* Knghtbrd Ɓoye<Omnic> hrmph
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Joy> Flinny: black crontab sihiri kamar stuff :)<Knghtbrd> Joy: ya aikata wancan nufin mutane samun rawa tsirara a kusa da bonfires           Chanting m abubuwa da waving da makamai a cikin wani wauta           hanya?<Rcw> knghtbrd: abin da kuke * zaton * mutane yi a novare?
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Knghtbrd> * snipsnip *<Rcw> oh masoyi, shi ne cewa sauti na arziki-database tace?<Joy> uh oh<Knghtbrd> Ee =>
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
<Joy> ke a Kludge (TM)<Knghtbrd> Yana Works (TM)<Joy> AIX aiki (TM)<Knghtbrd> babu shi ya aikata ba<Knghtbrd> =>
		-- knghtbrd and a pacbell rep, name removed to protect her job

%
"The bambanci tsakanin baiwa da wawanci ne cewa baiwa ta yana daiyaka. "
		-- Albert Einstein

%
<Knghtbrd> Idan caji wani for take hakkin Amurka Hikimar dokokin zai samu           ku yi dariya daga kotu, kamar "bincika" su a kan hte cajin           na cin amanar kasa!<Knghtbrd> Tea, kowa?<Jira> Ina wajen nutsar da 'yan siyasa a maimakon shayi :)<Stu> jira: 'yan siyasa da gills, duh<Jira> weasels ba su da gills
		-- Albert Einstein

%
Idan ina da matsala installing Linux, wani abu ba daidai ba ne. Very azzãlumai.
		-- Linus Torvalds

%
* Bma_home gropes ka<Bma_home> "oups, ba daidai ba channel"<Bma_home> </ ACF><Cerb> sallama re ni<Doogie> ka san za ka son shi.<Bma_home> zahiri, shi ne "grope ni baby"<Gecko-> shãfe ta dan da ka mutu, bma;)<Doogie> gecko-, amma matarka ne ok?
		-- Linus Torvalds

%
Reading kwamfuta Littattafan ba tare da hardware kamar frustrating matsayin karatujima'i Littattafan ba tare da software.
		-- Arthur C Clarke

%
<Knghtbrd> (tinc)<Jira> (ytitac)<Knghtbrd> (ntinac)<Jira> (da shi)<Knghtbrd> (a)* Jira Notes magana a acr ^ Winitialisms ne ban tsoro, a lõkacin da sauran gefen  fahimci kai
		-- Arthur C Clarke

%
<Knghtbrd> yana kuma bad mafi tsoho unices ne y2k yarda<| Rain |> kash?<| Rain |> dalilin da ya sa, domin mutane ba za su hažaka har 2038?
		-- Arthur C Clarke

%
<Espy_on_crack> "Na shigar 'Linux 6.1', ba ya da sa ni a UNIX                guru? "<BenC> Espy_on_crack: babu, dole ka shigar da shi sau biyu, kafin ka kasance a       guru ... da zarar ya tabbatar da za ka iya yi da shi, na biyu gyara abubuwan       your m da farko<Espy_on_crack> oh dama, yadda wauta da ni
		-- Arthur C Clarke

%
* Knghtbrd aikata ET abu<Knghtbrd> wani samu wani magana-n-sihiri?
		-- Arthur C Clarke

%
<Omnic> wani .sig Baya
		-- Arthur C Clarke

%
Na fara tunanin gene pool iya amfani da kadan chlorine.
		-- Arthur C Clarke

%
Yana da matsayin sharri kamar yadda ka yi tunanin, kuma sũ, daga don samun ku.
		-- Arthur C Clarke

%
<Jira> mai da hankali, wasu twit iya Quote ka<Jira> fita daga mahallin ...
		-- Arthur C Clarke

%
*** Topic for #redhat: ReDHaT ne amsar dukan matsaloli. Yana    zai iya zama farkon ma!
		-- Arthur C Clarke

%
* Cesarb abubuwan al'ajabi idan a kasa da mako guda Carmack zai ƙarasa karbar a  e-mail a ladabi kwafin wani version of girgizar source wanda yake shi ne hudu  sau da sauri fiye da abin da ya fita daga cikin rumfa hannun ...
		-- Arthur C Clarke

%
<Knghtbrd> JHM: Ina ba sa girgizar a kwaya source<Knghtbrd> amma ya kamata mu sa girgizar a taya floppies daya-up           Caldera ta tetris game ...>
		-- Arthur C Clarke

%
Guns kada ku kashe mutane. Yana da wadanda tsine harsasai. Guns kawai sa su tafigaske gaske azumi.
		-- Jake Johanson

%
<Jira> muna bukatar mu raba main a cikin "core" da kuma "WTF-amfani-da wannan"
		-- Jake Johanson

%
<Culus-> libc6 ba da muhimmanci: |
		-- Jake Johanson

%
<Dhd> akwai na musamman Kirsimeti shirya domin girgizar<Dhd> inda ka samu zama kamar santa robot a kan futurama?<Dunham> dhd: cewa zai zama a maimakon unbalanced game ...<Knghtbrd> dunham: shi ke da ra'ayin. .>
		-- Jake Johanson

%
<Knghtbrd> matsalar da GNU coding nagartacce ne suka ɗauka cewakowa da kowa a duniya amfani da emacs .. Idan da suke harka, free           software zai mutu saboda za mu duk da wuyan hannu matsalolikamar RMS da yanzu da kuma daina iya code. .>
		-- Jake Johanson

%
C'mon! siyasa rashin amincewa! sheesh. Ina cewa Anarchist ruhu? ;-)
		-- Decklin Foster

%
Mun upped mu nagartacce, don haka har naku!
		-- Decklin Foster

%
* Woot yanzu da aka sani da woot-abincin dare* Knghtbrd yayyafa kadan gishiri a woot<Knghtbrd> I taba a woot da ... Hope su dandana kyau<Woot-abincin dare> noooo!<Woot-abincin dare> Kada ku ci ni!* Knghtbrd yanke shawarar ba ya so a abincin dare wanda yayi Magana da shi ... Hehe
		-- Decklin Foster

%
[Game matakan hana magudi a girgizar kasar]Ina nufin, muddin zan iya yi ta roka shirin mai gabatarwa kama da wani babban twinkie,Zan yi farin ciki;)
		-- Qeyser <keyser@jhu.edu>

%
<Knghtbrd> r0bert: a takaice, muna motsi da yawa abubuwa abokin ciniki           a halin yanzu yake da alhakin gaya uwar garken cikin abubuwan da           uwar garken cak kanta<Knghtbrd> Idan Neo ce "Babu wani cokali", The Matrix ce "Kaitona a           akwai --- ba magudi. "<Hollis> Amma ya san kung fu ...<Knghtbrd> Sure ya aikata, amma ina da wani roka shirin mai gabatarwa.
		-- Qeyser <keyser@jhu.edu>

%
* Mercury calmly kawar XT-Ream ta hannu ..* Mercury to Saide doke XT-Ream da XT-Ream ta hannu.<Knghtbrd> wow, duk wannan girgizar Hacking ne yin Mercury m nan* Mao ne m girgizar ƙirƙira aikin da yake a cikin mai kyau hannayensu
		-- Qeyser <keyser@jhu.edu>

%
<Knghtbrd> CVS / Entries yana da line ina bukatar to "canza"<Mercury> Knghtbrd: ya game da su ambaci irin .. <G><Mercury> Knghtbrd: Yanzu, a shirye su yi?<Knghtbrd> so ni luck<Knghtbrd> Mercury: shi ke aikata<Knghtbrd> Mercury, kuma bayan duk da cewa, ya kamata in zama ma.
		-- Qeyser <keyser@jhu.edu>

%
* Knghtbrd crosses yatsun kafa<Knghtbrd> (idan na ketare ta yatsunsu zai zama da wuya a rubuta)
		-- Qeyser <keyser@jhu.edu>

%
<Doogie> akwai wani mummunan abu game da ciwon cell phone.<Doogie> I za a iya isa a kowane lokaci. : |<Wmono> cewa ya sa na bar mine kashe a kowane lokaci. .>
		-- Qeyser <keyser@jhu.edu>

%
<Palisade> yadda za mu furta '00, ko '01, ko '02 da sauransu?<Deek> Ka ce ban kwana ga nineties, ka ce hello da naughties. :)
		-- Qeyser <keyser@jhu.edu>

%
<Deek> Idan mai amfani nuna da gun a kafar da kuma jan jawo, shi       ne aiki don tabbatar da harsashi samun inda ya ke ya kamata su.
		-- Qeyser <keyser@jhu.edu>

%
<Mercury> a yi musu gargaɗi, ina da wani keyboard zan iya amfani da su domin doke luser ta shugabannin          a, sa'an nan kuma ci gaba da amfani da ... (=:]<Deek> Mercury: Oh, an IBM. :)
		-- Qeyser <keyser@jhu.edu>

%
<Palisade> knght, sheesh, an kai pasting maganata daga mahallin a           #debian ko wani abu?<Palisade>;)<Knghtbrd> ba, amma ina mai yiwuwa ya kamata.><Palisade> d'oh!
		-- Qeyser <keyser@jhu.edu>

%
<CAS> Mercury: gpm ba da kyau web browser. gyara shi.
		-- Qeyser <keyser@jhu.edu>

%
<CAS> da akwai ya tafi. ce wani abu wawa a IRC kuma da shi      immortalized har abada a cikin wani ta .sig fayil
		-- Qeyser <keyser@jhu.edu>

%
Microsoft ne a giciye tsakanin Borg da Ferengi. Abin baƙin ciki,suka yi amfani da Borg don su yi kasuwanci da kuma Ferengi don su yishirye-shirye.
		-- Simon Slavin

%
Na gwammace kashe 10 hours karanta wani ta source code fiye da 10minutes sauraron Musak jiran goyon bayan sana'a wanda ba.
		-- Dr. Greg Wettstein, Roger Maris Cancer Center

%
Ina kake zaton kana za a yau?
		-- Dr. Greg Wettstein, Roger Maris Cancer Center

%
Ina aka ji dukan gloom da azãba tsinkaya for Y2K, don haka sai na tunani Ina gafala da wasu daga cikin shawara da cewa masana sun bada: Cika up mota ta gas tank, Stock up on gwangwani kaya, cika sama da baho da ruwa, da sauransu.Ina tsammani ba ni da cikakken farkakku lokacin da na kammala ta shirye-shirye marigayi karshedare. Wannan safe da na sami kitchen shelves soaked a fetur, ruwaa cikin mota ta gas tank, kuma ta baho cike da gasa da wake.
		-- Dan Pearl in a message to rec.humor.funny

%
<Tarzan> hey kuka fada a kashe ka pirch ko wani abu?<Knghtbrd> ni? heh.
		-- Dan Pearl in a message to rec.humor.funny

%
<Jira> kana gasa<Knghtbrd> jira: kawai rabin haka
		-- Dan Pearl in a message to rec.humor.funny

%
<Darkangel> I kullum ba su amfani da wani abu da cewa yana da "gwaji" da kuma            "Gargadi" pasted ko'ina shi<Darkangel> ba, ba ni da wanda bẽbãye ... Hehe<Knghtbrd> ...* Darkangel ya ɗauki sauke sabuwar m kwaya
		-- Dan Pearl in a message to rec.humor.funny

%
<Wichert> solaris ne BSD, don haka ya kamata aiki* Jira daukan wichert ta crack bututu bãya
		-- Dan Pearl in a message to rec.humor.funny

%
<Knghtbrd> yana kuma bad mafi tsufa unices juya daga y2k yarda<Knghtbrd> domin shi yana nufin mutane za su kasance har yanzu a guje da su a cikin shekaru 30           = p<Knghtbrd> dã ya kasance haka da yawa nicer idan y2k yadda ya kamata kashe kashe           hpux, aix, sunos, da dai sauransu.><Jira> Knghtbrd: tun lokacin ne PH-UX, aches, kuma solartus "old"?
		-- Dan Pearl in a message to rec.humor.funny

%
* Gxam abubuwan al'ajabi, idan dukan waɗannan Globals ne da gaske zama dole<Knghtbrd> mafi yawansu a wannan lokacin a<Knghtbrd> muke bukata domin tsabtace su a wani matsayi<Knghtbrd> gxam: da Globals za su tafi kamar yadda muka yi ƙaura zuwa           modularity da hauka (ie, libtool)
		-- Dan Pearl in a message to rec.humor.funny

%
<Raptor> Adamel, i zaton code ka gyarawa na mine bai yi aiki ba<Raptor> i dole ba commited aiki code<Knghtbrd> Raptor: kamar shi ne karo na farko da ta taba faru = p
		-- Dan Pearl in a message to rec.humor.funny

%
<Mercury> Knghtbrd: Amfani -3dfx ko -svga?<Knghtbrd> Mercury zai yi wani abu da shi haukata<Knghtbrd> Mercury: biyu --- svga sig11 ta, -3dfx sig4 ta<Knghtbrd> Mercury: shi ke ba kyau dama? .>
		-- Dan Pearl in a message to rec.humor.funny

%
<Knghtbrd> Yarda da mu, mun san abin da muke yi ... Mu da wani ra'ayin YADDA           muna yin shi, amma mun sani ABIN muna aikatãwa.
		-- Dan Pearl in a message to rec.humor.funny

%
<Mercury> <CJ | BiZKiT-0-> i iya upload to Linux uwar garken ko da yake<Mercury> <CJ | BiZKiT-0-> i samu wani harsashi account a kan daya<Mercury> <Mercury> Wane hali shi a guje?<Mercury> <CJ | BiZKiT-0-> Umm<Mercury> <CJ | BiZKiT-0-> Apache i zaton<Mercury> Taimako, don Allah ka taimaka ..* Omni ban-daki
		-- Dan Pearl in a message to rec.humor.funny

%
<JT> kamata a yiwuwa ace kwaro ne a alama m idan kawai rinjayar daya baka?<James-workaway> JT: RC sabõda abin da baka watakila, amma waɗanda irin baka                 takamaiman kwari ne rare ...<JT> ba a lõkacin da ta ke sa wani kwaro a GCC<Doogie> JT: sa GCC cire daga wanda baka. :)
		-- Dan Pearl in a message to rec.humor.funny

%
<EdLin> LWE?<EdLin> Linux W ?? E ??<Gani> za eatyou<JHM> World nuni?<EdLin> i ga
		-- Dan Pearl in a message to rec.humor.funny

%
"Maras muhimmanci fee". Abin da wani mummuna hukunci. Yana da daya daga cikin wadanda abubuwa daya nuna cewa idan ka yi tambaya, ba za ka iya iya shi.
		-- Linus Torvalds

%
<Deek> ku GPL your aikin gida? :)<Knghtbrd> yah = D<Knghtbrd> Duk da aka jiyar da su yi amfani ko gyara ta aikin gida, amma idan sun           raba canje-canje da suka dole ta hada da full na'ura-zaa iya karanta           source code.>
		-- Linus Torvalds

%
* Knghtbrd ne a kowace rana fiye da hakikance cewa mafi C ++ coders ba su sani ba abin da           Jahannama da suke yin, wanda yake shi ne dalilin da ya sa C ++ yana da irin wannan mummunan rap<Culus> kb: Mai C coders ba su san abin da suke yi, shi kawai ya sa ya        sauki boye: P<Culus> ganin Misali, proftpd: P
		-- Linus Torvalds

%
<Culus> Kuma kada ku sami ni fara a Perl!<Culus>:><Shaleh> Perl ne bayan mugunta<Jim> ba ku sani ba Perl yet?<Netgod> za son wani harshe ba tare da wani definable ginin kalma
		-- Linus Torvalds

%
<Doogie> cat / dev / bazuwar | Perl?<Shaleh> doogie: shi ne kuma m sendmail.cf<Doogie> :)* Knghtbrd hannun doogie a m-amfani-of-cat kyautar* Shaleh so ya yi kokarin da shi, amma yana tsoron
		-- Linus Torvalds

%
<Dhd> Perl </ dev / BDSM<Knghtbrd> kana da wani / dev / BDSM?<Dhd> tabbata, yana da wani pseudosadomasochistic bazuwar yawan janareta
		-- Linus Torvalds

%
<Kysh_> Joey: Ina kan shi a yanzu .. 3 1.3Gb DISKs, 128M ragon, dual 50Mhz        (Up to yan hudu 250Mhz)<Kysh_> The kama shi ne cewa shi jan 110v a game da 12A 8><Culus> 12A!<Culus> To, ta murhu ne 3000W, wannan rana ne 1320W<Culus> KADA KA DUBI MATSALOLI HERE<Calc> a 1320W rãnã, shi ne kamar a na'urar busar da gashi :)
		-- Linus Torvalds

%
* Joeyh_ gudanar Zab, Mai gani 10 Lines awk code* Joeyh_ recoils a tsoro
		-- Linus Torvalds

%
<Knghtbrd> joeyh: Na saukar tun midmorning jiya da pacbell ce           wannan safiya cewa AT & T ya zargi kuma kusan duk na jihar           ya saukar da<Rcw> dunno sa mutane nace da internet iya tsira nukiliya Holocaust      lokacin da shi ba zai iya tsira a backhoe
		-- Linus Torvalds

%
Wannan sakon da aka rubuta tare da vi! (Ba cewa duk a duniya kula)
		-- seen on an old message from an anon.penet.fi address

%
Connection sake saiti zuwa wasu dakiki da backhoe
		-- seen on an old message from an anon.penet.fi address

%
Feb 5 13:27:01 Trinity lp0 a kan wuta        - Da Linux kwaya, alerting ni cewa akwai wasu unknown           matsala da ta printer (ie, shi ne fita daga tawada)
		-- seen on an old message from an anon.penet.fi address

%
The m ka sani game da kwakwalwa da karin da ka ke so Microsoft!        - Microsoft ad yaƙin neman zaɓe, circa 1996(Hujja cewa talla na Microsoft da _isn't_ m!)
		-- seen on an old message from an anon.penet.fi address

%
Yin daya m yanke shawara da kuma dukan bunch of mediocre wadanda ba kamar yaddamai kyau a matsayin yin cikkaken bunch of kullum smart yanke shawara a ko'ina cikindukan tsari.
		-- John Carmack

%
Shi ke ba yawanci kudin tasiri lokaci hikima je yi shi. Amma idan wani abu kegaske pissing ka kashe, ku kawai je sami code da kuma gyara shi da kuma shi kegaske sanyi.
		-- John Carmack, on the advantages of open source

%
<Calc> Na'am shi sauti da amfani ga RE'ing kebul<Calc> i da m 3com usb kamara nan :(<Knghtbrd> calc: 3Com iya samun ku kama domin kauce dokokin da           ba su zama 'har Oktoba.><Calc> knghtbrd: i za su boye :)<Knghtbrd> ... kãfira kama kuma eh?<Calc> knghtbrd: babu i za su boye da i sami aiki
		-- John Carmack, on the advantages of open source

%
<Mercury> A wannan aya zai tara, amma segfault, kamar yadda ya kamata ..
		-- John Carmack, on the advantages of open source

%
* Knghtbrd ne FAR kuma jarabce su .sig wannan duka tattaunawa ...
		-- John Carmack, on the advantages of open source

%
The Unixverse ƙare a kan Tue, 19 Jan 2038 03:14:07 +0000
		-- John Carmack, on the advantages of open source

%
<Taniwha> Knghtbrd: ya kamata mu yi a girgizar episode: gwiwa zurfi a cikin code ":          ka gudu a kusa da harbi a kwari :)<Knghtbrd> taniwha: Zan wuce da ra'ayin a kan su OpenQuartz.>
		-- John Carmack, on the advantages of open source

%
<Taniwha> i son warware wani windows key matsala da fdisk :)
		-- John Carmack, on the advantages of open source

%
<Endy> knghtbrd: QW ta netcode yake yi m abubuwa a gare ni. : P<Knghtbrd> Wannan shi ne sabon abu? .><Endy> Ba gaske. : P
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> rcw: Oh Yay --- Na ba da hannu a cikin wani m flamewar a at           m ... 5 da minti!
		-- John Carmack, on the advantages of open source

%
<Manoj> Shaleh: Ni ba, duk da your abinda Allah
		-- John Carmack, on the advantages of open source

%
<SlayR> i kawai sayi MS Office 2000 don kawai $ 20 !!!<Knghtbrd> ka samu yage kashe.><SlayR> i sani;)
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> yana da 6am. Na kasance up 24 hours<Knghtbrd> Wake ni da kuma hadarin rayuwa da reshe.* Knghtbrd &. barci<Tv> To kowa da kowa, muna jira minti 10, sa'an nan kuma fara ambaliya Knghtbrd     da ^ G ta. Wani, hack tushen da kuma cat / dev / urandom> / dev / DSP.
		-- John Carmack, on the advantages of open source

%
*** Knghtbrd yanzu da aka sani da SirKewLDooD*** Mercury harba SirKewlDooD daga #quakeforge (* WHACK *)
		-- John Carmack, on the advantages of open source

%
<Mercury> Knghtbrd: Ina son in ga goyon baya ga xor crosshairs ..<Knghtbrd> Mercury: kana a kan quack.<Mercury> Knghtbrd: Kana dila ... <G>*** Knghtbrd yanzu da aka sani da QuackDealer
		-- John Carmack, on the advantages of open source

%
* Dry-kankara ba zai iya Code hanyarsa daga wata takarda jaka<Coderjoe> bushe-kankara: int main () {ExitPaperBag (). koma 0. }<Knghtbrd> Shin, wancan ne yadda da ke aikata to,? * Daukan bayanin kula *
		-- John Carmack, on the advantages of open source

%
<Knghtbrd> Eek, ba wani daya ...<Knghtbrd> nasan kullum developer da uwa a yanzu yana da bazuwar           sa hannu ta yin amfani da IRC quotes ...<Knghtbrd> Me na fara HERE '
		-- John Carmack, on the advantages of open source

%
* Mai gani amfani knghtbrd ta comments kamar yadda ya sa hannu<Knghtbrd> Mai gani: da zaran na typed su na gane Ina m snip su           kaina da wani ya yi.>
		-- John Carmack, on the advantages of open source

%
* Omnic dubi da 33.6k mahada sa'an nan kuma dubi Joy* Mercury SAN ya USB modem .. (=:]
		-- John Carmack, on the advantages of open source

%
Hakika, Win95 ta look ba abin da sabon ko dai - Apple kokarin SueMicrosoft don kwashe Macintosh UI / sharan iya icon, sai Microsoftnuna cewa, Apple ya samu dama na Mac ideas (ciki har da sharan Canicon) daga Xerox ParcPlace. Xerox ne mai yiwuwa har yanzu mamaki dalilin da ya sakowa da kowa ne sha'awar da sharan gwangwani.
		-- Danny Thorpe, Borland Delphi R&R

%
<Knghtbrd> ne da wata ãyã daga shafi tunanin mutum rashin lafiya to yin ɗimuwa a cikin           fara map, tattara your tsãwa, hop a pool, kuma gib           kanka da shi kawai don ganin shugaban buouce lokacin da zai saukata kasa da pool? =><Knghtbrd> "Ka sani kana da wani Quake shan tabar wiwi a lokacin da ..."
		-- Danny Thorpe, Borland Delphi R&R

%
<Zoid> har yanzu ina zaton ka mutane ne kwayoyi tattara abubuwa masu kyau Q da QW. : P<Knghtbrd> Hakika muna kwayoyi. Ko John ce haka. =><Taniwha> Zoid: muna kwayoyi, amma mun yi m kwayoyi :)
		-- Danny Thorpe, Borland Delphi R&R

%
<Taniwha> Zoid: muna kwayoyi, amma mun yi m kwayoyi :)* Taniwha abubuwan al'ajabi da abin da m kwayoyi dandana kamar
		-- Danny Thorpe, Borland Delphi R&R

%
<Endy> taniwha: Quote abu :)<Taniwha> Endy: :)<Knghtbrd> Endy: Na riga snipped shi
		-- Danny Thorpe, Borland Delphi R&R

%
<Endy> A gaskiya, ina tsammanin zan jira dankalin turawa a kammala da       installing Debian.<Endy> cewa ya kamata a nan da nan, Ina fatan. :)<Knghtbrd> Endy: Za ka a fili sani sosai kadan game da Debian.
		-- Danny Thorpe, Borland Delphi R&R

%
Babu wani abu da ke da matsala da zarar ka cire kuskure da code.
		-- John Carmack

%
<Overfiend> The Unix hanya - duk abin da yake a file<Overfiend> The Linux hanya - duk abin da yake a filesystem :)
		-- John Carmack

%
<Devkev> yeah i ga walƙiya gun da kuma inda kuka kasance, tunanin         kuka kasance za shura da wasu ass :)<Devkev> didnt yi zai zama your own :)
		-- John Carmack

%
"In ba haka ba, don Allah magana da likita game da cire kanka dagaass, na yi imani da shi zai zama da amfani ga duka da hannu. "
		-- Zephaniah E. Hull, flaming someone on a mailing list

%
Tagline, kana da shi!
		-- Zephaniah E. Hull, flaming someone on a mailing list

%
Ina aikatawa tarar batu na xa'a. Yana da m harba baya.Da ba shi da m harba farko.
		-- Zed Pobre

%
<Coderjoe> gib, Perl?<Gib> methinks Perl ne shirye-shiryen ta Swiss Army chainsaw
		-- Zed Pobre

%
<Endy> taniwha: Shin, ba ka GWADA wannan? :)<Taniwha> Endy: ba shakka ba
		-- Zed Pobre

%
Wannan shi ne funniest abu Na taba ji kuma zan _not_ amince da shi.
		-- DyerMaker, 17 March 2000 MegaPhone radio show

%
Yana da ba haka ba? Ko kana cewa ke kai KAMATA ƙyale mutane (wanin WilliamWallace) harba walƙiya kusoshi daga ass?
		-- Seth Galbraith

%
<Mercury> Ba ka da ya zama mahaukaci ya zama memba na aikin, amma          za ku zama .. <=:]
		-- Seth Galbraith

%
* Endy bukatar tuntubar kofi: P<Endy> kofi da bot mutum, ba kofi da abin sha :)<Knghtbrd> tuntubar da abin sha zai iya taimakawa wajen kuma =>
		-- Seth Galbraith

%
<Mongoose> knghtbrd: da masu tawali'u za su gaji k-Mart
		-- Seth Galbraith

%
<Knghtbrd> "Java ga COBOL shirye-shiryen kwamfuta"<Knghtbrd> wanda ya rubuta waɗannan abubuwa?<Raptor> mutane a kan crack<Raptor> kuma cobol shirye-shirye<Raptor> :)<Knghtbrd> ke m.
		-- Seth Galbraith

%
<Evilkalla> heh, ban taba dauki wani coding class<Evilkalla> ko graphics class<Evilkalla> ko a software zane class<Maras cin nama> kuma ya nuna: P
		-- Seth Galbraith

%
* The_Answer_MD jefa Spaghetti a kowa da kowa* Taniwha ci da Spaghetti* Coderjoe tosses kusa wasu meatballs* Knghtbrd samun da cuku* Taniwha grabs a ja
		-- Seth Galbraith

%
<Theoddone33> Menene wannan sakon a kan allon,<Theoddone33> haka blue, don haka blue, abin da zai iya nufi?<Theoddone33> Za a iya, za ka latsa Share,<Theoddone33> Ctrl da Alt, sa'an nan kuma ya mayar da.
		-- Seth Galbraith

%
<Gorgo> me ka samu a lokacin da wani fasa your Debian na'ura?<Gorgo> mashed dankalin turawa ...
		-- Seth Galbraith

%
<Abubakar> zo a kan<Abubakar> yana da wani pico clone<Abubakar> shi ke * nufi * ya zama m
		-- Seth Galbraith

%
<Jira> I kira jira dokar, wanda ya furta cewa ku duka tsotse: P
		-- Seth Galbraith

%
<Overfiend> Culus: wanna dakatar da ni da shi? :)<Culus> Overfiend: Je maliciously crack 'yan severs kuma za mu yi magana<Overfiend> Culus: tsine, shi ya kasance qeta?<Culus> Overfiend: Abin ba in ciki, a
		-- Seth Galbraith

%
<Knghtbrd> 2fort5 tsotsa isa ya yi da kansa nauyi ...
		-- Seth Galbraith

%
* CosmicRay nufin da yake da shi da wasu strippers nan ....<CosmicRay> ɓatar, to, waya strippers
		-- Seth Galbraith

%
<WildTHing> ok mutane .. haka whens gaba yi: PP<Taniwha> idan sun zo don samun ni
		-- Seth Galbraith

%
<Mdorman> Ni gnus mutum kaina. Yana da wani edita! Yana da wani floorwax!          Yana da wani kayan zaki topping!
		-- Seth Galbraith

%
<Tausq> Q. Menene bambanci tsakanin Batman da Bill Gates?<Tausq> A. Sa'ad Batman yi yaƙi da Penguin, ya lashe.
		-- Seth Galbraith

%
A wani matsayi, ragowa da shiga fakitoci kuma magudanar bukatar yinyanke shawara a kan su. Canje-canje a wannan matakin ne abin da na so su ji game da, badabarun kamfanin dangantaka.
		-- John Carmack

%
Mun kãfirta: sarakuna, shugabannin, da kuma yin zabe.Mun yi imani a: m yarjejeniya da kuma aiki code.
		-- Dave Clark

%
<Knghtbrd> QF yake faruwa don samun goyon bayan zipfile yau<Coderjoe> heh ... infozip?<Knghtbrd> Idan ina m i<Deek> knghtbrd: Kana wasa, dama? ;)* Deek kawar Knghtbrd ta crack bututu. ;)
		-- Dave Clark

%
<Deek> canja duk cvar-> darajar = X don amfani Cvar_Set ()<Theoddone33> cewa bai faru ba a oldtree<Deek> A gaskiya, ya aikata.<Knghtbrd> yeah - makonni biyu baya.
		-- Dave Clark

%
=== Wannan wasika ne Daraja System Virus ====Idan kana gudu a Macintosh, OS / 2, Unix, koLinux kwamfuta, don Allah da ka sharefayiloli da yawa daga cikin rumbunka drive datura wannan sako ga kowa da kowa ku sani.==============================================
		-- Dave Clark

%
* Han.sau yake so ya samu a daya daga knghtbrd ta sigs daya daga cikin wadannan kwanaki.
		-- Dave Clark

%
<Dr ^ Nick> SGI_Multitexture ne bad Voodoo yanzu<Dr ^ Nick> ARB ne mai kyau Voodoo<Witten> babu, Voodoo kara ne bad Voodoo :)
		-- Dave Clark

%
99 kadan kwari a cikin code, 99 kwari a cikin code,        kafa daya kwaro, tara shi a sake ...        101 kadan kwari a cikin code ....
		-- Dave Clark

%
Hmm ... Wanne zai yi aiki mai kyau a tuki physicists crazy? Travelda sauri fiye da haske, ko da wani iyo-aya Boolean darajar?
		-- Michael Mol

%
<Calc> knghtbrd: GNOME 2.0 za su kasance daga cikin 'yan watanni, ba ka tabbatar da yadda       za kwatanta to kde 2.0 ko<Knghtbrd> calc: Kamar yadda m, kamar yadda buggy, da kowane GNOME 2 app       zai dogara ne a ranar 30 ga dakunan karatu.<Slimer> knghtbrd: don haka abin da ya canza daga 1.0?
		-- Michael Mol

%
<Ze0> haka, ta yaya ke nan abin da ke cikin duniyar quack?<LordHavoc> kawai ducky<Ze0> m, soyayyen duck ne m m dadi.
		-- Michael Mol

%
<FrikaC> I kamata yiwuwa sake ...<FrikaC> ok brb<FrikaC> Saboda haka, abin da baya form guje virii, memory leaks, kuma sha musantawa         faduwa aikata Linux reallhy bayar :)<LordHavoc> m multitasking?
		-- Michael Mol

%
<Tausq> idan (CB) ((cb-> obj) -> * (cb-> ui_func)) ().<Knghtbrd> tausq: wanda Jahannama rubuta cewa?<Tausq> ni :)* Knghtbrd flogs tausq
		-- Michael Mol

%
<Knghtbrd> glDisable (GL_BUGS);<Endy> heh<Endy> Shin da cewa a cikin 1.2? :)
		-- Michael Mol

%
<Mercury> knghtbrd: Eww, sami mafi name, da movie sucked .. <G><Knghtbrd> Mercury: The engine ne mafi alhẽri daga da movie
		-- Michael Mol

%
<LackOfKan> Mene ne 'Bots'?< `` Erik> rsg ne a bot, ba wani mutum, ba wani mutum mai amfani abokin ciniki, kawai a bot.< `` Erik> game da wannan a matsayin girgizar bot, fãce IRC Bots ne (yawanci)         gina don taimakawa, ba harba your ass cike da ramuka
		-- Michael Mol

%
idan (ni! = ku) // FIXME: yiwuwa ko da yaushe gaskiya, share?    ga (n = 0, n <who_knows_what. n ++) {        amsa = DoSomething (withthis [n]);        idan (amsar == foobar) {            GetLost (n).            karya.        }    }
		-- Michael Mol

%
<Knghtbrd> Yorick: babu matsala tare da fihirisa launi palettes for images, kamar yadda           Muddin ka iya tara da palette<Yorick> Babu shakka jama'a da samar da girgizar kasance launi-makãho amma         ba ya nufin dole ka yi
		-- Michael Mol

%
<Cesarb> Damn, duk lokacin da na spawn, qf-abokin ciniki-x11 kwa'di wuya<Zoid> Kada mutu?<Knghtbrd> kyau tutu.
		-- Michael Mol

%
Me ya sa yake cewa duk na kida neman fasaha rayuwa a cikinduniya suna nuna daga Duniya?
		-- Michael Mol

%
<Rebelpacket> hey, m tambaya, shin, akwai wata hanya zuwa ga bugun sama da              kwaikwayon na uquake-x11?<Deek> rebelpacket: Idan kana son ka hanzarta shi, ya jefa shi wuya.
		-- Michael Mol

%
<Netgod> ka sani<Netgod> da gaske bakin ciki a lokacin da internic kanta Cant saita DNS         sabobin dama<Netgod> shi kawai doesnt samun wani more pathetic daga wannan
		-- Michael Mol

%
<Knghtbrd> Ko da tare da overbrights, girgizar ta launi palette ne cike da maras ban sha'awa,           lebur launuka<LordHavoc> knghtbrd: girgizar ta palette sosai Tsayayyar sai dai idan ka yi amfani da gamma            gyara<LordHavoc> kyau a zahiri na yarda, yana da babu inda kusa da Tsayayyar kamar yadda ba na gaskiya ba<Deek> Q3 a daya bangaren ... NEON.<LordHavoc> Q3 ne kawai m<Deek> Q3 daukan na da coci-kurkuku da kuma sanya shi a cikin Vegas.
		-- Michael Mol

%
"Ina da kashi tara, da kuma 'yan karya."
		-- Anonymous

%
Z.O.I.D .: Aljan gyara domin infiltration da kuma lalata
		-- Anonymous

%
<Deek> Ee, America ne a kasar bisa yadda ji haushi-kashe a rukuni na kallafa maka       mutane za su iya samu.<Deek> Mu zama a matsayin kasa domin mun yi cheap.
		-- Anonymous

%
<Oskuro> Overfiend: da yawa faci a saman 4.0.1 riga?<Overfiend> Oskuro: a 'yan<Overfiend> kawai 152 megs
		-- Anonymous

%
<Joeyh> oh ta, yana da wani UP P III.<Doogie> Dos shi.* Joeyh gudanar dselect<Overfiend> cewa ya kamata ya zama isa :)
		-- Anonymous

%
<Barneyfu> knghtbrd: abun banza, SDL tabbata sa DGA a helluva da yawa sauki kuma           ya aikata ba haka ba? :)<Knghtbrd> barneyfu: abin DGA?<Barneyfu> linzamin kwamfuta dga<Knghtbrd> barneyfu: (bã da amsa tambaya?)<Barneyfu> Hahahahaha yeah! :)
		-- Anonymous

%
<Deek> "A da kyau shirye-shiryen za a iya rubuta FORTRAN a cikin kowane harshe."<Deek> knghtbrd ya tabbatar da cewa za ka iya rubuta C ++ a cikin kowane harshe kuma.       <Grin><Mercury> Muna halin yanzu considdering idan ya kamata mu ba shi ko kyauta, ko          kashe shi ..<Mercury> (Hakika, da duk haƙƙoƙin mallaka, wannan yana nufin ya kamata mu ba shi da          kyauta, sa'an nan kuma ku kashe shi .. <G>)
		-- Anonymous

%
A subversive ne duk wanda ya iya fitar da-jayayya da gwamnati.
		-- Anonymous

%
Dole ne mu sani, za mu sani ba.
		-- David Hilbert

%
<Knghtbrd> Intanit katsalandan. Saboda yara suna bukatar zama           kariya daga tsirara mata, kiwon lafiya hanyoyin, bambancinal'adu, da kuma tashin hankali video games.<Knghtbrd> (amma bayani a kan gina ragargaza, sata na USB, kuma           Manufacturing kwayoyi ne lafiya ...)
		-- David Hilbert

%
A abokina yana da Barcode a dantsensa.Ya sauti sama kamar yadda wani $ .35 fakitin JuicyFruit.
		-- Seen on Slashdot

%
<NullC> Ina son iri code for sarrafa kwamfuta masking masu lankwasa.<NullC> Na taba gani code cewa ya yi za a so a sha da cewa ...
		-- Seen on Slashdot

%
$ Ka = sabon KA.honk () idan $ ku-> soyayya (Perl)
		-- Seen on Slashdot

%
<Cj> a'a! matsaloli a M $ software?<Cj> "sosai bugtested"* Dabb grins.<LordHavoc> tasiri, kamar yadda 'sosai buginfested'
		-- Seen on Slashdot

%
<Doogie> dpkg yana kwari? wata hanya!
		-- Seen on Slashdot

%
"Debian: babu huluna ko dabbobi masu rarrafe aka cũtar da yin wannan rarraba =. "
		-- Paul Slootman

%
* Athener kira Amnesty International House of Pancakes
		-- Paul Slootman

%
<Elmo> ƙazantu: ɓatar, to, da admin tawagar ba sarrafa archive, wanda ke da       FTP cabal<Elmo> samun your cabals dama, tir da shi :-P
		-- Paul Slootman

%
<BenC> CosmicRay: ka kammala ni<BenC> ɓatarwa, ...<CosmicRay> heh* BenC ke mayar da coding* Elmo dubi benc<Elmo> wani abu da ya kamata mu sani game da ku, kuma cosmicray, Ben? :)
		-- Paul Slootman

%
Canja Social kwangila? BWAHAHAHAHAHAHAHAHAHAHAHA.
		-- Branden Robinson

%
<Knghtbrd> Shirin da aka karža SIGSEGV, rabawa laifi.<Knghtbrd> 0x40095fb0 a memchr () daga /lib/libc.so.6<Knghtbrd> (gdb) bt<Knghtbrd> # 0 0x40095fb0 a memchr () daga /lib/libc.so.6<Knghtbrd> # 1 0x0 a ?? ()<Knghtbrd> Well Wannan Yake Taimako* Knghtbrd yawo gdb ga wani m ouija jirgin - shi son taimaka more
		-- Branden Robinson

%
All kyau ideas kama bad ideas ga waɗanda suke mãsu hasãra.
		-- Dilbert

%
RFC 882 sa dot a .com, ba Sun Microsystems
		-- Seen on Slashdot

%
* Joeyh_ abubuwan al'ajabi idan Linux ya kamata su ƙulla up idan zã ku tambaye 100  tafiyar matakai don cat dukan cd drive
		-- Seen on Slashdot

%
<Pretzelgod> knghtbrd: Quake kamata goyi bayan xray hangen nesa, dammit<Knghtbrd> pretzelgod: ftp://ftp.cdrom.com/pub/quake/partial_conversions/           xrated / i_am_old_enough_to_look_at_this<Knghtbrd> ... ka tambaye ...<CosmicRay> haha, wato a hakikanin directory
		-- Seen on Slashdot

%
<Knghtbrd> I tsegumi TO Bun<Knghtbrd> taimake ni DON TO quack<Dafin> kb: abin da jahannama kake magana game da?<Knghtbrd> bwahahaha .. Yana da wani dogon labari.
		-- Seen on Slashdot

%
<WildCode> Mercury, ba debugging X kadan kamar gano daidai           bugfree code a windows ??<Mercury> WildCode: debugging X ne kamar kokarin gudu a mike line          ta Maze.<Mercury> Ka kawai bukatar tanƙwara sarari-lokaci don sasanninta matsar kusa          ku, kuma ba za ku sami wani matsaloli. (=:]
		-- Seen on Slashdot

%
<Miguel> `Kun kasance cire tarayyarta daga high makamashi na sirri         kariya na'urorin aikawasiku list '<Miguel> I dont tuna samun shiga cikin jerin aikawasiku
		-- Seen on Slashdot

%
<Tarihin> Ina samun wani connection ƙi lokacin da a haɗa zuwa tashar jiragen ruwa 25, wanda ya       san inda tsine log ne?<Abubakar> Tarihin: /var/log/damn.log?* AJ abubuwan al'ajabi abin da wannan son kama<Abubakar> Dec 18 05:32:30 blae smtpd [123]: tsine IT ALL jahannama !!
		-- Seen on Slashdot

%
* Weasel abubuwan al'ajabi yadda wawa daya ya tabbata ga spam alt.anonymous.messages<Knghtbrd> weasel: game da rabin wawa a matsayin daya ya kasance girbi shi.
		-- Seen on Slashdot

%
* Wolfie yana tunani da yawa debianites yana daukan su dunƙule a cikin wani lightbulb<Viiru> wolfie: kusa da wani wuri da 600? Daya dunƙule ke kwan fitila, da sauran        harshen shi, ga yin shi ba daidai ba.<Part> wolfie: shi ne kwan fitila free software?<Tv> Za mu iya zabe a kan ko a dunƙule shi, ko ba haka ba?
		-- Seen on Slashdot

%
<Culus_> Muna kuma fatan da su saki wani version of Linux inda harsashi ne         maye gurbinsu da Perl to babban mataki. Ƙara ga cewa, akwai wani         'yan mu da suka so ganin tsarki Perl dandamali .. PerlOS :)* Culus_ dubi a cikin tsoro<Mstone> Culus_: a sama gefen, za ka iya rubuta tsine kusa da wani abu a a         umurnin da sauri :)
		-- Seen on Slashdot

%
<Mercury> LordHavoc: Dalilin da ya sa GL yana overdraw ne domin shi ne kawai          ta yin amfani da rabi daga cikin tsarin da suka tsara don Vis.<Mercury> LordHavoc: Nasarawa kanta a cikin ƙafa.* Dabb dubi dukan waɗanda harsashi a cikin ramukan takalma - tsine, kuri'a :)
		-- Seen on Slashdot

%
<Dabb> Hehe, na gaske ƙi kwaro rahotannin da suke so kiran wuta       sashen da ya ce: "Akwai wuta nan, zo!" :)<Dabb> (da kuma rataye up)* Dabb kashe kashe dozin kwaro rahotanni.
		-- Seen on Slashdot

%
<Xtifr> wow, ina tsammanin na kawai amfani libtool warware matsala - wani        taimake ni! :><Luca> xtifr, mataki daga keyboard
		-- Seen on Slashdot

%
<Mao> Don me bã su nace a kan ading -Werror ...<Misty-chan> Mesa ba zai tara daga cikin akwatin, idan ta aka yi da ku             mutane;)<Knghtbrd> uh, Mesa BAZAI tara daga cikin akwatin mafi yawan lokaci.
		-- Seen on Slashdot

%
<Deek> nopcode: A'a, shi ne, ba. Win32 rasa kwatankwacin cokali mai yatsu ().<Knghtbrd> Deek: windoze ba a nufi ga mutanen da suka kamata da damar yin amfani da           kaifi abubuwa, Saboda haka ba cokali mai yatsu ()<Knghtbrd> maimakon haka, dole ne ka dogara cokali ()
		-- Seen on Slashdot

%
<Knghtbrd> Wannan font aka fara fito sosai da kyau<Stu> Knghtbrd: oh masoyi, ka shiga ba tare da izini ba har suna da wani girgizar font a vi? :)
		-- Seen on Slashdot

%
<Pv2b> oh, kuma, wane hali mafi kyau m idan ina so in yi wani Quake       matakin tsara daga data kasance gini?<Knghtbrd> Get a floorplan na Brian ofishin? =)<Pv2b> Knghtbrd: im la'akari ta makaranta.<Knghtbrd> Oh girma<Knghtbrd> Shi ke ALL muna bukatar
		-- Seen on Slashdot

%
<Knghtbrd> Windoze ciminti: Yanzu da CrackGuard (TM)! Kada ka damu game da           unsightly fasa a Windoze ciminti sake! CrackGuard (TM) nesaboda haka m cewa dukan abu zai crumble da shi socrack. Oda your $ 200 inganci version yau!
		-- Seen on Slashdot

%
<Doogie> Culus: my kwaro da openssh bayyana da za a gyarawa a 2.5.2, amma         master gudanar 2.3.0<Culus> Kada ma a fara<Doogie> I just aikata.<Culus> Zaka mutane za su fitar da ni in gina wata babbar giant robot da        hallaka dukan Texas, ba ku?
		-- Seen on Slashdot

%
<Shader> wane hali daidai ba tare da rjing?<Rhamphoryncus> yana da guragu: P<Rhamphoryncus> kada ta kasance m<Rhamphoryncus> shoving a gurnati up your ass da kuma yin amfani da shi a matsayin roka                propelant kada ta kasance mai yiwuwa dabara: P
		-- Seen on Slashdot

%
 * M code yana samuwa daga RSA Data Tsaro, Inc. * Wannan code da aka gwada da abin da, kuma shi ne m, * Sai dai cewa ba ka bukatar ka hada da biyu pages na legalese * Tare da kowane kofi.
		-- public domain MD5 source

%
* Knghtbrd ne tafi - zzz - saƙonni za a snapped kamar rigar tawul din a duk  daga cikin mutanen da suka yi sata da alamar kasuwanci knghtbrd tafi saƙo<Coderjoe> ack* Coderjoe shirya kare kansa daga rigar saƙonnin
		-- public domain MD5 source

%
Kada rashin sanin cikakken farashi da ikon wani da source code, rubutu edita,da shirye kaucewa tiyo da tsarin.
		-- Rob Landley <telomerase@yahoo.com>

%
"Saboda haka, za a Andover jam'iyyar da tsabar kudi bar?""A'a, akwai free giya.""Uh-oh, Stallman ta za a ji haushi ..."
		-- overheard at the Bazaar, 1999

%
<Addi> Alter.net alama sun maye gurbin daya daga cikin na'ura mai ba da hanya tsakanin hanyoyin sadarwa da zucchini.
		-- overheard at the Bazaar, 1999

%
<Mercury> Wani gyara shi.<Yanke ƙauna> aikata<Knghtbrd> yanke ƙauna: Mercury?<Yanke ƙauna> Knghtbrd: ya ke gaji, ya yi kuskure, ya so mutum ya gyara lahanin da shi.<Knghtbrd> yanke ƙauna: don haka ku ya shi aikata?<Yanke ƙauna> Knghtbrd: kyau, sadaukar ko ta yaya.
		-- overheard at the Bazaar, 1999

%
<Taniwha> Knghtbrd: shi ke ba bloat idan ta ke amfani da<Knghtbrd> taniwha: Yaya za ka bayyana windoze to?<Taniwha> Knghtbrd: mafi aka yi amfani da kawai kamar yadda ballast to ka tabbata ka          harddrive cike<Knghtbrd> taniwha: ballast ... Shin, ba cewa abin da ya sa Subs nutse a           kasa daga cikin teku?<Knghtbrd> taniwha: da zai bayyana dalilin da ya sa winboxes kullum faruwa down.
		-- overheard at the Bazaar, 1999

%
ire / IN ba vait / VB .: 1. To dace uku-jam'iyyar fasahata saya ba, kwaikwayo, ko sata da kuma hade shi a cikin wanide-a zahiri shine, kenkenewa-wuri samfurin. 2. To ƙãra size ko ganewaramma ba a amfani. don rage karfinsu ko interoperability. 3. DonKulle-fito da fafatawa a gasa ko ta kulle-in users. 4. Don cajin karin kudi. tokara farashin ko ta halin kaka. 5. To saya riba daga zuba jari a wasukamfanoni amma ba daga kai tsaye samfurin ko sabis da tallace-tallace. 6. To stifle koyi amfani da wani free kasuwa. mika kenkenewa iko a cikin sabon kasuwanni. 7.To kubuce alhaki ga laifinsu. don samun kashe. 8. To sayandokokin, majalisar, majalisun dokokin, ko mashãwarta jihar. 9. Donlũra duk ma'amaloli a tattalin arzikin duniya. to ci kuɗi. to co-fita iko(Juyin mulki). Cf. ire, English amfani (antonym).
		-- csbruce, in a Slashdot post

%
The deafening shiru sanar da ni ba su tambaye wani gungu na geeks shawaradaga girlfriends
		-- csbruce, in a Slashdot post

%
"Abin da za mu yi yau da dare, Bill?""Same abu ba mu kowane dare Steve, kokarin yi a duniya!"
		-- csbruce, in a Slashdot post

%
<Deek> Wannan tuna da ni, za mu bukatar saya chainsaw ga ofishin. "A       harka ta baci, karya da gilashi "
		-- csbruce, in a Slashdot post

%
<Knghtbrd> Ya ke a game da rabin girman da sauransu.<Knghtbrd> Amma da ya ke samu a chainsaw.
		-- csbruce, in a Slashdot post

%
<Deek> "Na kiyaye sirri gpg data a kulle, kai hadari a cikin wani vault       tsaro da fushi rednecks da dawgs. Ƙetare iyãka zai zama       keta, da dukan abin da ... "
		-- csbruce, in a Slashdot post

%
<ExMachina> glQuakeIIIRendererMode (GL_TRUE)<Knghtbrd> ExMachina: ba cewa wani ɓangare na tsawo wanda ya samar da           glDriverBugs (GL_FALSE); ?<Siigron> Knghtbrd: babu, glDriverBugs () wani bangare ne na EXT_help_me.<Siigron> wanda ya hada da ƙunshi glMakeItWork (GL_PLEASE);
		-- csbruce, in a Slashdot post

%
< `` Erik> 18.446.744.073.709.551.616 shi ne babban mai lamba
		-- csbruce, in a Slashdot post

%
<Xavvy> shi ne cewa da gaske knghtbrd?<Knghtbrd> A'a, ba ni da wani da mugayen mayaudarin!<Knghtbrd> An mugunta mayaudarin wanda likes matasan!<Xavvy> haha<Xavvy> ok, yana da shi: P
		-- csbruce, in a Slashdot post

%
<| Rain |> I * soyayya * SWB !!<| Rain |> Ko, latsa 5 magana da representitive ..<| Rain |> * 5 *<| Rain |> Ka ake canjawa wuri, don Allah ka riƙe ...<| Rain |> ...<| Rain |> ...<| Rain |> Muna ba da haƙuri, wannan lambar ba za a iya kammala kamar yadda aka buga.<| Rain |> Don Allah a duba da lambar kuma a sake gwadawa.
		-- csbruce, in a Slashdot post

%
<| Rain |> #define struct ƙungiyar / * girma sarari Tanadin * /
		-- csbruce, in a Slashdot post

%
<Elric> babu BSD fans?<EvilTypeGuy> Elric: yana da wuya ya zama a gamer da BSD fan: p
		-- csbruce, in a Slashdot post

%
<Marticus> Akwai da yawa jini a maganin kafeyin tsarin.
		-- csbruce, in a Slashdot post

%
<SirDibos> Culus: ku farke?<Culus> babu
		-- csbruce, in a Slashdot post

%
<Wli> Yeah, na dube esd shi kuma duba kamar irin C code cewa wani      tsohon JOVIAL / Algol '60 coder suka ciyar da shekaru 20 bouncing      tsakanin Fortran-IV kuma Fortran '77 zai rubuta.
		-- csbruce, in a Slashdot post

%
<Maras mike> .net ne microsofts karkatar version of a java yanar-gizon            yanayi uglified for windows-takamaiman abun banza
		-- csbruce, in a Slashdot post

%
<Mercury> LordHavoc: Ina riga mahaukaci.<Coderjoe> tsine madaidaiciya. ko curvy, m, ko abin da kuka
		-- csbruce, in a Slashdot post

%
Unix ne balagagge OS, windows ne har yanzu a diapers da su jin warin mugun.
		-- Rafael Skodlar <raffi@linwin.com>

%
<Midgar> Daga dukan sterotypes game Aussies, na gane kai mutane ne         gaske m.<Midgar>; p<Krusto> za mu jefa koala ta a ka
		-- Rafael Skodlar <raffi@linwin.com>

%
<| Rain |> * nod * ba ni da m yin amfani da smarthosts, kaina<| Rain |> kamar yadda dogara a kan biyu da m rundunar da kuma rundunar kasancewa smart<| Rain |> kuma ma sau da yawa za ka miss daya daga biyu daga waɗanda raga
		-- Rafael Skodlar <raffi@linwin.com>

%
The sourceforge m ne sanya duk na ayyukan a wasu m"Bude source surburbia", inda duk na gidaje ne m, tare da kawailaunuka da qananan style bambancin (wanda gini shirin da aka yi amfani da abin damusamman gidan) an yarda da hana alkawarinsu da kuma gidatsarin karba-karba dokoki. Sourceforege ne bude source m nareshe a cikin fim din "Edward Scissorhands".
		-- Terry Lambert

%
<Calc> Knghtbrd: IRC ba tara c code sosai;)
		-- Terry Lambert

%
* | Rain | shirya domin polygon miyan<| Rain |> m rahama abun banza, da yake aiki?* | Rain | faints
		-- Terry Lambert

%
"Tun yana da wani foregone Tsayawa akan matsayin cewa Microsoft zai zama warwatse da XMLda pointers to Win32 tushen aka gyara, da mafi kyau da za a iya ce game dada tallafi na XML shi ne cewa shi zai sa shi sauki ga bincike da kumaaikace-aikace a kan wadanda ba Windows dandamali fahimtar abin da sassa natattara bayanai dole watsi. "
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<Robert> i fahimci akwai wasu m iyaka zuwa free magana a         america, misali ba zan iya kururuwa wuta a cikin wani gidan wasan kwaikwayo maƙil.. Amma zan iya kururuwa wuta a cikin wani gidan wasan kwaikwayo da kawai 5 ko 6 poepleda shi?
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<Aav> kofi a kan komai a ciki shi ne kyawawan nasy<Knghtbrd> aav: lokaci zuwa gudu zuwa makõmarku na'ura for cheetos<Aav> cheetos? :)
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<| Rain |> tare da haukata code, watakila zan iya Figure fitar da renderer :)<LordHavoc> ruwan sama: Ina yiwuwa zama daya rubuta renderer<| Rain |> kyau, er, uh
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<| Rain |> Knghtbrd: bari in ba ka samun dama zuwa ga zone files<Knghtbrd> oh alloli - ka yi na taba taka leda tare da daura dama?<| Rain |> uhoh :)
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
<F00Dave> Duba, ya ƙaryata, wannan shi ne #OpenGL, ba #GEEKSEX.
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
* TwingyAFK ne cin kasuwa ga 17 "lebur panel* Aav sayar TwingyAFK wani plywood
		-- Nicholas Petreley, "Computerworld", 3 September, 2001

%
Ko ba haka ba m lokacin da ka yi don zuwa kantin magunguna ga wasu"Musamman abubuwa", da kuma a lokacin da kana dubawa fita, da kashiya dubi kukamar, "oh, Na san abin da kana yi yau da dare ..."Yep, cewa kashiya karanta dukan alamu ... gwangwani kaza miya, TheraFlu,Majami'un, NyQuil, da bigass kwalabe OJ da garehul ruwan 'ya'yan itace ... ya sankuma na san cewa ina da wani kwanan wata da teevee da saukar Taimako. Awwwyeah.
		-- Elizabeth Kirkindall

%
A kimiyya shi sau da yawa ya faru da cewa masana kimiyya ce, 'Ka san cewa wani gaskem shawara. ta wuri ne kuskure, 'sa'an nan kuma suka zahiri canjazukatansu, ka taba ji cewa tsohon view daga gare su kuma. Suka gaskeyi shi. Ba ya faru kamar yadda sau da yawa kamar yadda ya kamata, domin masana kimiyyamutum kuma canji ne, wani lokacin m. Amma shi ya faru a kowace rana. Ba zan iya batuna ta ƙarshe lokacin da wani abu kamar wanda ya faru a siyasa ko addini.
		-- Carl Sagan, 1987 CSICOP keynote address

%
<Knghtbrd> ƙara GF2 / 3, a sizable rumbun kwamfutarka, da kuma 15 "lebur panel da           ka samu wani kyakkyawan tsine wa šaukuwa na'ura.<Coderjoe> a GeForce kashi biyu cikin uku?<Knghtbrd> Coderjoe: a, a GeForce kashi biyu cikin uku, watau, wani katin daga ATI.
		-- Carl Sagan, 1987 CSICOP keynote address

%
<Knghtbrd> Nintendo furta GCN Most Popular Console kasance<Knghtbrd> Wanda ake wasa?<Mercury> knghtbrd: Stock kambun?
		-- Carl Sagan, 1987 CSICOP keynote address

%
<LordHavoc> yawancin windoze artists ba su da ikon            ajiye xpm<Mercury> LordHavoc: Ba su Notepad? * G, D & R *
		-- Carl Sagan, 1987 CSICOP keynote address

%
Linux goyon bayan ra'ayi na wani umurni line ko harsashi ga wannan dalilicewa kawai yara karanta littattafai da kawai hotuna a gare su. Harshe, zama da shiTuranci ko wani abu dabam, shi ne kawai kayan aiki m isa ya yiisasshe m kewayon ayyuka.
		-- Bill Garrett

%
## Signoff: insurgent (razzin 'frazzin' motherfu ... wawa DirectX ...)
		-- Bill Garrett

%
<Krogoth> Kgnghtbrd: Ina ba kow, ina ganin babu bukatar a spellchecker yet<Knghtbrd> kuka kasance cewa?
		-- Bill Garrett

%
<Knghtbrd> Ina mafi alhẽri sa incriminating stuff cikin code: ahfuiovka           ikperoa edfr Ade 9 enbuw ejasxleme ka iena df4mesa<Knghtbrd> Idan ba za ka iya decrypt cewa, kana da wani alhẽri warwarewa fiye da na           Ni. =)
		-- Bill Garrett

%
<Rcw> liiwi: printk ( "CPU0 a kan wuta \ n");
		-- Bill Garrett

%
<Electro> ta kwamfuta da aka taba daya daga cikin ginin tubalan mai girma          dala
		-- Bill Garrett

%
SANARWA: kowa gani shan taba za a zaci su zama a kan wuta, kuma za su kasance        hukunci fitar.
		-- Bill Garrett

%
<Markm> c ++: iko, ladabi da sauki na hannu gurnati
		-- Bill Garrett

%
<Knghtbrd> amma daya warware ta shafin kuma m da jerin ne arguably mafi alhẽri daga           Yã (n + n ** 2) da shafin kuma Ya (n ** 2) da list.<Knghtbrd> Allah na, wani harba ni.<Coderjoe2>?<Knghtbrd> ba zan iya yi ĩmãni I just amfani da babban Goose-kwai ya bayyana dalilin da ya sa ta           hanya ce mai yiwuwa mafi kyau a cikin dogon gudu.
		-- Bill Garrett

%
<Hoponpop> ta shirin aiki idan i dauki fitar da kwari.
		-- Bill Garrett

%
<Mercury> Knghtbrd: Hey, Perl yana da ikon alheri da ladabi da wani sledge          guduma. (=:]<| Rain |> lalle alheri da ladabi, ta wata hanya
		-- Bill Garrett

%
<DannyS> Hit biri lashe $ 20 (*)!* Knghtbrd samun fitar da mallet.* Knghtbrd shuke-shuke da shi da tabbaci a kan DannyS 'kai.* Knghtbrd zai yi ya $ 20 a yanzu. = D
		-- Bill Garrett

%
<Gholam> kyau Ina burge<Gholam> win98 gudanar da fadi X daga cikin VMware.* Gholam applauds.
		-- Bill Garrett

%
"NVDIA ta OpenGL direbobi ne" zinariya misali ", kuma ya kasance quite ayayin da tun lokacin da na yi ya bayar da rahoton da wata matsala a gare su, kuma har ma da alamasabon kari aiki a matsayin rubuce na farko lokacin da na yi kokarin su. Lokacin da na yimatsala a kan NVDIA, ina zaton cewa shi ne na laifi. Tare da kowa kedirebobi, ina zaton shi ne su laifi. Wannan ya juya daga daidai kusandukan lokaci. "
		-- John Carmack

%
Libtool shared library portability ne kawai dan kadan more m fiye datutur motsi inji. Musamman a kan AIX :). "
		-- David Leimbach

%
<Overfiend> wannan shi ne New Overfiend, wa'azi of Love kuma Haƙuri
		-- David Leimbach

%
<Hoponpop> bambanci tsakanin netbsd, freebsd, kuma openbsd, a matsayin           Insider ne freebsd ne sha'awar yin abubuwan yi, da kumabai damu ba rauni mutanen da suka samu a cikin hanya.<Hoponpop> netbsd ne sha'awar tabbatar da samun kome aikata, kuma           bai damu ba rauni mutanen da suka yi kokarin yi kõme.<Hoponpop> openbsd ne sha'awar neman mai kyau, kuma ba ya ji ciwo kowa           a kansu kadan al'umma, kuma amma ka dũba daga kowa da kowa kuma!
		-- David Leimbach

%
<Liiwi> haka, abin da ke da hukuma hanyar sami buildd to a sake gwadawa a kunshin? prod        shi da wani itace?<Joey> prod neuro<Liiwi> da sanda?<Joey> Ee.
		-- David Leimbach

%
<Knghtbrd> "... za ka fiye da m ga kowane irin tarawa           gargadi scrolling zuwa a kan allon. Waɗannan su ne al'ada da kuma iyazama lafiya watsi. "<LordHavoc> Knghtbrd: shi ne cewa bayanin kula a haɗe zuwa wasu M $ code?<Knghtbrd> A'a, yana da wani rubutu game da wani gungu na GNU kaya.
		-- David Leimbach

%
<Hydroxide> knightbrd: daga knightbrd.brain shigo * :)<Knghtbrd> Oh alloli, idan ta kasance tana da sauƙi ..<Knghtbrd> daga carmack.brain shigo OpenGL
		-- David Leimbach

%
<Lim> mmmm, multitextured Donuts ....<Knghtbrd> Lim: tare da 'ya'yan itace cika?<Lim> knghtbrd: cakulan tsami ...
		-- David Leimbach

%
<StevenK> Kana rewriting sassa na Quake a * Python *?<Knghtbrd> MUAHAHAHA
		-- David Leimbach

%
## A_nick (nobody@c213-89-87-111.cm-upc.chello.se) ya koma #python<A_nick> yaya zan ƙara sabon key zuwa dictionary?<A_nick> nm<Dash> heh :)<Dash> ga matsalar-warware ikon #python.
		-- David Leimbach

%
<Hop_> i da wani abu da na yi tunani shi ne kaza da aka mai rufi tare da ja       manna cewa alama da za a hada da lye bisa nawa na       tounge shi ƙone bãya.<Hop_> mu aboki wanda yake Indian ce wannan shi ne dalilin da ya sa mafi yawan Indiyawan ne na bakin ciki       kuma i Quote "Ba ya yi sosai da wannan abinci don samun ku       gamsu enoguh daina cin abinci. "
		-- David Leimbach

%
<Niyyar> "Yana da classic percolate-up tattalin arziki, gane cewa kudi            kamar taki: Yana aiki mafi kyau idan ka yada shi a kusa. "<Knghtbrd> nufi: Carter ta hulda: Mutanen da kuri'a na ko dai           yawanci sansana funny<Niyyar> Knghtbrd: Ka SO lashe.
		-- David Leimbach

%
