#!/bin/bash

/usr/ubin/translate art
/usr/ubin/translate bofh-excuses
/usr/ubin/translate computers
/usr/ubin/translate cookie
/usr/ubin/translate debian
/usr/ubin/translate debian-hints
/usr/ubin/translate definitions
/usr/ubin/translate disclaimer
/usr/ubin/translate drugs
/usr/ubin/translate education
/usr/ubin/translate ethnic
/usr/ubin/translate food
/usr/ubin/translate fortunes
/usr/ubin/translate goedel
/usr/ubin/translate humorists
/usr/ubin/translate kids
/usr/ubin/translate knghtbrd
/usr/ubin/translate law
/usr/ubin/translate linux
/usr/ubin/translate linuxcookie
/usr/ubin/translate literature
/usr/ubin/translate love
/usr/ubin/translate magic
/usr/ubin/translate medicine
/usr/ubin/translate men-women
/usr/ubin/translate miscellaneous
/usr/ubin/translate news
/usr/ubin/translate paradoxum
/usr/ubin/translate people
/usr/ubin/translate perl
/usr/ubin/translate pets
/usr/ubin/translate platitudes
/usr/ubin/translate politics
/usr/ubin/translate riddles
/usr/ubin/translate science
/usr/ubin/translate songs-poems
/usr/ubin/translate sports
/usr/ubin/translate startrek
/usr/ubin/translate tang300
/usr/ubin/translate tao
/usr/ubin/translate wisdom
/usr/ubin/translate work
/usr/ubin/translate zippy
