#!/bin/bash 

mv *.af /usr/share/games/fortunes/af
mv *.ar /usr/share/games/fortunes/ar
mv *.az /usr/share/games/fortunes/az
mv *.be /usr/share/games/fortunes/be
mv *.bg /usr/share/games/fortunes/bg
mv *.bn /usr/share/games/fortunes/bn
mv *.bs /usr/share/games/fortunes/bs
mv *.ca /usr/share/games/fortunes/ca
mv *.cs /usr/share/games/fortunes/cs
mv *.cy /usr/share/games/fortunes/cy
mv *.da /usr/share/games/fortunes/da
mv *.de /usr/share/games/fortunes/de
mv *.el /usr/share/games/fortunes/el
mv *.eo /usr/share/games/fortunes/eo
mv *.es /usr/share/games/fortunes/es
mv *.et /usr/share/games/fortunes/et
mv *.eu /usr/share/games/fortunes/eu
mv *.fa /usr/share/games/fortunes/fa
mv *.fi /usr/share/games/fortunes/fi
mv *.fr /usr/share/games/fortunes/fr
mv *.ga /usr/share/games/fortunes/ga
mv *.gl /usr/share/games/fortunes/gl
mv *.ha /usr/share/games/fortunes/ha
mv *.hr /usr/share/games/fortunes/hr
mv *.ht /usr/share/games/fortunes/ht
mv *.hu /usr/share/games/fortunes/hu
mv *.hy /usr/share/games/fortunes/hy
mv *.id /usr/share/games/fortunes/id
mv *.ig /usr/share/games/fortunes/ig
mv *.is /usr/share/games/fortunes/is
mv *.it /usr/share/games/fortunes/it
mv *.iw /usr/share/games/fortunes/iw
mv *.ja /usr/share/games/fortunes/ja
mv *.jw /usr/share/games/fortunes/jw
mv *.ka /usr/share/games/fortunes/ka
mv *.kg /usr/share/games/fortunes/kg
mv *.kk /usr/share/games/fortunes/kk
mv *.ko /usr/share/games/fortunes/ko
mv *.la /usr/share/games/fortunes/la
mv *.lo /usr/share/games/fortunes/lo
mv *.lt /usr/share/games/fortunes/lt
mv *.lv /usr/share/games/fortunes/lv
mv *.mg /usr/share/games/fortunes/mg
mv *.mi /usr/share/games/fortunes/mi
mv *.mk /usr/share/games/fortunes/mk
mv *.mn /usr/share/games/fortunes/mn
mv *.mo /usr/share/games/fortunes/mo
mv *.ms /usr/share/games/fortunes/ms
mv *.mt /usr/share/games/fortunes/mt
mv *.nl /usr/share/games/fortunes/nl
mv *.nn /usr/share/games/fortunes/nn
mv *.no /usr/share/games/fortunes/no
mv *.ny /usr/share/games/fortunes/ny
mv *.nyn /usr/share/games/fortunes/nyn
mv *.pl /usr/share/games/fortunes/pl
mv *.pt-BR /usr/share/games/fortunes/pt-BR
mv *.ro /usr/share/games/fortunes/ro
mv *.ru /usr/share/games/fortunes/ru
mv *.sh /usr/share/games/fortunes/sh
mv *.sk /usr/share/games/fortunes/sk
mv *.sl /usr/share/games/fortunes/sl
mv *.so /usr/share/games/fortunes/so
mv *.sq /usr/share/games/fortunes/sq
mv *.sr /usr/share/games/fortunes/sr
mv *.st /usr/share/games/fortunes/st
mv *.su /usr/share/games/fortunes/su
mv *.sv /usr/share/games/fortunes/sv
mv *.sw /usr/share/games/fortunes/sw
mv *.tg /usr/share/games/fortunes/tg
mv *.th /usr/share/games/fortunes/th
mv *.tl /usr/share/games/fortunes/tl
mv *.tr /usr/share/games/fortunes/tr
mv *.uk /usr/share/games/fortunes/uk
mv *.ur /usr/share/games/fortunes/ur
mv *.uz /usr/share/games/fortunes/uz
mv *.vi /usr/share/games/fortunes/vi
mv *.yi /usr/share/games/fortunes/yi
mv *.yo /usr/share/games/fortunes/yo
mv *.zh-CN /usr/share/games/fortunes/zh-CN
mv *.zh-TW /usr/share/games/fortunes/zh-TW
mv *.zu /usr/share/games/fortunes/zu

