Ke nahana hore ke e nyenyane fantastis ho leka ho theha setshwantsho a batho ka tsela elikelellong tsa Debian akhaefe thimi tsamaiso huddled ea 'onaboemelong ba, lifahleho tsa bona hotetsa feela ke CRT le e nyenyane khetla motsopotlakileng eo le taelo ea"/project/org/ftp.debian.org/cabal/s3kr1t/nuke-non-free.pl" Bohle keyeda 'me o itokiselitse ho tsamaea, menoana ea bona le mothating oa holim' a kena konopo ya, e leng mofufutso oalustful neng bo sa lebelloa beading melomong ea bona e ka holimo. "<20031104211846.GK13131@deadbeast.net> buisanathaothelang sesole hae Social konteraka phetolo
		-- Branden Robinson in

%
Haeba u eang ho matha e rinky-dink distro entsoeng ke banyalani ba bang babaithaopi, ke hobane'ng ha matha e rinky-dink distro entsoeng ka e ngata baithaopi?
		-- Jaldhar H. Vyas on debian-devel

%
Packages lokela haha-li itšetlehile ka seo ba lokelang ho haha-li itšetlehile.
		-- Santiago Vila on debian-devel

%
Ho na le mefuta 3 of bashanyana - bona ba hloea phlebotomy (kaofela phlebotomy, e le horeke; banana bona ba se ke ua lumella ho hlobola hook they); ba ba tšohileng theoha ka banana baba hanyenyane ho eketsehileng tse bohlale ho feta karolelano; le bashanyana bae boetse e batla a eketsehileng tse bohlale ho feta karolelano, empa ho joalo le lihlong hore baa ke ke a beha mantsoe 2 hammoho ha ba u ka hare ho maoto a 20 ea ngoanana.
		-- Vikki Roemer on debian-curiosa

%
Debian ke Jedi tshebetso ya ho sebetsa: "Kamehla 'meli ho na le, e leng monghali lee Apprentice ".
		-- Simon Richter on debian-devel

%
Sena ke UNIX re ntse u ho bua ka, hopola. Ho ke ke lokela ho bantle bakeng sa ditshebediso a thulaganyo.
		-- Matthew Danish on debian-devel

%
... Empa Hey, sena ke Linux, ke ke ke ha e reretsoe ho etsa loops ke keng ba lekanngoa a 5metsotsoana?
		-- Jonathan Oxer in the apt-cacher ChangeLog

%
Ke ka bouena thabileng haholo le e mong lokolloe tsitsitse seng le se seng ka lilemo tse peli, 'mehoseng oa maikutlo a hore o leka ho lokolla eketsehileng ho tla bolela re tla lokela horename ea distro tsoang "tsitsitse" ho fihlela "wobbly".
		-- Scott James Remnant on debian-devel

%
<Keybuk> Perl 6 scares 'na<Doogie> u ka bolela bagwebi ea hao ntho e itseng. lebitso mona ke          khoele '~ | _ | ~'* Lo-lan-2 baleha tleroha<Keybuk> e shebahala joaloka setshwantshothalo ea loko kanale :)<Jaybonci> Majapane onyeetsang bagwebi?<Nickr> ^ _ ^
		-- in #debian-devel

%
<Sam> /.ing khang e tšoana botsa palo e ke keng a lekanngoa bakeng sa ea litšoene       ho kopa keletso
		-- in #debian-devel

%
<Daniels> sa ntse e, terone ea mali utloahala eka filimi mabapi overfiend           'me baroetsana kapa tse ling crap
		-- in #debian-devel

%
<Jaybonci> ha e le hantle ke d-i emela "ea nang le bomolimo ho kenella ha ';)
		-- in #debian-devel

%
<Doogie> asuffield: hona u nahana dpkg eo qalong e neng e ngotsoe? : |<Asuffield> ka ho lumella iwj fumana kotsi haufi k'homphieutha
		-- in #debian-devel

%
<Asuffield> vmware ke ntho efe kapa efe u ka khomarela ka la somebodies deske             'me Con hore li kene sebelisa
		-- in #debian-devel

%
<Joshk> joshk @ tšubuhlellano: /etc/logrotate.d> sh -n *<Joshk> Apache: moleng oa 14: hokahanngoang bakeng sa liphoso haufi pontšo sa lebelloang `} '<Joshk> Apache: moleng oa 14: `} '<Joshk> plot ea thickens<Asuffield> tseo li ke ke shell mengolo<Erich> ena e ne e se khoho.
		-- in #debian-devel

%
Ke ile ka hlaseloa ke dselect joalokaha ngoana e monyenyane le 'nile tloha ha qojoadebian.
		-- Andrew Morton

%
* Joeyh installs debian sebelisa feela lefielo la hae e khōlō, kaha ba fetole lebelo
		-- in #debian-boot

%
* Liiwi nka sephali le mahlo pasc<Pasc> ohh !!! Kinky!<Pasc> kamoo loketseng, ke ne ke sa tsoa le mothating oa ho bitsa a kula mosebetsing ;-)
		-- in #debian-devel

%
<Lefifing leo> fellang kateng le hore grep khutlela khoutu ya phoso 1 ha ha ho na mollo.       Ke ne ke tseba seo. Ke hobane'ng ha nka 'na halofo ea hora?
		-- Seen on #Debian

%
Ho sa lumeleheng mpa feela bokae matla le boiqapelo batho bainvested ho kena bōpa lia ikhanyetsa, bogus me ba hloka kelello dilaesense ...
		-- - Sven Rudolph about licences in debian/non-free.

%
<Overfiend> partycle: Ke libe tse tebileng ka ho etsa hloka phomolong ho see            sephutheloana. Ke ha e le hantle o ne a e Dream mabapi kenyelletsa            hlokang kelello e ncha kokoanyana ho kena xbase-preinst bosiung bo fetileng. Eo ke            Bad Matsoho.
		-- Seen on #Debian shortly before the release of Debian 2.0

%
<Lefifing leo> shebahalang joaloka mocha oo ke li khutlisetsa ho :) tloaelehile<Jim> O se bolela hore lintho li ke ke scrolling ka potlako ho feta leha e le mang ka bala? :)
		-- Seen on #Debian after the release of Debian 2.0

%
Feela ho atolosa ka seo Ross o ile a re, ho ke ke ha ho pelaelo hore le ho hongata haholo ho lebellaoa ho aba leha e le efe hore e ka tsela e iketsang hlokomela hore na kapa ha eamotho kenya ho ka bala directions bonolo hakana Senyesemane, 'me haeba asitoang, tswela pele ka ntle ho fana malebela a hae. ka tsela eo larileng ka bohlanya.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Zedboy> dackel: ka kakaretso ea * feela * tsela ho sebelisa lenaneo la k'homphieutha         ke ho phethisa eona. U kile ua * * tsejoa e utility tsamaisong bao         ditokomane kgothaletswa ebang hlakola, kapa lahlela eona         pofaalama phoofolo?<Dackel> zedboy: Ummm ... ee<Zedboy> dackel: kenya manpages sephutheloana. e lokela ho moo         se a ntse a Tho.<Zedboy> dackel: mohlala oa e joalo e utility tlhako?* Greycat batla video ea dackel ho akhela / usr / moqomong / faele nakong e sa khomo
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Elmo> Joy: leboha, thabo<Doogie> elmo: seo e sa hlokeheng, elmo<Elmo> doogie: ee bapala ka har'a sephethephethe<Doogie> ah ea elmo rea tseba le ho mo rata
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Doogie> thabo / elmo: na ke hobane'ng ha a ke ke a ea IP tsoanang sebelisoa? e ne e mollo sena kahoo         leholo le hore e chesa atereseng e IP?
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Donnerjack> Ha ho letho le re: "Ke thabela ho phela le uena" joaloka mpho ea             3rd isa tekanyong e chesa ...<Mephron> haese ho hlakileng, ho retelehela bethe ea hae ka trebuchet e.<Ladegard> Hore boiteko bo matla e lokela ho bolele mofuta o itseng oa lerato.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Flimsy> Mang kapa mang ea mona knowledgable litabeng tsa nonyana metsi? haeba u         tsamaea serapeng sa boikhathollo, 'me e le khantsi e qala e latelang u ...' me         qetella latelang u fetang halofo ea k'hilomithara le halofo ho fihlela u fihla         koloi ea hao ... nakong 11pm. Ke likhantsi mabifi kapa ntho e 'ngoe?
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Wolfgang> sa bothata boo le 'tsamaea fumana ngoanana ea sebele' keletso e           hore ba 'maloa hakaalo ho bona ea hlileng na u hlobotse ntlafalo           tatellanong<Ntho ea sebele> Dude, kharebe ea ka e fetola joaloka makhetlo a mane ka letsatsi
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Z-Gryphon> Ha Unicron o ne a e theknoloji spec card ya hao, lepetjo la hae e tla ba "That            e leng ha e fetoha karolo ea 'ngoe e tla fetoha sekheo. "<Z-Gryphon> e mofuta wa o moholo oa tekanyo, timelong phetolelo ea "Ke            na seo ke se jang. ":)
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Liiwi> udp - ea bokahohleng e akhelang oa leeba e
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Lilo> Ke kamehla ne a batla ho ba le setša se ho web ka foto e khōlō ea rantipole e holim 'a eona
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Bdale> Bdale ke khutsufatso ea Barksdale.<Lo-lan-etsa'ng> Hm. Ho hang ha ke ntho eo ke tla kile ua hopola.<Lo-lan-etsa'ng> Mind haeba ke u bitsa Wensleydale e-na?
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Luca> le tseo e re: faeba lik'hebole na le bonyane ba wa koba radius le       hula khohlano joang? Araba! * Yank *<Culus> KE faeba le FREAKS: P<Luca> culus, o hoser, ho faeba. Ke gonna gonna go lokela ho tla holim 'a       Lithaba le u fa wedgie?
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Maswan> Joy: Lets fereko katse! :)<Maswan> Joy: nahana ka pitchfork kholo 'me e katse bafu ka holim'a         eona .. ka mali matha ho theosa ..
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Mjg59> Damnit. Ke na le khoeli ho ngola pampiring. sena se akarelletsa ho        ha e le hantle ngola ea chunks ea khoutu ke tl'o tla bua        ka sehloohong.<Asuffield> fumana tetemang ea liithuti le ho fana ka eona ho bona joalokaha ho ikoetlisa e<Mjg59> asuffield: Ke pota-potiloe ke e tetemang tsa liithuti. Lekhetlo la ho qetela ke        ba ke ba ama khoutu, ke khutla 'me a fumana ba kopa rewritten        tsohle C ++ khoutu a C le sehlopha sohle se C khoutu a C ++<Asuffield> mwahaha<Mjg59> LE ILENG BA Haha
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Moshez> seo ke ratang ka Manoj ke takatso ea hae bakeng sa rarahanang le ho se senyenyane         ditharollo. joaloka EMACS. kapa dvt.<Manoj> hantle, 'dvt ne _supposed_ ho ba bonolo ho e sebelisa<Manoj> eona feela nka qeta libeke tse 2 ho ngola<Moshez> Manoj: Ho hloka *-thalo * ho hlalosa seo karolo ka 'ngoe li etsang.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Moshez> ok,, nke ke nyala khomo Jo-Con-El Molimo.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> metlae le tswang botoneng ba ke siame a k'hamphani tsoakileng. VMS hase !!!
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> Ltd: Khabane, u ee le tsamaeang bophelong feela supa le grunting nakong            seo u se bolelang. Ea sebetsang ho bakeng sa basebedisi Mac.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
hlaoloa 1.17.2.7letsatsi: 2001/05/31 21:32:44; Author: branden; a re: Exp; meleng e ka: +1 -1ARRRRGH !! Got THE G D ** *** utloisisa A F ******* Test morao!
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend_> Overfiend oa Molao Pele ho sephutheloana Quality: Haeba             maintainer like ho peleta karolo kapa kaofela ha lebitso la hae ka             Caps, sephutheloana tla anya.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend_> Intel. Ho Tlisa u ea phelisong bohale theknoloji ea 1979             ka lilemo tse 22 hona joale.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> senotlolo sa ho loketseng French telaffuz ke ho hula            likhutlong tsa molomo oa hao ho theosa ho ea fihla ba ka mohlomong u tsamaee,            'me joale bobola joaloka u constipated<Overfiend> u tla hlile Nail selumi sa senyesemane utloahala tsela eo
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<- Overfiend e tlohela ( "ea moo e phallela timetsa sa tloaelehang tse ncha                         mikili, 'me le je bophelo le tsoelo-pele e ncha ")
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> mofuta oa khabisitse naha mona hore tšeha "AWD" likoloi tsena li le            o le romela bona tumbling ho kena likhohlo
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> Joy: Hey, ke e halo. Assholes emit khase odious.            Ke seo re se etsang.
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> joalokaha lehra ne a re, emetse linako tsohle e sebetsa<Overfiend> ebang seo u se batlang se etsahala, kapa u shoe 'me e ke ke            ferekanngoa hlola<Overfiend> khathatso le filosofi ena ke hore lehra ka tieo            dumela eona
		-- Shawn McMahon on debian-curiosa@l.d.o

%
* Doogie e retelehela ho kena gokul<Overfiend> doogie: qetellong, bohle rea fetoha Manoj<Overfiend> Manoj ke tsepe Debian oa<Overfiend> qetellong re kaofela ha rona re bola ho Manoj
		-- Shawn McMahon on debian-curiosa@l.d.o

%
<Overfiend> empa sheba French. U ka peleta lentsoe seng le se seng ka            puo ea bona phonetically sebelisa feela ka ho ngola litlhaku 6<Overfiend> 4 lilumisoa le 2 liluma-nosi<Overfiend> tsa c, f r bona, k. Le liluma-nosi? Buuoa hantle, e mong le molumo o            etsa ha u na, pipitlelano; tse ding ha u na            letshollo<Overfiend> u lebella hore seratsoana ya dikgopa le lihohoana?
		-- Shawn McMahon on debian-curiosa@l.d.o

%
X-Manoj-Boemo-Boeletsi: Ka kōpo hlokomela hore ka etsahala hore ebe Manoj Srivastava belaelang    linnete tse pakang seo leha e le efe posited le hanyetsa liqeto leha e le efe fihla a molaetsa ona.
		-- Seen in the headers of a mail from Branden Robinson

%
<Sangr> lehae ke moo kgonothebolo phahameng ka ho fetisisa ke
		-- Seen in the headers of a mail from Branden Robinson

%
<Sangr> che perl more ... e nyahamisang ...<Sangr> Ke nahana perl le ke hloka nako e itseng le e mong le tse ling<Sangr> re ile ra etsa 'mino o monate' moho mabapi selemong se fetileng ...<Sangr> empa ka makhetlo a na fetola, re ile ra fetola ..
		-- Seen in the headers of a mail from Branden Robinson

%
<StevenK> I ka hangata supress ea maikutlo ao mpolella hore etella          loantša ngoanana eo ho kena lihlahla
		-- Seen in the headers of a mail from Branden Robinson

%
<Wiggy> bwah, Krrish a toeba ea ka
		-- Seen in the headers of a mail from Branden Robinson

%
<Wiggy> a e hlollang rea sisinyeha e ncha ke ha e le hantle lekoa jarisa ena
		-- Seen in the headers of a mail from Branden Robinson

%
<WiggyWork> 3990 N Apr 15 Cute kharebe (45) Kopanela Liphate Hardcore likharebe<WiggyWork> Ke ne ke sa hlokomele u ne u le likharebe profeshenale haesita
		-- Seen in the headers of a mail from Branden Robinson

%
Leha ho le joalo, cheseho ea ka e le sefate modular e bonolo ke likarolong tse ling tsahase teng.bokamoso ba X
		-- Daniel Stone on debian-{x,devel}, commenting on the

%
Na o ile a nahana hore re mpa ba batla hore a lule ho potoloha ho penta debian swirls leeto la ronatoenails?
		-- Erinn Clark, referring to the Debian-women project

%
modconf (0.2.37) tsitsitse tsitsang; boemo bo potlakile = seaplane  [...]  * Eduard Bloch:    - Tsitsitseng Makefile robehileng Marcin Owsiany nakoana fetileng. The manpage ya kamehla      e 'nile ea overwritten nang phetolelo ea bentsa. Ke sa ntse ke ipotsa hore na ke hobane'ng      ha ho motho o ile a hlokomela sena ka pel'a. Koala: # 117474  [...]
		-- Eduard Bloch <blade@debian.org>  Sun, 28 Oct 2001 12:53:27 +0100

%
<| Ryan |> Ha ke sebelisa deb<Netgod> appa mofutsana ea<Disconnect> netgod: kmren<Kingsqueak> loketseng tikolohong-fumana kenya mosebetsi o mong-p0rn
		-- Eduard Bloch <blade@debian.org>  Sun, 28 Oct 2001 12:53:27 +0100

%
(Hoa sa khale Debian neano ho tlohela bonyane habeli ka selemo ...)
		-- Sven Rudolph

%
<Joey> gorgo: * lol! *<Gorgo> Joey: seo 's ho le joalo qabola? :)<Culus> shh, Joey e lahleheloa ke hlanya tsohle ho hloka boroko bo<Culus> 'ee Joey, qabola haholo'<Culus> Humor eena:>
		-- Seen on #Debian

%
* SynrG bolela hore palo ea botsa lipotso tse ngata phetolo ho araba ka sendmail  Ke Non-reng letho
		-- Seen on #Debian

%
* JHM limakatso seo Joey entseng ho fumana "Nka feela ka rata ho bua, etsoe tlaleho ea,  hore Joey busa. "
		-- Seen on #Debian

%
Ha batho ba joaloka hlahloba setsheng sa inthanete Debian seng le se seng metsotso e 5 ho hlahloba e hamorphed ho kena mong ho e mong? Eseng hore ke e 'ngoe ea ho bua, empa batho ba bang ba ka ka ho tebalokela ho fumana bophelo bo.
		-- james on #Debian

%
* Jakobo e ne e tla ba ho feta ke ile ka khahloa haeba matla netgod oa boselamose ne thibela  petsoha ka sebaka sa pele ...* Netgod bolela debian ke jwa ba tumme ka ho leng thata ho ba khahlisa
		-- Seen on #Debian

%
   * Ka tebello ea 2.10.02 lokolloe, ntjhafatswa ho patchlevel     +ircu2.10.01+.config6-7.config7-8.lgline3.iwho.limit.glibc.motdcache2.trace.whois1-2.config8-9.statsw.sprintf2-3.msgtree2.memleak1-2+.msgtree2-3.gline8-9.gline9-10.invite2.rbr.stats.numclients.whisper.whisper1-2.stats1-2.nokick1-2.chroot.config9-11.snomask7-8.limi+t1-3.userip1-3.userip3-4.config11-12.config12-13.umode2-3.akillsbt.who4-5.kn.kn1-2.freebsdcore2.msgtree3-5.y2k.glibc1-2.rmfunc.msgf+lags2.who5-6.nickchange2.glibc2-3.modeless3
		-- From the annoucement of ircd 2.10.01-3 for Debian GNU/Linux

%
* Joey lokela ho ngola dikenyo changelog 5:30 hoseng<Joey> * DFSC Free recently laebrari<Joey> Efe eo? DFSC?<Jim> Debian Free Software mroooooCows
		-- Seen on #Debian

%
<Jakobo> hlekefetsa 'na. Ke kahoo holofetseng ka romela tlaleho kokoanyana ho debian-devel-liphetoho tse
		-- Seen on #Debian

%
<Lefifing leo> ja itšetlehile: pheha | ja-tsoa.       Empa ho ja-tsoa ke bao e seng mahala e le hore 's tsoa.       Le ho pheha Buella: hloekileng-lipane.
		-- Seen on #Debian

%
U ke ke ua e hlahlobe ho 'na ka kokoanyana bokhukhuni.
		-- James Troup

%
<Doogie> Monahano ho kotsi. Ho isa litlhahiso.
		-- Seen on #Debian

%
<Jakobo> Na re tla etsa emacs tsoang ho loketseng tikolohong?        Loketseng - Debian a lenaneo la. E esita etsang hlatsoetsoang ea hao
		-- Seen on #Debian

%
Debian e tšoana Suse nang yast reteleha tima, feela hamolemo. :)
		-- Goswin Brederlow

%
Charles Briscoe-Smith <cpbs@debian.org>:  Ka mor'a hore tsohle, sephutheloana gzip o bitsoa `gzip 'ona, eseng` libz hours' ...James Troup <troup@debian.org>:  Uh, mohlomong ka lebaka la hobane gzip binary ha tsoa  non-ntseng di le teng libz sephutheloana kapa ea ntseng di le teng zlib sephutheloana.
		-- debian-bugs-dist

%
<Jim> Lemme etsa bonnete ba ha ke ho senya nako mona ... bcwhite tla tlosa      pkgs hore havent e tiisitsoe hore na ditsitsiri ikhethang oa ho tiea      "Bohlokoa". 'Nete kapa bohata?<JHM> Jim: "bohlokoa" kapa phahameng. 'Nete.<Jim> Joale re u le mothating oa ho lahleheloa ke ftp.debian.org le dpkg :)* Netgod tla hloloheloa dpkg - e ne e ka linako tse ling le thuso<Joey> Re ntse re na rpm ....
		-- Seen on #Debian

%
Ho overloaded ke pontšo ea ho ba motsoalle oa 'nete Debian maintainer.
		-- JHM on #Debian

%
Ke 'na ra makalla hore ebe ha ho na motho-li thehiloe e kabo ea oona likhoele tsa khoebo hodima Debianleha ho le joalo - ho ke ke ka ho go feta ya ho fetisisa tse tiileng UNIX-joaloka OS Ke leha e le neng hlomamisa,'me ke' nile ka bapala le HP / UX, Solaris, FreeBSD, BSDi, 'me SCO (eseng hobolele OS / 2, Novell, Win95 / NT)
		-- Nathan E. Norman

%
> <Boselamose +3 feheloa oa pheteletso deflection>The branden dodges feheloa ea hao ea boselamose. The branden hlasela u nang le mantsoe arinya oa mantsoe aa! The branden hloloheloa!
		-- Henning Makholm in <yahsmr7dk9k.fsf@pc-043.diku.dk>

%
Ha ke nahane 'Ho molemo ho feta betsa u ithata ho kena ka hara nama grinder'ke sepelago molemo bakeng sa ho etsa ntho e itseng.<20030905221055.GA22354@doc.ic.ac.uk> hodima debian-devel
		-- Andrew Suffield in

%
<Overfiend> whew.<Overfiend> ke hlile ke lokela ho fumana ba bang ba robala.<Overfiend> empa e bonnete ba ile ithabisa bua likatara, sa lipolotiki le lesbian.
		-- Andrew Suffield in

%
Mang kapa mang ea mo botsa hore na oa debian mokhatlo o hlophisitsoeng o ne a shoele ha a baladebian-devel. 66 melaetsa ka letsatsi le le leng, 'me e se e felile. Ke fumana hothata ho khema.
		-- Bruce Perens

%
<Asuffield> faeba ka US e joalo e le motlae. likarolong tse tsoetseng pele tsa             lefatše, DSL * qala * ka lebelo moo faeba US lumellang tima<Joshk> asuffield: AUSTRALIA ke sechaba se tletseng lintho tse savages?<Asuffield> joshk: ba saletsoe ke hoo e ka bang 9600 ve pakeng tsa nako ena kaofela             naha damn
		-- in #debian-devel

%
<Nobse> bleh ... bosiung bo fetileng ke ne ke toro ... motho e mong NMU'ed vim ...         litorong
		-- in #debian-devel

%
