A letsatsi le letsatsi ka liqeto tse re tiile !!!!! Kapa ha ho joalo?
		-- Ashleigh Brilliant

%
Lihora tse seng kae mohau ka pel'a bohlanya qala hape.
		-- Ashleigh Brilliant

%
A mpho ea lipalesa e haufinyane o tla etsoa hore u.
		-- Ashleigh Brilliant

%
A nako e telele-lebaloa moratuoa tla hlaha kapele.Buy li-negative ka theko leha e le efe.
		-- Ashleigh Brilliant

%
A se selelele, se lefifi ho osele ea tla ithabisa ho u feta.
		-- Ashleigh Brilliant

%
Ho etela sebakeng se itseng ka foreshe tla tlisa mosebetsi makatsa.
		-- Ashleigh Brilliant

%
Ho etela sebaka se makatsang tla tlisa mosebetsi bocha.
		-- Ashleigh Brilliant

%
A kelello ea e hlakileng 'me a ho bōpa e tšoaeang uena.
		-- Ashleigh Brilliant

%
Lahla ho batla 'Nete; rarolla bakeng sa e le toro molemo.
		-- Ashleigh Brilliant

%
Accent ka lehlakoreng thusa mantsiboea ea tlhaho ea hao. Drain ea foro.
		-- Ashleigh Brilliant

%
Tsoelo-pele ea boemong.
		-- Ashleigh Brilliant

%
Ka mor'a hore ea ratang oa hao o tsamaile u ntse u tla lokela PEANUT botoro!
		-- Ashleigh Brilliant

%
Thapameng e tšoanelang haholo bakeng sa ho ratana. Leka motho e le masoha ka phetoho e.
		-- Ashleigh Brilliant

%
Alimony le tjotjo li tla kopanela le kabelo e kholo ea leruo la hao.
		-- Ashleigh Brilliant

%
likhathatso tsohle tseo u nang tla feta ka potlako haholo.
		-- Ashleigh Brilliant

%
Har'a tse swathika, ke uena eo khethileng.
		-- Ashleigh Brilliant

%
An sehatsetsing avocado-ba modumo o ne a tla talima ntle ho tswella hao.
		-- Ashleigh Brilliant

%
E leng leeto eksotiske a litsi tsa Newark ke bokamosong ba hao.
		-- Ashleigh Brilliant

%
E 'ngoe bosiu bo bong le se ke la robala holim'a sefate eucalyptus.
		-- Ashleigh Brilliant

%
Na u sekolopata?
		-- Ashleigh Brilliant

%
Na u kile ua ke a etsa lijana? Kapa u tla fetola ka sehloohong tse ba hao hore ba baeloji?
		-- Ashleigh Brilliant

%
Na u ena eohle joaloka uena tsamaea?
		-- Ashleigh Brilliant

%
Na u kholisehile monyako o ka morao e notletsoe?
		-- Ashleigh Brilliant

%
ditabeng bonono totobatsa. Rob e leng musiamo.
		-- Ashleigh Brilliant

%
Qoba utloisisane ke khobile matšoafo, otlolohile, 'me ho leka-lekana.
		-- Ashleigh Brilliant

%
Qoba lithunya ya ho hlapela bosiung bona bona.
		-- Ashleigh Brilliant

%
Qoba ntho ea sebele ho sa tsotellehe tsohle.
		-- Ashleigh Brilliant

%
phosong Bank e emelang hao. Li Bokelleng '$ 200.
		-- Ashleigh Brilliant

%
Ela hloko! Na classified?
		-- Ashleigh Brilliant

%
Ela hloko! Mobe otlang 9 ho ba 10!
		-- Ashleigh Brilliant

%
Ba hlokolosi litabeng tsa hao letsatsi le letsatsi.
		-- Ashleigh Brilliant

%
Ba nyakaletse ha u ntse u phela.
		-- Phathotep, 24th Century B.C.

%
Ba fapaneng: lumellane.
		-- Phathotep, 24th Century B.C.

%
Ba lokolohile 'me ba bula le ho foka moea o pholileng! Thabela! Lintho ke ke ba leha e le efe hamolemo ho joalotloaela ho eona.
		-- Phathotep, 24th Century B.C.

%
Ba elang hloko tlhoko security - National ikarabella ka kotsing.
		-- Phathotep, 24th Century B.C.

%
Beauty le kutloano ke tse ho hlokahala hore ho uena joaloka phefumoloho ea bophelo.
		-- Phathotep, 24th Century B.C.

%
Molemo ka ho fetisisa ea libaka tsohle tse ho mohla ho tsoaletsoe. Bobeli e molemohali ke ho shoa kapele.
		-- Phathotep, 24th Century B.C.

%
Molemo le ho Feta tšepo ea bophelo-mohlahlobi ha a tle ho potoloha ha u ntse u ba na tsa haobophelo joalo mess.
		-- Phathotep, 24th Century B.C.

%
Hlokomela se lefifi wa moriri motho ea nang le thae lentsoe le phahameng.
		-- Phathotep, 24th Century B.C.

%
Hlokomela se selelele batsho motho ea nang le lieta e le 'ngoe blond.
		-- Phathotep, 24th Century B.C.

%
Hlokomela se selelele blond motho ea nang le batsho seeta le 'ngoe.
		-- Phathotep, 24th Century B.C.

%
Hlokomela Bigfoot!
		-- Phathotep, 24th Century B.C.

%
Hlokomela lirurubele tlase fofang.
		-- Phathotep, 24th Century B.C.

%
Hlokomela tse 'ngoe ka mor'a hao.
		-- Phathotep, 24th Century B.C.

%
Letsa ka eona litsebe tsa hao.
		-- Phathotep, 24th Century B.C.

%
Roba ho kena chankaneng 'me ba bolela mapolesa sehlōhō.
		-- Phathotep, 24th Century B.C.

%
Koala pele. Lefa khoa mang.
		-- Phathotep, 24th Century B.C.

%
Temoso: ho hema ka 'na ba le kotsi ho bophelo ba hao.
		-- Phathotep, 24th Century B.C.

%
Temoso: Boloka moo ho sa fihleloeng bana.
		-- Phathotep, 24th Century B.C.

%
Keteka Hannibal Day selemong sena. Nka tlou ho lijo tsa motšehare.
		-- Phathotep, 24th Century B.C.

%
Fetola maikutlo a hao 'me u fetola lefatše hao.
		-- Phathotep, 24th Century B.C.

%
Thaba! Lintho li mpefala ka lebelo lenama.
		-- Phathotep, 24th Century B.C.

%
Chess bosiung bona bona.
		-- Phathotep, 24th Century B.C.

%
Chicken Little feela ea nang le ho ba le letona-hang.
		-- Phathotep, 24th Century B.C.

%
Chicken Little ne a nepile.
		-- Phathotep, 24th Century B.C.

%
Cold matsoho, ho se na litlelafo.
		-- Phathotep, 24th Century B.C.

%
Buisanang! E ke ke ho etsa lintho leha e le life le ho feta.
		-- Phathotep, 24th Century B.C.

%
Mphe sebete se teng ya hao le tlhokahalo e kholo.
		-- Phathotep, 24th Century B.C.

%
Letsatsing la ae botse. O tla subpoenaed.
		-- Phathotep, 24th Century B.C.

%
U se ke ua overtax matla a hao.
		-- Phathotep, 24th Century B.C.

%
U se ke ua robala ka mokhoa o eucalyptus sefate bosiung bona bona.
		-- Phathotep, 24th Century B.C.

%
Etsa letho ntle le hore u lokela ho, 'me ha u lokela ho sebetsa - leqe.
		-- Phathotep, 24th Century B.C.

%
Etsa ntho e sa tloaelehang kajeno. Lefa bili e.
		-- Phathotep, 24th Century B.C.

%
Etsa eng ka tlhaho. Seethe le fume me u le lahlele e tantrum.
		-- Phathotep, 24th Century B.C.

%
ho tlisa thabo e ruuoang le metsoalle ea tšepahalang.
		-- Phathotep, 24th Century B.C.

%
U se ke ua fepa bo-'mankhane bosiung bona bona.
		-- Phathotep, 24th Century B.C.

%
U se ke ua ile a khomarela ka oteropo e - apara u ithata ho tsoa mathateng.
		-- Phathotep, 24th Century B.C.

%
U se ke ua fihla ikhantsetsa.
		-- Phathotep, 24th Century B.C.

%
U se ke ua palama maqhubu a South Dakota ka nakoana.
		-- Phathotep, 24th Century B.C.

%
U se ke ua hloea u ithata hoseng - boroko bo fihlela motšehare.
		-- Phathotep, 24th Century B.C.

%
U se ke ua aka tlou e melomong ea kajeno.
		-- Phathotep, 24th Century B.C.

%
U se ke ua lumella likelello tsa lōna hlahlathele - e 's ho honyenyane haholo ho ke tsoa le mong.
		-- Phathotep, 24th Century B.C.

%
U se ke ua hetla morao, ea lemmings ba fumane ho uena.
		-- Phathotep, 24th Century B.C.

%
U se ke ua talima ho fihlela joale, empa motho a khoeli e tšeha uena.
		-- Phathotep, 24th Century B.C.

%
U se ke ua talima ho fihlela joale, empa ho na le selotlolo l ¯ oe sebōpuoa lehetleng la hao.
		-- Phathotep, 24th Century B.C.

%
U se ke ua rera susumelletsa leha e le efe ea lepotlapotla. U tla lelekoa haufinyane khomarela.
		-- Phathotep, 24th Century B.C.

%
U se ke ua bala leha e le efe sepakapakeng-ho ngola bakeng sa dibeke tse peli tse latelang.
		-- Phathotep, 24th Century B.C.

%
U se ke ua bala sohle seo u se lumelang.
		-- Phathotep, 24th Century B.C.

%
U se ke ua phutholoha! Ho tsitsipano ea hao feela hore lintho li tšoere u hammoho.
		-- Phathotep, 24th Century B.C.

%
U se ke ua bolella mashano leha e le efe tse kholo kajeno. ba banyenyane ka ba feela joalokaha ho atlehe haholoanyane.
		-- Phathotep, 24th Century B.C.

%
U se ke ua tšoenyeha ho joalo le phahameng, roommate oa hao a ke ke a nahanang ka eona.
		-- Phathotep, 24th Century B.C.

%
U se ke ua tšoenyeha, Thabe.
		-- Meher Baba

%
U se ke ua tšoenyeha. Life 's nako e telele haholo.
		-- Vincent Sardi, Jr.

%
Na ha u ikutloe ka ho fetisisa jwalekaha u se etsang hona joale ho u feta ile a etsa ha u kena '?
		-- Vincent Sardi, Jr.

%
Na ha u lakatsang eka u ne matla a eketsehileng ... kapa ka tlaase ho rata botumo?
		-- Vincent Sardi, Jr.

%
Tsohle tse u tsebang hore se fosahetse, empa u ka otloloha ho tsoa mathateng.
		-- Vincent Sardi, Jr.

%
Tsohle li tla feela tickety--boo kajeno.
		-- Vincent Sardi, Jr.

%
Excellent letsatsi bakeng beha Slinkies hodima escalator e.
		-- Vincent Sardi, Jr.

%
Excellent letsatsing lena ho tla ba le letsatsi la bolileng.
		-- Vincent Sardi, Jr.

%
nako babatsehang ho be motho ea mphetang.
		-- Vincent Sardi, Jr.

%
bokhoni ba lekgotla la phethahatso e hlaheletseng e ileng ea ea heno etse-up.
		-- Vincent Sardi, Jr.

%
Bontšang hlokolosi litabeng tsa hao letsatsi le letsatsi.
		-- Vincent Sardi, Jr.

%
Lebella lengolo le tsoang motsoalle ea tla botsa emelang uena.
		-- Vincent Sardi, Jr.

%
Lebella mpe ka ho fetisisa, ho e monyenyane o ka se etsang.
		-- Vincent Sardi, Jr.

%
Fine letsatsi bakeng metsoalle.Joalo-joalo bakeng sa tsatsi le uena.
		-- Vincent Sardi, Jr.

%
Fine letsatsi la ho sebetsa tima eneji feteletseng. Utsoa ntho e 'ngoe e boima.
		-- Vincent Sardi, Jr.

%
Leruo: O tla hlaseloa Laboraro se tlang ka 3:15 p.m. ke a tšeletseng bahlabani basabole sebelisa litlhapi tse pherese glued ho lithuthuthu Harley-Davidson.Oh, le ho ba le letsatsi le monate!
		-- Bryce Nesbitt '84

%
Future sheba spotty. O tla qhalana sopho a mantsiboea.
		-- Bryce Nesbitt '84

%
Ho Fana ha hodimo le phetheho ke lipakane tsa hao ka ho sa feleng.
		-- Bryce Nesbitt '84

%
Mo fa karabo evasive.
		-- Bryce Nesbitt '84

%
Nahana ka botumo ba hao. Nahana fetola lebitso le ho fallelamofuta o mocha oa toropong kgafetsa.
		-- Bryce Nesbitt '84

%
Fana hao kajeno ntlehali. Leholimong tseba ho li haella.
		-- Bryce Nesbitt '84

%
Ee bosiung bona baesekopo. Lefifing fetoha uena.
		-- Bryce Nesbitt '84

%
Ka letsatsi le molemo bakeng sa ho fetola boemo bona. Repaper lerakong kamoreng.
		-- Bryce Nesbitt '84

%
Ka letsatsi le molemo bakeng sa ho hlōla litšitiso. Leka e steeplechase.
		-- Bryce Nesbitt '84

%
Lumela ho sebelisana le batho libakeng tse phahameng; haholo-holo ke jeoa ke bolutu stewardesses.
		-- Bryce Nesbitt '84

%
Ka letsatsi le Good to theolele metsoalle ea khale ea neng a hloka thuso.
		-- Bryce Nesbitt '84

%
litaba tse molemo hōle ka u tlisetsa amohela ka moeti.
		-- Bryce Nesbitt '84

%
litaba tse molemo. dibeke tse leshome ho tloha ka Labohlano e tla ba letsatsi la le ntle molemo.
		-- Bryce Nesbitt '84

%
robala hantle ho qeta le lelapa, empa qoba likhang le molekane oa hao oatse ncha ratang.
		-- Bryce Nesbitt '84

%
Khanya e tala ka A.M. bakeng sa diporojeke tse ncha. Khanya e khubelu a P.M. etsoe litekete sephethephethe.
		-- Bryce Nesbitt '84

%
Tšepo ea hore ka letsatsi leo ka mor'a hore u shoe a le letsatsi le monate.
		-- Bryce Nesbitt '84

%
Haeba u ka bala sena, u le haufi-ufi le eena.
		-- Bryce Nesbitt '84

%
Haeba u ithuta ntho e 'ngoe e se nang thuso letsatsi le letsatsi, ka selemo se nang balekane u tla ithuta365 tse se nang thuso lintho.
		-- Bryce Nesbitt '84

%
Haeba u jala habore ea hao e hlaha, le tšepo bakeng sa ho hloleha chai.
		-- Bryce Nesbitt '84

%
Haeba u eme hlooho ea hao, u tla fumana labnyomok a moriri oa hao.
		-- Bryce Nesbitt '84

%
Haeba u nahana Labobeli qetela e ne e le hula, ho letela ho fihlela u bona se etsahalang hosasane!
		-- Bryce Nesbitt '84

%
Haeba bophelo ba hao e ne e le pere, u tla ba le ho thunya ho eona.
		-- Bryce Nesbitt '84

%
A ea litepisi tsa bophelo, u tla molemohali nka lifte.
		-- Bryce Nesbitt '84

%
Eketseha tsebo e tla u thusa hona joale. Na fono molekane oa bugged.
		-- Bryce Nesbitt '84

%
Ke hore hlile le e bala see?
		-- Bryce Nesbitt '84

%
See hlile etsahalang?
		-- Bryce Nesbitt '84

%
Ke kahoo ho leng thata haholo hore e beon-ya hao-ipatlele-nka-tlhokomelong-of-u ithata-hobane-ho na-ke-ha ho se motho e mong--to-etsa'ng-it-bakeng-uu holile.
		-- Bryce Nesbitt '84

%
E se eka kapa a ke ke a ba le molemo, empa e ntse e lokela ho etsoa.
		-- Bryce Nesbitt '84

%
E 'ohle e ne e le tse fapaneng ka pel'a lintho tsohle li tsamaea fetoha.
		-- Bryce Nesbitt '84

%
Ho e haholo * __ UN * swathika bekeng e oo ba lokelang ho o ile a nka bafu.
		-- Churchy La Femme

%
Ho bohle a nahanne ka, Ya tsebe.
		-- Churchy La Femme

%
Ho swathika u tlil'o kahoo butle, hobane u ntse u tsamaea ka tataiso e fosahetseng.
		-- Churchy La Femme

%
hobane feela molaetsa ba ka 'na ha ho mohla tla amoheloa ha ho bolele ho ke keha le ba bohlokoa ho romela.
		-- Churchy La Femme

%
Feela ho na le ho ke ke ho lekaneng.
		-- Churchy La Femme

%
Boloka le mafolofolo maikutlong. Ipatlela neurosis u li ratang.
		-- Churchy La Femme

%
Boloka khutsoanyane ka lebaka pithy.
		-- Churchy La Femme

%
Lady Luck tlisa chelete ea leruo ea ekelletsoa kajeno. Lady motsoalle nka hōle bosiung bona bona.
		-- Churchy La Femme

%
Ithute ho u etse khefu - kapa letho le molemo leo ba ka fumana ho uena.
		-- Churchy La Femme

%
E-re ke behe ka tsela ena: kajeno e tla ba le phihlelo ea ho ithuta.
		-- Churchy La Femme

%
Bophelong ke ho u e khahlellana a le sebete a mangata.
		-- Churchy La Femme

%
"Bophelo, loathe eona kapa hlokomoloha taba ena, u ke ke ua e rata."
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Phela lefatšeng le ea hao, empa kamehla amohela baeti.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ba phelang bophelo ba hao bo mosebetsi o thata hakaale, e e-s'o ka se e leka neng pele.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Long bophelo bo letetsoe uena.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Bona bonela 'me le bone bofelo bo ho tloha tšimolohong.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Lerato le ka haufi. Ba lerato ho motho eo e leng adores uena.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Etsa lakatsa, ho ka 'na phethahetse.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
liphetoho tse ngata kelellong le maikutlong; u se ke ua tsila-tsila nako e telele haholo.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ha ho mohla ho khelositsoe holim'a tseleng ea bokhabane.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ha ho mohla etsa bouena! A motho e mong etsa uena.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ha ho mohla fana ka intshi!
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ha ho mohla phetla ha dragones fofa ka holim'a bona.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ha ho mohla li senola ho pheha khang ea hao molemo ka ho fetisisa.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Next Labohlano ke ke ba letsatsi la hao swathika. Joalokaha e le taba ea e le hantle, u saeba le letsatsi le swathika selemong sena.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ke 'nete hore u na le morero o - ho fumana morero.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Batho ba qala ho hlokomela uena. Leka ho apara ka pel'a u tloha lapeng.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ka letsatsi le phethahetseng bakeng scrubbing fatse 'me lintho tse ling e thabisang.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Belaetsang letsatsi.Botsa motho ntho e itseng.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Reply hazy, botsa hape hamorao.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Baballa eneji: ba sa thahaselleng.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Likepe li sireletsehile boema-kepeng, empa ba ne ba ka mohla ho ne ho bolela hore ke lule moo.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ea liehang letsatsi. Tloaetseng ho bo etsa hahaba.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Snow Day - lule lapeng.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Kahoo sena ke eona. Re tlil'o shoa.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Kahoo u khutlisetsa ... ka nako ...
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Motho e mong o bua hantle ka uena.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Motho e mong o bua hantle ka uena.How sa tloaelehang!
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Motho e mong eo u lahla kajeno, u tla lahla joang hosasane.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Lula hole le fofang saucers kajeno.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Lula hole le maholiotsoana ka nakoana.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Ho lula a phatlalatsa thohako.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Sephiri seo u 'nile lebelang, ha ho joalo.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Nako e tokelo ea ho etsa metsoalle e mecha.
		-- Marvin, "Hitchhiker's Guide to the Galaxy"

%
Lefatše lohle le ke Tuxedo 'me u para ea lieta e le putsoa.
		-- George Gobel

%
Ho na le monyetla oa 20% la hosane.
		-- George Gobel

%
Ho na le fofa ka la nko ea hao.
		-- George Gobel

%
Ho na le e ne e le mohala o bakeng sa lōna.
		-- George Gobel

%
Ho tla ba le liphetoho tse khōlō bakeng sa lōna empa u tla thaba.
		-- George Gobel

%
Lintho tla khanya ka P.M. cop A tla khanya le leseli sefahleho sa hao.
		-- George Gobel

%
Nahana ka makhetlo a mabeli ka pel'a bua, empa ha ba re "nahane nahana tobetsa tobetsa".
		-- George Gobel

%
Sena ke bophelo ba hao. Ngoe ea eona o ile a fuoa ho uena; ba bang kaofela, o ile a etsa u ithata.
		-- George Gobel

%
Sena e tla ba khoeli e hopolehang - ho sa tsotellehe hore ka matla hakae u leka ho lebala eona.
		-- George Gobel

%
Nako ea ho ba mabifi. E-eang ka mor'a hore a tattooed Virgo.
		-- George Gobel

%
Kajeno ke National Existential Ennui lemoha Day.
		-- George Gobel

%
Kajeno ke letsatsi la pele la ba bang kaofela ba mess.
		-- George Gobel

%
Kajeno ke letsatsi la pele la bophelo bohle ba hao.
		-- George Gobel

%
Kajeno ke letsatsi la ho qetela la bophelo ba hao ho fihlela joale.
		-- George Gobel

%
Kajeno ke joang hosasane u tšoenyehile mabapi maobane.
		-- George Gobel

%
Kajeno ke se ileng sa etsahalla maobane.
		-- George Gobel

%
weirdness kajeno ke eona e entseng joang hosasane oa hore na ke hobane'ng.
		-- Hunter S. Thompson

%
Hosane tla hlakola ka lebaka la ho hloka thahasello.
		-- Hunter S. Thompson

%
Hosane, sena se tla ba karolo ea sa fetoheng tsa nakong e fetileng empa ka lehlohonolo,e ntse e ka fetola kajeno.
		-- Hunter S. Thompson

%
Hosane, u ka kae kapa kae.
		-- Hunter S. Thompson

%
Bosiung bona u tla lefa moputso oa sebe; Se ke la lebala ho siea chelete e itseng.
		-- Hunter S. Thompson

%
Bosiung bona 's bosiu: Boroko e le sefateng eucalyptus.
		-- Hunter S. Thompson

%
Tletseng likhathatso bakeng sa tsatsi le baroetsana feta 16 ba e ntle le e ruileng ka phelalifateng eucalyptus.
		-- Hunter S. Thompson

%
'Nete e tla tsoa hoseng hona. (E leng ka hlile mess ema ho fihlela lintho.)
		-- Hunter S. Thompson

%
Leka lintho tse Moo Shu Pork. Ho molemo haholo-holo kajeno.
		-- Hunter S. Thompson

%
Leka ho fumana kaofela ha likhau tsa hao posthumous esale pele.
		-- Hunter S. Thompson

%
Leka ho ba le bophelo bo molemo e le u ka se khonang tlas'a maemo.
		-- Hunter S. Thompson

%
Leka ho khatholoha le ho thabela bothata bona.
		-- Ashleigh Brilliant

%
Leka ho ananela lit sobotsi le thuso ho e 'ngoe ea ratang uena.
		-- Ashleigh Brilliant

%
Labobeli mor'a Lunch ke nako marang la beke.
		-- Ashleigh Brilliant

%
Labobeli ke Laboraro la bophelo bohle ba hao.
		-- Ashleigh Brilliant

%
Ho ile ha etsahala'ng bosiung bo fetileng se ka etsahala hape.
		-- Ashleigh Brilliant

%
Ha u ntse u haufinyane tjena ba le mathata a hao ya matha, ba nile ka regrouped leetsa tlhaselo e 'ngoe.
		-- Ashleigh Brilliant

%
Ngola bothata u le mong lengolo le sokelang le pene tellang karabo.
		-- Ashleigh Brilliant

%
U qubu ea matla, kamehla e tsamaea.
		-- Ashleigh Brilliant

%
U fluke oa bokahohle; u na tokelo ea ho ba mona.
		-- Ashleigh Brilliant

%
U motho e sa hlokeheng haholo, le hore 's ea mofuta ofe motho eo u leng sona.
		-- Ashleigh Brilliant

%
Ha ho mohla u phathahane.
		-- Ashleigh Brilliant

%
U ke tse ke na le uena.
		-- Ashleigh Brilliant

%
U khonang ho rera bokamoso ba hao.
		-- Ashleigh Brilliant

%
U ferekane ebile; empa sena ke puso e ea hao tloaelehileng.
		-- Ashleigh Brilliant

%
O ka ho teba khomaretse metsoalle ea hao 'me bao ba ba tloaetseng.
		-- Ashleigh Brilliant

%
U li reretsoe hore e be commandant ea ntoa banna balefapheng la lipalangoang.
		-- Ashleigh Brilliant

%
U se tšepahale, empa ha ho mohla ho isa bohōleng ba utloisa motsoalle.
		-- Ashleigh Brilliant

%
O fairminded, toka le lerato.
		-- Ashleigh Brilliant

%
U bonelang hōle, e leng tla ngolla molemo, e ratang ea chesehang, 'me motsoalle e mong oa ba tšepahalang.
		-- Ashleigh Brilliant

%
O loanela ho pholoha a ipatlele monate le bonolo tsela ea hao.
		-- Ashleigh Brilliant

%
U eang ho e-na le tse ncha lerato taba.
		-- Ashleigh Brilliant

%
U khoheli a reheletsoeng ka ba hao.
		-- Ashleigh Brilliant

%
U se ke ua bafu yet. Empa ho shebella bakeng litlaleho tse eketsehileng.
		-- Ashleigh Brilliant

%
U nomoro 6! Ke tseo palo ea tsona e 'ngoe?
		-- Ashleigh Brilliant

%
U sa le mocha hanngoe feela, empa u ka lula immature e sa lekanyetsoang.
		-- Ashleigh Brilliant

%
U hlokolosi ho tšepahala, hlathe koana le koana, 'me a tobile haholoanyane. Ka hona una le metsoalle ba bakae.
		-- Ashleigh Brilliant

%
U kula, o sothehileng le khopamise. Ke rata hore a motho.
		-- Ashleigh Brilliant

%
U tle u tena hore ha ke bona u maoto a ka robala.
		-- Ashleigh Brilliant

%
O eme menoana ea ka.
		-- Ashleigh Brilliant

%
O nka u ithata tla fihlela joale ka botebo haholo.
		-- Ashleigh Brilliant

%
Ke uena motho feela ho kile ua fumana molaetsa ona.
		-- Ashleigh Brilliant

%
U bohlale, witty, le e hlollang, empa u qeta nako e ngata haholo ho balamofuta ona wa lithōle.
		-- Ashleigh Brilliant

%
U leka lintho tseo u sa li rera ka lebaka esita ea ea hlokang kelello ea hao e feteletseng.
		-- Ashleigh Brilliant

%
U ka batla monyetla oa hao oa e bekeng ena. Blackmail e lekgotla la phethahatso phahameng.
		-- Ashleigh Brilliant

%
U ka etsa hantle haholo a likhopolo-taba tse hokae naha kapa ho hong ho etsa le ditshilao amehile.
		-- Ashleigh Brilliant

%
U ka hira sebaka se sengata bakeng sa sena feela $ 5 ka beke.
		-- Ashleigh Brilliant

%
U ka phela bophelo bo betere, haeba u ne u le kelello e molemo le e lerato le 'mele oa hamolemo.
		-- Ashleigh Brilliant

%
U se tikatiko rera ho qala nako e itseng ho phela haufinyane.
		-- Ashleigh Brilliant

%
U letsetsa 5483.
		-- Ashleigh Brilliant

%
U bontša mekhoa e babatsehang ea sekgatlhi le mekhoa e metle.
		-- Ashleigh Brilliant

%
U se ke ua ba hlōlehile ho fihlela u se u khotsofatsoa ke ho ba e mong.
		-- Ashleigh Brilliant

%
U thabela ho ba le botsoalle le batho ba bang.
		-- Ashleigh Brilliant

%
U ikutloa ka kakaretso ngata ka ho fetisisa jwalekaha u se etsang hona joale ho u feta ile a etsa ha u tloaetseng.
		-- Ashleigh Brilliant

%
U tlatsa lekhalo lintho tse ngata-ho hlokahala.
		-- Ashleigh Brilliant

%
U phelisana hantle haholo mong le e mong haese liphoofolo le batho.
		-- Ashleigh Brilliant

%
U ne u ba bang ba fumana thabo ea 'hanngoe, empa batsoali ba hao ba falla,' me u ile a tlameha hotlohela morao.
		-- Ashleigh Brilliant

%
U na le kananelo e tebileng ea bonono le 'mino.
		-- Ashleigh Brilliant

%
U na le thahasello e tebileng ho sohle seo ke bonono.
		-- Ashleigh Brilliant

%
U na le botumo ba hore u ho feletseng tšepahalang 'me ka tšeptjoang.khauho A hore ho feletseng o sa tšoanelang.
		-- Ashleigh Brilliant

%
U na le matla bakeng sa boipiletso bona bo ba bong bo fapaneng.
		-- Ashleigh Brilliant

%
U na le matla bakeng sa boipiletso bona bo litho tsa ho kopanela liphate u le mong.
		-- Ashleigh Brilliant

%
O na le takatso e matla bakeng sa thuto ea lehae le lithahasello tsa lelapa la hao tla pele bophelong.
		-- Ashleigh Brilliant

%
U na le batho ba ikhethang e le kannete matla.
		-- Ashleigh Brilliant

%
O na le lengolo la thato ya e ka susumetsoa ke bohle bao u tla kopana le bona.
		-- Ashleigh Brilliant

%
O na le bokhoni ba ho utloa 'me ba tsebe' nete e phahameng.
		-- Ashleigh Brilliant

%
U na le lintho tsa tlhaho makoko le ka etsa lebitso u ithata.
		-- Ashleigh Brilliant

%
U na le thepa e sa tloaelehang hore u atlehe. Ba bonnete ba hore sebelisa ka tsela e nepahetseng.
		-- Ashleigh Brilliant

%
O na le e sa tloaelehang a khoheli botho. U se ke ua tsamaea haufi-ufi le eena hodintho tsepe feela tse sa tlamella fatše.
		-- Ashleigh Brilliant

%
O na le kutlwisiso e sa tloaelehang ea mathata a likamanong tsa batho.
		-- Ashleigh Brilliant

%
U 'nile ua khetha bakeng sa thomo lekunutu.
		-- Ashleigh Brilliant

%
O na le ntaramane Egepeta: u tla ba le kaliyo.
		-- Ashleigh Brilliant

%
O ne a e-tlhotlheletso nako e telele a lekanyelitsoeng ho khoebo.
		-- Ashleigh Brilliant

%
O na le talenta e ikhethang ea bongoli ba libuka linaheng tseo u lokelang ho e nka ka bohloko bo boholo hore ba be.
		-- Ashleigh Brilliant

%
O na le metsoalle e mengata le bao e leng lira tse 'maloa haholo tse phelang.
		-- Ashleigh Brilliant

%
Ha u na le lira tse sebele.
		-- Ashleigh Brilliant

%
U nkile u ithata ka botebo haholo.
		-- Ashleigh Brilliant

%
O na le 'mele oa e 19 selemo ka eona. Ka kopo khutla ka pel'a eona gets bukkake wrinkled.
		-- Ashleigh Brilliant

%
O na le bokhoni ba ho ithuta ho liphoso. U tla ithuta lintho tse ngata kajeno.
		-- Ashleigh Brilliant

%
O na le matla a ho susumetsa bohle bao u tla kopana le bona.
		-- Ashleigh Brilliant

%
U tsebe ho ngola joalokaha eka motho e mong hobane SELEMO E LATELANG U TLA BA"Motho e mong."
		-- Ashleigh Brilliant

%
U ka rata ho theha setsoalle e ncha le ho etsa bao ba ba tloaetseng e ncha.
		-- Ashleigh Brilliant

%
U shebahala joaloka lidolara milione. All tala 'me wrinkled.
		-- Ashleigh Brilliant

%
U sheba khathetse.
		-- Ashleigh Brilliant

%
U rata khotso.
		-- Ashleigh Brilliant

%
U rata lehae la hao le batla hore e be ntle.
		-- Ashleigh Brilliant

%
U ka 'na be li felile joang hosasane, empa seo ha se bolele hore u ne u ke ke ua mona kajeno.
		-- Ashleigh Brilliant

%
U ka 'na ua se lekanngoe nyenyane ho feta linthong tse ling tseo, empa u se lekanngoee kholoanyane ho feta ba bang.
		-- Ashleigh Brilliant

%
U ka 'na ua lemoha hore haufinyane. Ipata.
		-- Ashleigh Brilliant

%
U ka 'na fumana e le monyetla oa bakeng sa tsoelo-pele ea kajeno. Shebella it!
		-- Ashleigh Brilliant

%
U ka 'na tšoenyeha ka moriri wa hao-etsa'ng kajeno, empa botoro joang hosasane ho hongata peanut tlaho rekisoa.
		-- Ashleigh Brilliant

%
U lokela nako e ngata; 'me mohlomong u tla kamehla.
		-- Ashleigh Brilliant

%
U lokela ho se ho ngongoreha nako e telele ka bokamoso. Empa lekhetlong lena e hosasane u tla be ke shoele.
		-- Ashleigh Brilliant

%
Ha ho mohla u ba leqe ho loantša mathata thata ka ho fetisisa.
		-- Ashleigh Brilliant

%
Ha ho mohla u tseba hore na metsoalle e mengata o na ho fihlela u hira ntlo lebōpong.
		-- Ashleigh Brilliant

%
Hona joale u na le Asia Ntaramane.
		-- Ashleigh Brilliant

%
U na le ntja, empa u ka feela fepa katse.
		-- Ashleigh Brilliant

%
U rerang lintho tseo u sa esita leka ka lebaka la tlhokomeliso ea hao e feteletseng.
		-- Ashleigh Brilliant

%
U rua nahanne ka eseng feela sothile, empa ha e le hantle sprained.
		-- Ashleigh Brilliant

%
U khetha ho ba le botsoalle ba bong bo fapaneng, empa ba ratoa ke ba hao.
		-- Ashleigh Brilliant

%
U nyarosoa tsoang sa jese litheohelang ea; u atisa ka tlhaho nģ'a phethehileng eo.
		-- Ashleigh Brilliant

%
U batla ho sireletsa batho bao u rata le ho u rata ka seabo sa tsa mofani wa.
		-- Ashleigh Brilliant

%
U tla putsoa ka ho ketso e dastardly.
		-- Ashleigh Brilliant

%
U lokela ho emulate heros hao, empa u se ke ua jara haholo. haholo-holohaeba ba shoele.
		-- Ashleigh Brilliant

%
U lokelang ho tsamaea re ee mahae.
		-- Ashleigh Brilliant

%
U se nang balekane-handedly loana tsamaee u kene mess ena hlotseng lithipa.
		-- Ashleigh Brilliant

%
U ruta molemohali seo u fetisisa lokela ho ithuta.
		-- Ashleigh Brilliant

%
Le uena u ka apara lesale la nko mitten.
		-- Ashleigh Brilliant

%
U 'meli e lokela ho ba hlokolosi haholoanyane - lerato la hao e ka hula pele ka lilemo tse' me lilemo.
		-- Ashleigh Brilliant

%
U tla lula fumana kamohelo moholo ka ho fetisisa bakeng sa mosebetsi o bonyane rata.
		-- Ashleigh Brilliant

%
U tla lula ba le mahlohonolo litabeng tsa hao.
		-- Ashleigh Brilliant

%
O tla hohela batho rutehileng 'me ba baetsi ba lapeng la hao.
		-- Ashleigh Brilliant

%
U tla ba mohloli kajeno. Khetha loana le e mene ea lilemo li.
		-- Ashleigh Brilliant

%
O tla atamela sechabeng, ntle le ho bapala ka matla leha e le efe khethehileng karolong hao.
		-- Ashleigh Brilliant

%
O tla thusa haholo ka motho a bao u nahana hore ke se bohlokoa.
		-- Ashleigh Brilliant

%
O tla hlaseloa ke phoofolo ea nang le 'mele oa phiri, ho ea fihla mohatleng oatau, 'me sefahleho sa Donald Duck.
		-- Ashleigh Brilliant

%
O tla audited ke hare Lekgetho Service.
		-- Ashleigh Brilliant

%
O tla fuoa khau ea ho hlokomoloha ho sireletseha ha ho pholoseng motho e mong.
		-- Ashleigh Brilliant

%
O tla fuoa ba bang ba tlotla e khōlō.
		-- Ashleigh Brilliant

%
O tla fuoa Nobel Khotso Moputso ... posthumously.
		-- Ashleigh Brilliant

%
U tla bitsoa holim ho thusa motsoalle ea bothateng.
		-- Ashleigh Brilliant

%
O tla hlalane pele selemo se fela.
		-- Ashleigh Brilliant

%
O tla fuwa post oa ho tšepana le ho ba le boikarabelo.
		-- Ashleigh Brilliant

%
O tla tšoareloa koeteloa ke sehlopha fetelletseng.
		-- Ashleigh Brilliant

%
O tla hlompha bakeng sa tlatsetsa nako ea hao le bokhoni ba ho sebelisa e be sesosa tšoaneleha.
		-- Ashleigh Brilliant

%
O tla koalloa chankaneng ka tlatsetsa nako ea hao le bokhoni ba ho sebelisa e tlatlapo bankeng.
		-- Ashleigh Brilliant

%
O tla nyaloa ke ka hare ho selemo, 'me ka hare ho hlalane' meli.
		-- Ashleigh Brilliant

%
O tla nyaloa ke ka hare ho selemo.
		-- Ashleigh Brilliant

%
O tla e utloisisoang hampe ke batho bohle.
		-- Ashleigh Brilliant

%
O tla lemoha hore le hlomphuoa joaloka moeta-pele oa sechaba ea.
		-- Ashleigh Brilliant

%
O tla reincarnated joalokaha digogwane e; 'me u tla thaba haholo ho hongata.
		-- Ashleigh Brilliant

%
O tla matha holim 'ke teraka biri.
		-- Ashleigh Brilliant

%
O tla matha holim 'ke bese.
		-- Ashleigh Brilliant

%
O tla qolla tsoa bakeng nyolloa mosebetsing ka mosebetsi oa hao.
		-- Ashleigh Brilliant

%
U tla ba e atlehileng ka lerato.
		-- Ashleigh Brilliant

%
O tla makatsoa ke se lerata le phahameng.
		-- Ashleigh Brilliant

%
O tla pota-potiloe ke mabothobothong.
		-- Ashleigh Brilliant

%
U tla ba motho oa ho qetela ho reka Chrysler.
		-- Ashleigh Brilliant

%
U tla ba lehlatsipa la soasoa tloaelehang.
		-- Ashleigh Brilliant

%
U tla bolelloa ka eona moo Hosasane. E-eang 'me Home Lokisetsa Thyself.
		-- Ashleigh Brilliant

%
O tla ba tsamaeang le kena fumanang leruo leo e.
		-- Ashleigh Brilliant

%
U tla nang le mapheo ke betri-ba khahlanong le sefofane se seng.
		-- Ashleigh Brilliant

%
U tla fetoha ruileng le ba tummeng ntle le hore u se ke.
		-- Ashleigh Brilliant

%
O tla konteraka lefu le ka seoelo.
		-- Ashleigh Brilliant

%
O tla kopanela e joalo mosebetsing tsa kgwebo chelete e ngata.
		-- Ashleigh Brilliant

%
U tla ba le takatso e matla ea ho e etsa se molemo; empa e tla feta.
		-- Ashleigh Brilliant

%
U tla ikutloa u lapile hape ka hora e 'ngoe.
		-- Ashleigh Brilliant

%
U tla lebala hore u kile ua ntseba.
		-- Ashleigh Brilliant

%
U tla fumana chelete ke nke khato e molemo fattening.
		-- Ashleigh Brilliant

%
U tla fumana chelete ke likhopolo-taba tse kapa lothari.
		-- Ashleigh Brilliant

%
U tla fumana chelete ke ketso e seng molaong.
		-- Ashleigh Brilliant

%
U tla fumana chelete ke ketso ea boitšoaro bo bobe.
		-- Ashleigh Brilliant

%
U tla fumana seo u se tšoaneloa.
		-- Ashleigh Brilliant

%
U tla fana ka motho e mong sengoathoana sa kelello ea hao, eo u ka kula khona.
		-- Ashleigh Brilliant

%
U tla ba le nako e telele 'me u tena bophelo.
		-- Ashleigh Brilliant

%
U tla ba le puisano e susumetsang e telele e le e sa thabiseng le baokameli ba hao.
		-- Ashleigh Brilliant

%
U tla ba le thabo ea sebele e ruuoang le metsoalle ea tšepahalang.
		-- Ashleigh Brilliant

%
U tla ba le mahlohonolo le ho hlōla mathata a mangata.
		-- Ashleigh Brilliant

%
U tla ba le nako e telele 'me ka bophelo bo botle bophelong.
		-- Ashleigh Brilliant

%
U tla utloa litaba tse molemo ho e mong o nahana hore botsoalle ho uena.
		-- Ashleigh Brilliant

%
U tla rua ba limilione tsa liranta.
		-- Ashleigh Brilliant

%
U tla rua fuoa chelete e itseng kapa sengoathoana nyenyane ea mobu.
		-- Ashleigh Brilliant

%
O tla phela nako e telele, bophelo bo botle, bophelo bo thabileng le etsa mekotla ea chelete.
		-- Ashleigh Brilliant

%
U tla phela ka ho bona litloholo tsa hao.
		-- Ashleigh Brilliant

%
U tla lahleheloa ke mosebetsi wa hao hona joale le lokela ho fetoha ka ntlo le ntlo mayonnaisemorekisi.
		-- Ashleigh Brilliant

%
U tla kopana le motho ea bohlokoa hakaale ba tla u thusa hore u ntšetse pele ipabolang.
		-- Ashleigh Brilliant

%
Ho mohla u tla tseba tlala.
		-- Ashleigh Brilliant

%
U ke ke ua kgethilweng ho ofising ea phatlalatsa selemong sena.
		-- Ashleigh Brilliant

%
U tla mamela kapa e qhibilihisitsoeng silevera tla tšela ho kena litsebe tsa hao.
		-- Ashleigh Brilliant

%
O tla outgrow molemo hao.
		-- Ashleigh Brilliant

%
O tla hlōla litlhaselo tse etsoang metsoalle le boulele.
		-- Ashleigh Brilliant

%
U tla feta ka potlako haholo.
		-- Ashleigh Brilliant

%
O tla lefa bakeng sa libe tsa hao. Haeba u se u leshwa, ka kōpo hlokomolohangmolaetsa ona.
		-- Ashleigh Brilliant

%
O tla bula maliboho la pele la Martian kolone.
		-- Ashleigh Brilliant

%
Mohlomong u tla nyala ka mor'a hore a lefereho tse khutsoanyane haholo.
		-- Ashleigh Brilliant

%
U tla fihla ka ho fetisisa ho khoneha e thahasellisang ka ho ya hao ya kgwebo kapa mosebetsi ona.
		-- Ashleigh Brilliant

%
U tla fumana lefa la e tla beha u li ngotseng ka holimo e batlang.
		-- Ashleigh Brilliant

%
U tla hopola ntho e 'ngoe eo u sa lokelang ho li lebala.
		-- Ashleigh Brilliant

%
O tla haufinyane lebala lena.
		-- Ashleigh Brilliant

%
O tla haufinyane kopana le motho ea tla phetha karolo ea bohlokoa bophelong ba hao.
		-- Ashleigh Brilliant

%
O tla hata bosiung mobu oa linaheng tse ngata.
		-- Ashleigh Brilliant

%
U tla etsa sohle ho finyella sepheo sa hao, empa feela ka lebaka tsa haomariki a haelloang.
		-- Ashleigh Brilliant

%
O tla hlōla sera sa hao.
		-- Ashleigh Brilliant

%
O tla etela Dung likoti tsa Glive haufinyane.
		-- Ashleigh Brilliant

%
O tla hlōla katleho nakong ea ho sa tsotellehe hore ipiletsang u amohela.
		-- Ashleigh Brilliant

%
O tla lakatsa u ne u seng sona.
		-- Ashleigh Brilliant

%
U sebetsa ka thata haholo. U se ke ua leka ho nahana ka tsona.
		-- Ashleigh Brilliant

%
U tšoenyeha le ho hongata haholo mabapi mosebetsi oa hao. Thibela. Ha u lefile ho lekaneng ho tšoenyeha.
		-- Ashleigh Brilliant

%
U ne u tla haeba u ka se khonang empa u ka khonang ha ho joalo u tla se ke ua.
		-- Ashleigh Brilliant

%
U ka rata ho se etsa mbalakaka, empa hore 's tsamaeang butle haholo.
		-- Ashleigh Brilliant

%
U tla bitsoa ho a morago ga kalogo hlokang bokhoni ba ka sebetsana lihlopha tsa batho.
		-- Ashleigh Brilliant

%
U tla masoabi ...
		-- Ashleigh Brilliant

%
U tla thaba devilish bosiung bona bona. Krrish likatiba daenamaete ka tlas'a flamenco motantsi oaloma serethe.
		-- Ashleigh Brilliant

%
U tla ikutloa u imolohile ka hlaha hang ha o nile ka tetse tšepo.
		-- Ashleigh Brilliant

%
U sa tla hlola ba monna 'mè oa hao o ne a!
		-- Ashleigh Brilliant

%
U sa tla hlola a bona libakeng tsohle kapa u bale libuka tsohle, empa ka lehlohonolo,ba ntse u ke ke ua 'ohle kgothaletswa.
		-- Ashleigh Brilliant

%
U tla lakatsa eka u neng a li entse lintho tse ling tse ka thata ha ba sa le eo ho leng bonoloho se etsa.
		-- Ashleigh Brilliant

%
U karete e tla lokela ho sebetsana le.
		-- Ashleigh Brilliant

%
U hoo e ka bang jwalo ka ha thabileng joalokaha u nahana hore u na le.
		-- Ashleigh Brilliant

%
U qetellong ea tsela eo hape.
		-- Ashleigh Brilliant

%
U ntse latela. Etsetsoa ea hanky-panky matsatsi a seng makae.
		-- Ashleigh Brilliant

%
U ntse li etsahala ka nako e etsang le phetoho e bitsoa "Life."
		-- Ashleigh Brilliant

%
U se tikatiko lethathamong bona. botsa potso ena botsa hlahlamang ke seo le siyo lenaneng ho ke ke.
		-- Ashleigh Brilliant

%
U hōla ba felloa ke a mang a mathata a hao, empa ho na le ba bang horeu hōla ho.
		-- Ashleigh Brilliant

%
U se ke ua mofuta wa ka. Ka lebaka leo, u se ke ua esita le mefuta e ea ka !!!
		-- Ashleigh Brilliant

%
U mpe ebile 'mè oa hao apara u qabola.
		-- Ashleigh Brilliant

%
U sebetsa ka tlas'a na bokooa hanyenyane. Ho ka etsahala hore e be ea batho.
		-- Ashleigh Brilliant

%
U 'nile ea isang bophelong ke fumane ntja ea hae. Lula tima thepa ea ka tlung eo.
		-- Ashleigh Brilliant

%
sepheo sa hao e phahameng 'me ka ho le letona.
		-- Ashleigh Brilliant

%
e ikemiseditse ba hao ba phahameng, 'me u khonang ho hongata.
		-- Ashleigh Brilliant

%
mohlahlobisisi oa hao o na le uena tsoakane nyoloha le mamello haholoanyane 'ngoe. U se ke ua lumela entho O re uena.
		-- Ashleigh Brilliant

%
matšeliso matleng a hao ke tšepo ea hore lintho tseo u hlōlehileng ho fumana e ne e sehlile se swanelwago nang.
		-- Ashleigh Brilliant

%
mookameli oa ya hao hloa lere ea e kopanetsoeng, se fosahetseng ke fositse.
		-- Ashleigh Brilliant

%
mookameli oa hao ke disementshisi seng kae tsa pikiniki e.
		-- Ashleigh Brilliant

%
mohlankana oa hao o chokolete ho basele.
		-- Ashleigh Brilliant

%
ya hao ya kgwebo tla kena dilekanyetso sabaletseng.
		-- Ashleigh Brilliant

%
ya hao ya kgwebo tla ea feta nakong ea ho atoloha ho telele.
		-- Ashleigh Brilliant

%
botebo hao ea kutloisiso ea ka 'na ba etsa hore u hlepha ka litsela tsa lefatše.
		-- Ashleigh Brilliant

%
bophelo ba hao e ruuoang e ka 'na lumellana.
		-- Ashleigh Brilliant

%
fofa oa hao e ka 'na bulehetse (empa u se ke ua sheba e mpa feela e hona joale).
		-- Ashleigh Brilliant

%
likhantsi hao e pheha.(Lelinyane Your ya hajwale e cha haholo!)
		-- Ashleigh Brilliant

%
pelo ea hao e hloekile, 'me kelello ea hao e hlakileng,' me moea oa hao ea chesehang.
		-- Ashleigh Brilliant

%
ho hloka tsebo ea hao ea cramps moqoqo ka.
		-- Ashleigh Brilliant

%
bophelo ba hao e ne e tla tsa lefeela haholo haeba u ne u sa isa letho ka ikoahlaelang tsona.
		-- Ashleigh Brilliant

%
lerato bophelong ba hao e tla ba bo thabileng le tse lumellanang.
		-- Ashleigh Brilliant

%
lerato bophelong ba hao e tla ba ... thahasellisang.
		-- Ashleigh Brilliant

%
moratuoa oa hao le ka mohla lakatsa ho ka u tlohela.
		-- Ashleigh Brilliant

%
mmala wa hao wa swathika e faded.
		-- Ashleigh Brilliant

%
palo ya hao e se e swathika hakolla.
		-- Ashleigh Brilliant

%
palo ya hao swathika ke 3552664958674928. Watch bakeng sa eona hohle.
		-- Ashleigh Brilliant

%
screen reader mode wa hao wa tsa bophelo o tla li ile tsa ntlafala ka lebaka la litaba tse molemo haufinyane.
		-- Ashleigh Brilliant

%
screen reader mode wa hao wa tsa bophelo o tla li ile tsa ntlafala ka lebaka la tsoelo-pele e e ncha.
		-- Ashleigh Brilliant

%
sepheo sa hao bakeng sa ho etsa eng kapa eng eo molemo ka liketso le ka ba le a nahanne ka e tla bamisinterpreted ke e mong.
		-- Ashleigh Brilliant

%
lintho tsa tlhaho ya hao batlang lerato le thabo ea hao e itšetlehile ka lona.
		-- Ashleigh Brilliant

%
be ntho ea hao e le hore a pholose lefatše, empa ba ntse ba phela bophelo monate.
		-- Ashleigh Brilliant

%
lit sobotsi ea hao e tla thusa ho thibela hore tsoelo-pele ea hao lefatšeng.
		-- Ashleigh Brilliant

%
merero ea hao e sebetse hona joale e tla ba e atlehileng.
		-- Ashleigh Brilliant

%
oa ho beha mabaka hao ke e babatsehang ea - e 's feela likhopolong tsa hao tsa motheo tse fosahetseng.
		-- Ashleigh Brilliant

%
matla a hao a ho sebelisa mabaka a molemo, 'me u tla ngolla toka molemo.
		-- Ashleigh Brilliant

%
morali'eno swims tsoa ho ea kopana likepe troop.
		-- Ashleigh Brilliant

%
setjhabeng ea hao e tla ba batla ke batho ba latsoe 'me ntlafatso.
		-- Ashleigh Brilliant

%
mohato oa tla mobu oa hao linaheng tse ngata.
		-- Ashleigh Brilliant

%
mookameli oa hao o nahana ka uena.
		-- Ashleigh Brilliant

%
litalenta tsa hao ho tla lemoha hore le ka bomaleba putsoa.
		-- Ashleigh Brilliant

%
Your ba nakoana ho hlajoa ke lihlong sa ditjhelete tla imoloha ka tsela e makatsang.
		-- Ashleigh Brilliant

%
latela boleng ba hao oa 'nete ho itšetlehile ka ho feletseng ka seo u se bapisoa le' ona.
		-- Ashleigh Brilliant

%
