khethile mosebetsi A e khōlō, empa u ke ke ua matha menoana ea hao ho pholletsa moriri eona.
		-- Pat Benatar, "Hell is for Children"

%
A kako ke tsela ea azile, ka mano qapa, bakeng sa bobelistoppage ba puo nakong ea ha mantsoe ke lololo.
		-- Pat Benatar, "Hell is for Children"

%
Mosali e mong o ne a rata masole a metso e mene. E ne e ka ho hlaka platoonic.
		-- Pat Benatar, "Hell is for Children"

%
Ho ba sieo ha diminishes litšusumetso mediocre le eketsa ba baholo,joalokaha moea oa foka ka ntle likerese le Fans mello.
		-- La Rochefoucauld

%
Ho ba sieo ha ka lerato o joaloka metsi holim 'a mollo; e nyenyane quickens, empa lintho tse ngataextinguishes eona.
		-- Hannah More

%
litšusumetso tsohle etsa hore re etsa liphoso; lerato le etsa hore re etsa ka ho fetisisasethoto ba thabelang.
		-- La Rochefoucauld

%
Kamehla moo lule likarolo tse ling tsa lipelo tsa rōna ho kena leo ho seng ea o khona ho kena,mema bona ha re ntse re ka.
		-- La Rochefoucauld

%
Bokhobeng mohlomong, ha ho mohla taeo!
		-- T.K.

%
Ho se tšepane ba ratang u fetisisa holim'a tloaetseng hanyenyane haholo bohle'me ho se lebaka leha e le efe bopaki bo bonahalang.
		-- Lord Chesterfield

%
Se ke ua nyahama; moratuoa oa hao sebaka se setle e letetse ho u pota-pota sekhutlo.
		-- Lord Chesterfield

%
Falling LeratongHa batho ba babeli ba 'nile ba bolela linako tse lekaneng, ka kakaretso ba oelaba ratang. U ka bolella u ka lerato ke tsela eo u ikutloang: hlooho ea hao fetohaleseli, pelo ea hao leaps ka hare ho uena, u ikutloa joaloka u tsamaea moea,'me lefatše lohle le bonahala joaloka e le sebaka hlollang le bo thabileng. Ka bomalimabe,tsena le tsona ke lipontšo tse 'nè tse phatlalatsa temoso ea maloetse kaofela lelana, kahoo ho Kamehla ho emohopolo o motle ho hlahloba le ngaka ea hao.
		-- Dave Barry

%
Falling a lerato ke haholo joaloka shoa. Ha ho mohla u fumana ho e etsa ka ho lekaneng horeba ipabola ho tsona.
		-- Dave Barry

%
Qete kateng polelong ena e ka tlaase ka mantsoe kapa ka tlaase ho 25:"Lerato ke seo u ikutloa feela pele u fana ka motho e mong eo e neng e molemo ..."Romella e-mail karabo ea hao hammoho le halofo tlhōrōng ea mookameli oa hao ho:P.O. Box 35A tsielehile Segerike, Michigan
		-- Dave Barry

%
Mphe hloekile 'me continence, empa e se feela hona joale.
		-- St. Augustine

%
Molimo ke lerato, empa e fumana ka ho ngola.
		-- Gypsy Rose Lee

%
"O ne a etsa qeto ho le joalo, hore ka nako e eketsehileng le ho hongata ba kelelloho bapala ka matla, o ne a ka etsahala hore ebe retelehela ketsahalo hore e be sotha amohelehang. "
		-- Mick Farren, "When Gravity Fails"

%
O eo e ka lerato le ka boeena o na le bonyane manollo ea lingoloa sebelisa hamolemo libaka tseo sena - o ke keteana qothisanang lehlokoa tse ngata.
		-- Georg Lichtenberg, "Aphorisms"

%
Hearts ke ke bo sebetsang ho fihlela ba ka etswa tloloa.
		-- The Wizard of Oz

%
HEY Kids! Ann Landers SE BUANG:Ba bonnete ba hore ho ba 'nete, ha o re "Kea u rata." Ho ke sebe hoea bolela leshano. Batho ba limilione ba lipelo tsa ba robehile, hobane feelamantsoe ana a ne a buile.
		-- The Wizard of Oz

%
pelo ea hae e be tsa hao ho tloha motsotsong oa pele oa hore u kopanang le bona.
		-- The Wizard of Oz

%
Bokae ha a u rata? Ka tlase ho u tla kile ua tseba.
		-- The Wizard of Oz

%
Ke 'na maoatla a mabeli, ke tseba, ho rata,' me bakeng sa ho re joalo.
		-- John Donne

%
Nka lokisa ea khefu ea letsatsi le leng, folisa pelo e robehileng, le ho fana ka ba nakoanaimoloha hakaakang ho nymphomaniacs.
		-- Larry Lee

%
Ha ke batle hore batho ba nthata. E etsa hore bakeng sa ditlamo.
		-- Jean Anouilh

%
Kea u rata ho feta ntho leha lefatšeng lena. Ha kea lebella hore le tla tšoarella.
		-- Elvis Costello

%
Kea u rata, eseng feela molemong oa seo u, empa bakeng sa seo ke ha ke na le uena.
		-- Roy Croft

%
Ke ne ke rata 'me ka lerato ka nyoroa' me tsietsing. Ke ne ke ikutloa hore re ba babeli ba ka 'na ba etsaba bang ba nke bohato kahoo hlomolang pelo hore lefatšeng, re bonang, o ne a tla fumana ho ithiba.
		-- Gene Wolfe, "The Shadow of the Torturer"

%
Ha ho mohla ke rata motho e mong ka tsela eo ke ne ke rata 'na.
		-- Mae West

%
Ke nahana kamano ho tšoana le lishaka e. E na ho ba lula ba susumelletsa pelekapa e shoa. Buuoa hantle, seo re ba le matsoho a rōna mona ke lishaka bafu.
		-- Woody Allen

%
Ke ne ke Snow White, empa ke kene.
		-- Mae West

%
Ke ne ke nahana lerato le maikutlo a lerato e ne e le neurosis kopanela ke lintho tse peli, e leng ka holimo-limobooatla. Ha ke sa nahana hore. Ha ho letho le maoatla ba boleloang kalerato mang kapa mang. Nahana u tla rata le puseletso ke seo 's ka booatla.
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ke ile ka etsa ntho ea heso 'me joale ke saletsoe keho etsolla ho lona. "
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ke na le ho floss katse ka."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ke na le ho lula hae 'me le bone haeba ke snore."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ha ho mohla ke tsoa ka matsatsi hore qetella a` Y. ' "
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ke batla ho qeta nako e ngata le blender ka."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa kea teng ahlamisa monyako oa karache ea ka."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa kea fetola almanaka ea ka tebelo tsoangJulian ho ea Gregory. "
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ke se etsang ntlo le ntlo bakeng sa ho bokella ee sa fetoleng boemokhomarele. "
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa kea ho limela tse tloaelehileng ea ka eohle neutered."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa kea lula lehaeng la ho sebetsa ke leCottage chisi litsoantso tse betliloeng. "
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa kea nka Punk totem palo betla."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ke 'nile ha hlophisoa hore ho atseiko transplant."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ho parakeet oa ka boula bosiu."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa likhoele tsa khoebo ke e ratang ka ke thelevisheneng."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa lekhetlo la ho qetela, ke ile ka ntle, ha ho mohla ke tla khutlela teng."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa motho ea etsoa thelevisheneng mpolella hore ke lule tuned."
		-- Rita Mae Brown

%
"Nka rata ho intša le uena, empa ho na le litabeng tsa bohlokoa lefatšeng leo lehloka ho tšoenyeha ka. "
		-- Rita Mae Brown

%
Nka rata ho aka uena, empa ke feela ke hlatsoitse moriri oa ka.
		-- Bette Davis, "Cabin in the Cotton"

%
"Ke tla u bolella seo ke tseba, ka nako eo, o ile" a etsa qeto ea. "The Pin ke apereho bolela Ke setho sa IA. Eo Inamorati Anonymous. An inamorato kemotho ka lerato. Hore 's ea ho lemalla ho fetisisa tsohle. ""Ho na le motho e haufi le ho oela ka lerato," Oedipa a re, "u eang lula lebona, kapa ntho e 'ngoe? ""Right. Khopolo eohle e ho ikisa hohle moo u sa e hloka. Ke ne keswathika. Ke raha eona ba banyenyane. Empa ho na le banna mashome a tšeletseng ea lilemo li, ba lumela ho lona kapa kaeseng, 'me basali esita le moholoanyane, ba ka' nang tsoha bosiu sello sa batho. ""U tšoara liboka Joale, joaloka LH ea?""Che, ho hlakile hape eseng jwalo. O fumana nomoro ea mohala, e tshebeletso ya arabela lipotsou ka bitsa. Ha ho ea tsebang lebitso leha e le mang e mong; feela ea palo ea bohlokoa nyeoengeo fumana hobe hakaalo u ke ke ua sebetsana eona feela. Re u ikarolang, Arnold. tle libokengtla felisa ea boholeng oohle oa eona. "
		-- Thomas Pynchon, "The Crying of Lot 49"

%
Haeba lerato ke karabo, u ka rephrase potso eo?
		-- Lily Tomlin

%
Haeba Love ne Oil, ke ne ke E-About A Quart Low
		-- Book title by Lewis Grizzard

%
Haeba u feela ba ne ba tseba a ratile, u ka tobana le ho se tsitse hahore na o mo rata.
		-- Book title by Lewis Grizzard

%
Haeba u ke ke ba molemo, ba hlokolosi. Haeba u ke ke hlokomela, mphe letsetsa.
		-- Book title by Lewis Grizzard

%
Haeba u rata motho e mong, ba beha ntle ho tefo.Haeba ba sa khutla, joale ba bitsa kateng ha u se u noele.
		-- Book title by Lewis Grizzard

%
A ba ratana e khōlō, motho ka mong ha e le hantle e phetha karolo e satse ling hlile like.
		-- Elizabeth Ashley

%
Mehleng e ha feshene ke ho ba ka lerato le ithata, li bolelang hoba ka lerato le motho e mong ke kenoa ea ho se tšepahale e mong ho e batlangea ratoang.
		-- Russell Baker

%
Ka lerato, o ile a ea fanang ka potreite oa hae o tšepisa ho ea pele.
		-- Bruton

%
A lerato la sebele u batla motho e mong molemo. Leratong maikutlo a lerato ubatla motho e mong.
		-- Margaret Anderson

%
Ho molemo haholo ho thetsoa feta ho undeceived ke bao re ba ratang.
		-- Margaret Anderson

%
Kamoo ho leng thata kateng ho ngola go biography ka lekanya ke leha e le mangea ileng a lula fatše 'me o nahana ka hore na joang batho ba bangata ba tseba' nete ea sebelemabapi litabeng tsa lerato la hae la hae kapa.
		-- Rebecca West

%
A re ke re phela !!!A re ke re rata !!!A re ke re bolella liphiri tebileng ka ho fetisisa tsa meea ea rōna !!!U pele.
		-- Rebecca West

%
A re ke re feela ho fa metsoalle le etsa ho se boiteko bo khethehileng ho kile ua bonana hape.
		-- Rebecca West

%
A re ke re ke ua thatafatsa kamano ea rōna ka ho leka ho buisana le e mong.
		-- Rebecca West

%
Jeoa ke bolutu ke monna ea ba hlokang lerato.
		-- Englebert Humperdinck

%
Love - a ho qetela a mafu a tse tebileng tsa ea bongoaneng.
		-- Englebert Humperdinck

%
Lerato le mahlabisa-lihlong a ke sweeteners molemohali ea tee.
		-- Englebert Humperdinck

%
Love nakong qala ho se bona ke e mong oa kholo ka ho fetisisa disebediswa tsa mesebetsi ea pholosalefatše ea kileng a bona.
		-- Englebert Humperdinck

%
Lerato e ke ke ka tlaase ka ho hongata ho feta le takatso e feteletseng bakeng sa polao.
		-- Sigmund Freud

%
Lerato hlōlang lintho tsohle; a re ke re le eena o inehela ho lerato la hae.
		-- Publius Vergilius Maro (Virgil)

%
Lerato ke lebitla le maloetse a itseng a kelello.
		-- Plato

%
Lerato ke snowmobile reisisi ka mose tundra, e leng ka tšohanyetso flipslohle, 'pinning u ka tlaase. At bosiu mechalla leqhoa tlang.
		-- Matt Groening, "Love is Hell"

%
Lerato ke kamehla mofuthu. Ka libetsa bula u lumella lerato hore o tle leea joalokaha ho rata, ka bolokolohi, etsoe e tla etsa joalo joalo. Haeba u koala ya haoliphaka mabapi rata u tla fumana o siile feela tšoere u ithata.
		-- Matt Groening, "Love is Hell"

%
Lerato ke ho hloka kelello hammoho.
		-- Paul Valery

%
Lerato ke dope, eseng sopho khoho. Ke bolela, lerato ke ntho e hore o fetisweho pota-pota ka bolokolohi, eseng spooned theosa qoqotho motho e mong molemong oa bona keBajuda 'me ea pheha eona kaofela ke eena.
		-- Paul Valery

%
Lerato le ka haufi.
		-- The Homicidal Maniac

%
Lerato o joaloka setsoalle tšoaroa ka la mollo. Tšimolohong e be lelakabe, haholoe ntle, 'me hangata chesang le bohale bo tšosang, empa a sa ntse li khantse feela le paitsang. Ha leratohōla, lipelo tsa rōna ba hōlileng tsebong 'me lerato la rōna le fetoha joalokaha mashala, e tebileng-bo tukang'me unquenchable.
		-- Bruce Lee

%
Lerato o joaloka maselese ea; kaofela ha rona re lokela ho tsamaea ka lona.
		-- Jerome K. Jerome

%
Lerato ha ho mohla ho botsa hore na ke hobane'ng?
		-- Jerome K. Jerome

%
Lerato ke se sa lekana, empa e bonnete ba thusa.
		-- Jerome K. Jerome

%
Lerato ke amehileng maikutlo maselese.
		-- Jerome K. Jerome

%
Lerato e lula bosiu bohle le ngoana ea kulang, kapa motho e moholo ea phetseng hantle.
		-- Jerome K. Jerome

%
Lerato ke papali eo feela, e sa bitsoa ka lebaka la lefifi.
		-- M. Hirschfield

%
Lerato ke tshebetso ya ho ea ka isang u ka bonolo morao ho u ithata.
		-- Saint Exupery

%
Lerato ke tlhōlo ea monahanong holim 'bohlale.
		-- H. L. Mencken

%
Lerato ke eng hore lintho li tletlerana fihlang ho sona.
		-- H. L. Mencken

%
Lerato ke seo u bile qete ka motho.
		-- James Thurber

%
Lerato ha le foufetseng feela, ho boetse ba sa utloeng litsebeng, limumu, le ba hlokang kelello.
		-- James Thurber

%
Rata ho bolelwa nang ho re u masoabi seng le se seng metsotso e mehlano.
		-- James Thurber

%
Lerato ho bolelwa ka mohla ba le ho re u masoabi.Eo ntho fetisisa sethoto Ke kile ua utloa.
		-- Ryan O'Neill, "What's Up Doc?"

%
Lerato e re bolella lintho tse ngata tseo e seng joalo kapa che.
		-- Krainian Proverb

%
E se eka ea hao SO kamehla tseba ha u lokela ho mo haka.
		-- Krainian Proverb

%
"Mohlomong re lokela ho nahana ka sena e nkang beke e le 'ngoe bo phethahetseng ... moo re ile ra fumana e mong le ele leng, 'me o ne a rata e mong le e meng e ...' me joale e mong le e meng e ea ka pel'a mang kapa manga tlameha ho batla thuso ea litsebi. "
		-- Krainian Proverb

%
batho ba bangata ha ba hloka haholo oa lerato hoo e ka bang ho le tseo ba li hlokangka tsela e tsitsitseng le phepelo.
		-- Krainian Proverb

%
senoelo sa ka, au runneth'd holim 'ka lerato.
		-- Krainian Proverb

%
Nature o nyonya moroetsana - e ba letlotlo hoammeng.
		-- Clare Booth Luce

%
"Che, kea utloisisa hona joale, 'Auberon re, khobile matsoafo ka morung - e ne e lebonolo, hlile. "Ke ile ka etsa joalo, hobane ka nako e telele, empa ke se etsang hona joale. O sa tsoa ke ketšoara sechaba sa ka, u ke ke ua ba le bona. Ke bolele hore ke ba tlhaho feela, tshebetso tsa tlhahohlile. Litlhoko tsa bophelo. Ba ratang. Karolo ea bona. Bophelo bo tsoela pele. Ho ne ho ka mohla le lebaka la holebella oa hae hore a lule a e tsoanang kamehla - Ke bolela `ka lerato, 'u tseba" Ho ne ho.bao ho pelaelo hore-qotsa oa mosi, e ikatetse bontša. "Ha ke jara ka pelo. Ike ke. ""U se etsa," Ntate-moholo o ile a re trout. " 'Me ha u se utloisise."
		-- Little, Big, "John Crowley"

%
Tsa mefuta eohle hlokolosi, ba be hlokolosi ka lerato ke bolaeang ka ho fetisisa.
		-- Little, Big, "John Crowley"

%
Ke 'nete hore ho ka khonehang hore ba rate e motho haeba u sa tsebe hantle haholo.
		-- Charles Bukowski

%
Oh, lerato ke oa sebele ho lekaneng, u tla fumana ho ba bang letsatsi le leng, empa e na le e 'ngoekhoro ena-sera se tlileng - 'me seo se bophelong.
		-- Jean Anouilh, "Ardele"

%
Leqepheng la tous Machaba a Kopaneng peu peur de l'baperola, mais leqepheng la surtout peur de Khao souffrirOu de Khao faire souffrir.[ 'Ngoe ke ka linako tsohle e nyenyane tshaba oa lerato, empa ka holim'a tsohle, e mong o tengtshaba ea maemo a bohloko kapa utloisang bohloko.]
		-- Jean Anouilh, "Ardele"

%
Ka lekhetlo le leng hlokomela e amohela hore esita le ka har'a batho ba haufi-ufisebaka se selelele ke keng ba lekanngoa ba tsoela pele ho ba teng, e babatsehang phelang le bapile ka mahlakore kahōla, haeba ba ka atleha ho rata sebaka se pakeng tsa bona e leng ho etsa hore hokhoneha hore e mong le e mong le e mong ho bona kaofela ha yona tse ling khahlanong sepakapakeng.
		-- Rainer Rilke

%
E mong o buuoa hantle ka lerato leo ha a ikutloa joang.
		-- J. A. Karr

%
Batho ba nahane lerato ke maikutlo. Lerato ke boikutlo bo tebileng mabapi molemo.
		-- Ken Kesey

%
Hlile ?? Seo sea etsahala ka tsohanyetso, ke sa tebang le eena !!
		-- Ken Kesey

%
Nakoana ha u sa e lebellang, Lerato le tla Tlanya u lehetleng la ...'me u botsa ho fallela tsoileng tseleng hobane e sa ntse e ke ua retelehela hao.
		-- N. V. Plyter

%
Ka linako tse ling lerato ha le na letho haese ho se utloisisane pakeng tsa maoatla a mabeli.
		-- N. V. Plyter

%
Sorry ho mohla bolela ho ba le Buelang ho rata.
		-- N. V. Plyter

%
Ha a bua ka lerato, bothata e 'ngoe eo recurs ho eketsehileng khafetsa tsenamatsatsi, libukeng le tla bapala le lifilimi, ke ho hloleha ha batho ho buisanale batho ba rata; Banna le basali ba ea ke keng a buisana, banaea ke keng a buisana le batsoali ba bona, 'me joalo-joalo. 'Me batho bao ho buuoang kalibuka tsena le tla bapala le lintho tse ling (le ka bophelo ba sebele, nka eketsa) qeta lihorabemoaning 'nete ea hore ba ke ke ba buisana. Ke nahana hore haeba motho a ke kebuisana, e leng eona _____ bonyane o ka e etsang ke ho koala!
		-- Tom Lehrer, "That Was the Year that Was"

%
Support liphoofolo tse hlaha - voute bakeng mothabo oa batho ba bangata e.
		-- Tom Lehrer, "That Was the Year that Was"

%
Eo ke nako ea 'nete ea lerato, ha re lumela hore re feela ea ka ratang,hore ha ho motho ka be a ile a rata kahoo ka pel'a rōna, 'me ha ho na motho o tla rataka tsela e tšoanang le re fileng eona.
		-- Johann Wolfgang von Goethe

%
Eo bophelo bakeng sa lōna, a re McDunn. Motho e mong kamehla emetse motho eaha ho mohla a fihla lapeng. Kamehla motho e mong ea lerato ho hong ho fetang hore ntho ratabona. 'Me ka mor'a hajoale o batla ho senya ntho e le sefe se ke, kahoo hoa ke ke a u utloisa bohloko hlola.
		-- R. Bradbury, "The Fog Horn"

%
linonyana bina, lipalesa ba budding, 'me ke nakoetsoe Miss Mekhoa ho bolella batho ba ratang ba banyenyane hore ba khaotse ho necking a sechaba.Ha se hore Miss Mekhoa ea sa hlaheloeng ke ho ratana. Miss Mekhoae 'nile ea tsebahala hore squeeze letsoho le ngoloang ea ha a ntse a thusoa ka lilemo tse fetangthibela, 'me, bocheng ba hae e hlaha, esita le ho tobetsa e disilipara tetemang khahlanong leleoto kapa tse peli tlas'a ea lijo tsa mantsiboea. Miss Mekhoa boetse o lumela horemahlong a batho strolling ba tsoarane ka matsoho kapa a letsoho la letsoho kapa letsoho la ka letsohoDresses fihlang motseng o haholo ho feta mahlong tloaelehileng haholoanyane eabatho sisinya likhele ho e 'ngoe le e mong. Seo Miss Mekhoa lintho hoKe ea mofuta ofe mosebetsi oa hore frightens lipere seterateng ...
		-- R. Bradbury, "The Fog Horn"

%
The Giraffe u nahana u khopehe bekeng e fetileng o ikemiselitse ho nuzzled kajeno.
		-- R. Bradbury, "The Fog Horn"

%
Pelong ho na le mabaka a ea oona e leng la mabaka a etsang tseba letho ka.
		-- Blaise Pascal

%
Pelo e bohlale ho feta bohlale eo.
		-- Blaise Pascal

%
Likotoana bue hakaalo bophelong ba ka ke fana ho uena, lerato, ho etsa koboho boloka-hang a batang.
		-- Blaise Pascal

%
The boselamose ba lerato la rōna ho hloka tsebo ea rona ea pele ke hore ho ka fele.
		-- Benjamin Disraeli

%
Tšōmo ea lerato a lerato o kena ka lekhetlo le leng u oele ka lerato lemolekane wa ea phethahetseng, u ee lapeng la mahala. Ka bomalimabe, a rothelang ka lebaka la leratoho bonahala eka feela joalokaha involuntary joalokaha oela ka ho sona.
		-- Benjamin Disraeli

%
Phapang feela papaling ea lerato ka lilemo tse ngata ho qetela likete tse seng kaeke hore ba u fetotse trumps tsoang melangoana ho litaemane.
		-- The Indianapolis Star

%
Ho qala le waning oa lerato etsa ka bobona ikutloa a hlokang botsitso eaphihlelo nakong ho ba le babeli feela.
		-- Jean de la Bruyere

%
The ratang bo phethahetseng ke e 'ngoe ea ileng a fetoha pizza, e ka 4:00 A.M.
		-- Charles Pierce

%
Motho eo u lahlile maobane ka etsang hore u thabe bophelong, haeba u se buang e.
		-- Charles Pierce

%
Ka selemo sa supileng itch tsoa ithetsa ho pota-pota nakong oa bone, bohlano,'me ka lilemo tse botšelela.
		-- Charles Pierce

%
Pale ea serurubele e reng:"Ke ne ke a Bogota le emetse motsoalle e mong oa mofumahali eo. Ke ne ke le lerato,nakong ea khale. Ke a leta matsatsi a mararo. Ke ne ke lapile, empa a se ke ua tsamaeatsoa bakeng sa lijo, esere a tla 'me ha kea ba teng ho lumelisa hae. Joale, kaletsatsi la boraro, ke ile ka utloa motho a kokota. ""Ke ile ka potlaka hammoho litemana tsena tse tsofetse 'me ho na le, a khanya ea letsatsi, eho ne ho letho. ""Feela," Vance Joy o ile a re, "serurubele, e fofang-hang."
		-- Peter Carey, BLISS

%
The monate ea apole, ea blacker mesebetsi ea mantlha -Scratch ea ratang le fumana sera!
		-- Dorothy Parker, "Ballad of a Great Weariness"

%
tsela eo ho rata eng kapa eng e ka hlokomela hore se ka lahleha.
		-- Dorothy Parker, "Ballad of a Great Weariness"

%
Na le ba bang dikokwanyana hore bontša litsobotsi tsa limela tse ka bobelile liphoofolo. Ha a pepesa ho tla leseling ba feta tala; 'me hamaseli a tsamaea ka eona, ba fetoha liphoofolo. Empa ka nako eo hape, u se ke ua re 'ohle?
		-- Dorothy Parker, "Ballad of a Great Weariness"

%
Ha ho tšabo leratong; empa lerato le phethahetseng le lahlela ka ntle tšabo.
		-- 1 John 4:18

%
Ho na le tsela e 'ngoe feela ho thaba ho hang ba pelo - ho na le letho le ikhanyetsang.
		-- Paul Bourget

%
Ho na le ho hongata hakana ho re empa mahlo a hao ho boloka hanong 'na.
		-- Paul Bourget

%
Lekanya lokela ho ba phethahetseng hona joale. 'Meli-lekanya lokela ho molemo ho feta motho ea phethahetseng.
		-- Paul Bourget

%
Ho ratoa ke a nyahamisa haholo.
		-- Katharine Hepburn

%
Ho tšaba lerato ke ho tšaba bophelo, 'me ba tšabang bophelo ba se a ntse a mararolikarolong bafu.
		-- Bertrand Russell

%
Tsebeng ho hloka lerato, haholo; 'me ke sa mo tsebeng ho feta ka ho fetisisa.
		-- Bertrand Russell

%
thabo ea 'nete e tla fumanoa feela ka lerato la' nete.
		-- Bertrand Russell

%
Tlas'a khatello e fokotseha ipehela nako bakeng sa beke e tlang. Haeba u batla ntho e itseng, e ka emela.Ntle le haeba e 's foufetseng tleroha paroxysmally hedonistic ...
		-- Bertrand Russell

%
Ha re lumela ho lerato rheumatism le oa 'nete ho fihlela ka mor'a tlhaselo eo pele.
		-- Marie Ebner von Eschenbach

%
Ke eng e halefisa ka lerato ke hore ke tlōlo ea molao o hlokang hore e accomplice.
		-- Charles Baudelaire

%
Ha bophelo ba hao ke lehlaku hore linako tsa selemo tabola tima le ho ahlolaBa tla tlama u ka lerato hore ke graceful le ho tala joalokaha bakoang e.
		-- Leonard Cohen, "Sisters of Mercy"

%
Ke hobane'ng ha ke Keng intša le U:Nka rata ho, empa ...- Ke lokela ho floss katse ka.- Ke 'nile ka nehela bophelo ba ka ho linguini.- I lokela ho qeta nako e ngata le blender ka.- E ne e ke ke hlokang leeme ho batho ba bang naheng Beautiful People.- E 's bosiung boo ba ka ho Pet ntja / ferret / ditlhapigauta.- Ke tl'o litsi tsa ho leka tse ling litlelafo.- Ke lokela ho hlahloba freshness matlha thepeng ea ka lebese.- Ke theohelang lebakeng ho shebella buns tsoha.- Ke na le ka behelana nako ea botsebi cuticle.- Ke na le mantsoe a mang a sebele ho thata ho phetla.- Ke 'nile ka ile ka fumana Friends oa seboka tlaase Rutabaga.
		-- I promised to help a friend fold road maps.

%
Ke hobane'ng ha ke Keng intša le U:Nka rata ho, empa ...- Ke na le ho araba tsohle tsa mangolo a ka 'occupant. "- Ha ho likausi ea ka dumellane teng.- Ke ho limela tse tloaelehileng ea ka eohle neutered.- I ea fetola senotlolo monyako oa ka 'me hona joale ke sitoa ho tsoa.- My yucca semela se ikutloa yucky.- Ke touring China e nang le Wok sa 'mino.- My chokolete-kananelo tlelaseng kopana bosiung boo.- Ke matha ho ea Yugoslavia le seithuti sa lisele le phapanyetsanobitsoang Basil metabolism.- Ho na le litabeng tsa bohlokoa lefatšeng leo le ho hlokahale ho tšoenyeha ka.- Ke tl'o bala bristles a borashe ba meno ka.- Ke khetha ho lula e Enigma.- Ke nahana hore u rata ba bang Peggy / Cathy / Mike / mang kapa mang eo.
		-- I feel a song coming on.

%
Ke hobane'ng ha ke Keng intša le U:Nka rata ho, empa ...- Ke na le ho atamela "Cubby" bakeng sa bonono lihlapiso.- Ke na le ho lula le mohlankana e mong bohloa kula.- Ke leka ho ba ka tlaase ho moo e ratoang haholo.- Hlapela lithaele My hloka grouting.- Ke emetse ho bona hore na ke se e ntse e mohlodi.- Subconscious oa ka o re ha ho joalo.- I feela nka buka e bitsoang "Sekhomaretsi linaheng tse ngata" 'me kea ke ke a bonahala ho e beha fatše.- My likhoele tsa khoebo ratang haholo ke thelevisheneng.- Ke lokela ho ithuta bakeng sa diteko di supa mali a ka.- Ke 'nile rekisa ho Cincinnati.- Ke ho lesea lieta ea ka bronzed.
		-- I have to go to court for kitty littering.

%
Ke hobane'ng ha ke Keng intša le U:Nka rata ho, empa ...- Ke leka ho bona ka nako e kae ke ka ea kantle ho re e.- Ke ho ba teng ha ho phetloa monyako oa karache ea ka.- The litonanahali li sa suthela o moputsoa-s'o, 'me ke lokela ho ja matheba more.- Ke fetola almanaka ea ka tebelo tsoang Julian ho ea Gregory.- Ke na le hore a phethahatse ntlafatsa bokhoni ba ka.- Ha ke batle hore a tlohe tselisang libaka.- Ho haufi haholo ea mathoasong a lekholo la.- Ke lokela ho bleach mutla ka.- Ke tšoenyehile ka mpolokela tsepameng kotola.
		-- I left my body in my other clothes.

%
Ke hobane'ng ha ke Keng intša le U:Nka rata ho, empa ...- Ke 'nile ka ile ka fumana Friends oa seboka tlaase Rutabaga.- I o ile a tšepisa ho thusa motsoalle ea mene limmapa a ala tseleng.- Ke 'nile ha hlophisoa hore ho atseiko transplant.- Ke lula lehaeng la ho sebetsa Cottage chisi ea ka litsoantso tse betliloeng.- Ho parakeet oa ka boula bosiu.- Ke ho haha ​​semela go tswa Kit e.- Ho na le tsoalla pherekano ka har'a Force.- Ke se etsang ntlo le ntlo bakeng sa ho bokella khomarele ee sa fetoleng boemo.- Ke ho ruta ferret ea ka ea ho yodel.
		-- My crayons all melted together.

%
"Ke hobane'ng ha u lokela ho mpolella hore na senola liphiri tsohle tsa hao ha ho ho le thata ka ho lekaneng hore ba rateu tseba lefeela? "
		-- Lloyd Cole and the Commotions

%
Ba hlokang lerato bohlale motho kotsi;ntle le bohlale motho lerato ke ha hoa lekana.
		-- Ashley Montagu

%
Ba ne ba sa sena ho lefatše le leholo haeba ho sa sireletseha 'me tsietsing e ne e le mothinya-pele?
		-- "Broadcast News"

%
Yeah, ho na le lintho tsa bohlokoa haholoanyane bophelong ho feta chelete, empa ba ke ke eatsoa le uena haeba u ha ba na leha e le efe.
		-- "Broadcast News"

%
Ha ua lokela ho ba le ho lefa ka lebaka la lerato la hao ka masapo a hao le nama ea hao.
		-- Pat Benatar, "Hell is for Children"

%
