  A eme mahlaba bue hakaalo ka mohla bohloko leha e le mang.
		-- Arthur Baer, American comic and columnist

%
  "A momahaneng, li sa jele paate Germany? Fuoa hore lefa la sechaba, e joalo e  poleloana ena e ka hore e be oxymoron ea lilemo tse leshome tse. "-Kevin M.  Matarese, Fulda, West Germany; joalokaha bonoa "Letters", Time  makasine eo, leq. 5, March 5, 1990.
		-- Arthur Baer, American comic and columnist

%
  A konteraka molomo ke ha le ba bohlokoa ea pampiri e lintho li ngotsoe. kenyeletsa  'na tsoa. -Samuel Goldwyn
		-- Arthur Baer, American comic and columnist

%
  Kreste o ile a hlaha a 4 B.C.
		-- Arthur Baer, American comic and columnist

%
  Cum tacent, clamant. Ha ba khutse, ba hoeletsa. -Cicero
		-- Arthur Baer, American comic and columnist

%
  Borra, ke batla hore le tsebe hore ke 'na hase kamehla le letona, empa ha ke  ha ho mohla se fosahetseng. -Samuel Goldwyn
		-- Arthur Baer, American comic and columnist

%
  Tsoela (Tsoela) lilemo tse fetang joaloka balune e loto.
		-- Arthur Baer, American comic and columnist

%
  Melumo haeba u khahlanong tshilafatso lerata!
		-- Arthur Baer, American comic and columnist

%
  Ke tla u fa e tobileng mohlomong. -Samuel Goldwyn
		-- Arthur Baer, American comic and columnist

%
  Ke a ke ke a re, "Ke u boleletse joalo."
		-- Arthur Baer, American comic and columnist

%
  Ke 'na motho ka ho teba ka ntle feela. -Andy Warhol
		-- Arthur Baer, American comic and columnist

%
  Ke motlotlo ka boikokobetso bo etella ka.
		-- Arthur Baer, American comic and columnist

%
  Nka hanela lintho tsohle li tsamaea haese molekong. -Oscar Wilde
		-- Arthur Baer, American comic and columnist

%
  Haeba Roosevelt a ne a phela, o ile a kopa retelehela holim 'a lebitla la hae. -Samuel  Goldwyn
		-- Arthur Baer, American comic and columnist

%
  Haeba ke ne ke tlohele bafu hona joale, ke ne ke e-ba monna thabileng ka ho fetisisa phela!
		-- Samuel Goldwyn

%
  Haeba u ka itihela le roba meomo ea hao, u se ke ua kena matha ho 'na. -Samuel  Goldwyn
		-- Samuel Goldwyn

%
  Ha ho mohla ke apare para ea lieta ho fihlela Ke tsofetseng bona lilemo tse hlano.
		-- Samuel Goldwyn

%
  Ho ke ke ha e-ithetsa Optical. E mpa feela e shebahala joaloka e 'ngoe.
		-- Samuel Goldwyn

%
  Ho tse fetang tse khanyang li-ho mediocre. -Samuel Goldwyn
		-- Samuel Goldwyn

%
  Na nka botsa potso?
		-- Samuel Goldwyn

%
  Ha ho na motho o tsoela ho hore reschorente hlola-it li kamehla le eena tletse.  (Ngotsoe ke Yogi Berra)
		-- Samuel Goldwyn

%
  comedies rōna ba ho se tšeha. -Samuel Goldwyn
		-- Samuel Goldwyn

%
  Arohana e joalo e tsoekere ho sareloa. -William Shakespeare
		-- Samuel Goldwyn

%
  Lieha ho etsa lintho ho bolela ka mohla ba le ho re u masoabi.
		-- Samuel Goldwyn

%
  "Professional tiiseletswe koloi batho ba ka utloahala eka e  oxymoron. "-e leng Wall Street Journal, leqepheng la B1, Labobeli, la 17 July,  1990.
		-- Samuel Goldwyn

%
  Ha a bua ka buka e: Ke ile ka bala karolo ea sona tseleng eohle ka ho hlaka.
		-- Samuel Goldwyn

%
  Tsuba ke sesosa se ka sehloohong sa dipalopalo.
		-- Samuel Goldwyn

%
  Ba bang ba bachelor batla bo nang le morero kamano panya ha leihlo.
		-- Samuel Goldwyn

%
  Ho bua ka sekotwaneng sa baesekopo lipuisano: A re ke re be le lingoliloeng tse ncha  cliches. -Samuel Goldwyn
		-- Samuel Goldwyn

%
  Nahana ka boemo ke thotofetseng. Mo bolelle hore a bophelo haholoanyane shoang hae.
		-- Samuel Goldwyn

%
  Leboha Molimo ke sa lumele ho molimo.
		-- Samuel Goldwyn

%
  tlaleho ena e tletse omissions.
		-- Samuel Goldwyn

%
  Re ke ke ra lebella maemo a tshohanyetso leha e le efe.
		-- Samuel Goldwyn

%
  Re ntse u overpaying eena, empa o ile a 's bohlokoa e. -Samuel Goldwyn
		-- Samuel Goldwyn

%
  tlisa tlotla ea hae le metse ka metso ka ho hlompholoha ema,  'Me tumelo ea sa tšepahaleng a' na a mo bohata ba 'nete.
		-- Alfred Lord Tennyson

%
  The oxymoron molemo, ho hlalosa e ke ho intša papiso, e be  rerile inadvertency. -Wilson Follett
		-- Alfred Lord Tennyson

%
  An Irishman ha ho mohla le khotso, ntle le ha a li loana.
		-- Alfred Lord Tennyson

%
  Ke tsota matla a bofokoli ba botho.
		-- Alfred Lord Tennyson

%
  Lula ho ba lipelo li ntle, esita le ha u sa bolele eona. -Irene Peter
		-- Alfred Lord Tennyson

%
  Phela ka moputso oa hao, esita le haeba u ba le ho alima ho etsa joalo.
		-- Josh Billings

%
  Ke 'nete hore nka boloka makunutu. Ho ea batho ke ba bolella hore ba etse joalo  a ke ke a tsoela pele bona. -Anthony Haden-Guest
		-- Josh Billings

%
  The pheko ea lona e molemohali bakeng sa lefu la ho hlobaela ke ho fumana e ngata ho robala. -W. C. Fields
		-- Josh Billings

%
  Ke khethollehileng hopola lebala seo. -Clara Barton
		-- Josh Billings

%
  Re lokela ho lumela bolokolohi ba ho ikhethela. Ha re na boikhethelo. -Isaac B. Singer
		-- Josh Billings

%
  Nka fana ka letsoho la ka le letona ho ambidextrous.
		-- Josh Billings

%
  Monotheism ke mpho e tsoang melimo.
		-- Josh Billings

%
  Ka mor'a hore ba ile felisa kotlo ea motse-moholo, ba ne ba ka makhetlo a mabeli hore a fanyehe  joalokaha batho ba bangata ba joaloka pele.
		-- Josh Billings

%
  Ha ho mohla ke rata uena, 'me kamehla ke tla. -Samuel Goldwyn
		-- Josh Billings

%
  Ke hobane'ng ha u para `rang fihlang a threes? -Yogi Berra
		-- Josh Billings

%
  ho tšoana ho rona ba fapaneng. -Dale Berra, mora oa Yogi
		-- Josh Billings

%
  Ka mor'a hore Donald Trump oa otlolle Limousine ile utsoitsoeng 'me ba fumana  undamaged e diboloko tse 'maloa tsamaee; O ile a re, "Ha ho letho le utsuitsoe. Ke ne ke  ea tšepahalang lesholu. "- International Herald Tribune, leqephe la 3, March 2,  1992
		-- Josh Billings

%
  Ba bang ba baahi nonyana soaring theosa-Headline Ea sehlooho seScience News, leqepheng la 126, February 20, 1993.
		-- Josh Billings

%
  libaktheria fetisisa na le bolongobani ho ba nyenyane. Epulopiscium  fishelsoni hase har'a bona. E sa tsoa tsebahatsoa e le 'ngoe e nang le sele  macro-kokoana-hloko ke tletseng .5 limilimithara nako e telele, kholo ka ho lekaneng ho bonoa  le mahlo. Hlalosoa ka Nature hona joale, "Ke  ka makhetlo a ba limilione tse joalokaha setonanahali e le baktheria tse tloaelehileng. "- Time, leqepheng la 25,  March 29, 1993
		-- Josh Billings

%
  "Tlhōlo ntle le Tlhōlo, The History Unreported ea Persia  Gulf Ntoa ", -Headline hatisitsoeng ka Litaba Tse US & Report ea Lefatše,  1992.
		-- Josh Billings

%
  An terakeng tsa lefeela mohlape nyoloha 'me Sara Bernhardt theoha. -Arthur Baer,  American metlae le likoranta
		-- Josh Billings

%
  O ne a sebelisa ho ja lijo tse matlafatsang ka la mofuta ofe kapa ofe ea lijo a ne a ka behang matsoho a hae on.
		-- Arthur Baer, American comic and columnist

%
  Boemo ba ho se shoe pele la ke lefu. -Stanislaw LEC
		-- Arthur Baer, American comic and columnist

%
  Joalokaha e tummeng joalokaha lesole leo e sa tsejoeng.
		-- Arthur Baer, American comic and columnist

%
  Ke lokela ho latela sechaba. Na ha ke moeta-pele oa bona? -Benjamin Disraeli
		-- Arthur Baer, American comic and columnist

%
  Hegel nepahetseng ha a ne a re re ka ithuta eng ho historing ea hore motho  ha ho mohla ithuta ho itseng historing. -George Bernard Shaw
		-- Arthur Baer, American comic and columnist

%
  amohela melao William Safire oa bakeng sa ho ngola joalokaha bonoa New York Times     U se ke ua beha lipolelo tse foromong negative.     'Me u se ke ua qala lauseet kopanelo e.     Haeba u Bala mosebetsi oa hao, u tla fumana ka la rereading hore e leholo     sebetsana ho pheta-pheta ka qojoa ka rereading le ho lokisa.     Ha ho mohla sebelisa lentsoe nako e telele ha ho le ea mong diminutive tla se etsa.     ome mathe sa tšoanelehe ke mpe ka ho fetisisa e phahametseng tsohle.     Haeba lentsoe leha e le efe e sa lokang ke qetellong ea polelo, e leng hokahanya leetsi ke.     Qoba locutions fesheneng hore utloahala flaky.     Ha ho mohla, kile ua sebelisa redundancies repetitive.     Hape, qoba sa phutholoha kapa ameha dipoeletsomodumo.     Last, empa e se senyenyane, qoba tloaelehile haholo kajeno oa joaloka lefu le.
		-- Arthur Baer, American comic and columnist

%
  Mong le e mong oa ngola maboteng haese 'na. -Said Ho maboteng bonoa Pompeii
		-- Arthur Baer, American comic and columnist

%
  Ke tripped holim 'lesoba e neng e khomarelang ho tsoa fatše.
		-- Arthur Baer, American comic and columnist

%
  Ha ke nahane leha e le mang a ngole autobiography bona ho fihlela ka mor'a  ba u shoele. -Samuel Goldwyn
		-- Arthur Baer, American comic and columnist

%
  leqepheng lena boomo siea sekheo sena.
		-- Arthur Baer, American comic and columnist

%
  Rerang bobe hase tsohle tse mpe.
		-- Arthur Baer, American comic and columnist

%
  Ke sa lumellane le unanimity.
		-- Arthur Baer, American comic and columnist

%
  "Ho talima mohato ho kgelosa hoja ho ne ho se khatelo-pele."  Mopresidente Hosni Murbarak ea Egepeta leka ho beha sefahleho molemohali  leqepheng la soabisang tlhōrōng pokano pakeng tsa Mopresidente Clinton le  mohatelli Syria Hafez Assad.
		-- Arthur Baer, American comic and columnist

%
  "Kamehla ke qoba ho profeta esale pele hobane ho molemo ho hongata  ho profeta ka mor'a ketsahalo eo e se e etsahetse. "- Winston  Churchill
		-- Arthur Baer, American comic and columnist

%
 linnete tsa bohle ba 'nete hore ba e atolosa, ho akarelletsa le enoa. -XA
		-- Arthur Baer, American comic and columnist

%
 Inkele bokhabane e, haeba u ba ho ke ke ha. -William Shakespeare
		-- Arthur Baer, American comic and columnist

%
 generalizations tsohle li kotsi, ho akarelletsa le enoa.
		-- Arthur Baer, American comic and columnist

%
