TselaTsela e ka nang le phihlelo hase 'nete;Lefatseng e le hore e ka hahoa ke seng ea sebele.Tsela bontša sohle seo se etsahala 'me' na ha etsahala'ng;lefatše emela sohle seo teng 'me ba ka' na ba teng.Ho latsoa ntle le khemise ke ho utloa lefatše;Ho latsoa nang khemise ho tseba lefatše.Liphihlelo tsena tse peli ke tsoana ka litsobotsi;hlophisitse kaho ea bona e fapana empa le phello ea bona e tšoana.Ka nģ'ane ho heke ea phihlelo ea phallang ea Way,E leng eketsehileng le ho feta 'me e poteletseng tse fetang lefatše.
		-- Lao Tse, "Tao Te Ching"

%
khemiseHa botle ba e abstractedKa mor'a moo, o 'nile a fana ka maikutlo a ugliness;Ha molemo abstractedKa mor'a moo, o 'nile a fana ka maikutlo a rerang bobe.Kahoo phela 'me le bafu ba abstracted tsa tlhaho,Thata ho le bonolo abstracted tsoang khatelo-pele,Telele le tse khutsoanyane abstracted tsoang lehlakoreng le leng,High e tlase le abstracted tsoang botebo,Song le ho bua abstracted tsoang lipina tsa thoriso,Ka mor'a hore le ka pel'a abstracted tsoang tatelano.liphihlelo tse Sage ntle le khemise,'Me finyelloang e se nang mesebetsi;O amohela tsepahale borapeling bo hloekileng le phallo ea lintho,Nurtures bona, empa ha ba le bona,'Me o lula, empa ha a lule.
		-- Lao Tse, "Tao Te Ching"

%
ntle le ActionEseng rorisa re lokeloe ke ho thibela ho hloka kutloano,Eseng hlompha ea bohlokoa eo thibela motho bosholu,Eseng ho bontša thibela motho se setle takatso.Ka mokhoa ona oa Sage laola sechaba:Emptying likelello tsa bona,Tlatsa limpa tsa bona,Fokolisa batla ho nka maemo a bona,Le ho matlafatsa masapo a bona.Haeba batho ba ha ba na tsebo le takatsoKa mor'a moo, ba ke ke ba sebetsa;Haeba ho se nke khato e molemo e nkiloeTumellanong ntse.
		-- Lao Tse, "Tao Te Ching"

%
lekanngoengTsela ke sejana se se nang moeli;Sebelisoa ke boithati, e sa tlala ke lefatše;E ke ke ea khaoloa, nkileng, dimmed kapa stilled;bolibeng lona ke patiloeng, e fumaneha hohle 'me ka ho sa feleng;Ha ke tsebe moo e tsoa ho;Ho tluoa tabeng ea pele tlhaho.
		-- Lao Tse, "Tao Te Ching"

%
NatureNature e se mosa;E tšoarang lintho tsohle ka ho hloka leeme.The Sage hase mosa,'Me o tšoara batho bohle ka ho hloka leeme.Nature e tšoana bellows e,Empty, leha ho le joalo ha ho mohla phepelo ea khaotsa eona.Ka ho eketsehileng ho eona susumelletsa ho eketsehileng, e beha;Kahoo boholo ba nako Sage hulela holim phihlelo ea'Me a ke ke a khathetse.
		-- Lao Tse, "Tao Te Ching"

%
ExperienceExperience e nōka,mohloli o moholo oa eona patiloe, ho sa feleng phallang:monyakong oa eona, e leng motso oa lefatše,Tsela susumelletsa ka hare ho eona:Thala holim 'a eona; e ke ke matha omme.
		-- Lao Tse, "Tao Te Ching"

%
CompleteNature feletseng hobane ha sebeletsa ka boeona.The Sage beha ka boeena ka mor'a 'me o fumana ka boeena o neng pele,Hlokomolohang takatso ea hae 'me o fumana ka boeena o re khotsofetse.O feletseng hobane ha a sebeletsa ka boeena.
		-- Lao Tse, "Tao Te Ching"

%
metsiMolemo ka ho fetisisa ea motho e tšoana le metsi a phelisang,E leng melemo lintho tsohle, 'me ha a loana le bona,E leng phallang libakeng tseo ba bang ba khesa,Moo e ke ka tsela e lumellanang le tsela eo.Kahoo Sage e reng:Maphelo a ka hare ho lintho tsa tlhaho,Nahanang ka hare ho fihlela litaba tse tebileng,O fana ka ka hare ho hloka leeme ha,Bua ka hare ho nahanang kateng,Laola ka hare ho e hlophisehileng,Crafts ka hare ho bokhoni,Liketso ka hare ho sebelisa monyetla oo.Ha a loana, 'me ea mong loana khahlanong le eena.
		-- Lao Tse, "Tao Te Ching"

%
tlohela mosebetsiTlatsa senoelo ho molomo oa lona 'me e habonolo tšolloa;Bohale sabole ho thata ka ho fetisisa tsa eona le eona e robehile habonolo;Bokella letlotlo moholo ka ho fetisisa 'me e habonolo utsoitsoeng;Ipolelang sekoloto le lits'ebeletso hlompha le ho u habonolo oa;Tlohela mosebetsi ka lekhetlo le leng sepheo sa hao e fihlellwa - sena ke tlhaho.
		-- Lao Tse, "Tao Te Ching"

%
tumellanongHakana Tsela, u ba amohela;Hema ka bonolo, o ba le sa tsoa tsoaloa;Tlosa kelello ea hao, u ba tse hlakileng;Hōlisa bana ba hao, u ba se nang leeme;Qalang pelong ea hao, u ba amogetwe;Amohela lefatše, u amohela Way.Jara 'me hōlisa,Empa eseng ho bōpa nang,Ho fana ntle ho batla,Sena ke tsela e lumellanang.
		-- Lao Tse, "Tao Te Ching"

%
ToolsMashome a mararo spokes kopana nave e;Ka lebaka la lesoba re ka sebelisa lebili.Clay o bōpetsoeng hore e be sejana;Ka lebaka la mokoti oo re ka sebedisa senoelo.Marako a pota-potileng hahiloeng leifo e;Ka lebaka la menyako re ka sebelisa ntlo.Ka tsela eo lithulusi tsa tsoa seo teng,Empa sebelisa ho seo ha ho joalo.
		-- Lao Tse, "Tao Te Ching"

%
boleng bammala le ho hongata haholo foufatsa leihlo,mino le ho hongata haholo deafens tsebe,tatso le ho hongata haholo dulls mahalapa,bapala le ho hongata haholo maddens kelello,takatso e ngata haholo oe pelo.Ka mokhoa ona oa Sage tsotella sechaba:A fanang ka eona mpeng, eseng bakeng sa kutloisisong ea;O hlokomoloha kgopolo le nang tieo ho mokelikeli ona.
		-- Lao Tse, "Tao Te Ching"

%
SelfKa bobeli thoriso le ho behoa molato sesosa kamehoEtsoe ba tlisa batho tšepo le tšabo.Ntho ea tšepo le tšabo e bontsang boithati -Bakeng sa tsona, ntle le tsa ho itlhahisetsa, eo ka 'na ba fumanang leruo le likoluoa ​​li sentseng meaho etsahala neng?Ka lebaka leo,Ea ileng a khethollang boeena lefatšeng ka fuoa lefatše,Empa ke mang ea le ipitsa lefatše le ka amohela lefatše.
		-- Lao Tse, "Tao Te Ching"

%
MysterySheba empa a ke ke a bonoa - ho ke ke ka tlas'a foromo;O ile a mamela empa a ke ke a utloa - ho ke ke ka tlas'a molumo;E neng e tšoaretsoe empa a ke ke a ama - ho ke ke ka tlas'a boikutlo bo joalo bo;Lintho tsena depthless qoba tlhaloso,'Me motsoako o kena ka sephiri ba se nang balekane.Ea eona ea phahama ha ho na leseli,A oela ea oona ha ho na lefifi,A tsoele sa khaotseng ka nģ'ane ho tlhaloso,Lera seo ha a eo;foromo ea eona ea formless,setšoantšo sa sona letho,lebitso la eona moo ho khutsitseng;Latela, ho se na morao,Khahlanyetsa eona, e se nang sefahlehong.Ba teng hona joale e sebetsana le lintho tse etsahetseng;Ka tsela eo u utloisisa tswelopela ea Way,E leng lero la eona.
		-- Lao Tse, "Tao Te Ching"

%
leseliThe leseling rua nang le kutloisisoKahoo o tebile ka ho ba ke ke a utloisisoa.Hobane ba ke keng a utloisisaNka feela hlalosa ponahalo ea bona:Seli joaloka e 'ngoe tšela leqhoeng,Etsetsoa qeto e be e mong pota-potiloe ke kotsi,Inyenyefatse ha u le e mong eo e leng moeti,Unbounded joalokaha qhibiliha leqhoa,Kannete ebile lia joalokaha lehong unshaped,E pharaletse joalokaha phuleng e,Seamless joalokaha metsi seretse.Ea ileng a Stills metsi a seretseng ka 'na rarolla,Ea batlang ho khaotsa ho le hore a ka tsamaea ho ea pele,Ea batlang ka tlase ho ka 'na transpire,Decays, empa ba ke ke ba nchafatsa.
		-- Lao Tse, "Tao Te Ching"

%
Bola 'me NchafatsaEmpty e bontsang boithati ka ho feletseng;Amohela khotso e phethahetseng.lefatše le tla tsoha 'me rea sisinyeha;Shebella khutlela ho phomola.lintho tsohle holangE tla khutlela ho tsoe mohloling oa bona.khutlele Sena ke litsela tsa khotso,;Ke phallo ea tlhaho,An bola sa feleng le nchafalo.Amohela sena tlisa leseli,Hlokomoloha sena tlisa masisa-pelo.Ea ileng a amohela phalla tlhaho fetoha 'ohle-cherishing;Ho feta tsohle-e cherishing a fetoha ea se nang leeme;Ho ea se nang leeme o ile a fetoha magnanimous;Ho magnanimous a fetoha mokhoa oa tlhaho;Ho tsa tlhaho o ile a fetoha 'ngoe ka tsela eo;Ho ba e mong le Way a fetoha shoeng:Leha ho le joalo 'mele oa hae o tla bola, Tseleng ke ke.
		-- Lao Tse, "Tao Te Ching"

%
babusiBabusi bana molemohali tse scarcely tsejoa ke bafo ba bona;Ha letsatsi le hlahlamang molemohali ratoa le ho rorisoa;Ha letsatsi le hlahlamang a tšaba;Ha letsatsi le hlahlamang nyelisitse:Ha ba na tumelo ho batho ba habo bona,'Me batho ba eona li be ea sa tšepahaleng ho bona.Ha babusi bana molemohali fihlela morero oa tsonabafo ba bona ba bolela phihlello e le ea bona.
		-- Lao Tse, "Tao Te Ching"

%
boikaketsiHa Tsela e lebalaHobane ba tlamehile le toka hlaha;Ka mor'a moo, tsebo le bohlale ba tsoaloaHammoho le boikaketsi.Ha likamanong tsa lumellanang qhalaKa mor'a moo, ho hlompha le ho boinehelo ho hlaha;Ha sechaba se oela pherekanoKa mor'a moo, botšepehi le lerato la naha ea tsoaloa.
		-- Lao Tse, "Tao Te Ching"

%
nolofatsaHaeba re ne re ka lahla ho tsebo le bohlaleKa mor'a moo, batho ba ne ba rua molemo halekholo;Haeba re ne re ka lahla hobane ba tlamehile le tokaKa mor'a moo, likamanong tsa lumellanang ne a theha;Haeba re ne re ka lahla artifice le etseng phaelloKa mor'a moo, a matlakala le bosholu e ne e tla nyamela.Leha ho le joalo phekoloa ha tšoara joalo matshwao afe kapa afe feela'Me kahoo ba ile ba ba a sa tšoanelehe.Batho ba hloka phekoloa ha ea botho:Senola ho itlhahisetsa oa hao hlobotse 'me li amohele lintho tsa tlhaho ba hao ba pele;Tlama tsa hao boithati le ho laola ho rata botumo ba hao;Lebala senya mekhoa e metle ea hao 'me nolofatsa litaba tsa hao.
		-- Lao Tse, "Tao Te Ching"

%
leleraKe phapang pakeng tsa ananela le itima lintho life?Ke phapang pakeng tsa se setle le se khopisa eng?Ke phapang pakeng tsa se tsosang 'me a tsohile eng?Batho ba nyakaletse joalokaha eka le phathing le mokhoa o babatsehangKapa ho bapala serapeng sa boikhathollo nakong ea selemo,Empa ha ke khutsitseng le lelera,Joaloka tsoa tsoaloa e pel'a eona o ithuta ho bososela,A le mong, ba se na lehae oa 'nete.batho ba na ka ho lekaneng 'me ho qenehela,Moo ke se na letho,'Me pelo ea ka e booatla,Sarakane le koahetsoeng.Batho ba e khanyang le itseng,Moo ke leng lerootho 'me ekare oa ferekana;Batho ba bohlale le ea bohlale,Moo ke leng lerootho le tse hlokang tsebo;Aimless joalokaha e tsokoang hoholeha holim'a leoatle,Khomaretse letho.Batho ba tšoarehile ka morero,Moo ke leng sa sebetseng 'me kaba;Ha ke bolella tsotella lichaba 'Empa ke fepa nakong ea letsoele tlhaho.
		-- Lao Tse, "Tao Te Ching"

%
amohelaTumellano feela a latela Way.Tsela e ntle le foromo kapa quality,Empa o bolela mefuta eohle le lit sobotsi;Tsela e patiloe 'me implicate,Empa o bolela kaofela ha tlhaho;Tsela e sa fetoheng,Empa o bolela tshisinyo tsohle.Ka tlas'a boikutlo le memoriTsela ke mohloli oa lefatše lohle.Nka utloisisa mohloli oa lefatše?Ka ho amohela.
		-- Lao Tse, "Tao Te Ching"

%
HomeAmohela 'me u be kaofela,Bend 'me u otlolla,Empty 'me u tlatse,Bola 'me u nchafatse,Batla le u se fumanang,Phethahatsa 'me u be ferekana kelellong.The Sage amohela lefatšeJoalokaha lefatše amohela Tsela;Ha a bonahatsa ka boeena, kahoo e bonoa ka ho hlaka,Ha lokafatsa boeena, kahoo e ile a hlokomela,Ha ithorisa, kahoo e tlotloa,Ha boikakaso boeena, kahoo le mamella,Ha loana, kahoo ea mong loana khahlanong le eena.The boholo-holo a re, "Amohela 'me u be eohle",Ka lekhetlo le leng kaofela, lefatše ke e le lehae la hao.
		-- Lao Tse, "Tao Te Ching"

%
mantsoeNature e re mantsoe a seng makae feela:High moea o fokang Ha e tšoarelle nako e telele,Kapa hona hore pula ea litloebelele.Haeba mantsoe lintho tsa tlhaho ha li tšoarellaKe hobane'ng ha batho ba tsamaeang le motho?Ea ileng a amohela kutloano, e fetoha lumellana.Ea ileng a amohela tahlehelo, e ba lahlehile.Etsoe ke mang ea amohelang kutloano, Tseleng lumellana le eena,'Me ke mang amohela tahlehelo, Tseleng ke keng fumana.
		-- Lao Tse, "Tao Te Ching"

%
ikhotsofatsaOtlolla itlhokomele le u ke ke ua ema e tsitsitseng;Behantsha u ithata 'me u ke ke ua bonoa ka ho hlaka;Lokafatsa u ithata 'me u ke ke ua hlomphuoa;Kgothaletsa u ithata 'me u ke ke ua lumela;Boikakaso itlhokomele le u ke ke ua mamella.maitshwaro Tsena ke bakang tsenyo, ho ikhotsofatsa,'Me kahoo ba hohela disfavour;Tumellanong qoba bona.
		-- Lao Tse, "Tao Te Ching"

%
Ka tlas'a AbstractionHo na le e le sephiri,Ka tlas'a khemise,Khutsa, depthless,A le mong, ea sa fetoheng,E fumaneha hohle 'me e mokelikeli,'Mè oa tlhaho.Bo se na lebitso la ka, empa ke e bitsa "Tsela";Bo se na moeli, empa ke e bitsa "a se nang moeli."Ho sa lekanngoeng, ho phalla-hang ho sa feleng;Phallang-hang ho sa feleng, ho khutlela ho intša ka:Tsela e sa lekanngoeng,Kahoo lintho tsa tlhaho e se nang moeli,Kahoo lefatše le ke se nang moeli,Kahoo ke na sa lekanngoeng.Etsoe ke abstracted tsoang lefatšeng,Lefatshe go tswa tlhaho,Nature tswa ho Way,'Me Tsela ho se ka tlas'a khemise.
		-- Lao Tse, "Tao Te Ching"

%
CalmMatla a khoheli ke mohloli oa lightness,Le bonolo, le mong'a loketseng lia potlaka.A ka bomong ba chesehang motsamai tla leeto la letsatsi lohle, lebela haethepa;Feela sireletsehile betheng ea hae ka boeena o ile a lahleheloa ke ka 'na tsona a robala.Kahoo mookameli oa sekepe se leholo lokela ho sebetsa habobebe kapa ka lepotlapotla ka.Emelang habobebe, o ile a ea lahleheloang mahlong a lefatše,Emelang ka lepotlapotla, o ile a ea lahleheloang taolo ea ka boeena.motsamaisi oa sekepe ka ke tsa tšoara sekepe la hae le leholo e le seketsoana;Ho e-na glitter joaloka a jadeO tla ema ka joaloka lejoe.
		-- Lao Tse, "Tao Te Ching"

%
phethehongMotsamai bo phethahetseng siea ha ho tselaneng e tla lateloa;Sebui se ile sa bo phethahetseng siea pelaelo lokela ho arajoa;The akhaontente bo phethahetseng siea ha ho sebetsana le ho beha ho tlatswa;Setshelong bo phethahetseng siea ha ho notlela ho koaloa;The lefito bo phethahetseng siea na bofelo ho ravelled.Kahoo boholo ba nako Sage nurtures batho bohle'Me tlohela mang kapa mang.O amohela lintho tsohle li tsamaea'Me a furalla letho.O ba teng ho makolopetso nyenyane ka ho fetisisa.Bakeng sa matla e tsoang lokela tataisa ba fokolang;Ba fokolang ba disebediswa tsa e tala ho ea matla.Haeba tataisa ha a hlomphuoa,Kapa lintho tse bonahalang tse e sa hlokomeloa,Pherekano e tla fella, ho sa tsotellehe hore o bohlale 'ngoe ke.Sena ke sephiri sa phetheho:Ha patsi e tala e betliloeng, e ba thulusi ea e;Ha motho a se hiriloe, o ile a fetoha sesebelisoa e;'Metli oa mapolanka bo phethahetseng siea nang patsi ho se betliloeng.
		-- Lao Tse, "Tao Te Ching"

%
baSebelisa e motona, ho e motsehali,Ho monyako oa lefatše,U amohele tsela e lumellanang'Me ba joaloka tsoa tsoaloa e.U sebelisa matla a rona, ho ba fokolang,Ho sebetsana le motso oa lefatše,U tumellanong feletse e'Me ba joaloka unshaped lehong.U sebelisa leseli, ho lefifi,Ho lefatše,U lumellana ka ho phethahetseng'Me ba khutlele ho tsela.
		-- Lao Tse, "Tao Te Ching"

%
ho rata botumoBa lakatsang ho fetola lefatšeHo latela nang takatso ea bonaA ke ke a atleha.lefatše le bōpehileng joaloka ka tsela eo;E ke ke bōptjoe ke e bontsang boithati.Leka ho fetola eona, u senya eona;Leka ho rua, u lahleheloa ke eona.Kahoo ba bang ba tla etella pele, ha ba bang latela.Ba bang ba tla ba mofuthu, ba bang batangBa bang ba tla be matla, ba bang ba fokolang.Ba bang ba tla fumana moo ba ileng ba eangHa ba bang ba oe ka lehlakoreng la tsela.Kahoo boholo ba nako Sage e tla ba leha e majabajaba leha e mabifi.
		-- Lao Tse, "Tao Te Ching"

%
thoe pefobanna ba matla ba buuoa hantle eletsa se ke a sebelisa pefo,Liketso tse mabifi e na le mokhoa oa ho khutlela;Meutloa le litlama-tlama hōla hohle moo lebotho etelang'Me ka lilemo tse otileng latela ntoa e khōlō.kakaretso A hantle eletsaHo fihlela ha ho letho tse fetang ditaelo hae:Eseng ho nka monyetla ka tlhōlo ea hae.Leha e le ho khanya, ithorisa kapa boikakaso boeena;Ho etsa se e bitsetsa ke hlokahala hore,Eseng ka qeto e thehiloeng tsebong.Etsoe esita le lebotho la matla ka ho fetisisa e tla fokolisa le nako,'Me joale tlaleha pefo ea oona e tla khutla,' me ba bolaea eona.
		-- Lao Tse, "Tao Te Ching"

%
mabothoMabotho ke lithulusi tsa pefo;Ba etsa hore batho ba le hloea le tšabo.The Sage tla kopanela le tsona.Morero oa hae ke pōpo;morero oa tsona ke ho timetsoa.Libetsa ke lithulusi tsa pefo,Eseng ea Sage ea;O sebelisa feela ho bona ha ho se na qeto e thehiloeng tsebong,'Me joale ka bonolo,' me ka masene a seng makae,Etsoe o fumana ho se na botle ba ho 'ona.Mang kapa mang ea fumanang botle bo ka libetsaO thabela ho tlhabong oa batho;'Me ke mang thabela ho polaoA ke ke a khotsofalla boeena ka khotso.Kahoo slaughters lokela ho llela'Me tlhōlo ketekoa ka lepatong.
		-- Lao Tse, "Tao Te Ching"

%
dibopehoTsela ha e na sebopeho sefe oa 'nete,'Me ka hona ha ho lea mong ka laola.Haeba 'musi o ne a laola Waylintho tsohle e ne e tla latelaTumellanong le takatso ea hae,Le monate pula e ne e tla oa,Seng matsapa slaking seng le se seng lenyora.Tsela e bōpehileng joaloka ke sebelisoe,Empa ka nako eo sebopeho sefe e lahlehileng.U se ke ua tšoarelle ka tieo ho dibopehoEmpa a ikutloa joang phalla lefatšengJoalokaha dikhoso nōka e theosa ho leoatle.
		-- Lao Tse, "Tao Te Ching"

%
makhabaneEa ileng a utloisisa lefatše o ile a ithuta;Ea ileng a utloisisa ho itlhahisetsa e leseling.Ea ileng a hlōla lefatše o matla a;Ea hlōlang ea ho itlhahisetsa na tumellanong;Ea ikemiselitseng na morero.Ke mang ea khotsofetse na leruo;Ea ileng a sireletsa lehae la hae ka 'na nako e telele mamella;Ea ileng a nehelana ka lapeng la hae ka 'na nako e telele pholoha ho lona.
		-- Lao Tse, "Tao Te Ching"

%
ControlThe phallang Way le ebbs, ho bōpa le ho timetsa,Phethahatsa lefatšeng lohle, ho ba teng ho makolopetso manyenyane ka ho fetisisa,Ipolelang ha ho letho le puseletso.E nurtures lintho tsohle,Leha ho le joalo ha ho laola;E na sa ikemisetsa,Kahoo, ho bonahala ea bohlokoa.Ke mokelikeli ona lintho tsohle;Leha ho le joalo ha ho laola;Bo se na mokhelo,Kahoo, ho bonahala kaofela-bohlokoa.The Sage ne a ke ke a laola lefatše;O se lumellana le lefatše.
		-- Lao Tse, "Tao Te Ching"

%
khotsoHaeba u fana ka 'mino le lijoBasele ba se ba khaotse ho ba le uena;Empa haeba u tumellanong le tsela eobatho bohle ba lefatše e tla tsoela pele uPolokehong, bophelo bo botle, sechaba, le khotso.Tsela nang bonono le tatso ea;E ka leha e bonoa leha e utloa,Empa molemo mosebetsing oa ea oona e ke ke khathetse.
		-- Lao Tse, "Tao Te Ching"

%
hanyetsa lekhotlaHo fokotsa susumetse mokhoa motho e mong, pele atolosa eona;Ho fokotsa lebotho la motho e mong, pele eketsa eona;Ho ba liha motho e mong, ka lekhetlo la pele phahamisa bona;Ho nka ho tswa mothong e, pele ba fa eona.Sena ke nna bofitlha leo ka sebele ba fokolang hlōla matla:Fish aa lokela ho tlohela bolibeng ba bona,'Me lisabole aa lokela ho tlohela scabbards bona.
		-- Lao Tse, "Tao Te Ching"

%
TranquillityTsela ha a nka khato, empa ha ho letho le siea etsolloa.Ha u amohela senalefatše le tla atleha,Tumellanong le tlhaho.Nature ha rua takatso;Ntle le takatso, pelo fetoha sebakeng se khutsitseng;Ka mokhoa ona lefatše lohle le entsoeng khutsitseng.
		-- Lao Tse, "Tao Te Ching"

%
lineanoBuuoa hantle thehoa hierarchies ha habonolo fotholoa;Haufi-ufi tšoaroa litumelo tse sa habonolo lokolloa;Kahoo lineano enthralls tloha molokong o mong ka mor'a o mong.Tumellanong ha a tsotelle kutloano, 'me kahoo e ka tlhaho finyelloa;Empa lineano ke morero o holim 'kutloano,' me kahoo a ke ke a fumanang.Tumellanong leha e liketso leha e mabaka a;Rata liketso, empa ho se lebaka;Toka ea sebetsang sebakeng sa hae hore a sebeletse le lebaka le;Empa liketso lineano ho tiisa nahana.Ha Tsela e lahlehileng, ho setse tumellanong;Ha tumellanong e lahlehileng, ho setse lerato;Ha lerato e lahlehileng, ho setse toka;'Me ha toka lahlehileng, ho setse lineano.Lineano ke bofelong ba selemo sa kutloelo-bohloko le botšepehi,Ho qaleha ha pherekano;Tumelo ke tšepo mebala-bala kapa tšabo,Ho qaleha ha bothoto.The Sage tsoela ka tsela e lumellanang, eseng ka tšepo;O lula tholoana eo, ha ho buuoe ka lipalesa;O amohela boleng ba, 'me hlokomoloha khemise.
		-- Lao Tse, "Tao Te Ching"

%
SupportMehleng ea inahaneloang lintho tsohle e ne e le karolo eohle:sepakapakeng eohle e ne e hlakile,lefatše lohle e ne e tsitsitse,lithaba tsohle tse ba ne ba tiile,linoka tse eohle e ne e tletse,All ea tlhaho e ne e mobu o nonneng,'Me babusi bohle ba ne ba tšehetsoa.Empa, ho lahleheloa ke mokhoa o hlakileng, leholimo hahola;Ke Ile ka Lahleheloa botsitso, lefatše petsoha;Ke Ile ka Lahleheloa matla, lithabeng teba;Ke Ile ka Lahleheloa metsi, ba linoka tse tletlerana;Ke Ile ka Lahleheloa tsoalo, lintho tsa tlhaho li ile tsa nyamela;'Me ho lahleheloa ke tshehetso, babusi ba oa.Babusi itšetlehile bafo ba bona,E khabane itšetlehile ba ikokobelitseng;Kahoo babusi ipitsang likhutsana, ba lapetse 'me a le mong,Ho hlōla tshehetso ya batho.
		-- Lao Tse, "Tao Te Ching"

%
Tshisinyo le UseThe tshisinyo ya Way ke ho khutlela;Ho sebelisoa ha Way ke ho amohela;lintho tsohle li tsoa tseleng,'Me Tsela tsoa letho.
		-- Lao Tse, "Tao Te Ching"

%
latelangHa motho a maholo ithuta tsela, o ile a latela ka ho eona le mahlahahlaha a;Ha motho tloaelehileng le sebelisoang malapeng ithuta tsela, o ile a latela eona ka linako tse ling;Ha ho lokolloa bolele monna ithuta tsela, o ile a tšeha ka lentsoe le phahameng;Ba sa tšeha, u se ke ua ithuta ho hang.Ka hona e re:Ea ileng a utloisisa Tsela bonahala leoatla;Ea ileng a tsoela pele leetong la Tsela bonahala hlōleha;Ea latelang Tsela bonahala ho hlahlathela.Bakeng sa botle ka ho fetisisa tsela e lumellanang le hlaha thota;E leng 'nete e khanyang bonahalang mebala;Tlhaku eo ruileng hlaha sa fellang;Pelong ho bravest hlaha bonolo;Mofuta rarahanang hlaha inconstant.Sekwere, phethahetseng, ea se nang sekhutlong;Mino, phethahetseng, ea se nang lipina tsa thoriso;Mo Ratang, phethahetseng, ea se nang sehlohlolo;Art, phethahetseng, ea se nang moelelo.Tsela e ka leha e utloa leha e le hona tsejoa:E fetisetsa boikutlo le fetisang tsebo.
		-- Lao Tse, "Tao Te Ching"

%
likelello tsaTsela libere boikutlo,Boikutlo beha ho hopola lintho,Boikutlo le memori bere khemise,'Me khemise beha lefatšeng lohle;E mong le e ntho lefatšeng beha ikutloa joang le se etsang,'Me, imbued ka kelello, tumellanong le Way.Joalokaha ba bang ba rutile, le etse joalo ke se rutang,"Ke mang ea lahleheloang tumellanong hanyetsa tlhaho";Sena ke motso oa ho ruta ka.
		-- Lao Tse, "Tao Te Ching"

%
Ho hlōlaMetsi overcomes lejoe;Ntle le boleng ba eona e hloka ho se bula faele;Sena ke molemong oa ho nka ho se nke khato.Leha ho le joalo rua molemo e se nang mesebetsi,'Me phihlelo ntle le khemise,Na etsoa ke ba seng bakae feela.
		-- Lao Tse, "Tao Te Ching"

%
khotsofaloHealth kapa botumo: e neng e tšoaretsoe dearer?Health kapa thepa ea: nang eketsehileng bokae?Etseng phaello kapa tahlehelo: e leng ho eketsehileng likhathatso?lerato le leholo incurs litsenyehelo tsa bo boholo,'Me leruo la leholo incurs tšabo e khōlō,Empa khotsofalo ho na le liphello che.Etsoe ke mang ea tsebang ha ho thibelaHa tsoela pele ho kena kotsing,'Me kahoo ka' na nako e telele mamella.
		-- Lao Tse, "Tao Te Ching"

%
sebakeng se khutsitsengphethehong Great bonahala e sa fellang,Empa ha e bola;Great bongateng ho bonahala se nang letho,Empa ha e tlohele.nete Great bonahala lia ikhanyetsa;Great cleverness bonahala hlokang kelello;Great ya koloba bonahala sa phutholoha.Joalokaha selemo overcomes serame,Le hoetla overcomes mocheso,Kahoo khutsitseng le bo thōtseng hlōla lefatše.
		-- Lao Tse, "Tao Te Ching"

%
HorsesHa sechaba se latelang Way,Horses jara manyolo pholletsa masimo a sona;Ha sechaba se hlokomoloha tsela,Horses jara masole a literateng tsa eona.Ha ho na phoso khōlō ho feta latelang takatso;Ha ho na likoluoa ​​li sentseng meaho khōlō ho feta lebala khotsofalo;Ha ho na ho kula khōlō ho feta ho batla ho fihlellwa;Empa ea se nang dikahare ho khotsofatsa litlhoko tsa haeFumana hore u khotsofale le mamella.
		-- Lao Tse, "Tao Te Ching"

%
Ho tsebaNtle le ho nka mohato oa ka ntleU tseba lefatše lohle;Ntle le ho nka peep ntle ka fensetereU tseba 'mala oa leholimo.Le ho feta u ba,Hakaalo u tsebe.The Sage e ea lelera ba sa tsebe,Sheba ka ntle ho bona,Finyelloang ntle le emelang.
		-- Lao Tse, "Tao Te Ching"

%
nke khatoThe molateli oa tsebo ithuta lintho tse ngata kamoo a ka khonang letsatsi le letsatsi;The molateli oa Way ea lebala lintho tse ngata joalokaha a ka khonang letsatsi le letsatsi.Ke attrition a fihla boemong ba ho nke khatoAo ho 'ona a etsa letho, empa ha ho letho ntse etsolloa.Ho hlōla lefatše, finyella letho;Haeba u tlameha ho finyella ntho e itseng,lefatše ntse ka nģ'ane ho tlhōlo.
		-- Lao Tse, "Tao Te Ching"

%
bathoThe Sage ha khetholla pakeng tsa hae le lefatše;Litlhoko tsa batho ba bang ke tse a hae.O molemo ho ba le molemo;O molemo ho ba ha e ntle le eena,Ka tsela eo, o molemo.O tšepa batho ba ka tšeptjoang;O ile a boela o tšepa batho ba sa tšepahale,Ka tsela eo, o ka tšeptjoang.The Sage lulang tumellanong le lefatše,'Me kelello ea hae e likelello tsa lefatše.Kahoo o ile a nurtures mikili tsa ba bangJoalokaha 'mè a etsa bana ba hae.
		-- Lao Tse, "Tao Te Ching"

%
lefuBanna phalla ho kena bophelong, 'me ebb lefung.Ba bang ba tlala ka ho fumana bophelo;Ba bang ba se nang letho le lefu;Ba bang ba tšoarelle ka tieo ho phela, 'me ka tsela eo, timela,Bakeng sa bophelo ke khemise.Ba tlala bopheloHa ho hlokahale hore ba tšabe linkoe ​​le litsukulu a palo karolong eo,Leha e apara lihlomo le lithebe ntoeng;The rhino fumana ho se na sebaka ka tsona bakeng sa lenaka eona,Nkoe se na sebaka bakeng sa claw eona,Lesole leo ho se na sebaka bakeng sa sebetsa,Bakeng sa lefu fumana ho se na sebaka ka tsona.
		-- Lao Tse, "Tao Te Ching"

%
hōlisaTsela jara lintho tsohle;Tumellanong nurtures bona;Nature shapes bona;Sebedisa phetha bona.E mong le e latelang Tsela me sea mo tlotlisa kutloano,Eseng ka molao,Empa ka ho ba.Tsela libere nurtures, dibopeho, tlatsang,Isitsoeng litsing tsa tlhokomelo, tšelisang, 'me o etsa hore ke ee lehaeng la bona.Jara ntle le nang,Hōlisa ntle le taming,Shaping ntle le qobella,Sena ke tsela e lumellanang.
		-- Lao Tse, "Tao Te Ching"

%
tlhakisetsoKa tsimoloho ea lefatše ke 'm'a eona;Utloisise 'me le u utloisisa ngoana;Amohela ngoana, 'me u amohele' mè,Ea ke keng a timela ha u e-shoa.Bolokela likahlolo tsa hao le mantswe'Me u lule u susumetse mokhoa oa hao;Bua kelello ea hao 'me u nke maemo'Me ha ho letho le tla u pholosa.Joalokaha ho sheba dintlha tse felletseng ke hlaka,Kahoo ho lula ho tenyetseha ke matla;Sebelisa leseli empa a tšolotsoeng ho se na khanya,E le hore u ka etsa u ithata ntša kotsi,Empa amohele mokhoa o hlakileng.
		-- Lao Tse, "Tao Te Ching"

%
litsela tsa thataWith kutloisiso empa se senyenyaneE mong a ka latela Way tsoana le tsela e khōlō,Tšabang feela ho tlohela;Ka mor'a tseleng e khōlō ke ho le bonolo,Leha ho le joalo sechaba sa thabela litsela tsa thata.Ha matlo a borena li tsoela pele hoMasimo a setseng ho mofoka'Me meliko lefeela;Apereng liaparo tsa mabitso setle,Jara lisabole bohale,Glutting ka lijo le ho noa lino,Hoarding leruo le matlotlo a -Tsena ke litsela tsa bosholu,'Me le hōle le tsela.
		-- Lao Tse, "Tao Te Ching"

%
hlaolela HarmonyHlaolela kutloano ka bothata u le mong, 'me tumellanong le fetoha ea sebele;Hlaolela kutloano ka lelapa la hao, 'me tumellanong le fetoha mobu o nonneng;Hlaolela kutloano ka heno, 'me tumellanong le fetohamangata;Hlaolela kutloano ka setso sa hao, 'me tumellanong le fetohamamella;Hlaolela kutloano ka lefatšeng, 'me tumellanong le fetoha e fumaneha hohle.Lula le motho a utloisise motho eo;Lula le lelapa la ha ho utloisisa hore lelapa;Lula le sechabeng ho utloisisa hore baahi;Lula le setso ho utloisisa setso sa moo;Phela lefatšeng ho utloisisa lefatše.Nka phela le lefatše?Ka ho amohela.
		-- Lao Tse, "Tao Te Ching"

%
Bones bonojoanaKe mang ea tlala tumellanong le tšoana le sa tsoa tsoaloa e.Bobi 'me ba kopana le linoha ke ke loma mo loketseng;Hawks le linkoe ​​ke ke claw eena.masapo a hae a bonolo 'leha ho le joalo li utloisise hae ke ea sebele,Etsoe nama ea hae e bonojoana;kelello ea hae e se nang molato leha ho le joalo 'mele oa hae o virile,Etsoe mahlahahlaha a hae a ke matletsetletse;pina ea hae e tšoarellang halelele leha ho le joalo lentsoe la hae ke monate,Ka mohau oa hae o phethahetse.Empa ho tseba tsela e lumellanang baka khemise,Le ho latela khemise baka lineano.Feteng lintho tsa tlhaho baka tlokotsi,'Me ho laola lintho tsa tlhaho baka pefo.
		-- Lao Tse, "Tao Te Ching"

%
ho se be leemeEa ileng a utloisisa ha bolela;Ea ileng a pakela ha ba utloisise.Bolokela likahlolo tsa hao le mantswe;ho se tšoane boreleli haholo le e tšoarela liphapang;Thotofetseng babyalebaby ea hao 'me nolofatsa morero oa hao;Amohela lefatše.Joale,Setsoalle le bora,Etseng phaello le tahlehelo,Re le lihlong,Ba ke ke ba u ama;lefatše le tla amohela uena.
		-- Lao Tse, "Tao Te Ching"

%
Hlōla nang nke khatoU se ke ua laola batho ka melao,Leha e tlaleha pefo leha e espionage,Empa li hlōla nang nke khato.for:Boitšoaro haholoanyane 'me taboos ho na le,Le sehlōhō eketsehileng afflicts batho;Lithunya eketsehileng le lithipa ho na le,The mekha eketsehileng arola batho;Tsa bonono eketsehileng 'me ho na le litsebo tsa ho iphelisa,Ho etsoa phetoho eketsehileng obsoletes batho;Melao eketsehileng le makhetho ho na le,The bosholu eketsehileng corrupts batho.Leha ho le joalo nka khato, 'me batho ba hōlisa rose;Etsa se na melao, 'me batho ba sebetsana ka ho lekana nang rose;Le tsona ha ba thahaselle, 'me batho sebelisana le Krrish;Bontše se na takatso, 'me batho e lumellana le Krrish.
		-- Lao Tse, "Tao Te Ching"

%
No EndHa 'muso o botsoa' me bo sa reroangBatho ba mofuta ofe 'me ka botšepehi;Ha 'muso o phethahetseng ebile tse matlaBatho ba sa khotsofalle maemo le ba thetsang.mahlohonolo tjena holim likoluoa ​​li sentseng meaho;Likoluoa ​​li sentseng meaho lurks ka hare ho mahlohonolo;Mang ea ka reng kamoo lintho li tla fela neng?Mohlomong ha ho na bofelo.Botšepehi bo kile ua thetsoa;Mosa o kile ua ekoa;Banna ba 'nile ba joaloka ena bakeng sa nako e telele.Kahoo boholo ba nako Sage e tiile empa eseng seha,O ile a supa empa eseng phunya,Otlolohile empa e se tenyetsehe,Khanyang empa eseng blinding.
		-- Lao Tse, "Tao Te Ching"

%
ho ithiba joaloka eenaSebelisang sechaba se seholo joaloka u ne u tla pheha tlhapi baa tiea.Ho busa banna tumellanong le tlhahoHo molemo ho thiba;Ho ithiba joaloka eena le etsa tumellano eo ho leng bonolo ho finyella,'Me tumellano eo ho leng bonolo haha ​​likamano tse ntle tsa lumellanang;With tumellanong ou lekane ha ho itoanela hoo ho tla hlaha;Ha ho se ho itoanela hlaha, joale u rua Pelo easechaba,Le ha u rua pelo tsa sechaba, tšusumetso ea hao e tla nako e telelemamelle:Metse ka metso 'me tiisoa ka thata.Sena ke mokhoa oa ho fihlela ha joale ua bona 'me bophelo e telele.
		-- Lao Tse, "Tao Te Ching"

%
bademonaHa u sebelisa Tsela ea ho hlōla lefatše,bademona oa hao o tla lahleheloa ke matla a bona ho kotsi.Hase hore ba lahleheloe ke matla a bona ka tsela e loketseng,Empa e le hore ba ke ke ba ntša kotsi ba bang;Hobane ba ke ke ba ntša kotsi ba bang,U ke ke ua ntša kotsi ba bang:Ha uena kapa bademona ba hao ba ka ntša kotsi,O tla ba khotsong le tsona.
		-- Lao Tse, "Tao Te Ching"

%
ikokobeletse eenasechaba se ke joaloka baeta, e ka 'marakeng,' me e moroetsana.moroetsana eo A hapa monna oa hae ka ho ikokobelletsa tsoelo-pele ea hae;Ikokobeletse eena ke mokhoa oa ho bonngoe.Kahoo, ha e le naha kholo ikokobelletsa naha e nyenyane e hlalosangE tla amohela ea naha e nyenyane;Ha leng naha e nyenyane ikokobelletsa naheng e kholoE tla ho amohelwa ke naha e kholo;E leng eena ea ikokobelletsang 'me adopts;The o ikokobelletsa tse ling 'me e li ile tsa amohela.Ke thahasellong ea naha sebaka se seholo sa ho kopanya le ho fumana tshebeletso,'Me a ba thahasellang ba naha e nyenyane e hlalosang ho kopanya le ho fumana tswang mmusong;Haeba ka bobeli ba ne ba sebeletsa lithahasello tsa bona,Ka bobeli lokela ho ikokobelletsa.
		-- Lao Tse, "Tao Te Ching"

%
sebeTsela e qetello ea banna,Letlotlo la mohalaleli eo,'Me setšabelo sa moetsalibe.mantsoe Fine ba atisa ho alima,Le liketsong boholo li atisa ho appropriated;Ka hona, ha motho a oa, u se ke ua mo lahla,'Me ha motho a rua matla, u se ke ua mo hlompha;Feela lule se nang leeme 'me a mo bontše tse Way.Ke hobane'ng ha motho e mong a ananela Way?The boholo-holo a re, "Ka eona, batho ba batlang ba ka 'na habonolo fumana,Le ba neng ba soabile ka 'na habonolo absolve "Kahoo, ho ke mpho ea bohlokoa e ka ho fetisisa.
		-- Lao Tse, "Tao Te Ching"

%
thatafalloa ke hoTloaela ho etsa ho se nke khato e molemo-;Ba teng ho etsa-ha ho letho;Latsoa flavorless,Tlotlisang ba banyenyane,Atisa ho ba seng bakae,Khutlele lerato bakeng sa lehloeo.Sebetsana le thata ha a ntse a e sa ntse e ho leng bonolo;Sebetsana le leholo ha a ntse a e sa ntse e le manyenyane;Tseo ho leng thata develops ka tlhaho ho tswa ho bonolo,'Me letsatsi le leholo ho tswa ho a le manyenyane;Kahoo boholo ba nako Sage, ka sebetsana le ba banyenyane,Etsa ntho le leholo.Ea ileng a fumana ho le bonolo ho fumana tšepisa ho le thata ho tšeptjoa;Ea ileng a nka lintho habobebe fumana lintho tseo ho leng thata;The bothata ba ho bolelela molaetsa amohela, 'me kahoo o na letho le ikhanyetsang.
		-- Lao Tse, "Tao Te Ching"

%
Hlokomela qalongSe larileng ka sa ntsane ke ho le bonolo ho utloisisa;Se larileng ka hōle ho bonolo ho nahana;Ke eng brittle bonolo ho tamukanya;Ke eng se senyenyane bonolo ho qhalakanyetsa.Leha ho le joalo sefate se pharaletseng ho feta motho le ka amohela tsoetsoeng ya letlobo nyenyane joaloka;letamo A khōlō ho feta nōka ka khaphatseha e qala ka e clod ealefatše;A leeto la lik'hilomithara tse likete tse qala ka letheba ka tlas'a maoto a motho.Ka hona sebetsana le lintho pele li etsahala;Create hlophisa ka pel'a na le pherekano.
		-- Lao Tse, "Tao Te Ching"

%
Hlokomela nakong BofeloEena ea ileng a nka khato, hapiloeng;Eena ea ileng a utloisisa, ea lahleheloang.Hangata batho ba hlōleha le mothating oa ho atleha ho namola;Hlokomela qetellong joaloka qalong,E le hore u ka 'na qoba hlōlehile.The Sage lakatsa ho se-laba-labelang,Makgabane a se na-boleng,O ithuta ho se ithuta,'Me o khutlela libakeng tseo batho ba lebetse;O ne a tla thusa batho bohle hore ba tlhaho,Empa ka nako eo o ne a sa ba tlhaho.
		-- Lao Tse, "Tao Te Ching"

%
bofitlhaBa boholo-holo ba ne ba sa batle ho busa batho ba nang le tsebo,Empa ho ba thusa ho fetoha mokhoa oa tlhaho.Ho thata bakeng sa batho ba le tsebo e batsi ho ba la tlhaho.Ho sebelisa molao ho laola sechaba se fokolisa sechaba.Empa ho sebelisa lintho tsa tlhaho ho laola sechaba se matlafatsa sechaba.Ho utloisisa litsela tsa tsena tse peli tse nang le kutloisiso ke nna bofitlha;Bofitlha mathela tebileng, ranges ka bophara,Nka qeto pherekano le boloka khotso.
		-- Lao Tse, "Tao Te Ching"

%
Lebisang ke Ka mor'aNōka ea carves tsoa phuleng ke phallang ka tlas'a eona.Ka tsela eo, nōka ea e mong'a phula eo.E le hore a tsebe bathoE mong o lokela ho bua le mohlanka ea bona;E le hore ho etella bathoE mong o lokela ho e latela.Kahoo ha Sage e hlaha ka holimo ho bophahamo sechaba,Ba u se ke ua hateletsoeng;'Me ha Sage eme ka pele ho sechaba,Ba u se ke ua sitisoa.Kahoo boholo ba nako ha ho tloaeleha ha Sage ea ha e tlohele,Ha a loana, 'me ha ho motho ea pheha khang khahlanong le eena.
		-- Lao Tse, "Tao Te Ching"

%
be bohlokoalefatšeng lohle o re,"Ke 'na ea bohlokoa ka;Ke 'na ikarotse lefatšeng lohle.Ke 'na ea bohlokoa hobane ke' na ka thoko,Ba ne ba ke e tšoanang, ke ne ke ha ho mohla ba bohlokoa. "Leha ho le joalo mona ke matlotlo a mararoE le hore nka ananela le babatsa ho uena:Ea pele ke kutloelo-bohloko,Oo ka oona motho a fumana sebete.Ea bobeli ke ho ithiba joaloka eena,Oo ka oona motho a fumana matla.'Me ea boraro ke be bohlokoa,Oo ka oona motho a fumana tšusumetso.Ba sa tsabe, empa kantle ho qenehelo,Matla, empa a se na ho ithiba joaloka eena,Kapa tšusumetso, leha ho le joalo bohlokoa,A ke ke a mamella.
		-- Lao Tse, "Tao Te Ching"

%
kutloelo-bohlokoKutloelo-bohloko ke sebetsa botle ka ho fetisisa le e molemohali ikarabella ka.Haeba u ne a tla theha kutloano,Kutloelo-bohloko lokela lika-liketsa u ka rata qhobosheane e.Ka lebaka leo,A lesole le molemo ha bululela tshabo;A moloaneli molemo ha bontša mabifi;A mohloli molemo ha ba kopanela ntoeng;A moeta-pele oa molemo ha a sebelise matla.Sena ke bohlokoa ba ho be bohlokoa;Sena ke kamoo re lokelang ho hlōla tšebelisano-'moho ea ba bang;Sena ho kamoo ho haha ​​tumellanong tšoanang le eo ke tsa tlhaho.
		-- Lao Tse, "Tao Te Ching"

%
laletsengHo na le polelo har'a masole:Ho bonolo ho lahleheloa ke jareteng feta nka senthimithara.Ka mokhoa ona e mong a ka romela mabotho a kantle ho marshalling bona,Tlisetsa libetsa ho beha ka ntle ho pepesa bona,Kopanelang ea sera ntle le hlaselang bona,'Me fuputse metjha matla a bona ntle le ho loantša bona.Ha ho na ea bobeng bo fetisisang ho feta likoluoa ​​li sentseng meaho utloisisane sera sa hao;Ho etsa joalo endangers kaofela ha matlotlo a ka;Kahoo, ha ba babeli buuoa hantle matched makhotla hanyetsa rose,Molaoli eo oa sesole ea ileng a lula kutloelo-bohloko e tla hlōla.
		-- Lao Tse, "Tao Te Ching"

%
batho ba ikhethangmantsoe a ka ho le bonolo ho utloisisa'Me liketso tsa ka ho le bonolo ho phethaLeha ho le joalo ha ho e meng ka utloisisa kapa ho phethisa mosebetsi bona.mantsoe a ka ba le morero; liketso tsa ka-na le lebaka;Leha ho le joalo tsena e ke ke tsejoa 'me ke ke ke a tsejoa.Re ka 'ngoe e ikhethang,' me ka hona bohlokoa hakaakang;Le hoja Sage wears har'a liaparo tsa mahoashe, pelo ea hae e a jade.
		-- Lao Tse, "Tao Te Ching"

%
ho meediEa ileng a amohela mefokolo ea hae ke bophelo bo botle;Ea hlokomolohang mefokolo ea hae oa kula.The Sage amohela ho kula hona hore le tle le moedi e.'Me kahoo e ba' mele.
		-- Lao Tse, "Tao Te Ching"

%
phetoheloHa batho ba se na letho ho eketsehileng ho lahleheloa ke,Ka mor'a moo, phetohelo tla fella.U se ke ua tlosa linaheng tse ea bona,'Me u se ke ua timetsa mekhoa ea boipheliso ea bona;Haeba moroalo oa hao hase tse boima ka nako eo ba ke ke ba baleha ho eona.The Sage lula ka boeena empa ho se na exacts sethabathaba,O nka ka boeena empa ho se na ho hloka sea mo tlotlisa;O hlokomoloha kgopolo le amohela mokelikeli ona.
		-- Lao Tse, "Tao Te Ching"

%
Phello e sa QojoengKe mang ea sebete ea bileng ka sebete o tla timela;Ke mang ea sebete ea bileng a poteletseng tla rua molemo.Phaello e poteletseng moo ho nang le timela ka sebeteEtsoe Phello e sa Qojoeng e sa hlomphe tse makatsang.Esita le bolelela molaetsa dares eseng leka qetello.Phello e sa Qojoeng e sa hlasela, leha ho le joalo lintho tsohle li hlōloe ke eona;Ha ho botsa, leha ho le joalo lintho tsohle araba ho lona;Ha ho hooa, leha ho le joalo lintho tsohle kopana eona;Ha ho rera, leha ho le joalo lintho tsohle li ikemiselitse ka eona.Phello e sa Qojoeng oa letlooa ke pharaletseng e nang le letlooeng sona ke mahoashe,Leha ho le joalo ea mong phonyoha eona.
		-- Lao Tse, "Tao Te Ching"

%
ho bolaoa haHaeba batho ba ne ba sa tšabe lefu,Ka mor'a moo, seo e ne e tla tšebeliso ea Mophethahatsi oa Kahlolo e?Haeba batho ba ne ba tšaba feela ea lefu,'Me u phethisitse mong le e mong ea neng a sa mamele,Ha ho na motho o ne a tla iteta sefuba ho se mamele uena.Ka mor'a moo, seo e ne e tla tšebeliso ea Mophethahatsi oa Kahlolo e?Batho ba tšaba lefu ka hobane lefu le ke kofuto ea qetello.Ha batho ba bolaoa ke ho bolaoa ha ho e-na ke qetello,Sena ke joaloka ho betla lehong la sebakeng sa 'metli e.Ba ileng ba carve lehong sebakeng sa 'metli eHangata lematsa matsoho a bona.
		-- Lao Tse, "Tao Te Ching"

%
borabeleHa babusi nka lijo-thollo le hore ba ka keteka,batho ba habo bona ba lapile;Ha babusi nka khato ea ho sebeletsa lithahasello tsa bona,batho ba habo bona ba lerabele;Ha babusi nka maphelo a hoo bophelo ba bona ba lula,batho ba habo bona ha e sa tšabe lefu.Ha batho ba sebetsa ba sa natse bophelo ba bonaBa ba neng ba ananela hlōla bophelo ba bona feela.
		-- Lao Tse, "Tao Te Ching"

%
tenyetsehasa tsoa tsoaloa ke e bonojoana hamonate,A crone, ka thata 'me ka sekhahla.Limela le liphoofolo, bophelong, ke tenyetseha le succulent;Lefung, ponne le e omme.Kahoo softness le borutho li dipharologantsho tsa bophelo,'Me thatafala le ho satalla ka sehloohong sa lefu.Feela joalokaha sefate se setle sapless tla arola le ho bolaKahoo matla tenyetsehe tla kopana hlōloa;O boima le se matla leshano fatše ka tlas'aHa a ntse a bonolo le motjeko fokola mabapi le pholileng o fokang hasesaane ka holimo.
		-- Lao Tse, "Tao Te Ching"

%
Ho hlokahalaKe khato eo lintho tsa tlhaho hase ho fapana le ho atamela ka seqha?Ke eng e e phahameng e heletsa, hona ka tlaase o tsosoa o;Ke eng molelele o shortened, hona thinner e broadened;Nature o tshisinyo decreases ba nang le tse fetang tseo ba li hlokang'Me eketsa ba hlokang ho li feta nang le sona.Ho ke ke ha ho joalo nang Man.Monna decreases ba hlokang ho li feta-na'Me eketsa batho ba nang le tse fetang tseo ba li hlokang.Ho fana ka seo u se ha ba hloke ke ho latela Way.Kahoo boholo ba nako Sage fana ka ntle ho tebello,Finyelloang ntle le ipolelang mokitlane,'Me ha se na takatso ea ho ostentation.
		-- Lao Tse, "Tao Te Ching"

%
inehelaHa ho letho le lefatšeng o tšoana le bonolo 'me ho inehela joalokaha metsi,Leha ho le joalo ho letho le ka bo molemonyana hlōla ka thata le ho ba matla,Etsoe ba ile ba ka leha e laola kapa hona ho felisa le eona.Le bonolo la overcomes ea thata,The tenyetseha overcomes ea matla;Mong le e mong motho ea tsebang sena,Empa ha ho ea ka etsang.Ea ileng a ba teng ho batho ba ne laola naha le lijo-thollo;Ke bo-mang ba teng boemong ba ne laola lefatše lohle;'Nete habonolo patiloe ke ipolela ha.
		-- Lao Tse, "Tao Te Ching"

%
poelanoHa ntoa e bakiloeng ke e boelane, ba bang ba laola maikutlo a ka thata lule;Sena ke kotsi.The Sage amohela ka tlase ka lebaka la'Me ha a molato kapa otla;Etsoe tumellanong batla tumellanoWhere toka ea batla tefello.The boholo-holo a re: "lintho tsa tlhaho ha a leeme;Ka hona ho sebeletsa batho ba sebeletsang tsohle. "
		-- Lao Tse, "Tao Te Ching"

%
maemo a phethahetsengA heno ba tse nyenyane, tse nang le batho ba 'maloa feela ba;Boloka lithulusi tsa ka bongata, empa u se ke ua itšetleha ka tsona;Ananela bophelo ba hao 'me e be le khotsofaletse lapeng la hao;Ka sekepe le liketsoana 'me palama lipere, empa u se ke ua tsamaea haholo;Boloka libetsa 'me tsa ntoa, empa le se ke hira bona;Mong le e mong ho bala le ho ngola,Ja le ho etsa lintho tse ntle.Phela ka khotso le thabo sechabeng u le mong;Lula ka hare ho mokoko o lla-ea baahelani ba hao,Empa boloka boipuso hao ho bona.
		-- Lao Tse, "Tao Te Ching"

%
The Sagebatho ba tšepahalang ba sebelisa ho se ipolela ha;Ipolela ha hase botšepehi.batho leseling hase rutehileng;Culture ha leseli.batho dikahare hase ea morui;Leruo hase khotsofalo.Kahoo boholo ba nako Sage ha sebeletsa ka boeena;Ka ho eketsehileng o nahanela ba bang, le ho feta a khore;Ka ho eketsehileng o fana ka ho eketsehileng, a mo amohelang.Nature flourishes ka ho qhekella ha ho motho ea;Kahoo boholo ba nako Sage melemo batho bohle 'me pheha khang nang letho le ikhanyetsang.
		-- Lao Tse, "Tao Te Ching"

%
