A kgone ea ASPARAGUS, 73 maeba, ba bang LIVE likulo, 'me e hoamisoa DAQUIRI !!
		-- Bob Violence

%
dwarf A lea feta tsoa kae-kae Detroit!
		-- Bob Violence

%
A shapely OA MOK'HATHOLIKE SCHOOLGIRL e FIDGETING hare moaparo oa ka ..
		-- Bob Violence

%
A ka bophara-eyed, ba se nang molato UNICORN, le mothating oa delicately a Meadow e tletsenang LILACS, LOLLIPOPS & BANA nyenyane ea Thōla ea meso ??
		-- Bob Violence

%
Ha e le hantle, ke eng Nka rata ke e nyenyane ea ho bapala ka spaceship !!
		-- Bob Violence

%
All I ka nahana ka ke platter ea PRUNE manyolo CRISPS ntse hatakeloale lebotho la swarthy, Setaliana libini Lounge ...
		-- Bob Violence

%
Ka tšohanyetso, ke batla hore a lahlele fetang emelang ea ka ba solofetsang BOIPHELISO, hōlae LONG Black litelu 'me ba apara BASEBALL Hat !! ... Le hoja ha ke tsebe HOBANE'NG !!
		-- Bob Violence

%
Ohle a bophelo ba ke fifatsa ea MaRephabliki le nama!
		-- Bob Violence

%
Ho lokile, u degenerates! Ke batla sebaka sena evacuated ea metsotsoana e 20!
		-- Bob Violence

%
nako ena eohle ke 'nile a nka e Russia MIDGET SODOMIZE e HOUSECAT!
		-- Bob Violence

%
Ke siame, o !! Etsisa e TIISO lemetseng kōpa ka tieo bakeng sa Pool Space !!
		-- Bob Violence

%
Na ke tsamaisana le motsoali kapa mohlokomeli?
		-- Bob Violence

%
Na ke kgethilweng leha ho le joalo?
		-- Bob Violence

%
Na ke se ke ka fumana lengolo SCHOOL-s'o?
		-- Bob Violence

%
Na ke SHOPLIFTING?
		-- Bob Violence

%
America !! Ke ile ka bona sena sohle !! Ho hlatsa! Tsoka! Jerry FALWELLING ho kenahlokisa phaephe ya hao ya UHF lebaloa !! SAFEWAY ba kelello ...
		-- Bob Violence

%
Sa moeeng la French gela gela gela o susumetsa linkong tsa ka !!
		-- Bob Violence

%
An enke-LING? Bonnete ba - Nka 'ngoe !! Na u ne u leha e le efe Buy junifomo ea Bokomonisi ??
		-- Bob Violence

%
An Setaliana e COMBING moriri oa hae a ea teropong Des MOINES!
		-- Bob Violence

%
'Me ho feta moo, ea ka karolelano boula ke unimpeachable !!!
		-- Bob Violence

%
Ann Jillian OA moriri etsa LONI Anderson OA moriri shebahala joaloka RicardoMONTALBAN OA moriri!
		-- Bob Violence

%
Ke STEWED PRUNES sa sisinyehe ka har'a moriri Dryer?
		-- Bob Violence

%
Na re phela kapa tse theipi?
		-- Bob Violence

%
Na re ka la Otla leha ho le joalo?
		-- Bob Violence

%
Na re HO leha ho le joalo?
		-- Bob Violence

%
Na re HO leha ho le joalo? Kelello ea ka e SUBMARINE !!
		-- Bob Violence

%
Na u kelellong mona ho Pizza Hut ??
		-- Bob Violence

%
Na u rekisa Nylon OLI liliba ?? Haeba ho joalo, re ka sebelisa PELI dozen !!
		-- Bob Violence

%
Na u sa ntse u le lekhoba la tahi?
		-- Bob Violence

%
Joalokaha Mopresidente ke na ho tsamaea vacuum chelete ea tšepe ea ka pokello!
		-- Bob Violence

%
Awright, e leng e mong oa lōna a pata botoneng ea ka mohono?
		-- Bob Violence

%
Barbara STANWYCK etsa hore ke tsosoe ke !!
		-- Bob Violence

%
Barbie re, Nkang quaaludes a gin 'me le tsoele ho disco le e hang-hang!Empa Ken o re, Woo-Woo !! No mokitlane nakong "Monghali Liquor" !!
		-- Bob Violence

%
Barry ... Eo e ne e ka ho fetisisa PELO-futhumala ha rendition ea "Ke ILE BA KA KATENGTSELA "Ke kile ua utloa !!
		-- Bob Violence

%
Ho ba lefatla mohale e batla e le ea mokete e le TATTOOED KNOCKWURST.
		-- Bob Violence

%
Bela LUGOSI ke ea ka sebedisana moqhobi ...
		-- Bob Violence

%
Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-Bi-
		-- Bob Violence

%
... ... Bleakness lesupi, ... polasetiki lifereko ...
		-- Bob Violence

%
Bo Derek sentse bophelo ba ka!
		-- Bob Violence

%
Boy, na ke nyakaletse ka ho 1971 feela ...
		-- Bob Violence

%
Boys, u TSOHLE khethiloeng hore ba tlohe go th 'Planet a metsotso e 15 !!
		-- Bob Violence

%
Empa ba ile ba pota-pota Mars 1953 !!
		-- Bob Violence

%
Empa o ne a hōlile ka ho lekaneng ho qetela bosiu masquerade lesbiana?
		-- Bob Violence

%
Nka na le tšusumetso e tsoang ho e-na le karolo?
		-- Bob Violence

%
U ka romela e Bean CAKE?
		-- Bob Violence

%
Catsup le Mosetareta hohle sebakeng sa! Ho ea Human Hamburger!
		-- Bob Violence

%
Chubby CHECKER feela o ne a e kana Sandwich a litsi tsa Duluth!
		-- Bob Violence

%
Tsoelopele ea e ithabisa! Joalo, e ntse e le 'na phetheselang seo ho emeloang !!
		-- Bob Violence

%
Hlakola ea laundromat !! Sena setsokotsane-o le-matic feela o ne a e meltdown nyutlelie !!
		-- Bob Violence

%
Nahanang ka th'cute, li'l Cartoon bashanyana! Hopola SerialNUMERE !! Latela Whipple Rd. ETSOA!! Na le FREE PEPSI !! lehlakoreng le lengSiea th'HOLIDAY INN !! Join the Tlhaloso ea Moo LEFATŠE !! ETSA 'na OFFER !!!
		-- Bob Violence

%
CONGRATULATIONS! Hona joale ke lokela ho etsa litlhaloso thinly li koahetsoe mabapiHlompheha, itšepe le ho fumana monate 'NETE a VENTRICLE hao le letona ??
		-- Bob Violence

%
Content: 80% POLYESTER, 20% DACRONi ... The waitress oa junifomo hlakisangTARTAR spaghetti joaloka 8 "ka 10" benyang ...
		-- Bob Violence

%
Na ke na le ho sebelisa lithethefatsi 'overdose?
		-- Bob Violence

%
Ofe o Setaliana Crane Operator feela latsoa sensations thijoe ae MALIBU HOT tub?
		-- Bob Violence

%
Ke ne ke etsa ntho e fosahetseng ??
		-- Bob Violence

%
O ile a ke re ke ne ke le tlhapi? Kapa ka bese ???
		-- Bob Violence

%
Ke ne ke lahla leha ho le joalo ??
		-- Bob Violence

%
Na le ne le fumana WATCH Digital lebokoseng HAO ea VELVEETA?
		-- Bob Violence

%
Na u ne u susumelletsa linthong tse ngata tse lithipa Korean Steak leeto lena, Dingy?
		-- Bob Violence

%
DIDI ... ke hore lebitso la MARTIAN, kapa, na re ka ISERAELE?
		-- Bob Violence

%
Ha aa ka a ke reka 1951 Packard tsoang ho uena March qetela a Cairo?
		-- Bob Violence

%
Disco oli bussing tla bopa throbbing naugahide lipeipi mathangotlolohile ho chesang e mongobo ho tloha libakeng tse mmetsheng hlahisa le devalue dolara ea!
		-- Bob Violence

%
Na ke lokela ho phela ka eona e sa ntse?
		-- Bob Violence

%
Na u tseba bashanyana feela re mpe re ho fetile hara e HOLE Black a sepaka-pakeng?
		-- Bob Violence

%
Na u na le hantle seo ke batlang a e plaid poindexter mokoallo mankhane ??
		-- Bob Violence

%
Na u ka rata "lerato le VITTLES"?
		-- Bob Violence

%
Na u nahana hore ho fana ka "Monkees" ba lokela ho fumana khase ka matsatsi makatsa kapa esita?
		-- Bob Violence

%
Na motho e mong ho tloha Peoria na le Shorter HO sepane mpheta?
		-- Bob Violence

%
ha apara ya hao kamoreng na ASPARAGUS lekaneng?
		-- Bob Violence

%
U SE KE UA ea !! Ha ke Howard COSELL !! Ke tseba metlae Poland ... ema ho !!U se ke ua !! KE Howard Cosell! ... And HA KEA tseba metlae Poland !!
		-- Bob Violence

%
U se ke ua nkotla !! Ke a sa meso Zone !!!
		-- Bob Violence

%
U se ke ua 'na SANFORIZE !!
		-- Bob Violence

%
U se ke ua tšoenyeha, ho motho ea hlileng mamela lipuo Moscow, ebang! ...Sefora, PELE, Advanced CALCULUS, k'homphieutha mananeo, e ntšoLITHUTO TSA, SOCIOBIOLOGY! ... Na ho na le leha e le efe LIPOTSO ??
		-- Bob Violence

%
Edwin Meese etsa hore ke se aparang CORDOVANS !!
		-- Bob Violence

%
Eisenhower !! o etsang likopi mochini oa hao halefisa mpeng ea ka !!
		-- Bob Violence

%
Ebang ke Lokela ho Bolela hona joale kapa re ee "BATHO BA LI LEKHOTLA" !!
		-- Bob Violence

%
Bohle fumana mahala BORSCHT!
		-- Bob Violence

%
Bohle etsahalang sebakeng se itseng !! Ho ka etsahala hore ebe karache thekiso kapa elikoluoa ​​li sentseng meaho Movie !!
		-- Bob Violence

%
Hohle moo ke bonang ke bona NEGATIVITY le ASPHALT ...
		-- Bob Violence

%
Ntšoarele, empa o ne a sa kea u bolella ho na le NO HOPE bakeng sa ho pholoha haKoala Khatiso?
		-- Bob Violence

%
MAIKUTLO a cascading ka lebaka la ka !!!
		-- Bob Violence

%
Qetellong, Zippy lehlanya hae 1958 RAMBLER Metropolitan ho kena fakalthi eakamore ea ho jella.
		-- Bob Violence

%
Taba ea pele, ke tl'o u fa LIKARABO tsohle tekong la kajeno ... Kahoofeela plug ea heno SONY WALKMANS le phutholoha !!
		-- Bob Violence

%
Thetseha uena! Monya EGO SHATTERING mahlaseli tšusumetso e tsoang ho, poliester poltroon !!
		-- Bob Violence

%
etsoe FLAVORING maiketsetso !!
		-- Bob Violence

%
Likete tse 'nè MAGNATES fapaneng, MOGULS & NABOBS ba romping ea hesogotika solarium !!
		-- Bob Violence

%
ENTREES hoamisoa ka flung ke litho tsa hanyetsa Swanson maquloana ...
		-- Bob Violence

%
Fun ho mohla ho bolele hore u se u Sushi !!
		-- Bob Violence

%
Gee, ke ikutloa ke mofuta o mong oa leseli hlooho hona joale, re tseba Ke sitoa ho etsa ea kasathalaete sejana ditefello tse!
		-- Bob Violence

%
Gibble, Gobble, re AMOHELA le ...
		-- Bob Violence

%
Fe Radar ea Tataisoang ke SKEE-bolo LANES le VELVEETA BURRITOS !!
		-- Bob Violence

%
Le tsoele pele ho, EMOTE! Ke holisitsoe ka la libalune ho nahanoa !!
		-- Bob Violence

%
MOLEMO bosiu, bohle ... Hona joale ke na ho tsamaea laola thuso ea pele molemong oa kaPet boikhathollo sutu !!
		-- Bob Violence

%
Hair TONICS, ka kōpo !!
		-- Bob Violence

%
Halofo ea kelello ke ntho e tšabehang ho senya!
		-- Bob Violence

%
Nehelana 'na para ea borikhoe letlalo le e CASIO tastatur - Ke phelang kajeno!
		-- Bob Violence

%
Na batho baa kaofela ba ile HALVAH jala hohle maqaqailaneng ea bona ?? ... Hona joale, honako ea ho "NA A NAGEELA" !!
		-- Bob Violence

%
... O laola ea DECADENT tsamaeang ka tlas'a lefatše moo.
		-- Bob Violence

%
Ke eena Melba-Ka ho ba ... Lengeloi CAKE ... XEROX eena ... XEROX eena -
		-- Bob Violence

%
Mohlomong o sa tsoa batla ho nka lilemo tse fetang lisele tsa ka 'me ka mor'a moo phatloha ka hare ho' najoaloka bolo ka moqomo oa runny CHOPPED sebete! Kapa mohlomong o ka rata hoPSYCHOLIGICALLY TERRORISE ME ho fihlela ha ke na le khanyetso ea ho tokelo-lepheoSesole TAKEOVER oa folete ea ka !! Ke nahana kea lokela ho re AL PACINO!
		-- Bob Violence

%
HELLO KITTY sehlopha sa litlokotsebe terrorizes toropong, lelapa STICKERED ho isa lefung!
		-- Bob Violence

%
HELLO, bohle, Ke BATHO !!
		-- Bob Violence

%
Hello, GORRY-O !! Ke GENIUS tsoang Harvard !!
		-- Bob Violence

%
Lumela. Ke tseba tlhalo har'a ba sa nyalanang ba batšehali Catholic Alaskan !!
		-- Bob Violence

%
Lumela. Feela tsamaea 'me ba leka SE ho nahana ka mala oa haoho hoo e ka bang mashome a mane limithara LONG !!
		-- Bob Violence

%
Hello ... tšepe lesira? Romela e fetang boroso Pizza! Ntoa III? Che kea leboha!
		-- Bob Violence

%
Lumela? Enema bokhobeng? Ke bitsa hobane ke batla ho ba ea thabileng, Ke nahana ...
		-- Bob Violence

%
Ke 'na enoa at sa letsetse' marakeng empa motho ea rekang ea ka libotlolong sampole moroto ...
		-- Bob Violence

%
Ke 'na enoa a 53 B.C. 'me bohle ke batla ke dille asene !!
		-- Bob Violence

%
Ke 'na enoa a sa kamorao OLFACTORY LOBULE empa ha ke bone Carl Sagankae kapa kae !!
		-- Bob Violence

%
Mona re Amerika ... ha ha re bokella ho hloka mosebetsi?
		-- Bob Violence

%
Hey, letela motsotso !! Ke batla ho hlala !! ... U se u se ke ua Clint Eastwood !!
		-- Bob Violence

%
Hey, metala! Ke batla ho SHIRT NEW le e Pony mohatla with spaghetti lemone!
		-- Bob Violence

%
Hiccuping & thothomela ho kena ka har'a litšila DUMPS ea New Jersey joaloka tse lingtahiloeng k'habeche setsiba popi, khohlela moleng FIORUCCI OA !!
		-- Bob Violence

%
Ngakak ... e holofetseng akhaontente ka mohoo o FALAFEL sandwich 'e otla keTROLLEY-koloi ea ...
		-- Bob Violence

%
Ngakak ... A hashe-sebini 'me sefapano-eyed Guy ne ba robetse e sa tsamauoengsehlekehleke seo, ha ...
		-- Bob Violence

%
Ngakak ... e PINHEAD, nakong tšisinyeho ea lefatše, litlhaselo e TSOHLE-MIDGETFIDDLE Orchestra ... ... hei hei ...
		-- Bob Violence

%
Ngakak ... e lipalesa ikakasang e nang le tlhahiso poteletseng ea POLYVINYLChloride ...
		-- Bob Violence

%
Tšoara Mayo & fetisa elelloa bokahohleng ...
		-- Bob Violence

%
Hooray, Ronald !! Hona joale le ka nyala Linda RONSTADT le eena !!
		-- Bob Violence

%
Ke fihla joang HOME?
		-- Bob Violence

%
U ka hlalosa MATLA Wayne Newton holim'a ba limilione? Ho go th 'MOUSTACHE... Na u kile ua hlokomela go th 'tsela hlahang botšepehi, botšepehi & mofuthu?Ho e MOUSTACHE u batla ho nka HOME le hlahisang ho Nancy Sinatra!
		-- Bob Violence

%
Kamoo batho ba bangata retured lihahi tsoang Florida ba tsoa reka pentšeleSHARPENERS letona HONA JOALE ??
		-- Bob Violence

%
How li eona kenang bao MODULAR lihlopha LERATO ??
		-- Bob Violence

%
How 's mosali eo? Na o u lula lapeng thabela bokhaphithaliste?
		-- Bob Violence

%
hubub, hubub, HUBUB, hubub, hubub, hubub, HUBUB, hubub, hubub, hubub.
		-- Bob Violence

%
Hugh Beaumont a hlokahala ka 1982 !!
		-- Bob Violence

%
REPLICAS BATHO ba kenngoa VATS ea tomoso phepo e nepahetseng ...
		-- Bob Violence

%
Kamehla ke ithabisa ka lebaka ha ke khone oa kelello ea ka !!!
		-- Bob Violence

%
Ke jelly bagel. Ke jelly bagel.
		-- Bob Violence

%
Ke sephethephethe leseli, 'me Alan Ginzberg koeteloa hlatsoetsoang ea ka ka 1927!
		-- Bob Violence

%
Ke koahetsoeng ka oli e hloekileng meroho le ke le ngolla morekisi molemo ka ho fetisisa!
		-- Bob Violence

%
Ke 'na ka ho teba tšoenyehile' me ke batla ntho e 'ngoe bakeng sa lijo tsa hoseng E MOLEMO!
		-- Bob Violence

%
Ke ithabisa ... Ke ipotsa hore na e 's NET monate kapa tse tebileng Ithabisa?
		-- Bob Violence

%
Ke 'na SE KE UA e linate ....
		-- Bob Violence

%
Ke u beha hore u moemeli Fantasy Island !!!
		-- Bob Violence

%
Ke ile Bowling ea ka bolo - 'me ba bang SEBELISA LITHETHEFATSI !!
		-- Bob Violence

%
Ke sitoa ho etsa qeto ea hore FOSAHETSENG retelehela ho etsa ka lekhetlo la pele !! Kea ipotsa haeba BOBGUCCIONE na mathata ana!
		-- Bob Violence

%
Ke sitoa ho nahana ka seo. Ha ho tsamaea le HEDGES a le sebopeho saLITTLE LULU - kapa liroboto etsa litene ...
		-- Bob Violence

%
Ke batla ratang kateng!
		-- Bob Violence

%
Ke ne ke sa laela leha e le efe Woo-Woo ... Mohlomong e YUBBA ... Empa ha ho Woo-Woo!
		-- Bob Violence

%
Ha ke lumele ho hlile E khase khaello .. Ke nahana hore ke 'ohle feelaleshano le BIG ka lehlakoreng la salesmen polasetiki pontso - ho rekisa dinomoro tsa eketsehileng !!
		-- Bob Violence

%
... Ha ke tsebe hore na ke hobane'ng empa, ka tšohanyetso, ke batla ho buisana fokolloa I.Q.Maemong e nang le 'mala o moputsoa lente Senate-potlana KOMITI!
		-- Bob Violence

%
Ha ke tsebe hore ke hobane'ng ha ke re hore ... Ke nahana hore e tsoa ho FILLINGS kamolars ea ka morao ...
		-- Bob Violence

%
... Ha ke rate FRANK Sinatra kapa bana ba hae.
		-- Bob Violence

%
Ha ke utloisise Humor ea STOOGES BORARO !!
		-- Bob Violence

%
Ke ikutloa ... ... JUGULAR
		-- Bob Violence

%
Ke ikutloa mathata a lefatše a hona joale!
		-- Bob Violence

%
Ke ikutloa joaloka motho eo a emisoang likoloi mitha kolobile hodima Darvon!
		-- Bob Violence

%
Ke ikutloa joaloka ke phelang ka `` poone-Dog '' nang Nikita KHRUSCHEV ...
		-- Bob Violence

%
Ke ikutloa joaloka ke a e ntloana Bowl e nang le thumbtack a phatleng ea ka !!
		-- Bob Violence

%
Ke ikutloa ke mokhoa o sa fellang hydrogenated!
		-- Bob Violence

%
Ke tlatsa linkho liindasteri KA lesupi le le limakasine boholo-holo oa "MOLULA-QHOOA"'me joale u ka eketsa Hawaii Punch tlhōrōng ... Ba batla ntle jareteng ...
		-- Bob Violence

%
Ke nahana e ne e le toro 'ohle ... kapa e ketsahalo ea HAWAII BOHLANO-O ...
		-- Bob Violence

%
Ke nahana u bashanyana ile mesifa BIG ho etsa lintho tse ngata haholo ho Ithuta!
		-- Bob Violence

%
Ke ne ke a ntshe ka OEDIPUS rarahaneng morao koana ka '81 ...
		-- Bob Violence

%
Ke ne ke dipanekuku litlolo bakeng brunch!
		-- Bob Violence

%
Ke na le sekotlolo e nyenyane a hlooho ea ka
		-- Bob Violence

%
Ke na le molemo haholo meno RERANG HO SE ETSA. Kea leboha.
		-- Bob Violence

%
Ke na le pono ea! Ho e rancid habeli FISHWICH ka Bun ntlafatsa !!
		-- Bob Violence

%
Ke amohetse Provolone bophelong ba ka!
		-- Bob Violence

%
Ke na le lichate tse ngata le litšoantšo ..
		-- Bob Violence

%
... Ke bala DITAELO ...
		-- Bob Violence

%
- Ke bone monate -
		-- Bob Violence

%
Ke bone EXTENDERS tsena lehe a suphamaketeng ke ... Ke balaDITAELO ...
		-- Bob Violence

%
Ke na le matla a ho ema TLHAHISO ka mosebetsi oohle oa COMEDIES lilemong tsa bocha HO KOPANELA LIPHATE !!
		-- Bob Violence

%
KE NA ho reka ncha "Dodge MISER" 'me ba babeli dozen JORDACHE Jeans hobaneviewscreen ka ke "User-ba botsoalle '!!
		-- Bob Violence

%
Kea nyalane ka lilemo tse fetang lilemo tse tšeletseng, empa re ne re tlhabollo ea ho kopanela liphateletsatsi le letsatsi ho tloha Oral Roberts !!
		-- Bob Violence

%
Ke tšepa Ke ile ka reka ea relish letona ... ... zzzzzzzzz
		-- Bob Violence

%
Ke tšepa ntho e 'ngoe MOLEMO ile ka poso kajeno kahoo ke na le lebaka la ho phela !!
		-- Bob Violence

%
Ke tšepa tsa `` Eurythmics '' itloaetsa ho thibela pelehi ...
		-- Bob Violence

%
Ke tšepa u ralimilione ba ithabisa! Ke feela invested halofo bophelo ba haoentsoeng polokelong a tomoso !!
		-- Bob Violence

%
Ke qapa skydiving ka 1989!
		-- Bob Violence

%
Ke ile ka ikopanya scientology nakong karache thekiso e !!
		-- Bob Violence

%
Ke feela lebala filosofi ea ka eohle ea bophelo !!!
		-- Bob Violence

%
Ke feela a ea ka Khosana bumper sticker ... Empa joale ke hopole WHO a ke ...
		-- Bob Violence

%
Ke ile ka tlameha nko JOBO !!
		-- Bob Violence

%
Ke feela ba ne ba mala oa ka lohle pampitšana tlotsitsoeng ba nang le TEFLON!
		-- Bob Violence

%
Ke feela utloa SEVENTIES ba ne ba okametse !! 'Me ke ile sa tsoa ho iteanyanang boikhathollo sutu ea ka !!
		-- Bob Violence

%
Ke feela ka hopola ho hong ka e TOAD!
		-- Bob Violence

%
Ke Kaiser moqolo ?! Life tse molemo ke Kaiser Roll ntle le e nyenyane Cole SLAWka lehlakoreng?
		-- Bob Violence

%
Ke se ke Tseba Joke A !!
		-- Bob Violence

%
Ke tseba kamoo u ka etsang KHETHEHILENG LIPHELLO !!
		-- Bob Violence

%
Ke tseba th'MAMBO !! Ke na le PELI-molumo k'hemistri SET !!
		-- Bob Violence

%
Ke tseba lintho tse mabapi le Troy Donahue hore sitoa le ho hatisoa !!
		-- Bob Violence

%
Ke ile ka tloha sepache sa ka a Bathroom ea !!
		-- Bob Violence

%
Ke rata tsela eo FEELA melomong ea bona susumelletsa ... Ba shebahala joaloka shoa OYSTERS
		-- Bob Violence

%
Ke rata SNOOPY oa hao Fotobehang !!
		-- Bob Violence

%
- Ke rata KATRINKA hobane o lehlanya e Pontiac. Re ntse u tlohehona joale. Ke fepa ba katse.
		-- Bob Violence

%
Ke rata ROCK 'N moqolo! Ke tšoara ka hlooho ea MANTSOE bohle hore ba 'HLAKOLA-KA HO "a1965 !!
		-- Bob Violence

%
Ke lokela ho buisana ka ho reka-BACK LITOKISETSONG TSA nang SLEAZEBALLS tse tsheletseng bonyane studio !!
		-- Bob Violence

%
Nkile ka khabisitsoeng foleteng ea ka ka ho feletseng tse leshome tse lifereko leoto salate !!
		-- Bob Violence

%
Ke nang le tsona tse supileng-borobeding ea baetsi ba litšoantšo tsohle a litsi tsa Burbank!
		-- Bob Violence

%
Ke beha ka thoko kopi ea ka ea 'Bowling LEFATŠE "' me nahana ka sethunya LAOLAlekgotla le etsang molao ...
		-- Bob Violence

%
Ke emela tlhapi !!
		-- Bob Violence

%
Ke kopa mafelo-bekeng a La Habana nang Phil Silvers!
		-- Bob Violence

%
... I bona ntloana litulo ...
		-- Bob Violence

%
Ke khetha E5 ... empa ke ne ke sa utloa "Sam ea Sham le Pharoahs"!
		-- Bob Violence

%
Ke nkha e rancid poone Dog!
		-- Bob Violence

%
Ke nkha joaloka e kolobile fokotsa tleliniki hodima Columbus Day!
		-- Bob Violence

%
Ke nahana hore ke e ikutloa joang ho panya ha leihlo hona joale !!
		-- Bob Violence

%
... Ke nahana ke ne ke bo molemonyana khutlela behile deskeng ea ka 'me ho bapala e nang le tse seng kae tloaelehileng le sebelisoang malapengMISAPPREHENSIONS ...
		-- Bob Violence

%
Ke nahana hore ke tla li bolaea iphumanetse ke qhomela ka ntle ho sena bo14 PALE Window ha a ntse abala lithothokiso Erica Jong OA !!
		-- Bob Violence

%
Ke nahana khethile mosebetsi oa ka e senngoa!
		-- Bob Violence

%
Ke ile ka sebelisa ho ba FUNDAMENTALIST, empa ka nako eo ke utloile ka HIGHMahlaseli boemo 'me ka reka e Encyclopedia !!
		-- Bob Violence

%
... Ke batla MEBALA T.V. le bethe VIBRATING !!!
		-- Bob Violence

%
Ke batla ho BURRITO ea Litsoa-mobung ho ea ... ka e eketsehileng MSG !!
		-- Bob Violence

%
Ke batla ho WESSON OLI a ntshe !!
		-- Bob Violence

%
Ke batla e 'ngoe u ngole ho RE-CEASAR salate ea ka !!
		-- Bob Violence

%
Ke batla UTLOANG! Ke batla 'meli ka hohle Black UTLOANG ho etsa hore ke ikutloe ke a futhumetseng' n boloka !!
		-- Bob Violence

%
... Ke batla mane a metso e PELI TRYNEL FLOATATION Systems hlomamisa ka hare hoTšeletseng le halofo lihora tse !!!
		-- Bob Violence

%
Ke batla e le mopresidente mobe hakaalo ke ka se a ntse latsoa hors d'oeuvres.
		-- Bob Violence

%
Ke batla ho apara ka lōna joalokaha TALLULAH Bankhead le u koahela nang VASELINEle koro THINS ...
		-- Bob Violence

%
Ke batla ho bolaea mong le e mong mona le entsoeng joaloka motle tse mebala-bala haedrojene Bomb !!
		-- Bob Violence

%
... Ke batla ho etsa mesebetsi cranial nang Labobeli Weld !!
		-- Bob Violence

%
Ke batla ho bala thothokiso ea ka e ncha ka boko nama ea kolobe le sebaka sa ka ntle ...
		-- Bob Violence

%
Ke batla ho joalo HAPPY, ea methapong ka molala oa ka totobale !!
		-- Bob Violence

%
Ke batla hore u ho tšoara ka hlooho ea lithothokiso bokella oa Edna ST Vincent MILLAY... Morao !!
		-- Bob Violence

%
Ke batla hore u ho hlophisa pastry diterei ea ka ... ea ka tee-TINS ba benyang athehoe joaloka mola oa Drum MAJORETTES - ka kopo u se ke ua halefa le 'na -
		-- Bob Violence

%
Ke hlahetse fekthering Hostess Cupcake pele nakong ea phetohelo ea ho kopanela liphate!
		-- Bob Violence

%
Ke ile ka etsa makoenya 'me hona joale ke ka beseng e!
		-- Bob Violence

%
Ke lakatsa eka ke ne ke le manicurist kopanela liphate-tlala fumanoa bafu Bronx !!
		-- Bob Violence

%
Ke lakatsa eka ke ne ke le e Cincinnati sekhutlo seterateng a tšoere ke fumane ntja ea e bolokoe e hloekile!
		-- Bob Violence

%
Kea ipotsa hore na nka kile ua qala ka ea ho reka ka mokitlane lefatše?
		-- Bob Violence

%
Kea ipotsa haeba ke lokela ho ba bolella ka bophelo ba ka joalokaha FETILENG e FeletsengOsele?
		-- Bob Violence

%
Kea ipotsa haeba nka lokela ipeha boemong ESCROW !!
		-- Bob Violence

%
Kea ipotsa hore na ho na le letho leo e MOLEMO hodima bosiung bona?
		-- Bob Violence

%
Ke tla rata ho urinate a e letamong OVULAR, porcelain -
		-- Bob Violence

%
Ke kopa KA ya data-botlaaseng JULIENNED le hlohlelletsa-halikiloeng!
		-- Bob Violence

%
Ke kopa LIJO nang molemo phepong 'me joale ... Ke batla ho ba mong -
		-- Bob Violence

%
Ke tla ja eng kapa eng eo le e khanyang Blue !!
		-- Bob Violence

%
Ke tla u bontša KA telex palo haeba u mpontše lōna ...
		-- Bob Violence

%
Ke fuschia boula bolo kae-kae Brittany
		-- Bob Violence

%
Ke GENIUS! Ke batla ho pheha khang kateng polelong sebopeho sa ba nang le Susan SONTAG !!
		-- Bob Violence

%
Ke sebelisa libetsa tsa nyutlelie tsa nyutlelie tlasa botataisi ba leqhoa le cap, 'me ke lokela ho ba le Kleenex!
		-- Bob Violence

%
Ke boetse khahlanong BODY-palama maqhubu !!
		-- Bob Violence

%
Ke boetse pele ho TŠOLLOA pele ho thuisa le pele ho RAPHAELITE !!
		-- Bob Violence

%
Ke Ann Landers !! Nka SHOPLIFT !!
		-- Bob Violence

%
Ke fetola CHANNEL ... Empa bohle ke fumana ke lipapatso bakeng sa "RONCOMohlolo lehlaka STEAMERS "!
		-- Bob Violence

%
Ke sa khaotse tsota th'breathtaking liphello tsa moea khoholeho ea mobu !!
		-- Bob Violence

%
Ke sebele hase ka Omaha!
		-- Bob Violence

%
Ke nyahame ... Ke tšepa ho na le ntho e 'ngoe e tebileng-Fried tlas'a enanyenyane DOMED Stadium ...
		-- Bob Violence

%
Ke ho apara ka le ngotsoe ka e mebe loketseng Ivy League-sutu !! Morao nakong...
		-- Bob Violence

%
Ke MAIKUTLO hona joale hobane ke na le MERCHANDISING CLOUT !!
		-- Bob Violence

%
Ke encased a lera la e hloekileng nama ea kolobe boroso !!
		-- Bob Violence

%
Ke thabela Ke ile ka hopola ho XEROX UNDERSHIRTS tsohle tsa ka !!
		-- Bob Violence

%
Ke lelemelang e fetang ea nyutlelie litšila DUMP haufi ATLANTA, Georgia !!
		-- Bob Violence

%
Ke ho ba le Big Bang Theory !!
		-- Bob Violence

%
Ke ho ba le bohareng ba bo-BEKE BOTHATA!
		-- Bob Violence

%
Ke ho ba le phihlelo e e BOLUMELI ... 'me ha ke nka SEBELISA LITHETHEFATSI leha e le efe
		-- Bob Violence

%
Ke ho ba le phihlelo ea nt she lekgetho deductible! Ke hloka matla ao ea sebelisang crunch !!
		-- Bob Violence

%
Ke ho ba le phasolohile maikutlong !!
		-- Bob Violence

%
Ke ho ba le phasolohile MAIKUTLO !! Empa, uh, KE HOBANE'NG ha ho WAFFLE aPAJAMA ea ka pokothong ??
		-- Bob Violence

%
Ke ho ba le menahano e ntle mabapi le ho sebelisa BASALI INSIPID oa moithati leea ruileng o babuelli ba molao Corporate ...
		-- Bob Violence

%
Ke ithabisa HITCHHIKING ho Cincinnati kapa FAR ROCKAWAY !!
		-- Bob Violence

%
... Ke nahana hore na Giraffe sensuous, CAVORTING ka morao kamorengya kosher Deli -
		-- Bob Violence

%
Ke ka ho toba le batho ba bangata likhopolo tsoetseng pele monate.
		-- Bob Violence

%
Ke ho kena Software!
		-- Bob Violence

%
Ke thuisa ka FORMALDEHYDE le ASBESTOS leaking tsa ka tsePersonal Space !!
		-- Bob Violence

%
Ke kelellong OVERDRAWN! Ke'ng e hore SIGNPOST fihlang pele? E hokae molamuSterling ha u hlile u hloka eena?
		-- Bob Violence

%
Ha ke e-MoIran !! Ke voted bakeng Dianne Feinstein !!
		-- Bob Violence

%
Ke ha e fumanehe bakeng sa maikutlo ..
		-- Bob Violence

%
Ke etsa eka ke hula ka trout e! Na ke etsa ka tsela e nepahetseng ??
		-- Bob Violence

%
Ke etsa eka hore re se ntse u ho shebella kaofela BAFIL SILVERS ho e-na RicardoMONTALBAN!
		-- Bob Violence

%
Ke ka khutso bala tokollong ea morao-rao ea "Bowling LEFATŠE" ha mosali oa ka'me bana ba babeli ho ema li khutsitse KA ...
		-- Bob Violence

%
Ke rated PG-34 !!
		-- Bob Violence

%
Ke amohela molaetsa o ile oa coded tsoang EUBIE Blake !!
		-- Bob Violence

%
Ke BOLUMELI !! Ke rata motho a nang le HAIRPIECE e !! Hlomella 'na ka metsu !!
		-- Bob Violence

%
Ke tlaleha bakeng hobane ba tlamehile joalokaha motho ea kajeno. Ke batla ho etsa se Latin Hustle joale!
		-- Bob Violence

%
Ke beola !! Ke ho kuta litelu ho !!
		-- Bob Violence

%
Ke lutse Lebelo mofumahali oa ka ... Ho 'na, ho e be e thabisang ... Ke mofuthu... Ke VIBRATORY ...
		-- Bob Violence

%
Ke nahana ka Digital litsamaiso BALA-KA HO le k'homphieutha generatedSetšoantšo FORMATIONS ...
		-- Bob Violence

%
Ke ho feletseng nyahame holim 'bakeng sa boemo Ägyptisch le theko ea khoho ...
		-- Bob Violence

%
Ke sebelisa ea ka X-ray Vision ho fumana tlhase etsahala seoelo ea ka hareSebetsang ea litapole ena !!
		-- Bob Violence

%
Ke apere PAMPERS !!
		-- Bob Violence

%
Ke kolobisa! Ke tse hlaha!
		-- Bob Violence

%
Ke ba banyenyane ... Ke HEALTHY ... Ke ka Hike hara CAPT GROGAN OA LUMBAR libaka!
		-- Bob Violence

%
Ke ZIPPY ea PINHEAD 'me ke ho feletseng itlamme ho screen reader mode mokete.
		-- Bob Violence

%
Ke ile ka fumana motsoal'ae ea sebetsang seaparo Setereke ...
		-- Bob Violence

%
Ke na le e le maikutlo a !! Ke hobane'ng ha ke STARE nakong u tle HARD, o lebala oa haoNOMORO EA TŠIRELETSEHO EA SECHABA!!
		-- Bob Violence

%
Ke 'nile ka bala SUPILENG LIMILIONE libuka !!
		-- Bob Violence

%
... Ich moqomong einem dusenjet ins Monaten 53 Vor chr ... ich lande Imantiken Bar ... einige gladiatoren spielen scrabble ... ich riechePizza ...
		-- Bob Violence

%
Haeba motho a tsebahalang naheng ena, ba ile ba lokela ho tsamaea tseleng e etsoeLikhoeli ka nako 'me ba lebitso la bona misspelled ka lehlakoreng la motho eaGREYHOUND SCENICRUISER !!
		-- Bob Violence

%
Ha a kgethwa Zippy tumellano ho e mong le e American e houseboy 55 ea lilemo li ...
		-- Bob Violence

%
Haeba ke kgethilweng ho se motho ea tla ke lokela ho etsa ho hlatsoetsoang ea bona hape!
		-- Bob Violence

%
Haeba ke kgethwa mekoallo e hahiloeng ka konkreite ho pota WHITE HOUSE tlankeloa sebaka ke tasteful bubble replicas ea Ann Margaret!
		-- Bob Violence

%
Haeba ke ne ke ikutloa leha e le efe rarahaneng ho feta ke tla shoa ho hlajoa ke lihlong!
		-- Bob Violence

%
Haeba ke ne ke Q-KELETSO, ke ne ke thibela go th 'putlama lipuisano !!
		-- Bob Violence

%
... Haeba ke ne pelo ho hloleha hona joale, ke ne ke sitoa ho monna eketsehileng lehlohonolo !!
		-- Bob Violence

%
Haeba ke hula switjha lena ke tla Rita HAYWORTH !! Kapa e SCIENTOLOGIST!
		-- Bob Violence

%
ha eba e GLISTENS, gobble eona !!
		-- Bob Violence

%
Haeba boitshwaro ja rōna ke tieo, ha re hloke ithabisa!
		-- Bob Violence

%
Haeba Robert Di Niro assassinates Walter Slezak, e tla Jodie Foster nyala Bonzo ??
		-- Bob Violence

%
Ka 1962, o ne a ka reka para ya SLACKS SHARKSKIN, ka "ContinentalLebanta, "etsoe $ 10,99 !!
		-- Bob Violence

%
A Newark ea laundromats li bulehetse lihora tse 24 ka letsatsi!
		-- Bob Violence

%
Hare, ke na le e tšoanang botho boloetse joalokaha Lucy Ricardo !!
		-- Bob Violence

%
Hare, ke se ke ntse ke lla!
		-- Bob Violence

%
Ke cheselelitsoeng ea sebele, joaloka hanele kapa e battleship? Kapa re utloa bohloko ka Safeway?
		-- Bob Violence

%
Na o sa boselamose INCA nkile Frog mahetleng hae ?? Ke FrogGUIDELIGHT hae ?? Ke labalabela ho tseba e le hore ntja mathela se a ntse a mabapi le ESCALATOR ea ...
		-- Bob Violence

%
Na ho 1974? Ke'ng e etsoe lijo tsa mantsiboea? Nka qeta k'holejeng ea ka Letlōle la ka e le 'ngoetse hlaha thapameng ??
		-- Bob Violence

%
Na ho hloeka litekanyo tse ling?
		-- Bob Violence

%
Na ho NOUVELLE cuisine ha 3 mehloaare loana le e scallop a epoleiti ea spaghetti MORNAY?
		-- Bob Violence

%
Ke ntho e MABIFI ba tlil'o hlaheloa ke e litšila ho ka?
		-- Bob Violence

%
Na see e ka ntle-nka tse ling tsa "Brady tetemang"?
		-- Bob Violence

%
See tlil'o akarelletsa tala ecstasy batho?
		-- Bob Violence

%
Na see ithabisa Terminal?
		-- Bob Violence

%
Na enoa ke eena mocheng oa ho fumana tsa morao-rao whimsical YUGOSLAVIAN tšoantšiso e leng se boetsengetsa hore u batle ho lla 'me ho boela se tshohla Ntoa ea Vietnam?
		-- Bob Violence

%
Na see ke ra khaotsa ea ka ?!
		-- Bob Violence

%
E ha a bolele ntho haeba u e sa ile eo SWING !!
		-- Bob Violence

%
E ne e le motlae !! E fumane?? Ke ile ka amohela melaetsa e tsoang ho DAVID LETTERMAN !!YOW !!
		-- Bob Violence

%
Ho e ngata monate ho phela kapa che ... Ke ipotsa hore na bethe ea ka e entsoe?!?
		-- Bob Violence

%
Ho NO SEBELISA ... Nkile il'o "CLUB z" !!
		-- Bob Violence

%
Ho totobetse ... The FURS ho mohla fihla Istanbul ... O ne e eketsehilenga ea REMAKE ea "TOPKAPI" ... E-eang malapeng hobane ba mosali oa hao ... O etsaFrench toast!
		-- Bob Violence

%
Ho oke - Ke e kelello, haholo.
		-- Bob Violence

%
Ho ea RINSE Potoloho !! Ba nile ka TSOHLE hlokomolohile RINSE Potoloho !!
		-- Bob Violence

%
JAPANE ke HLOLLANG polanete - Kea ipotsa haeba re tla kile ua fihla ho bophahamo ba ea bonaea mabenkeleng COMPARATIVE ...
		-- Bob Violence

%
baprista Mojesuite ba intša BOIPHELISO baemeli !!
		-- Bob Violence

%
Jesu ke oa ka POSTMASTER KAKARETSO ...
		-- Bob Violence

%
Kids, u se ke ua feteletseng ke tsamaee ... "Resort nang kelello bohloeki" e ka bajara le eena FAR!
		-- Bob Violence

%
Kids, marena a supileng a lihlopha tse itseng tsa motheo lijo tse kauwen, hula hanngoe pastry, Pizza,Chefo e bolaeang likokoanyana, lithibela-mafu, NUTRA-monate le lebese DUDS !!
		-- Bob Violence

%
Hlatsoetsoang ke nahana ka ho teba bohlano !! ... ... Um Um ... go th 'mochine o hlatsoang liaparoke sekoti batsho le likausi pinki tse bese bakhanni ea ileng a oela feela a !!
		-- Bob Violence

%
LBJ, LBJ makae metlae ha u ile ua bolella kajeno ??!
		-- Bob Violence

%
Leona, ke batla ho Bolela lintho tse tlang ho uena ... Ke batla ho thatela u ka 'mala o sekareleta eRobe trimmed nang POLYVINYL chloride ... Ke batla ho ea lefeela ASHTRAYS hao ...
		-- Bob Violence

%
E-re ke etse sethabathaba ka ea ho STOCKINGS FISHNET ...
		-- Bob Violence

%
A re ke re tsohle bontša kameho ea botho bakeng sa mathata REVERAND MOON oa molao !!
		-- Bob Violence

%
A re ke re romela Marussia haelloang phelang ka eona ya disebediswa tse kathoko!
		-- Bob Violence

%
Bophelo ke ratoa Tlholisanong! Ke khathollang boemo !!
		-- Bob Violence

%
Joaloka kamehla ke re - ha ho letho le ka otla BRATWURST mona DUSSELDORF !!
		-- Bob Violence

%
moriri Loni Anderson oa lokela ho ngolisoa ka molao !!
		-- Bob Violence

%
Bona tebileng ka openings ea !! Na u bona ELVES leha e le efe kapa EDSELS ... kapa eHIGHBALL ?? ...
		-- Bob Violence

%
Sheba ka mahlo a ka 'me u leke ho lebala hore o na le Macy tatofat karete!
		-- Bob Violence

%
Bonang! A lere! Mohlomong ho isa leholimong, kapa sandwich!
		-- Bob Violence

%
BATLA !! Hlomohile bacha American apere Madras marukgwe le "Mohlape oaSeagulls "kuta moriri!
		-- Bob Violence

%
Nketse shebahala joaloka Linda RONSTADT hape !!
		-- Bob Violence

%
Mary Tyler Moore oa BOSUPA monna se apereng DACRON ea ka Tank Top a ebaratos hotel Honolulu!
		-- Bob Violence

%
Mohlomong re ka hlalosa GOLDIE HAWN ea ruileng PRUSSIAN Blue -
		-- Bob Violence

%
MERYL STREEP ke obstetrician ka!
		-- Bob Violence

%
MMM-limilimithara !! Kahoo ENA ke Bio-NEBULATION!
		-- Bob Violence

%
Mmmmmm-MMMMMM !! A poleiti ea STEAMING likotoana tsa kolobe tsoakane le eashreds ea likhoho tse 'maloa !! ... Oh BOY !! Ke hoo e ka bang ka koenyangTsekolotsoeng-theoha karolo ea e khomo le letšehali leoto soaked a COTTONSEED OLI leTsoekere !! ... A re bone ... Ka mor'a moo, ke tla ba le fatše-UP nama ea Cute,BABY likonyana halikiloeng a sa qhibilihile, mafura lisele tsoang e mofuthu-sehloho,motho e mong o kile a phoofolo PETTED !! ... Yum !! Eo e ne e MOLEMO !! Etsoe DESSERT,Ke tla ba le TOFU Li-burger Toropong ea nang le Bean hlaha leqepheng la lejoe-mobung, WholeKoro Bun !!
		-- Bob Violence

%
Mr le Mofumahali PED, Nka alima 26,7% ya RAYON Textile tlhahiso eaea Seindonesia lihlekehleke?
		-- Bob Violence

%
My Mangoane Maureen e ne e le mogakolodi wa sesole ho Ike & Tina Turner !!
		-- Bob Violence

%
Alamo My likokoana-hloko Box feela tloha ... Ho na noiseless DOZESebetsa hammoho le kichine tletseng !!
		-- Bob Violence

%
Code ea ka ea Ethics e phomolong nakong tummeng SCHROON LAKE ka leboea New York !!
		-- Bob Violence

%
UTLOANG ba ka ba tlohile !!
		-- Bob Violence

%
sefahleho sa ka e ncha, e leng lengolo la tumello ea ka e fetile, 'me ke tlhokomelong ea ngaka !!!!
		-- Bob Violence

%
ka kuta moriri oa ka o feletseng tsa moetlo!
		-- Bob Violence

%
akaretsa chelete KA ke TSOHLE lahloang!
		-- Bob Violence

%
My Leslie Gore rekoto e robehile ...
		-- Bob Violence

%
bophelo ba ka ke Patio ea ithabisa!
		-- Bob Violence

%
kelello ea ka e tšimo litapole ...
		-- Bob Violence

%
kelello ea ka e etsang ashtrays a Dayton ...
		-- Bob Violence

%
lesale la nko ea ka ikutloa joaloka o mobe Ronald Reagan baesekopo ...
		-- Bob Violence

%
Nko ea ka e matla!
		-- Bob Violence

%
... Borikhoe My feela tsoela pele e rampage tse hlaha ka Long Island Bowling Alley !!
		-- Bob Violence

%
borikhoe My feela kena sekolo se phahameng a sa Carlsbad Caverns !!!
		-- Bob Violence

%
My polyvinyl cowboy sepache e ne e entsoe ka Hong Kong ke Montgomery Clift!
		-- Bob Violence

%
Malome Murray hapa Egepeta ka 53 B.C. 'Me ke ka bontša oona o !!
		-- Bob Violence

%
vaseline ka a matha ...
		-- Bob Violence

%
Nancy !! Ke hobane'ng ha lintho tsohle li tsamaea RED ?!
		-- Bob Violence

%
Nathan ... BATSOALI ba hao ba ka CARCRASH e !! Ba ntse u VOIDED - BaOele Ba ne ba se CHAINSAWS ... Ba ne ba se mechine CHELETE ... Bao ile a Pills a SKIMPY joang liaparong ... Nathan, ke EMULATED bona ... empaba ne ba off-SEHLOOHO ...
		-- Bob Violence

%
NEWARK 'nile REZONED !! Des MOINES 'nile REZONED !!
		-- Bob Violence

%
Nipples, dimples, knuckles, NICKLES, wrinkles, lihloba !!
		-- Bob Violence

%
Eseng SENSUOUS ... feela "FROLICSOME" ... le ho hloka MOSEBETSI meno ... a BOHLOKO !!!
		-- Bob Violence

%
Hona joale ke tepeletse maikutlo ...
		-- Bob Violence

%
Hona joale Ke nahana hore Ke fihla boemong ba ho HYPERTENSION e tlisoang FEELAPELE u bona Kakaretso at sa SAFEWAY Checkout stats!
		-- Bob Violence

%
Hona joale ke utloisisa se boleloang ke "THE MOD masole"!
		-- Bob Violence

%
Hona joale ke ntse INVOLUNTARILY shuffled haufi le CLAM ina leRobehile polasetiki lifereko tse ho lona !!
		-- Bob Violence

%
Hona joale ke concentrating 'ngoe e tobileng tanka ntoeng elella qetellong ea Ntoa ea II ea Lefatše!
		-- Bob Violence

%
Hona joale ke na le menahano INSIPID mabapi beatiful eo, basali ba pota-pota oaHollywood MOVIE MOGULS encased a likoloi PLEXIGLASS 'me le ntse a atamelake BOYS NYENYANE rekisa LITHOLOANA ...
		-- Bob Violence

%
Hona joale KEN le Barbie ba sa ruri lemaletse kelello tse fetolang SEBELISA LITHETHEFATSI ...
		-- Bob Violence

%
Hona joale RESOURCES ea ka MAIKUTLO a ikakhetse ikemiseditse ho 23% ea ho qhibilihisa sa'me ho hloekisoa lefapha la puso ea Nevada !!
		-- Bob Violence

%
Kaha joale ke na le ka "mela", ke utloisisa TEFO boikarabello !!
		-- Bob Violence

%
Hona joale, a re ke re romele bakeng QUICHE !!
		-- Bob Violence

%
Ke 'nete hore u utloisisa mabapi le ho sebelisa PLAIDS a sa ohla Potoloho -
		-- Bob Violence

%
Oh MOLIMO - Letsatsi feela oela Yankee Stadium !!
		-- Bob Violence

%
Oh, ke e fumana !! "The Beach tsoela pele", huh, Sonny ??
		-- Bob Violence

%
Ho lokile ... ke tl'o lehae hore a ngole buka ea CUBE RUBIK "ke hloile oa FORBafu Cat ratang "...
		-- Bob Violence

%
HO LOKILE!! Bulela molumo FEELA bakeng TRYNEL CARPETING, ho feletseng hlomelloaR.V. OA le FLOATATION Systems !!
		-- Bob Violence

%
OMNIVERSAL elelloa ?? Oh, Yeh !! Pele, u lokela lilithara tse 'nè tsa JELL-O'me e BIG wrench !! ... Ke nahana hore u tlohele th'WRENCH a sa JELL-O joalokaha ekae ne e le tatso, kapa motsoako o ... ... kapa ... Ke ... ... Um HOKAE OAHo itlhoekisa mechine?
		-- Bob Violence

%
On BOBELI nahana, mohlomong ke tla futhumatsa tse ling linaoa Baked le ho shebella RégisPHILBIN ... Ho MOHOLO ho PHELA !!
		-- Bob Violence

%
Ka lehlakoreng le leng, bophelo ba ka ba parade sa feleng ea TRANSSEXUALQUILTING linotši palama sekepe Bay ho DISNEYWORLD haeba feela re e lumella hore !!
		-- Bob Violence

%
Tseleng, ZIPPY ke hloohoana ea phini ntle ho morero, empa ha ho mohla ntle le Point.
		-- Bob Violence

%
Ka lekhetlo le leng holim 'a nakoana, ba bane AMPHIBIOUS HOG baletsi ba hlasela lelapa laMokhoa oa ho itšireletsa, nahanela chelete ea tšepe babokelli le tlisa fatše thepa ea bonaMelao ea Boitšoaro !!
		-- Bob Violence

%
Ka lekhetlo le leng, ho ne ho NO ithabisa ... Ena e ne e ka pel'a thero ea menu, FASHIONlipolelo tse kapa thepa NAUTILUS ... Joale, ka 1985 ... monate neka ho feletseng encoded a MICROCHIP ena e nyenyane ... E fupere 14.768 batlang liqabolang bakhanni lula-Com !! Re ile ra tlameha ho ema lilemo tse BONE LIBILIONE TSE empa rea qetella a fihla Jerry Lewis, MTV le ya kgetho e kholo ea creme-khorisoaseneke mahobe!
		-- Bob Violence

%
FISHWICH 'ngoe ea nyolohang !!
		-- Bob Violence

%
ONE BOPHELO HO PHELA bakeng BANA BA KA TSOHLE a LEFATŠE E 'NGOE MATSATSI tsohle tsa bophelo ba rōna.
		-- Bob Violence

%
PELE: Ke tla donate bohle "BABY HUEY" metlae buka koleke ena hoea litsi tsa lero la mali Center ...BOBELI: Nke ke Tsela ea ho Qala BAND bitsoa "KHADAFY & THE otla masole" ...BORARO: Ke tla se ke ua hlola TUMBLE omileng ea ka Fox TERRIER hape !!
		-- Bob Violence

%
... Kapa ba u khanna oa Pontiac hore HONKED nakong 'na a Miami Labobeli ho qetela?
		-- Bob Violence

%
ntat'a rōna ea ileng a Art e etsahala leholimong ... Ke ka tieo rapella hore motho nakong enatafoleng tla lefa bakeng sa hore ke SHREDDED SEO le Senyesemane MUFFIN ... 'me boetsesiea KELETSO seatla se bulehileng ....
		-- Bob Violence

%
holim 'a bophirimela Philadelphia le lelinyane la ntja e hlatsa ...
		-- Bob Violence

%
Fetang underpass eo! TLAS'A overpass eo! Around BOKAMOSO le ka ho Feletseng !!
		-- Bob Violence

%
Tšoarela 'na, na ke bua Senyesemane?
		-- Bob Violence

%
Tšoarela 'na, empa u tseba hore na ho bolela'ng ho ba LE KANNETE ONE nang lephephe hao!
		-- Bob Violence

%
Peggy Flemming e utsoa baskete libolo ho fepa masea ka Vermont.
		-- Bob Violence

%
Batho tlotlolla e salami!
		-- Bob Violence

%
Pizza !!
		-- Bob Violence

%
Mpehe leqepheng la Buffer sebadi ha u ntse u nyenyefatsa BELLHOPS tse 'maloa tseTrianon Room !! E-re ke e mong oa ka tiasa yona ba hao!
		-- Bob Violence

%
Ka kopo khutlela lapeng le 'na ... Ke na Tylenol !!
		-- Bob Violence

%
Psychoanalysis ?? Ke ile ka nahana e ne e le oa rap nude fa setlhopha se kopane !!!
		-- Bob Violence

%
Punk ROCK !! Disco letata !! Tsoalo LAOLA !!
		-- Bob Violence

%
Quick, bina 'na ea Budapest National Anthem !!
		-- Bob Violence

%
BENG !!
		-- Bob Violence

%
Hopola, a 2039, MOUSSE & bijoux tla fumaneha feela ke moriana !!
		-- Bob Violence

%
RHAPSODY a Sekhomaretsi!
		-- Bob Violence

%
Santa Claus theoha mollo balehela apere khanyang a maputsoa leoto WARMERS... O scrubs mopapa e nang le sesepa e le bonolo kapa detergent ka metsotso e 15,starring Jane Fonda !!
		-- Bob Violence

%
Romela lipotso tsa hao ho `` BOTSA ZIPPY '', Box 40474, San Francisco, CA94140, USA
		-- Bob Violence

%
SHHHH !! Ke utloa tšeletseng TATTOOED teraka-bakhanni tossing enjene likhopiso ho kenatsa lefeela OLI meropa ...
		-- Bob Violence

%
Ke lokela ho etsa'ng oa ka Bobbie VINTON medley?
		-- Bob Violence

%
Ke lokela ho fumana notletsoe a sa PRINCICAL OA OFFICE kajeno - kapa ho ba le VASECTOMY ??
		-- Bob Violence

%
Ke lokela ho qala ka nako eo ke lithuto tsa botho nang BEATNIK emoriri stylist ho hloleheng ea ka ea ho bolela BACHA hlano ho isa ho e OCULIST molemo?
		-- Bob Violence

%
Saena boipiletso ka.
		-- Bob Violence

%
Kahoo sena ke seo ke ikutloa ka rata ho ba litapole salate
		-- Bob Violence

%
Kahoo, haeba re sokolla Phepelo-lehlakoreng SOYABEAN bokamoso ho kena HIGH-ka lihlahisoa T-BILLMatšoao, e leng ea pele ho INFLATIONARY likotsing tse tla DWINDLE ho lebelo la 2Shopping SPREES ka EGGPLANT !!
		-- Bob Violence

%
Motho e mong a Dayton, Ohio e rekisa lik'hapete sebelisa ho e SeSerbo-Croatia
		-- Bob Violence

%
Nakoana ka 1993 Nancy Sinatra o tla etella pele phethola 'muso e sa sebeliseng mali pele ho Guam !!
		-- Bob Violence

%
Kae-kae Downtown Burbank letekatse e OVERCOOKING konyana ratha !!
		-- Bob Violence

%
Kae-kae ea teropong Honolulu, e sa sebetseng bellhop e shapa emamethaka ea seng molaong psilocybin chop suey !!
		-- Bob Violence

%
Kae-kae Tenafly, New Jersey, e chiropractor e shebella "Leave eonaho Beaver "!
		-- Bob Violence

%
Ho Hasa botoro peanut nkhopotsa 'mino oa opera !! Kea ipotsa hore na ke hobane'ng?
		-- Bob Violence

%
TAILFINS !! ... ... Tobetsa
		-- Bob Violence

%
Ho bua Blues Pinhead:Oh, ke ile ka felloa ea ka `` HELLO KITTY '' popi 'me ke fumana MPE ho amohelloang batho hodima kanale    A MABELI A MOTSO e tšeletseng !!Th'HOSTESS fektheri e closin 'fatše' me ke feela ba utloa ZASU Pitts o 'nile    Shoele LILEMO .. (sniff)My sethaleng SHOE pokello ile CHEWED nyoloha ka ntja go th ', Alexandere Haig    ba ke ke ba ntumella hore ke nka hlapa 'Til Easter ... (snurf)Kahoo ke ile ka ea sebetsa kichineng, empa Walnut PANELING whup 'na hlohlolingoane lo mah Haid !!    (Ka ho re che, che, ha ho na .. Heh, kmren)
		-- Bob Violence

%
Phaphatha? U ralipolotiki! Na ha u hlokomele hore qetellong ea "HlatsoaPotoloho "ke ka motsotsoana e bolokeloang bakeng batho ba bangata ?!
		-- Bob Violence

%
Tex HO KOPANELA LIPHATE! The HOME oa mabili! The rotha ea kofi !! NkisaMinnesota empa u se ke ua 'na tlotlolla !!
		-- Bob Violence

%
Th 'kelello ke Pizza Palace th' MOEA
		-- Bob Violence

%
Tanki molimo!! ... Ho HENNY YOUNGMAN !!
		-- Bob Violence

%
Ka kananelo ea karolelano ya pono graphisticator a ntahle Ke habohlokoaea suaveness oohle le decadence e leng atile !!
		-- Bob Violence

%
Oohle oa Chinese BASALI VOLLEYBALL TEAM tsohle kabelo ea ONE botho -'me ho tloha ka ba le Tsoalo !!
		-- Bob Violence

%
'Nete ea hore tse 47 BATHO ba hooa' me mofufutso e cascading theosa oa kaLesapo la mokokotlo lenaneng la e toka e be e thabisang !!
		-- Bob Violence

%
The FALAFEL Sandwich linaheng tse hloohong ea ka 'me ke be ea Litsoa-mobung ...
		-- Bob Violence

%
... E khōlō o entsoe ka LIME JELLO le Honda oa ka ke barbequeuedOYSTER! Yum!
		-- Bob Violence

%
Ntoa e Korean tlameha ebe monate.
		-- Bob Violence

%
... Ea MYSTERIANS ba mona hammoho le CORDUROY ea ka sesepa le sejana !!
		-- Bob Violence

%
The Osmonds! U Osmonds tsohle !! Lahlele ba ka ka bulehileng e ka meso !!!
		-- Bob Violence

%
The PILLSBURY DOUGHBOY e hoeletsang ho kōpa felisa Burt Reynolds lifilimi !!
		-- Bob Violence

%
The PINK likausi ne tsoa 1952 !! Empa ba ile ba Marsho pota-pota ka 1953 !!
		-- Bob Violence

%
E tsokoang tšoanang e ntse e tsoela tla le COLLAPSING joaloka e rayon ea MUU-MUU ...
		-- Bob Violence

%
Ha ho na 'NETE. Ha ho na ntho ea sebele. Ha ho na mantsoe a tsoanang.Ha ho na mantsoe a feletseng. Ke ka etsahala hore ebe haholo fosahetseng.
		-- Bob Violence

%
Ho na le setshwantsho llisoa ke lintho tseo ED McMahon etsa lintho tse mpe ho Joan linōkaa e $ 200.000 MALIBU Beach HOUSE !!
		-- Bob Violence

%
Ho na le chelete e lekaneng ho reka mona makotikoti 5000 ea noodle-Roni!
		-- Bob Violence

%
"Ana ke TIMES se lefifi bakeng sa moloko oohle oa batho o melemo HO FETISISA!""Ana ke se lefifi TIMES tokoloho le nala!""Ana ke TIMES MOHOLO ho beha chelete ea hao ho Guy MPE ho raha ea CRAPho tsoa MEGATON MAN! "
		-- Bob Violence

%
Boloka tsena e lokela ho ba matla a fepehileng ho Pentagon bahlanka ba !!
		-- Bob Violence

%
Ba oele ... joaloka masistere seterateng ... ba ne ba se bacha baoipiletsa!
		-- Bob Violence

%
Sena ASEXUAL kolobe hlile taba MALI oa ka ... O kahoo ... ... kahoo potlakileng !!
		-- Bob Violence

%
"Sena ke mosebetsi o etsoe BOB PEFO le SCUM, ea hlokang kelello Hoa makatsa hore ebe sehole ntja."
		-- Bob Violence

%
Sena ke NO-FRILLS balehelang - tšoara go th 'Bacon Canada !!
		-- Bob Violence

%
Sena e lokela ho ba le phathi molemo - khopo My gorole e ntse e utloa bohloko ha petelitsoe fihlangkhahlanong Martini motho e mong !!
		-- Bob Violence

%
... Ena e lokela ho ba hore na ho joang ho ba College kalogo !!
		-- Bob Violence

%
Pizza ena e tšoantšetsa MAIKUTLO oa ka ka ho feletseng hlaphoheloa !!
		-- Bob Violence

%
PORCUPINE ena tseba ZIPCODE hae ... And o "Visa" !!
		-- Bob Violence

%
Sena litlhōrō Off phihlelo ea oa ka partygoing! Motho eo ke sa rate keho buisana le 'na ka pelo e-futhumala ha European filimi ...
		-- Bob Violence

%
Bao ha ba WINOS - hore 's JUGGLER ka, AERIALIST ka, sabole ea kaSWALLOWER, 'me Latex ea ka NOVELTY thepa !!
		-- Bob Violence

%
Lilemong tse likete tse mehleng ea baahi ... hlahisitse ... ikutloa bakeng sabokgabane dimmojule -
		-- Bob Violence

%
Kajeno, BORARO WINOS tsoang Detroit nthekisitse e Framed senepe sa tab ya HUNTERpele Makeover hae!
		-- Bob Violence

%
Menoaneng, mangole nipples. Menoaneng, mangole nipples, KNUCKLES ...Nipples, dimples, knuckles, NICKLES, wrinkles, lihloba !!
		-- Bob Violence

%
Tony Randall! Ke bophelo lōna Patio monate ??
		-- Bob Violence

%
Uh-oh - ke hobane'ng ha ke nahana ka tšohanyetso sa moeta-pele oa bolumeli oa VENERABLEfrolicking leqepheng la Fort Lauderdale mafelo a beke?
		-- Bob Violence

%
Uh-oh !! Ke lebetse ho ikokobelletsa URINALYSIS qobelloang!
		-- Bob Violence

%
UH-OH !! Ke apara "MOHOLO HEAD-ka tereneng thulana ea batlang 50" kephoso !!!
		-- Bob Violence

%
UH-OH !! Ke nahana KEN okametseng-e loketseng mabapi le R.V. hae Ditefello le O ba leTšohile thipitlo le eena !! Ha hektare.
		-- Bob Violence

%
Uh-oh !! Ke ho ba le ho hongata haholo monate !!
		-- Bob Violence

%
UH-OH !! Re u tsoang ho koloi Parts le rabara thepa ea!
		-- Bob Violence

%
Used lijo tse lengoang tse ntle le soya spaghetti!
		-- Bob Violence

%
VICARIOUSLY latsoa lebaka le itseng ho PHELA !!
		-- Bob Violence

%
Vouta bakeng ME - Ke hantle tapered, half-cocked, ba kulang-emoloa le lekhetho DEFERRED!
		-- Bob Violence

%
Leta ... ke ena e monate ntho kapa qetellong ea bophelo ba ka Petticoat Junction ??
		-- Bob Violence

%
O ile a soya ea ka bohobe mokhelo a th'RAIN? E latsoeha SEBELE MOLEMO !!
		-- Bob Violence

%
Hona joale re thabela tjhelete yohle bond bobeli a la litoro har'a faki chesang ...
		-- Bob Violence

%
Re na le FAPANENG bokae ha moriri -
		-- Bob Violence

%
Re mpa re ikopanya ea lehae moriri paterole!
		-- Bob Violence

%
Re beha likopi tse peli tsa BATHO makasine ea e lefifi, mongobo mobile home.metsotso e 45 hamorao CYNDI LAUPER hlaha apere nonyana gorole hloohong ea hae!
		-- Bob Violence

%
Buuoa hantle, ke 'na enoa Amerika .. Ke e rata. Ke e hloile. Ke a e rata. ILehloeo eona. Ke a e rata. Ke e hloile. Ke a e rata. Ke e hloile. I LIKE ...Maikutlo a ba fiela ka lebaka la ka !!
		-- Bob Violence

%
Buuoa hantle, ke khale Anal RETENTIVE !! 'Me ke batla tsela ea hoVICARIOUSLY latsoa lebaka le itseng ho PHELA !!
		-- Bob Violence

%
Buuoa hantle, ke sa bonahaleng NAKO ... nka haesita lefa a etetse Ladies eaRoom ...
		-- Bob Violence

%
Buuoa hantle, O.K. Ke tla sekisetsa melao-motheo ea ka ka lebaka la ho nyahama EXISTENTIAL!
		-- Bob Violence

%
Ba ne ba parsnips tsena ka mokhoa o nepahetseng MARINATED a TACO spaghetti?
		-- Bob Violence

%
Ruri iketsahaletse! Ke e matla "SNOOTS OF THE LINALELI" morekisi !!
		-- Bob Violence

%
Seo MOLEMO ke lebokoso sutuk'heise Joalo?
		-- Bob Violence

%
Seo ke se hlokang ke ea hōlileng tsebong KAMANO EA e nang le FLOPPY lebili ...
		-- Bob Violence

%
Seo ke se batlang ho fumana hore ke - u se lipapakhaie tseba ho hongata ka Astro-Turf?
		-- Bob Violence

%
Seo Lenaneo ba ba shebeletse?
		-- Bob Violence

%
ke seo Bokahohle ena, ka kōpo ??
		-- Bob Violence

%
Ke'ng e BOHLOKOA Sid? ... Na seno ea hao e sa khotsofatseng?
		-- Bob Violence

%
Ha ke kopana le th'POPE morao koana ka '58, ke scrubbed eena le mohlankana e mong sesepa bonolo kapaDETERGENT ka metsotso e 15. O ne a bonahala ho thabela ...
		-- Bob Violence

%
Ha mojaro Sena se etsoa ke nahana hore ke tla hlatsoa hape ...
		-- Bob Violence

%
Ha u fihla Ph.D. ea hao U tla fumana ba khona ho sebetsa ka Li-burger Toropong KING?
		-- Bob Violence

%
Ha u re "haholo meru" e nkhopotsa ya Hloekisa saletseng moraoBILL ... U se ke ua u SHEBA? O'Grogan metsoa ea bohlokoa chelete ea tšepe COLLECTION'me NE bolaile eena feela motho ea neng a tseba !!
		-- Bob Violence

%
Ke hokae moo likausi ba hao u tsoele ha u lahleheloe ke bona th 'WASHER?
		-- Bob Violence

%
Where ha e ee ha u flush?
		-- Bob Violence

%
E hokae Sandy Duncan?
		-- Bob Violence

%
E hokae go th 'DAFFY letata Bontša ??
		-- Bob Violence

%
E hokae mochine Coke? Ak'u mpolelle le motlae !!
		-- Bob Violence

%
Ha a ntse a ea ka BRAINPAN bo ntseng bo hana tšebeletso ea Li-burger Toropong a KING, Mojesuitebaprista ba intša BOIPHELISO baemeli !!
		-- Bob Violence

%
Ha a ntse a u hlafuna, nahana ka tlaleho ena e bankeng Steven SPIELBERG OA ... haee tla ba le phello e tšoanang le tse peli "BLOCKERS starch"!
		-- Bob Violence

%
WHO bona Beach Bunny lla leqepheng la SHAG RUG ?!
		-- Bob Violence

%
Whoa !! Ken le Barbie ba le ho hongata haholo monate !! E tlameha e beIONS MAIKUTLO !!
		-- Bob Violence

%
Ke hobane'ng ha tsena salesmen liatleletiki seeta se ke a ntatela ??
		-- Bob Violence

%
Ke hobane'ng ha u kile ua kena litlhōlisano leha e le efe, Marvin ?? Na ha u tsebe ea haoZIPCODE mong?
		-- Bob Violence

%
Ke hobane'ng ha lintho tsohle li tsamaea entsoe ka Lycra Spandex?
		-- Bob Violence

%
Ke hobane'ng ha e hore ha u shoa, u ke ke ua nka HOME oa hao BOITHABISOSetsi na le uena ??
		-- Bob Violence

%
E tla ntlafatsa chelete ea ka phallo?
		-- Bob Violence

%
O tla lefatše boraro ntoa boloka "sefubeng Buddies" tima moeeng?
		-- Bob Violence

%
See se tla ho mohla-ho ipolaea letoto la liketsahalo tse Monate khaotsa?
		-- Bob Violence

%
Le lōna, ke khona ho ba ke ... ha re hloke Dan-na le hoo ...
		-- Bob Violence

%
Ntoa III? Che kea leboha!
		-- Bob Violence

%
Ntoa Three ka qojoa ka ho khomarela mokhoa oa ho moaparo khoutu ya sebediswa tieo!
		-- Bob Violence

%
Joooh! Bona !! A meatball itaola !! A re ke re buisana it!
		-- Bob Violence

%
Xerox lijo tsa motšehare le tsa hao file eona tlas'a "basenyi kopanela liphate"!
		-- Bob Violence

%
E, empa ba tla ke bona Easter Bunny a letlalo skintight nakong tšepe eMoroetsana konsarete?
		-- Bob Violence

%
U ke ke ua 'ntša kotsi !! Ke na le sekoloto sa ntlo ASSUMABLE !!
		-- Bob Violence

%
U bolele hona joale ke thunya le go th ka morao 'me BLUR ka ho eketsehileng'phapang pakeng tsa Fantasy le ntho ea sebele?
		-- Bob Violence

%
U bolele hore u batle ho shebella Loana tsoang ATLANTA?
		-- Bob Violence

%
Le nka nko Karl Malden OA !!
		-- Bob Violence

%
U lokela ho tsohle UP qhomela le tlaase ka lihora tse peli ha ke ntse ke etsa qeto ka e BOIPHELISO NEW !!
		-- Bob Violence

%
U ne u s'posed ho tšeha!
		-- Bob Violence

%
Le !! Mphe CUTEST, PINKEST, linaha tse ngata e khahlehang bue hakaalo VictorianDOLLHOUSE u ka fumana !! An etsa hore ho SNAPPY !!
		-- Bob Violence

%
Marameng oa hao a lule joaloka NECTARINES lefahla le ka holim'a molomo oa hore o tseba se na meeli -
		-- Bob Violence

%
Youth ea kajeno! Join 'na a e thaotha ka bongata bakeng sa tsa setso tsa kelello lintlhengmaikutlo a loketseng!
		-- Bob Violence

%
Yow!
		-- Bob Violence

%
Yow! Ke ithabisa leha ho le joalo?
		-- Bob Violence

%
Yow! Na ke se ke ka Milwaukee?
		-- Bob Violence

%
Yow! Ebe ka mor'a moo re ka lula ka lehlakoreng le nt shwe tsa likoloi mabone setopong!
		-- Bob Violence

%
Yow! Na re beha morao-s'o?
		-- Bob Violence

%
Yow! Na re kolobisa leha ho le joalo?
		-- Bob Violence

%
Yow! Na u mopresidente ho intša frying?
		-- Bob Violence

%
Yow! O ile a ntho e mpe ho etsahala kapa ke ka mokhoa o ntsamaisa ka koloi-ka baesekopo ??
		-- Bob Violence

%
Yow! Ke ikela ka tlaase mona moleng o oela bofutsaneng!
		-- Bob Violence

%
Yow! Ke ile ka lahla ka ka fensetere ea ka!
		-- Bob Violence

%
Yow! Ke batla nko ea ka le ngotsoe ka mabone!
		-- Bob Violence

%
Yow! Ke batla ho romela e artichoke bronzed ho Nicaragua!
		-- Bob Violence

%
Yow! Ke ho ba le boikutlo quadrophonic ea winos tse peli a le mong motseng leloala tšepe!
		-- Bob Violence

%
Yow! Ke nahana hore na surfer Van tlala spaghetti soya!
		-- Bob Violence

%
Yow! Ke otla mabopong ea ka bolulo termite bopaki?
		-- Bob Violence

%
Yow! Ke likamano tse sena ba ho kopanela liphate-s'o ?? Ke ho eona, huh, na ha ho ??
		-- Bob Violence

%
Yow! Ho phunya lesoba ka tsela tsohle ho litsi tsa Burbank!
		-- Bob Violence

%
Yow! Ho batho ba bang ba ka har'a lerako! Sena ke molemo ho feta ho mopping!
		-- Bob Violence

%
Yow! Mohlomong nka be ke kōpa Neutron ea ka Bomb a Paisley -
		-- Bob Violence

%
Yow! Hona joale ke khona ho nahana ka lintho tsohle MPE ke entse ho Bowling eBall ha ke ne ke le Junior HIGH SCHOOL!
		-- Bob Violence

%
Yow! Hona joale re ka ba makhoba a tahi!
		-- Bob Violence

%
Yow! batho bao sheba hantle feela joaloka Donnie le Marie Osmond !!
		-- Bob Violence

%
Yow! Re tlil'o le disco tse ncha!
		-- Bob Violence

%
YOW !! Bohle ho tsoa letamo liphatsa tsa lefutso!
		-- Bob Violence

%
YOW !! Ke ka mokhoa o bohlale haholo 'me adorable INSANE tshireletso !!
		-- Bob Violence

%
YOW !! Hona joale ke utloisisa MICROBIOLOGY e tsoetseng pele le go th 'melao ea lekhetho e ncha liphetoho !!
		-- Bob Violence

%
YOW !! Naha ea bochaba SONY !!
		-- Bob Violence

%
YOW !! Up ka pele! Ho e bagel Hut !!
		-- Bob Violence

%
YOW !! Ke eng e lokelang oohle oa moloko oa batho ETSANG ?? Jang karolo ea bohlano eaCHIVAS Regal, Ski nude theosa MT. EVEREST, 'me ba na le tse hlaha HO KOPANELA LIPHATE mafelo-beke!
		-- Bob Violence

%
YOW !!! Ke ithabisa !!!
		-- Bob Violence

%
Zippy liseleng tsa boko di straining ho koala synapses ...
		-- Bob Violence

%
